### PR TITLE
LPD-33706 Use of library with known vulnerability: cxf 3.4.10 osb-faro

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jgarcialr** [comment]
ci:reevaluate:1307401_10048

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
@jgarcialr I tried to deploy osb-faro-web locally and I am getting the following exception:

nt development and demonstration purposes. Do NOT use sidecar in production. Refer to the documentation for details on the limitations of sidecar and instructions on configuring a remote Elasticsearch connection in the Control Panel.
faro                  | 2024-09-10 18:26:08.711 INFO  [main][ModuleFrameworkImpl:1713] Started dynamic bundles
faro                  | 2024-09-10 18:26:08.711 INFO  [main][ModuleFrameworkImpl:1720] Starting web bundles
faro                  | 2024-09-10 18:26:09.715 ERROR [Framework Event Dispatcher: Equinox Container: 206a3cab-4d2d-446b-98a7-17f0c58755ba][Framework:47] FrameworkEvent ERROR
faro                  | org.osgi.framework.BundleException: Could not resolve module: com.liferay.osb.faro.web [1776]
faro                  |   Unresolved requirement: Import-Package: org.apache.cxf.helpers; version="3.5.0"
faro                  | 
faro                  |         at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
faro                  | 2024-09-10 18:26:09.864 ERROR [main][DirectoryWatcher:988] Unable to start bundle: file:/opt/liferay/osgi/modules/com.liferay.osb.faro.web.jar
faro                  | org.osgi.framework.BundleException: Could not resolve module: com.liferay.osb.faro.web [1776]
faro                  |   Unresolved requirement: Import-Package: org.apache.cxf.helpers; version="3.5.0"
faro                  | 
faro                  |         at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:426) ~[org.eclipse.osgi.jar:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:971) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1004) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:945) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:838) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher.start(DirectoryWatcher.java:341) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.activator.FileInstallImplBundleActivator.start(FileInstallImplBundleActivator.java:98) [bundleFile:?]
faro                  |         at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:769) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:995) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:352) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.Module.doStart(Module.java:581) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.container.Module.start(Module.java:449) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:426) [org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) [org.eclipse.osgi.jar:?]
faro                  |         at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1766) [com.liferay.portal.bootstrap.jar:?]
faro                  |         at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:280) [com.liferay.portal.bootstrap.jar:?]
faro                  |         at com.liferay.portal.module.framework.ModuleFrameworkUtil.startFramework(ModuleFrameworkUtil.java:40) [portal-impl.jar:?]
faro                  |         at com.liferay.portal.spring.context.PortalContextLoaderListener._contextInitialized(PortalContextLoaderListener.java:430) [portal-impl.jar:?]
faro                  |         at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:205) [portal-impl.jar:?]
faro                  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
faro                  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
faro                  |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
faro                  |         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
faro                  |         at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:34) [com.liferay.shielded.container.impl.jar:?]
faro                  |         at com.liferay.shielded.container.internal.proxy.EventListenerInvocationHandler.invoke(EventListenerInvocationHandler.java:55) [com.liferay.shielded.container.impl.jar:?]
faro                  |         at com.sun.proxy.$Proxy6.contextInitialized(Unknown Source) [?:?]
faro                  |         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4460) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:680) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1844) [catalina.jar:9.0.87]
faro                  |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
faro                  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
faro                  |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.87]
faro                  |         at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) [?:?]
faro                  |         at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:575) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:466) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1584) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:312) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.87]
faro                  |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
faro                  |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.87]
faro                  |         at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
faro                  |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:925) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.Catalina.start(Catalina.java:735) [catalina.jar:9.0.87]
faro                  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
faro                  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
faro                  |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
faro                  |         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
faro                  |         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) [bootstrap.jar:9.0.87]
faro                  |         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473) [bootstrap.jar:9.0.87]
faro                  | 2024-09-10 18:26:09.888 INFO  [main][ModuleFrameworkImpl:1774] Started web bundles
faro                  | 2024-09-10 18:26:09.888 INFO  [main][ModuleFrameworkImpl:283] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
faro                  | 2024-09-10 18:26:09.893 ERROR [fileinstall-directory-watcher][DirectoryWatcher:988] Unable to start bundle: file:/opt/liferay/osgi/modules/com.liferay.osb.faro.web.jar
faro                  | org.osgi.framework.BundleException: Could not resolve module: com.liferay.osb.faro.web [1776]
faro                  |   Unresolved requirement: Import-Package: org.apache.cxf.helpers; version="3.5.0"
faro                  | 
faro                  |         at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
faro                  |         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:426) ~[org.eclipse.osgi.jar:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:971) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1004) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:945) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:838) [bundleFile:?]
faro                  |         at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:298) [bundleFile:?]
faro                  | 
faro                  |     __    ____________________  _____  __
faro                  |    / /   /  _/ ____/ ____/ __ \/   \ \/ /
faro                  |   / /    / // /_  / __/ / /_/ / /| |\  /
faro                  |  / /____/ // __/ / /___/ _, _/ ___ |/ /
faro

**Comment by jgarcialr** [comment]
Hi @ivicac ,
Could you give me some repro steps to test faro locally? Is it enough setting ant setup-profile-dxp and then building and launching the portal?

Regards

**Comment by jgarcialr** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by ivicac** [comment]
@jgarcialr we are building faro Docker image against liferay/dxp:7.4.13.nightly and see Apache CXF still on version 3.4.10

CleanShot 2024-09-12 at 19 13 51@2x

**Comment by jgarcialr** [comment]
Hi @ivicac ,
Maybe we need to ask in docker channel in order to know which githash are they using to create 7.4-nightly.
If I start a master bundle, it shows 3.5.9, but if I start a docker run of liferay/dxp:7.4.13.nightly-d7.0.6-20240912101209 it shows your results.

**Comment by ivicac** [comment]
hi @jgarcialr I left the question in Slack: https://liferay.slack.com/archives/CM1GPPDLN/p1726496547396769?thread_ts=1726496338.577139&cid=CM1GPPDLN

**Comment by ivicac** [comment]
@jgarcialr you can forward PR. I have just built the latest image and CXF is updated:

CleanShot 2024-09-16 at 18 18 28@2x

**Comment by jgarcialr** [comment]
//cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward:force

**Pull request closed without merging**
