### PR TITLE
[TS] LPS-188149 Stateless redirection fix

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
**Steps to reproduce:**
1. Set up SMTP
2. Log in as admin user
3. Control panel → Instance settings → Login → Prompt Enabled →  
4. Product menu → Content & Data → Documents and Media → open tree.png → bookmark the page
5. Control panel → Instance settings → Multi-Factor Authentication → Enabled   
6. Log out
7. Open the bookmarked link
8. Log in & insert OTP

_Expected Behavior:_ Get redirected to the bookmarked page
_Actual Behavior:_ A green confirmation banner shows that the process was successful, but the page does not redirect anywhere

**Implementation Details:**

The problem was that with a page like the tree image render in DL, the combination of "state" and "redirect" parameters quickly approached 4000 characters. At that limit parameters can get dropped.

The redirect parameter that is provided to /c/portal/login (and the login portlet) was encoded into the state parameter and hence could not be accessed when building the "return to full page" link. Hence it was sent separately in another parameter. So I extracted it from state and sent it separately, removing the need to send a second parameter altogether. Resulting in a considerably shorter request URL length.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@MirnaGama since you worked on this issue also and know the code well it would be great if you could check if this fix covers everything?

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by MirnaGama** [comment]
Okay @stian-sigvartsen 
I'll take a look !

**Comment by stian-sigvartsen** [comment]
CI results look good

**Comment by MirnaGama** [comment]
@stian-sigvartsen 
LGTM !

**Comment by stian-sigvartsen** [comment]
Thanks for reviewing @MirnaGama .

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
