### PR TITLE
LPS-194389 Account's 'Blocked Email Domains' 

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Review by manuelecastro — CHANGES_REQUESTED** [review]
Hi @stian-sigvartsen,

Since we're dealing with an attribute value here, shouldn't we use `HtmlUtil.escapeAttribute()` instead? Otherwise the fix looks great to me! 😄

the SF is failing due to an extra space at the beginning of the line 71.

Thank you!

**Comment by stian-sigvartsen** [comment]
Hi @manuelecastro . Excellent question! The thing in this case is that we are dealing with an attribute on a JSP tag, which gets processed server side to produce the actual HTML. If you have a look at the tag's implementation you will you will that it simply writes to the output using `jspWriter`. See https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/util-taglib/src/com/liferay/taglib/ui/MessageTag.java#L85-L89

Because of this, when the HTML is output, it is just a HTML text node and should be escaped as such.

One thing I noticed just now is that the `<liferay-ui:message>` tag actually has a "escape" attribute that can be used. You may want to see if that can be used instead of what I proposed.

**Review by stian-sigvartsen — COMMENTED** [review]
See my previous comment

**Comment by manuelecastro** [comment]
Resent here with SF fix: https://github.com/liferay-appsec/liferay-portal/pull/1407

**Pull request closed without merging**
