### PR TITLE
LPS-134144 OIDC system proxy config support

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:bundle

**Comment by lipusz** [comment]
Hey Guys, @petersimonyi @davidhegedus

Would you mind testing the OIDC proxy support and let us know your results? You can obtain the bundle built from this PR once the ci:test:bundle command finishes, there will be a link provided in a comment.

As it's `master`, make sure you are using `~` in the provider config name instead of `-`. So like

`com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration~Google.config`:
```
openIdConnectClientSecret="<client_secret>"
tokenEndPoint="https://www.googleapis.com/oauth2/v4/token"
issuerURL="https://accounts.google.com"
discoveryEndPointCacheInMillis="360000"
openIdConnectClientId="<client_id>"
jwksURI="https://www.googleapis.com/oauth2/v3/certs"
userInfoEndPoint="https://www.googleapis.com/oauth2/v3/userinfo"
authorizationEndPoint="https://accounts.google.com/o/oauth2/v2/auth"
discoveryEndPoint="https://accounts.google.com/.well-known/openid-configuration"
providerName="Google"
subjectTypes="public"
scopes="openid\ email\ profile"
```

Thanks,
Tibi

**Comment by stian-sigvartsen** [comment]
Manual tests has passed (details on ticket, thanks @petersimonyi !) and agreed with @lipusz also.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
