### PR TITLE
LPS-198503 Add audit logs for SegmentsEntryRole related events

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPS-198503](https://liferay.atlassian.net/browse/LPS-198503)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@nikolettabuza great job! I'll forward

**Comment by stian-sigvartsen** [comment]
c:forward

**Comment by stian-sigvartsen** [comment]
Integrated to local branch `audit-wip-i-1`

**Pull request closed without merging**
