### PR TITLE
LPD-6865 Update the displayed default utility page name

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPD-6865](https://liferay.atlassian.net/browse/LPD-6865) -> [LPD-19972](https://liferay.atlassian.net/browse/LPD-19972)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
@nikolettabuza this looks good. Let's forward it 👍

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
