### PR TITLE
LPD-33706 Use of library with known vulnerability: cxf 3.4.10

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
Motivation: https://github.com/liferay-appsec/liferay-portal/pull/1894#issue-2465436289

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:report:71428261

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by alvarosaugarlr** [comment]
create a new [pr](https://github.com/liferay-appsec/liferay-portal/pull/1916) because the commerce's tests are failing and [it looks like a rebased was needed](https://liferay.atlassian.net/browse/LPD-34541?focusedCommentId=2724504).

**Comment by smottal** [comment]
ci:report:71649918

**Comment by jgarcialr** [comment]
closing as #1916 was forwarded

**Pull request closed without merging**
