### PR TITLE
LRQA-81639 | master

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://liferay.atlassian.net/browse/LRQA-81639

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:security

**Comment by JessieZhao0714** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
Manually sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/138295

**Pull request closed without merging**
