### PR TITLE
LRQA-76559 Update test tool's URL address

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-76559](https://issues.liferay.com/browse/LRQA-76559)

### CODE REVIEW

**Review by stian-sigvartsen — APPROVED** [review]
Looks good to me!

**Comment by gaborlovasdotcom** [comment]
ci:stop:security

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
