### PR TITLE
LPD-18593 Fix Funtional Test: LocalFile.Audit#VerifyAuditMessageAfterModifyImpersonatedUserDisplaySettings with CLDR locale provider

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-18593](https://liferay.atlassian.net/browse/LPD-18593)

JDK internal may provide different display name based on the different locale providers used. JDK8 uses JRE/COMPAT by default. JDK21 uses CLDR as default. This made many locale related things change a little bit but enough to make many functional tests fail. Core Infra team decision is to move to use CLDR locale provider. So we need to update our functional tests or our production code accordingly.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
Test passed successfully locally and on CI! [Testray Build](https://testray.liferay.com/home/-/testray/case_results/2546219362?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayComponentId%3D1600089737%26testrayBuildId%3D2546218953%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by julschong** [comment]
ci:report:2546218953

**Comment by julschong** [comment]
unique failure seems unrelated
good to go

**Comment by manuelecastro** [comment]
ci:forward

**Pull request closed without merging**
