### PR TITLE
LPS-152126 LPS-157406 LPS-150933 | SAML Admin REST tests (+ follow ups)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hi @gaborlovasdotcom . This is ready for full QA.

- The SemVer issue is unrelated for sure. 
- Please can you check LocalFile.SAML#ViewIdPSingleLogoutWithMultipleSPs ? There is nothing in this PR which should affect the existing SAML provider logic.

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
> 

The failure of LocalFile.SAML#ViewIdPSingleLogoutWithMultipleSPs is an poshi issue, it will occur on Jenkins randomly and will be fixed under https://issues.liferay.com/browse/LPS-166743.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
Continue in https://github.com/liferay-appsec/liferay-portal/pull/943

**Pull request closed without merging**
