### PR TITLE
LPS-194700 & LPS-194655 As a Developer I want to be able to list every inactive User via a Headless-API endpoint

### PR DESCRIPTION
**Pull request by ruben-pulido**
Original PR: https://github.com/liferay-appsec/liferay-portal/pull/1348

This PR adds integration tests to the previous one.

Motivation
=======
https://liferay.atlassian.net/browse/LPS-188650

Proposed Solution
========
Two GET endpoints have been added to the headless-admin-user application:

- `/headless-admin-user/v1.0/user-accounts/by-status/${status}`
where status is either "active" or "inactive", to allow getting users by its status value.

- `/headless-admin-user/v1.0/user-accounts/by-email-address/${emailAddress}` to allow getting a user by its email address, regardless of its current status. 

An additional **readOnly** field `status` has been added to the `UserAccount` entity (with value `Active` or `Inactive`), which is returned in every endpoint returning a `UserAccount` or a collection of `UserAccount`s.

The story mentions the response should include the following fields:
`userID`
`firstName`
`lastName`
`emailAddress`
`Role`
`Status(active/inactive)`

Besides `status` (which has been added) and `emailAddress`, the names of the fields are already defined in the UserAccount entity with slightly different names:

`userID -> id`
`firstName -> givenName`
`lastName -> familyName`
`Role -> roleBriefs`

The new endpoint returns instances of the entity `UserAccount`, and therefore contains all its fields with the already existing field names.

Steps to Verify
========
- Make sure you have enabled feature flag LPS-188420
- Create several users via UI or headless API
- Deactivate some of them via UI

- Invoke the new endpoint `/headless-admin-user/v1.0/user-accounts/by-status/inactive` and verify that only the inactive users are returned
- Verify that users returned contain field `"status" : "Inactive"`

- Invoke the new endpoint `/headless-admin-user/v1.0/user-accounts/by-status/active` and verify that only the active users are returned
- Verify that users returned contain field `"status" : "Active"`

- Invoke the new endpoint `/headless-admin-user/v1.0/user-accounts/by-email-address/${emailAddress}` for an inactive user and verify that the inactive user is returned
- Verify that user returned contains field `"status" : "Inactive"`

- Invoke the new endpoint `/headless-admin-user/v1.0/user-accounts/by-email-address/${emailAddress}` for an active user and verify that the active user is returned
- Verify that user returned contains field `"status" : "Active"`

- Verify that filter, page, search and sort can be included as parameters to `/headless-admin-user/v1.0/user-accounts/by-status/${status}` similarly to how they are included for the already existing endpoint `/headless-admin-user/v1.0/user-accounts` 

References to existing code
========
The `/user-accounts/by-status/${status}` is the endpoint chosen to display users with a specified state.
This follows the pattern of already existing endpoints like:
- `/sites/{siteId}/data-definitions/by-content-type/{contentType}`
- `/structured-contents/{structuredContentId}/by-version/{version}`
while making the api flexible enough for supporting any status value that may be supported in the future without having to add additional endpoints.

//cc @ealonso @jkappler

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:um

**Comment by JessieZhao0714** [comment]
_java.lang.UnsupportedOperationException_ is thrown in **com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest** ([Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9385/modules-integration-mysql57-jdk8/2/3/jenkins-console.txt.gz?authuser=0)):
`[exec] com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest > testGetUserAccountByEmailAddress STARTED
     [exec] 2023-09-12 15:19:53.956 ERROR [http-nio-8080-exec-3][ExceptionMapper:59] null
     [exec] java.lang.UnsupportedOperationException: null
     [exec] 	at com.liferay.headless.admin.user.internal.resource.v1_0.UserAccountResourceImpl.getUserAccountByEmailAddress(UserAccountResourceImpl.java:386) ~[?:?]
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [exec] 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) [bundleFile:3.4.10]
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) [servlet-api.jar:4.0.FR]
     [exec] 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [bundleFile:3.4.10]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at com.liferay.portal.security.auth.verifier.internal.tracker.AuthVerifierFilterTracker$RemoteAccessFilter.doFilter(AuthVerifierFilterTracker.java:199) [bundleFile:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at com.liferay.portal.security.auth.verifier.internal.tracker.AuthVerifierFilterTracker$AuditFilter.doFilter(AuthVerifierFilterTracker.java:168) [bundleFile:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:138) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilter.processFilter(AuthVerifierFilter.java:203) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:71) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.doDispatch(HttpServiceRuntimeImpl.java:372) [org.eclipse.equinox.http.servlet-1.2.2.v20211118-0920.LIFERAY-PATCHED-1.jar:?]
     [exec] 	at com.liferay.portal.osgi.web.http.servlet.internal.servlet.HttpServletEndpointServlet.service(HttpServletEndpointServlet.java:57) [bundleFile:?]
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [servlet-api.jar:4.0.FR]
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkServletAdapter.service(ModuleFrameworkServletAdapter.java:45) [portal-impl.jar:?]
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [servlet-api.jar:4.0.FR]
     [exec] 	at com.liferay.shielded.container.internal.proxy.ServletWrapper.service(ServletWrapper.java:103) [com.liferay.shielded.container.impl.jar:?]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.75]
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.75]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:115) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:138) [portal-kernel.jar:?]
     [exec] 	at com.liferay.change.tracking.internal.servlet.filter.CTCollectionPreviewFilter.processFilter(CTCollectionPreviewFilter.java:56) [bundleFile:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:206) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:107) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:47) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:206) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:107) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:49) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:206) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:107) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:138) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:236) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:206) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:107) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:187) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:187) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) [portal-kernel.jar:?]
     [exec] 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [urlrewritefilter-4.0.4.jar:4.0.4]
     [exec] 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [urlrewritefilter-4.0.4.jar:4.0.4]
     [exec] 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [urlrewritefilter-4.0.4.jar:4.0.4]
     [exec] 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) [urlrewritefilter-4.0.4.jar:4.0.4]
     [exec] 	at com.liferay.portal.url.rewrite.filter.internal.URLRewriteFilter.processFilter(URLRewriteFilter.java:86) [bundleFile:?]
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:40) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:206) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:107) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:166) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:166) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:187) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:95) [portal-kernel.jar:?]
     [exec] 	at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:69) [com.liferay.shielded.container.impl.jar:?]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.75]
     [exec] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.75]
     [exec] 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.75]
     [exec] 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.75]
     [exec] 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-coyote.jar:9.0.75]
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.75]
     [exec] 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.75]
     [exec] 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.75]
     [exec] 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.75]
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.75]
     [exec] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
     [exec] 
     [exec] com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest > testGetUserAccountByEmailAddress FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-3,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:321)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)`

cc @oliverkecskemety and @ruben-pulido

**Comment by oliverkecskemety** [comment]
Hey @ruben-pulido,

Thank you for the changes but the tests still seems to be failing: https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/683308/testReport/

Can you check them please?

Thank you!

**Comment by ruben-pulido** [comment]
Hi @oliverkecskemety 

Thanks for the heads up. I'll go over them and update the PR

**Comment by ruben-pulido** [comment]
Hi @oliverkecskemety 
I have updated the PR again. I had forgotten to activate the feature flag for the tests. This last [commit](https://github.com/liferay-appsec/liferay-portal/pull/1374/commits/57475626bad3910c2ac6b1b2938307f89553668f) should fix it.

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:um

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:um

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:um

**Comment by alvarosaugarlr** [comment]
This pr continuous in https://github.com/liferay-appsec/liferay-portal/pull/1410

**Pull request closed without merging**
