### PR TITLE
LRQA-80484 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-80484

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
@melodywu , the Account component is related to the um test suite

**Comment by gaborlovasdotcom** [comment]
ci:test:um:nocompile

**Comment by gaborlovasdotcom** [comment]
@melodywu Could you please review the test fix:
[LocalFile.Account#CanRemoveUserFromPersonAccount](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120276//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Account_CanRemoveUserFromPersonAccount_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/LocalFile.Account_CanRemoveUserFromPersonAccount/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/LocalFile.Account_CanRemoveUserFromPersonAccount/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/jenkins-console.txt.gz)

**Comment by melodywu** [comment]
> ci:test:um:nocompile

thanks I will run ci:test:um:nocompile for um tests.

**Comment by melodywu** [comment]
ci:test:um

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Comment by melodywu** [comment]
> @melodywu Could you please review the test fix: [LocalFile.Account#CanRemoveUserFromPersonAccount](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/120276//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Account_CanRemoveUserFromPersonAccount_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/LocalFile.Account_CanRemoveUserFromPersonAccount/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/LocalFile.Account_CanRemoveUserFromPersonAccount/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11343/functional-tomcat90-mysql57-jdk8/1/4/jenkins-console.txt.gz)

Ok and Done

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
Forwarded to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/134899

**Pull request closed without merging**
