### PR TITLE
LPD-26151

### PR DESCRIPTION
**Pull request by ChrisKian**
Forwarded from https://github.com/liferay-appsec/liferay-portal/pull/1785 with SF commit squashed

Related Issue: [LPD-26151](https://liferay.atlassian.net/browse/LPD-26151)

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:forward

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
All failures seem to be related to this: `java.net.NoRouteToHostException: No route to host (Host unreachable)`

Seems to be a known issue, so we'll try running stable again.

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
Relevant and upgrade test failures look unrelated.  Forcing forward now.

**Comment by ChrisKian** [comment]
ci:forward:force

**Pull request closed without merging**
