### PR TITLE
LPS-156400 Hide Cookie configuration until release

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-156400](https://issues.liferay.com/browse/LPS-156400)

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:sf

**Comment by oliverkecskemety** [comment]
ci:relevant

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:security

**Review by gaborlovasdotcom — APPROVED** [review]
Manual testing passed.
The cookie setting doesn't appear in the Site menu, Instance menu, or System settings menu when the feature flag is not set.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
