### PR TITLE
LPD-25296 add wait for element present to fix AuthPromptInRequestScopeShouldNotBeVisible

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by cdbm** [comment]
ci:test:stable

**Review by ChrisKian — APPROVED** [review]
Looks good, requesting review from @stian-sigvartsen

**Review by stian-sigvartsen — APPROVED** [review]
LGTM @cdbm , Thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
