### PR TITLE
LPD-33235 Use of library with known vulnerability: Bouncy Castle 1.76

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-33235](https://liferay.atlassian.net/browse/LPD-33235)

This PR upgrades bouncycastle to version 1.78, previously tested as LPP-55026 in https://github.com/jgarcialr/liferay-portal/pull/85

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
The changes consist of updating the version of the library.
The dependencies have been updated. The tests of the affected modules have been validated to check the correctness:

- [PBKDF2PasswordEncryptor](https://testray.liferay.com/web/testray#/project/34754/routines/90235/build/56062567/case-result/56426590) for encryption - The test passes them in TestRay - PasswordEncryptorUtilTest.
- SAML - used for certificate creation for communication. For example, in test [LocalFile.SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithExistingUser](https://testray.liferay.com/web/testray#/project/34754/routines/90235/build/56062567/case-result/56427701) the certificate is created and used correctly (in CI it passed).
- Multifactor Authentication - Reviewing the related tests only one related to Email and one related to IP validation failed, but not related to Fido (where the library is used).

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
