### PR TITLE
LPD-15723 notify

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
@cdbm Please can you look into the CI test failures on this PR? 
That `ci:test:sf` failure is especially odd.

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
@ChrisKian I am trying ci:test:sf one more time, but it seems to keep failing on this PR.
I cannot see anything unusual in the Jenkins logs except that it fails ultimately. I don't know if you can spot anything?

**Comment by ChrisKian** [comment]
Found it @stian-sigvartsen:

```
format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA dc759adbccbd16ce262de46d761f1abfce16c688:
     [java] The commit message contains the word 'password', which could reveal potential security vulnerablities. Please see the vulnerability keywords that are specified in source-formatter.properties in the liferay-portal repository
```

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1267401_12808

**Comment by cdbm** [comment]
@stian-sigvartsen ci errors seem to be unrelated

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks for checking @cdbm . Then we just need to get it through the stable suite before forwarding.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
