### PR TITLE
LPS-199336 | master

### PR DESCRIPTION
**Pull request by GergoMathe**
[LPS-199336](https://liferay.atlassian.net/browse/LPS-199336)

### CODE REVIEW

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:scim:nocompile

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:scim

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forwarf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:scim

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop:scim

**Pull request closed without merging**
