### PR TITLE
[TS] LPS-135566 Allow root-relative Logout Redirect URL in Token Based SSO at instance level configuration

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-135566

Cannot configure a root-relative Logout Redirect URL in Token Based SSO at instance level configuration.

This problem is reproduced after the https://issues.liferay.com/browse/LPS-102185 changes.

Before that LPS, you were able to define a root-relative Logout Redirect URL at system level configuration.

This is necessary in case you have several site domains and you want to redirect to a generic page for every domain.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @jorgediaz-lr ! Forwarding...

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
