### PR TITLE
[TS] LPS-137638 allow s tag on sanitizer configuration

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi team,

Can you help review this PR?

**Notes from @leticia-maciel:**

> **Issue**: CKEditor uses the `<s>` tag to strike through the words on body text but Questions portlet and Message Board execute the Anti Sanitizer method before saving on the database and it was filtering the `<s>` tag. That was happening because the `sanitizer-configuration.xml` did not have the `<s>` tag added on its tag-rules to accept the tag and not filter it. 
> 
> **Fix**: The `<s>` tag was added on tag-rules on `sanitizer-configuration.xml` by `build.gradle`. Similar case on [LPS-91238](https://issues.liferay.com/browse/LPS-91238).

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @ericyanLr !

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
