### PR TITLE
LPS-177021 Modify implementation of GraphQLRequestContextValidator to improve the corner cases

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to improve some corner cases in which a request could be returned with a HTTP code different from 403 Forbidden.

The method `isValidationRequired` has been replaced with `isJaxRsResourceInvocation`, and the implementation of that method, by default returning `true`, is delegated to the developer that creates the implementation of the `ServletData` interface. By now, in Liferay there are two different implementation types of that interface:

- `StructuredContentGraphQLContributor`: Implementation of the `GraphQLContributor` interface that is adapted to the `ServletData` interface by the `ServletDataAdapter` registered. The implementation just returns an implementation that provides a new field `version` for the extended element `StructuredContent`. It is not invoking any JAX-RS resource, that is why the value of the `isJaxRsResourceInvocation` method returns false.
- `ServletDataImpl`: Auto-generated by REST Builder for all the REST APIs of Liferay created with REST Builder. It will not change the returned value, so it will be returned the default value : true. The default value is that because it is not allowed to include a breaking change for the customers that use REST Builder with previous versions.

How to test the `StructuredContentGraphQLContributor`:

For example with the following body:

```
query {
    admin {
        structuredContents(
            siteKey: "20121"
        )
        {
            items {
                title
                version {
                    number
                    status {
                        code
                    }
                }
            }
        }
    }
}

```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:security

**Comment by ccorreagg** [comment]
Push forced because of conflicts in baseline commit

**Comment by ccorreagg** [comment]
Any news?

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@ccorreagg forgot to say thank you for that really helpful PR description.

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Launched relevant again as it seems the vulcan-api version was not properly set, but it is weird as rebasing did not change anything

**Comment by stian-sigvartsen** [comment]
@ccorreagg maybe a `vulcan-api` release has happened in the mean time so we may need to bump the version?

**Comment by ccorreagg** [comment]
@stian-sigvartsen It should be fixed just by baselining :thinking: I am trying again

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
The error is no longer reproducible @stian-sigvartsen . I guess someone fixed it

**Comment by stian-sigvartsen** [comment]
Looks good now. I haven't checked the `CommentResourceTest` & `StructuredContentResourceTest` failures but from an AppSec components perspective this looks good to go.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
Agreed to forward with @ccorreagg . Thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
