### PR TITLE
LPS-123623 Add Portal CORS default configuration at System level

### PR DESCRIPTION
**Pull request by martamedio**
To solve this issue I think it's only necessary to add a default configuration associated to System Settings (blank _companyId_).

We're using _PortalCORSConfiguration_ class in two places:
1. On a [ModelListener](https://github.com/liferay-appsec/liferay-portal/blob/master/modules/apps/portal-remote/portal-remote-cors-impl/src/main/java/com/liferay/portal/remote/cors/internal/configuration/persistence/listener/PortalCORSConfigurationModelListener.java#L50) to validate the introduced values on the UI
2. On the [ServletFilter](https://github.com/liferay-appsec/liferay-portal/blob/master/modules/apps/portal-remote/portal-remote-cors-impl/src/main/java/com/liferay/portal/remote/cors/internal/servlet/filter/PortalCORSServletFilter.java#L302) to merge the multiple possible Configurations: we're creating a common configuration class based on the existing ones

Please @csierra & @arthurchan35, correct what you consider if I'm missing something.

Thanks!

### CODE REVIEW

**Comment by arthurchan35** [comment]
https://github.com/liferay-appsec/liferay-portal/blob/master/modules/apps/portal-remote/portal-remote-cors-impl/src/main/java/com/liferay/portal/remote/cors/internal/servlet/filter/PortalCORSServletFilter.java#L241

Maybe we can add something like this?
```
		PortalCORSConfiguration config = ConfigurableUtil.createConfigurable(
			PortalCORSConfiguration.class, new HashMapDictionary<>());
                if (!config.enable()) {
                     // feeding it an config of empty url-patterns
                }
```

**Comment by arthurchan35** [comment]
NVM my last comment, the default configuration created here: https://github.com/liferay-appsec/liferay-portal/blob/master/modules/apps/portal-remote/portal-remote-cors-impl/src/main/java/com/liferay/portal/remote/cors/internal/servlet/filter/PortalCORSServletFilter.java#L244
is enabled by default...

**Comment by arthurchan35** [comment]
ci:test:help

**Comment by arthurchan35** [comment]
Wait, can we make it disabled by default in configuration interface:
https://github.com/liferay-appsec/liferay-portal/blob/1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3/modules/apps/portal-remote/portal-remote-cors-api/src/main/java/com/liferay/portal/remote/cors/configuration/PortalCORSConfiguration.java#L37

**Comment by martamedio** [comment]
> Wait, can we make it disabled by default in configuration interface:
> https://github.com/liferay-appsec/liferay-portal/blob/1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3/modules/apps/portal-remote/portal-remote-cors-api/src/main/java/com/liferay/portal/remote/cors/configuration/PortalCORSConfiguration.java#L37

I do not see it necessary... I think it's useful: when somebody is going to add a configuration using the UI, the usual is that the user wants to leave it activated (we saved a click to the user).

Take into account that with this change we are only visually adding the default configuration that is added in the code itself, I don't think we need to change any existing behaviour.

**Review by csierra — COMMENTED** [review]
so can we just get rid of the part where we got the defaults from the metatype? If the GUI is not showing them and we are always going to provide a configuration file with the defaults we shoudl assume that, if the configuration is gone, the system should not have CORS enabled at all, right?
So in this case we should only take into account metatype defaults to populate the configuration interface, not to enable the feature by default and rely on actual configurations for that.

**Comment by martamedio** [comment]
> so can we just get rid of the part where we got the defaults from the metatype? If the GUI is not showing them and we are always going to provide a configuration file with the defaults we shoudl assume that, if the configuration is gone, the system should not have CORS enabled at all, right?
> So in this case we should only take into account metatype defaults to populate the configuration interface, not to enable the feature by default and rely on actual configurations for that.

Got it... So @arthurchan35 was right! We should disabled by default in configuration interface to work as you described

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
I wonder if we can test enabled here for everyone:
https://github.com/liferay-appsec/liferay-portal/pull/176/commits/3536788fe2ecefabe4350398098fb6f47f789450#diff-59b0496a7e9b86be120a8fb4375ec60b688384b4cb69c4428a1319e2897ce92dL312

instead of testing it only for default:
https://github.com/liferay-appsec/liferay-portal/pull/176/commits/3536788fe2ecefabe4350398098fb6f47f789450#diff-59b0496a7e9b86be120a8fb4375ec60b688384b4cb69c4428a1319e2897ce92dR245

**Comment by csierra** [comment]
hey @arthurchan35, @martamedio 

as we discussed we are going to leave the metatype defaults as enabled, so the default configuration and if someone adds a configuration from the GUI would have it enabled. 
What we discussed is to remove the current code in the CORS filter that pulls the defaults always from the metatype. Now, if the admin removes the default configuration, no CORS should be enabled.

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
hey @martamedio, @arthurchan35:

I pushed a couple of commits, please have a look at them to see if they are correct. 

otherwise it looks good to me...

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
