### PR TITLE
LPD-31949 Apply digest on PBKDF2

### PR DESCRIPTION
**Pull request by rafaprax**
- **LPD-31949 Create test to expose failure. SHA1 is applied even if SHA256 is indicated.**
- **LPD-31949 Use the proper digest based on the algorithm name.**
- **LPD-31949 SF**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:report:63973798

**Comment by manuelecastro** [comment]
Security suite unique failures are not related to the changes. This is good to go :+1: 

cc: @marianoalvarosaiz @rafaprax

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
