### PR TITLE
[TECHNICAL SUPPORT] LPS-150022 Duplicate error message on login page with multi-factor-auth

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-150022](https://issues.liferay.com/browse/LPS-150022),

This is the same issue that was already fixed in [LPS-86044](https://issues.liferay.com/browse/LPS-86044) just not for multi-factor authentication.

Unfortunately there is an ongoing issue on master [LPS-150234](https://issues.liferay.com/browse/LPS-150234), that prevents reproducing and testing this issue, however it can be tested on 7.3.x with the same codbase where the change was made.
Please test the issue on 7.3.x and review my changes.

Thanks,

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:mfa

**Comment by arthurchan35** [comment]
ci:test:mfa

**Comment by arthurchan35** [comment]
ci:help

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:mfa

**Comment by JoyceWang08211** [comment]
The above unique failure of [semantic-versioning-jdk8/0](https://testray.liferay.com/home/-/testray/case_results/1646581344) is not related to the current PR, it also exists on a[cceptance run](https://testray.liferay.com/home/-/testray/case_results/1646729300).

Need to wait for the test results of ci:test:mfa.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:mfa

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
