### PR TITLE
LPS-154744 Unit tests (SF)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1257401_4076

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Interesting that we didn't get those test failures on the previous run. We should review tomorrow.

**Comment by stian-sigvartsen** [comment]
No longer needed, the story is closed.

**Pull request closed without merging**
