### PR TITLE
LPS-148284 As a Site Administrator, I want the End User's cookie preferences to be considered at managing cookies on server side

### PR DESCRIPTION
**Pull request by moltam89**
cc @gaborlovasdotcom 

Hey guys,

This is the backend part of the cookie consent story, I'm planning to forward this to Brian.
I'm a bit confused by the **.lfrbuild-releng-ignore** , **.lfrbuild-portal** and **app.bnd** files, as I haven't created a separate module before, let me know if you know the exact rules for this. I'll look into this in the meantime.

I'm not sure what QA can do with this code, because this version of the backend shouldn't change the logic at all.
We'll need the UI part, which should store consent preferences in cookies.
Also the Site level OSGI configs are missing.
Furthermore we'll either need to update every _CookieKeys.addCookie_ call in the code base, or create a cookieName-type map, so we can pass in the type for the new API.

I included an Example usage commit, which marks languageIdCookie as functional. 
We can add a cookie via developer console, to simulate the UI part:
_document.cookie = "COOKIE_CONSENT_TYPE_FUNCTIONAL=false"_
In this case, the languageIdCookie shouldn't be stored.

**Note:**
I used the story ticket's [LPS-148284](https://issues.liferay.com/browse/LPS-148284) number, [LPS-148334](https://issues.liferay.com/browse/LPS-148334) might have been a better choice.

Best,
Tamas

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle:norebase

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
I've force pushed the rebased version.

Another small change is that I deleted the **.lfrbuild-releng-ignore** from the cookie folder, it should be enough to have it in cookie-consent-impl.

**app.bnd** seems fine to me according to our documentation, though I'm still not sure about **Liferay-Releng-Category: Productivity** and **Liferay-Releng-Suite: web-experience**, however ocne we'll have the UI ready these markers should be fine.

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
As discussed with @moltam89, we should add API call unit/integration tests for it.

**Comment by moltam89** [comment]
I'll resend this with the tests.

**Pull request closed without merging**
