### PR TITLE
LPS-127093

### PR DESCRIPTION
**Pull request by martamedio**
Hey @stian-sigvartsen 

This should address what we discussed this morning.

Thank you!

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:saml

**Comment by martamedio** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
