### PR TITLE
LPS-203417 Add integration tests for the available scim endpoints

### PR DESCRIPTION
**Pull request by rafaprax**
These changes depend on https://github.com/liferay-headless/liferay-portal/pull/1732

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Thanks @rafaprax . I understand we should wait with CI testing until LPS-203423 is merged.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
BChan merged the https://github.com/brianchandotcom/liferay-portal/pull/145182. So, when the sync happens, we can run the integration tests here.

/cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
Thanks @rafaprax ! I will rebase to those commits and review hopefully this afternoon

**Comment by rafaprax** [comment]
rebased.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward:force

**Pull request closed without merging**
