### PR TITLE
LRQA-76240 | master

### PR DESCRIPTION
**Pull request by weller0246**
[LRQA-76240](https://issues.liferay.com/browse/LRQA-76240)

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
The locator change will also affect on echo's testcases. Don't forget to do the reverse check. 
cc @weller0246

**Comment by JoyceWang08211** [comment]
ci:test:echo:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:echo:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:staging:nocompile
@JoyceWang08211  I created a new locator for this, because we use it on a different page than the echo team

**Comment by JoyceWang08211** [comment]
LGTM.
Testcase passed on Jenkins: https://testray.liferay.com/home/-/testray/case_results/1919052679

**Comment by weller0246** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:reevaluate:1267401_4173

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:forward

**Pull request closed without merging**
