### PR TITLE
Lps 162055 user mapper

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @weller0246 

I have fixed birthday bug you found.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by weller0246** [comment]
ci:test:bundle:nocompile

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
Part I of this PR has been merged

See https://github.com/liferay-appsec/liferay-portal/pull/845 for PART II

**Pull request closed without merging**
