### PR TITLE
LPS-157790 Initial merge with no impact on releases

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The unique failure of relevant run: [junit.framework.TestSuite.com.liferay.portal.kernel.util.StringBundlerTest](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200581//testReport/junit.framework/TestSuite/com_liferay_portal_kernel_util_StringBundlerTest) seem like that it's releated to CI issue https://issues.liferay.com/browse/LRCI-3168.

**Comment by JoyceWang08211** [comment]
The unique failure of relevant run [junit.framework.TestSuite.com.liferay.portal.kernel.util.StringBundlerTest](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200707//testReport/junit.framework/TestSuite/com_liferay_portal_kernel_util_StringBundlerTest) is a new test criterion which is introduced by https://issues.liferay.com/browse/LPS-158207.
This issue is also reported in https://issues.liferay.com/browse/LRQA-76614.

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@JoyceWang08211 Could you help verify it the failures are real?

**Comment by JoyceWang08211** [comment]
> HTTP 403 Forbidden

The unique failures in the relevant run are not related to current changes and they've been reported in https://issues.liferay.com/browse/LRQA-73764 and https://issues.liferay.com/browse/LPS-161532.

**Pull request closed without merging**
