### PR TITLE
LPS-189689 reset

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
Hey @stian-sigvartsen, saw your changes and I think it's all fine, its simpler now and makes more sense, Thank you! You can forward it, no problems from me.

**Comment by daiazius** [comment]
ci:forward:force

**Comment by daiazius** [comment]
ci:forward:force

**Comment by zsigmondrab** [comment]
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/141765

**Pull request closed without merging**
