### PR TITLE
LPS-170427 - Migrate oauth2 usages of sessionStorage to new API

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-165343](https://issues.liferay.com/browse/LPS-165343) - FI issue
- [LPS-170427](https://issues.liferay.com/browse/LPS-170427) - Appsec issue

### What is the goal?

* Migrate usages of `sessionStorage` in `oauth2-provider` to new consent-based API in `frontend-js-web`.

### Notes

If this is unexpected, here's some info on why you're getting this PR!

We've recently been making some changes to make Liferay comply with data legislation, such as GDPR. For this purpose, in Frontend Infrastructure we recently added some JS APIs that will only allow storing information in the user's device if they have consented to it, and this affects both Cookies and Web Storage (`localStorage`/`sessionStorage`).

For this specific case, we have found usages of `sessionStorage` in one of your modules, specifically `oauth2-provider-web`. We have replaced the usages with the utility exported from `frontend-js-web`, but this could require additional changes from your team:
1. We have assumed the consent type for your use case is `NECESSARY`, but that could be wrong. Please check that this is correct with the legal team.
2. If the consent type if different, **you must make additional changes** to make sure that the case where the **user hasn't accepted** that type of cookies is covered in the code. 

   If the user hasn't consented, when trying to set a value (`sessionStorage.setItem`) the method will return `false`, and when reading a value (`localStorage.getItem`) the method will return `undefined`. 
   
   You can check the consent status anywhere as follows:

   ```js
   // Where X ∈ {NECESSARY,FUNCTIONAL,PERFORMANCE,PERSONALIZATION}
   const hasConsent = Liferay.Util.Cookie.get(Liferay.Util.Cookie.TYPES.X, Liferay.Util.Cookie.TYPES.NECESSARY); 
   ```
   
   
### How to replicate
The cookie banner where you can set the consent preferences is currently behind a feature flag (`feature.flag.LPS-142518`), so to test this:
* Add `feature.flag.LPS-142518=true` to `portal-ext.properties`
* Restart portal
* Navigate to `Control Panel > System Settings > Cookies`
* Enable the cookie banner by checking the corresponding checkbox and click `Save`
* Cookie banner should now be visible

With this you should be able to check that everything is working as expected in all cases (with/without consent management enabled, with/without user consent).

Please let us know if you need any extra info for this.

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test:security

**Review by oliverkecskemety — APPROVED** [review]
LGTM! Thanks!

**Comment by oliverkecskemety** [comment]
ci:forward

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
Hi @tinycarol,

SF check seems to fail consistently because:
```
[exec] Out-of-date TypeScript build artifacts at:
[exec] 
[exec]     apps/object/object-web/types
[exec] 
[exec] Please commit them.
[exec] 
[exec] M modules/apps/object/object-web/types/src/main/resources/META-INF/resources/js/utils/string.d.ts
[exec] 
[exec] Preflight check failed:
[exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 1 project was out of date. Please commit updated versions of the artifacts in the projects listed above.
```

Can you check it please?

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:forward

**Comment by tinycarol** [comment]
Hi @oliverkecskemety! The issue with SF appears to be fixed after rebasing, but a test is failing in [com.liferay.oauth2.provider.client.test.AnnotatedApplicationPrefixHandlerClientTest](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359096/testReport/com.liferay.oauth2.provider.client.test/AnnotatedApplicationPrefixHandlerClientTest). Could you take a look?

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
