### PR TITLE
LPD-31128

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-31128](https://liferay.atlassian.net/browse/LPD-31128)

Hi Team,

Based on the original changes of Jorge, the PR contains multiple changes to stabilize tests.

Thanks for reviewing!

cc @alvarosaugarlr @jgarcialr @stian-sigvartsen

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:63667138

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
