### PR TITLE
LPD-24898 add null safety to disabled antisamy

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @cdbm,
I see you removed the exception throw from the method.  Was there a specific reason for this?

If it is no longer needed due to your changes, please include that in the commit message.  If it wasn't needed to begin with, please remove it in a different commit, again with a message explaining why.  Other than that, your changes look good.

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
Hi @ChrisKian, just updated the commits, thanks for the review

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @cdbm,
I'm having trouble reproducing this issue in master, could you verify the steps to reproduce are correct?

**Comment by cdbm** [comment]
Hi @ChrisKian the steps to reproduce are correct, i could reproduce it in b8309c3b03ada55d3d6c791842da708fd6fe2590

**Comment by ChrisKian** [comment]
Thanks @cdbm, I must have already had your changes applied.  I did find a small issue, but resolved it on my own.  See  https://github.com/liferay-appsec/liferay-portal/pull/1751

**Pull request closed without merging**
