### PR TITLE
[TS] LPS-196784 Redirect back to the Sign In widget instead of continuing to display the Forgot Pass or Create Account screens

### PR DESCRIPTION
**Pull request by jonathanmccann**
Resending as per https://github.com/brianchandotcom/liferay-portal/pull/141164#issuecomment-1731706233

Previously reviewed under https://github.com/liferay-appsec/liferay-portal/pull/1387

### CODE REVIEW

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by zsigmondrab** [comment]
ci:stop

**Comment by zsigmondrab** [comment]
ci:forward:force

**Comment by zsigmondrab** [comment]
ci:forward:force

**Comment by zsigmondrab** [comment]
@jonathanmccann, I cannot forward this even with force because of test failures. As I can see, they are not relevant and one of them is some StackOverflowError that I don't know what to do with. Could you please forward this to Brian directly?

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
