### PR TITLE
[TS] LPS-193127 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi team,

I send this PR with a redesign asked for @brianchandotcom in https://github.com/brianchandotcom/liferay-portal/pull/139758#issuecomment-1695749220

Regards

References:
Previous PR: https://github.com/liferay-appsec/liferay-portal/pull/1317
https://liferay.atlassian.net/browse/LPS-193127

### CODE REVIEW

**Comment by samanzanedo** [comment]
Hi team,

I wonder if somebody could review this PR. Just because customer is waiting for it.

Kind regards

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
Hi @nikolettabuza ,

Does this PR need anything from my side?

Regards

**Comment by nikolettabuza** [comment]
Hi @samanzanedo,
thanks for the explanation.
I'm currently looking into the cause of the test failures. No changes required at the moment, we can forward it if it is unrelated and the `stable` test suite has a `PASSED` status.

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
Hi @samanzanedo,
I opened the [new PR](https://github.com/liferay-appsec/liferay-portal/pull/1367#issue-1886993580) with an additional commit!

**Comment by samanzanedo** [comment]
Thanks for review, @nikolettabuza ! :-)

**Pull request closed without merging**
