### PR TITLE
LPS-193143 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-193143

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
