### PR TITLE
LPD-4056

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi @daiazius ,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/1599. Could you please review it?

I didn't make any change, because I see no related test failures.

Thank you!
Istvan

cc @zsigmondrab

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:playwright

**Comment by istvansajtos** [comment]
ci:reevaluate:1407401_9352

**Comment by istvansajtos** [comment]
@daiazius, FYI, OrderItemResourceTest failure is not related. The same test is passing when running locally.

**Review by daiazius — APPROVED** [review]
Test failures are indeed not related and the SEV is not reproducing either. LGTM!

**Comment by daiazius** [comment]
ci:forward:force

**Pull request closed without merging**
