### PR TITLE
[TS] LPS-196784 Redirect back to the Sign In widget instead of continuing to display the Forgot Password or Create Account screens

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-196784

When switching from the maximized screens of the Forgot Password or Create Account pages the Sign In widget continues to render those screens. By setting the back URL it will now switch back to the regular Sign In fields.

If there are any issues or concerns please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
Relevant failures are not connecting to the code changes

**Comment by zsigmondrab** [comment]
ci:forward:force

**Pull request closed without merging**
