### PR TITLE
LPS-75442 CI retest

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@jorgediaz-lr I am a bit concerned that in your previous PR vs your dummy upstream, many of the same tests were failing, but at different steps. Hopefully CI will give us some new results to compare soon.

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
I am going to double check the semantic versioning error just in case it is related to the new Exception created in this PR

**Comment by jorgediaz-lr** [comment]
Hi @stian-sigvartsen 

I have executed an `ant all` with latest master and there was a problem with the semantic versioning, I have sent a new PR with and updated Semver commit, see: https://github.com/liferay-appsec/liferay-portal/pull/410

**Comment by jorgediaz-lr** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
Thanks @jorgediaz-lr !

**Pull request closed without merging**
