### PR TITLE
LPS-164521 Unify SAML column lengths

### PR DESCRIPTION
**Pull request by achaparro**
Hi @liferay-appsec team,

We need you to make a decision about how to fix this issue with the SAML module. A customer reported this error:
`com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(75)`

And this happened in _SamlIdpSpSessionUpgradeProcess_ because we moved data from the following columns:
- SamlIdpSpSession.nameIdValue (VARCHAR 1024 char) -> SamlPeerBinding.samlNameIdValue (VARCHAR 75 char)
- SamlIdpSpSession.nameIdFormat (VARCHAR 1024 char) -> SamlPeerBinding.samlNameIdFormat (VARCHAR 75 char)
- SamlIdpSpSession.samlSpEntityId (VARCHAR 1024 char) -> SamlPeerBinding.samlPeerEntityId (VARCHAR 75 char)

As you can see, if the value stored in those columns is bigger than 75 chars we will get the mentioned error.

So @javalosjr96 implemented a direct solution, unifying SAML column lengths to 1024 (changes of this PR). However, this solution is not valid in Oracle because the maximum length for an index is 6398 bytes and we reached that limit when two of these columns are present, in this one for example:
`create index IX_E642E1AE on SamlPeerBinding (companyId, deleted, samlNameIdFormat[$COLUMN_LENGTH:1024$], samlNameIdNameQualifier[$COLUMN_LENGTH:75$], samlNameIdValue[$COLUMN_LENGTH:1024$], samlPeerEntityId[$COLUMN_LENGTH:1024$]);
`
Remember that 1024 chars in oracle and UTF8 can reach 1024 * 4 bytes = 4096 bytes)

So I would like to ask you for other options:
1. Can we reduce the size of those columns to 400 chars for example? (we can deal with customers with higher sizes during an upgrade)
2. Do you need those finders that generate the indexes?
3. Another option is using TEXT fields but I'd rather save unnecessary database space when possible.

Thanks.

- Tickets:
https://issues.liferay.com/browse/LPS-164521
https://issues.liferay.com/browse/LPP-46542

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @liferay-appsec,

Could you check my previous comment?

Thanks.

cc/ @javalosjr96

**Comment by achaparro** [comment]
Hi @javalosjr96,

I have been talking to @alvarosaugarlr regarding this pull request and they can't reduce the length of the fields since that's defined by the standard. Another solution that came to our mind is to use the following property for oracle in the same way we are using it now for mysql or mariadb:
`database.string.index.max.length[oracle]=255`

This will solve the problem and I think limiting the varchar columns to 255 in non-unique indexes make sense since is enough to filter.

Can you try to add that to the portal.properties and test the pull locally and in the CI to see the results?

Thank you.

**Comment by javalosjr96** [comment]
@liferay-appsec 
Hi Team,
I encountered another issue if we try to use 1024 CHAR SIZE limits.

MySQL has the same limitation as Oracle, that being that the index key limit is 3072.

Notes from Alberto:
`we have three fields with 255 chars which can be up to 1020 bytes in UTF8 (255 * 4) so if the limit is 3072 in MySQL, just with another field we are going to pass the limit`

cc @achaparro

**Comment by alvarosaugarlr** [comment]
Hi @javalosjr96 ,

He understood that the property
`database.string.index.max.length
`
 was limiting the size of the index to the value indicated in the property, so what it does is to cut the size of the index.

**Comment by javalosjr96** [comment]
@alvarosaugarlr 
So how do we move forward with this solution?
You're comment doesn't help.

**Comment by alvarosaugarlr** [comment]
@javalosjr96 
I was asking to confirm. 
If the property does not solve the problem, we will try another solution because the sizes cannot be reduced.
Thanks for testing it!

**Comment by achaparro** [comment]
@javalosjr96 mentioned in Slack that the issue with Mysql could be a false positive, Jorge can you confirm it to take one solution or another?

**Comment by alvarosaugarlr** [comment]
After the results of the tests and the conversations we have had, we will change the finder so that the index has less fields. The fields removed from the index will be used by filtering in java.

**Comment by alvarosaugarlr** [comment]
Pr with the changes (of this pr and the ones needed to reduce the indexes) - https://github.com/liferay-uniform/liferay-portal/pull/861

**Pull request closed without merging**
