### PR TITLE
LPS-189689

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:security

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
Hi @daiazius . Sorry for the long wait for this review.
Generally it looks good and works well. I just refactored a little to simplify it. Can you have a look if you see any issues?

Please see liferay-appsec/liferay-portal/pull/1378

**Pull request closed without merging**
