### PR TITLE
LPS-166215 API for resource scopes checking

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
[LPS-166215](https://issues.liferay.com/browse/LPS-166215)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by stian-sigvartsen** [comment]
This PR represents the original design expectation where an API is exported so GraphQL can consume that into another module. However, this is unnecessary because they intend to provide an exported SPI in a GraphQL module, and we can implement that directly in the `oauth2-provider-rest` module.

Replaced by: liferay-appsec/liferay-portal/pull/877

**Pull request closed without merging**
