### PR TITLE
Lps 121461 new

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey Brian,
1. I have removed the comment that is no longer needed(the one with the typo word travesalling).
2. Regarding to changing class names, it seems there is some sort of conflicts between code coverage tool and JDK, which makes it impossible to have the class name you wanted (in such inheritance structure) with code coverage tool enabled, see https://liferay.slack.com/archives/C08SHT1M0/p1603426054007400

So I am adding https://github.com/liferay-appsec/liferay-portal/pull/152/commits/5e51f56bac469efc3d083397ddb5030d74639cb1 and https://github.com/liferay-appsec/liferay-portal/pull/152/commits/f0820625b1629c953596042713ceff210dbc123a
together.
So you can choose between:
1. Change the class name to add Correctness, but without enabling code coverage.
2. Do not change the class name, and keep the code coverage.

Carlos:
I added a `@ProviderType` annotation to prevent an excessive version bump. Let us know if this is allowed here. it is only build time dependency. 
I also increased the time limit of the base "performance" test because the simple case (which we are not using) has hit the limit at least once now (https://github.com/liferay-appsec/liferay-portal/pull/152#issuecomment-715326835)

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:forward

**Review by csierra — APPROVED** [review]

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:reopen

**Pull request closed without merging**
