### PR TITLE
[TS] LPS-173047 Anonymous users are exported to LDAP

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-173047](https://liferay.atlassian.net/browse/LPS-173047)

Hi,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/1358. I've added the commit https://github.com/liferay/liferay-portal/commit/35341f579e6921fa917a1d4c30702a0f79527179 to fix the regression mentioned [here](https://github.com/liferay-appsec/liferay-portal/pull/1358#issuecomment-1707584287).

Please let me know if you have any question.

Thank you,
Istvan

cc @oliverkecskemety @JoyceWang08211

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
c:test:security

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
The reent relevant test results contains the following upgrade test error:
[Testray](https://testray.liferay.com/home/-/testray/case_results/2425449238)
[Jenkins log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3302/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1/jenkins-console.txt.gz?authuser=0)
[Liferay log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3302/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1/liferay-log.txt.gz?authuser=0)
```
2023-09-15 13:39:32.936 ERROR [main][UpgradeStepRegistratorTracker:178] Failed upgrade process for module com.liferay.user.associated.data.web
com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.configuration.persistence.listener.ConfigurationModelListenerException: The listener com.liferay.user.associated.data.web.internal.configuration.persistence.listener.AnonymousUserConfigurationModelListener was unable to save configuration com.liferay.user.associated.data.web.internal.configuration.AnonymousUserConfiguration: An anonymous user is already defined for the company: 20097
```

**Comment by zsigmondrab** [comment]
Resent: https://github.com/liferay-appsec/liferay-portal/pull/1409

**Pull request closed without merging**
