### PR TITLE
LPS-163950 Lockout mechanism used in a denial of service attack

### PR DESCRIPTION
**Pull request by oliverkecskemety**
Missed some impact in previous PR.

Previous PRs:
https://github.com/liferay-appsec/liferay-portal/pull/969
https://github.com/liferay-appsec/liferay-portal/pull/1202
https://github.com/brianchandotcom/liferay-portal/pull/137286

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:security

**Review by stian-sigvartsen — APPROVED** [review]
Looks good to me! I will forward if CI agrees

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
