### PR TITLE
LPS-164371 Add Integration Test

### PR DESCRIPTION
**Pull request by quanhuynhces**
Hi team,
This PR is for adding integration test for [LPS-164371](https://issues.liferay.com/browse/LPS-164371) based on this comment https://github.com/brianchandotcom/liferay-portal/pull/126112#issuecomment-1311872182 by Brian Chan.
Please review and leave your comment.
Thanks,
Quan
cc @alvarosaugarlr

### CODE REVIEW

**Comment by quanhuynhces** [comment]
ci:test:sf

**Comment by quanhuynhces** [comment]
ci:test:sf

**Comment by quanhuynhces** [comment]
Hi @alvarosaugarlr,
Can you take a look to this PR? 
Thank you so much

**Comment by quanhuynhces** [comment]
Hi @gaborlovasdotcom,
Seem like Mr Saugar does not have time to review this PR. Could you take a look to this PR? 
Thank you so much!

**Comment by gaborlovasdotcom** [comment]
ci:test:usm

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:usm:stop

**Comment by gaborlovasdotcom** [comment]
ci:stop:usm

**Comment by gaborlovasdotcom** [comment]
@quanhuynhces could you please check the following test failure:

>      [exec] com.liferay.user.service.test.UserLocalServiceTest > testLockoutUser STARTED
[beanshell] 2022-12-02 08:56:16.432 ERROR [com.liferay.user.test-executor-thread][AuditMessage:139] Impersonated actions must be audited on the real user's ID
[beanshell] 2022-12-02 08:56:16,432 com.liferay.user.test-executor-thread ERROR An exception occurred processing Appender 7pOFS6jK org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.kernel.audit.AuditMessage, message=Impersonated actions must be audited on the real user's ID

**Comment by gaborlovasdotcom** [comment]
@stian-sigvartsen could you please help @quanhuynhces review the test failure?

**Comment by quanhuynhces** [comment]
Hi @gaborlovasdotcom @stian-sigvartsen,
I have updated the integration test. Please review it again!
Thank you.

**Comment by quanhuynhces** [comment]
ci:test:relevant

**Comment by quanhuynhces** [comment]
Hi @gaborlovasdotcom 
Could you take a look at my new update code. Many thanks.
cc @stian-sigvartsen

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
