### PR TITLE
LPD-35766 Set user in HttpSession for WebDAV requests

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPD-35766](https://liferay.atlassian.net/browse/LPD-35766)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
LGTM @nikolettabuza . When the CI testing passes we can forward

**Comment by stian-sigvartsen** [comment]
@shuyangzhou just wanted to highlight this PR whilst we are working on the test coverage because it is partially reverting your commit. Do you have any strong feelings about it?

**Comment by stian-sigvartsen** [comment]
After discussing it with @nikolettabuza , we can only forward this PR after we add a test for this behaviour. Because existing tests are not covering it. She will push additional commits when ready.

**Comment by shuyangzhou** [comment]
Just to confirm, the "basic_auth" and "digest_auth" paths are not going to be triggered for normal http(s) access, right? If this is only going to be invoked for WebDAV path (or some other non-http(s) paths), then this is fine, it should not re-add back the duplicated User setting for HttpSession.

**Comment by stian-sigvartsen** [comment]
I've just checked liferay-web.xml and it appears to be filtering more than just that. Even MainServlet for FORWARD/INCLUDE dispatches.
Would you prefer if we moved into WebDAVServlet to reflect the approach of MainServlet?

**Comment by shuyangzhou** [comment]
yes, if you can split the trigger path to not let them overlap, that will be best to avoid any unnecessary performance cost.

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:report:28441464

**Comment by jgarcialr** [comment]
PR looks good, no unique failures related.

cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
Looks good to me also! Thanks @nikolettabuza @jgarcialr !

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward:force

**Pull request closed without merging**
