### PR TITLE
Lps 121461 task

### PR DESCRIPTION
**Pull request by arthurchan35**
- Carlos:
hey Brian, here comes the addition of the missing multiple matches API for the URL mapper before it can be applied to filters. Please read Arthur's comments below regarding the tests and let us know if that's ok.
We have the `Consumer<T>` API because it is very handy for cases like the filter chain and it saves the time of building an unnecessary collection to return the results. Besides, it is very easy to provide a default method that returns the collection for those usages that would need it.

- Arthur:
Hey @brianchandotcom,
I know you didn't like using indexes for matching between path and expected patterns, but it's actually the logical way to do it. The previous way you used was very confusing in terms of how everything correlates to each other.
Also here in the commit of rewriting test, I have stated that it's okay to use index for patterns, because they are very stable once we finalized them. We don't have to update them at all in the future. We only need to add new paths for new test cases.

I think I have done sorting lines for test cases.

Another thing is, for all matches, the performance tests running on my machine showed that:
Simple:
    testGetValue() ~= 1340ms
    testConsumeValues() ~= 3425ms
    testConsumeValuesOrdered() ~= 3630ms
    testGetValues() ~= 4000ms

Dynamic:
    testGetValue() ~= 620ms
    testConsumeValues() ~= 650ms
    testConsumeValuesOrdered() ~= 730ms
    testGetValues() ~= 1200ms

Static:
    testGetValue() ~= 305ms
    testConsumeValues() ~= 370ms
    testConsumeValuesOrdered() ~= 550ms
    testGetValues() ~= 920ms

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
