### PR TITLE
Lps 157790 without tests

### PR DESCRIPTION
**Pull request by arthurchan35**
[LPS-157790](https://issues.liferay.com/browse/LPS-157790)

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:oauth2

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@gaborlovasdotcom @JoyceWang08211 
The failure seems not related, I ran an empty PR here and still seeing samilar failures:
https://github.com/liferay-appsec/liferay-portal/pull/815

**Comment by stian-sigvartsen** [comment]
@arthurchan35 s Please see liferay-appsec/liferay-portal/pull/816 for integrating some things I have from last week.

Are you convinced about the reorganization? I mean if we didn't want to store only the JWT ID, would you still do it? The previous state seemed to let the base class drive the logic more, but I'm not decided.

I see you left out the TOXTOU

**Comment by JoyceWang08211** [comment]
> @gaborlovasdotcom @JoyceWang08211 The failure seems not related, I ran an empty PR here and still seeing samilar failures: #815

Hi @arthurchan35, most of OAuth2 functional tests are failed on AppSec daily [runs](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1951503676&testrayCaseTypeId=101949&testrayComponentId=1310733455). Our QAs are working on analyzing these failures. As a result of this, we cannot determine if there is regression from the current changes or not. 
I suggest that don't forward this PR until QA finished all the analysis of OAuth2 functional failures.
cc @gaborlovasdotcom

**Pull request closed without merging**
