### PR TITLE
LPS-120269-PART-I-Make-URLMapper-Petra-Ready-TEST-FULLY-COVERED

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey Brian, 

we had discussed time ago with core infra folks that they are keeping 100% code coverage in petra libraries, so we are sending these commits first to have it fully covered. If you are ok with this we can send the two commits that we discussed as a followup, one moving and the other updating the usages. 
Let us know what you think. 

Carlos.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
