### PR TITLE
LPS-131518

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@martamedio @stian-sigvartsen 
Here is a bug I found in StaticSizeTrieURLPatternMapper during testing saml functional tests.

I understand the class is less easy to understand, and I have prepare another branch to simplify code readability for URLPatternMapper related class.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Good catch! 
LGTM, forwading...

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
