### PR TITLE
LPS-19999

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:saml

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:saml

**Comment by arthurchan35** [comment]
ci:test:saml:nocompile

**Comment by liferay-appsec** [comment]
@arthurchan35 as far as I can tell, Xalan was a dependency until org.opensaml:opensaml:2.6.4 . So I believe it is unused since.

On master I executed `b {saml-opensaml-integration bundle ID}` with GoGo shell and I wasn't able to see any imports of Xalan packages. Did you say you found this?

**Comment by arthurchan35** [comment]
> @arthurchan35 as far as I can tell, Xalan was a dependency until org.opensaml:opensaml:2.6.4 . So I believe it is unused since.
> 
> On master I executed `b {saml-opensaml-integration bundle ID}` with GoGo shell and I wasn't able to see any imports of Xalan packages. Did you say you found this?

Hey thanks for looking!
But can I know who are you?

**Comment by stian-sigvartsen** [comment]
@arthurchan35 it was me :)

**Comment by arthurchan35** [comment]
> @arthurchan35 as far as I can tell, Xalan was a dependency until org.opensaml:opensaml:2.6.4 . So I believe it is unused since.
> 
> On master I executed `b {saml-opensaml-integration bundle ID}` with GoGo shell and I wasn't able to see any imports of Xalan packages. Did you say you found this?

So this could be another sold evidence to prove the dependency not used by the module right?
We can probably leave message of this in the ticket as well.
And assign reviewer to Dante Wang

**Comment by stian-sigvartsen** [comment]
Yes, I believe so. Without 51a8165d135 because that was only for debugging.

**Pull request closed without merging**
