### PR TITLE
LPD-35832 Allow configuration of ui_locale parameter in lowercase (AD B2C restriction)

### PR DESCRIPTION
**Pull request by jgarcialr**
This PR aims to solve the problem of sending ui_locales langTag in lowercase, this is required by azure AD B2C.

We will read from System/Instance Settings Configuration
imagen

In OAuthClientAdministration Portlet, the value has to be filled as:
imagen

Accepted values are:
`$DISABLED$ , $LOWERCASE_BCP47_LANGUAGE_CODE$`

Expected behavior:

DISABLED:

/auth/realms/master/protocol/openid-connect/auth?scope=openid+email+profile&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fc%2Fportal%2Flogin%2Fopenidconnect&state=kbJxEpo-xdcM4w-kTO4dRxExq0nfL6PBFoOhmIzK9kg&code_challenge_method=S256&ui_locale=%24LOWERCASE_BCP47_LANGUAGE_CODE%24&nonce=uC_geb4QLgVZWw4FoB-kSusKtyg0o2J-AAq09T7VJrs&client_id=liferay-limited-session&code_challenge=j5LnomZKcDOhe3CJpb049o1GNhMCXcy5qPx6M4Ttb9M

LOWERCASE_BCP47_LANGUAGE_CODE:

/auth/realms/master/protocol/openid-connect/auth?**ui_locales=en-us**&scope=openid+email+profile&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fc%2Fportal%2Flogin%2Fopenidconnect&state=kbJxEpo-xdcM4w-kTO4dRxExq0nfL6PBFoOhmIzK9kg&code_challenge_method=S256&ui_locale=%24LOWERCASE_BCP47_LANGUAGE_CODE%24&nonce=uC_geb4QLgVZWw4FoB-kSusKtyg0o2J-AAq09T7VJrs&client_id=liferay-limited-session&code_challenge=j5LnomZKcDOhe3CJpb049o1GNhMCXcy5qPx6M4Ttb9M

DEFAULT behavior (according to OIDC standard):

/auth/realms/master/protocol/openid-connect/auth?**ui_locales=en-US**&scope=openid+email+profile&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fc%2Fportal%2Flogin%2Fopenidconnect&state=kbJxEpo-xdcM4w-kTO4dRxExq0nfL6PBFoOhmIzK9kg&code_challenge_method=S256&ui_locale=%24LOWERCASE_BCP47_LANGUAGE_CODE%24&nonce=uC_geb4QLgVZWw4FoB-kSusKtyg0o2J-AAq09T7VJrs&client_id=liferay-limited-session&code_challenge=j5LnomZKcDOhe3CJpb049o1GNhMCXcy5qPx6M4Ttb9M

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
This workaround is no longer needed by the customer, but I have recreated the PR on my personal fork for future reference. See stian-sigvartsen/liferay-portal/pull/301

**Pull request closed without merging**
