### PR TITLE
[TS] LPS-133357 Unexpected format for whitelisting JSONWS API paths

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

For an explanation of the changes please consult the description of the LPS.
https://issues.liferay.com/browse/LPS-133357

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

The test failures are not related to the solution.

Best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
