### PR TITLE
LPS-145191

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
> 

The above functional failures are not related to the current changes.

**Comment by arthurchan35** [comment]
resolve bnd merge conflicts

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by arthurchan35** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/623

**Comment by JoyceWang08211** [comment]
Caught a unique [integration failure](https://testray.liferay.com/home/-/testray/case_results/1667584377):
```
[exec] com.liferay.oauth2.provider.client.test.HttpMethodApplicationClientTest > testIgnoredMethods FAILED
     [exec]     java.lang.AssertionError: expected:<200> but was:<403>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.oauth2.provider.client.test.HttpMethodApplicationClientTest.testIgnoredMethods(HttpMethodApplicationClientTest.java:99)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
```
Detailed [console log](https://testray.liferay.com/reports/production/logs/2022-04/test-1-34/test-portal-acceptance-pullrequest(master)/1561/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0).

@arthurchan35 Could you take a look? Thx

**Pull request closed without merging**
