### PR TITLE
LPS-152126 LPS-157406 LPS-150933 LPS-162107 LPS-170861 | SAML Admin REST tests (+ follow ups) - rebased

### PR DESCRIPTION
**Pull request by JoyceWang08211**
cc @stian-sigvartsen and @gaborlovasdotcom

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
All the SAML test cases passed on Jenkins:
https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2182513647&testrayCaseTypeId=101949&testrayComponentId=1310779464

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1397401_2664

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
The failures in relevant run are not related to current changes.

**Comment by JoyceWang08211** [comment]
Sent to BChan directly.
https://github.com/brianchandotcom/liferay-portal/pull/129605

**Pull request closed without merging**
