### PR TITLE
LPS-176527 PortalImpl.getUserId() returning 0 for AuthVerifier authenticated requests

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:commerce

**Comment by gaborlovasdotcom** [comment]
Starting commerce tests fyi: @victoroscuro

**Comment by stian-sigvartsen** [comment]
The ScopeMapperNarrowDownClientTest passes locally and appears to be flaky when looking at execution history. So we can forward this PR once the Commerce tests pass.

**Comment by victoroscuro** [comment]
@stian-sigvartsen @gaborlovasdotcom this is good to go. Thanks

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
