### PR TITLE
Preliminary AuthVerifier PR

### PR DESCRIPTION
**Pull request by csierra**
hey @arthurchan35, 

this is another attempt to fix the double tracking. I believe this goes in the correct direction and _most_ of the tests work. There are still a couple of them that fail but we can keep on working on those tomorrow. 

Please let me know your thoughts about this approach. 

Carlos.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@csierra 
I pushed two commits to optimize certain area in code.

There are serveral other smaller things I wanted to do but didnt do because I was stuck on portal_property_prefix.

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test

**Comment by csierra** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/239

**Pull request closed without merging**
