### PR TITLE
LRQA-75529 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-75529

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, waiting for test results.

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Pull request closed without merging**
