### PR TITLE
LPS-122673 LAX cookies are sent with top level navigation requests using GET

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
Functional test failures are unrelated / environmental.

**Comment by csierra** [comment]
ci:forward

**Review by csierra — APPROVED** [review]
LGTM

**Pull request closed without merging**
