### PR TITLE
LPS-148998 Add 1 minute to end date in Audit

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-148998](https://issues.liferay.com/browse/LPS-148998)

Add 1 minute to the end date field, to find log in the actual minute

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:security - 243 out of 261 jobs passed in 2 hours 21 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [1576ea8c7f4c6b75f39b7a323977ea1d36a4146c](https://github.com/liferay/liferay-portal/commit/1576ea8c7f4c6b75f39b7a323977ea1d36a4146c)
> 
> #### Upstream Comparison:
> Branch GIT ID: [1576ea8c7f4c6b75f39b7a323977ea1d36a4146c](https://github.com/liferay/liferay-portal/commit/1576ea8c7f4c6b75f39b7a323977ea1d36a4146c)Jenkins Build URL: [Acceptance Upstream DXP (master) #3578](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3578)
> 
> **ci:test:security - 243 out of 261 jobs PASSED**
> ##### For more details click [here](https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4091/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/0/8](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128134//consoleText)[beanshell] 
>    [beanshell]     [maven-release-plugin] prepare release pluto-3.1.0
>    [beanshell] 
>    [beanshell] 
>    [beanshell] commit deb2fd4ce696bd7f48df7166acb8afa1a1ef4afe
>    [beanshell] Author: Lawrence Lee <lawrence.lee@liferay.com>
>    [beanshell] Date:   Mon Apr 2 09:51:43 2018 -0500
>    [beanshell] 
>    [beanshell]     revert to 2.x version of blade for legacy support tests
>    [beanshell] 
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] 
>    [beanshell] commit c71a9c1a9c556f40b9a3a202b34158d5cd9026cb
>    [beanshell] Author: Leslie Wong <leslie.wong@liferay.com>
>    [beanshell] Date:   Thu Jul 14 18:30:31 2022 -0700
>    [beanshell] 
>    [beanshell]     LRAC-11481 Update test resources
>    [beanshell] 
>    [beanshell] 
>    [beanshell] commit 9a482017d2fb59f6f8ce13569835cc4c50a783b2
>    [beanshell] Author: Liferay Continuous Integration <continuous-integration@liferay.com>
>    [beanshell] Date:   Wed Jul 20 02:48:12 2022 -0700
>    [beanshell] 
>    [beanshell]     Commit cache
>    [beanshell] 
>    [beanshell] Executing commands: git clean -dfx
>    [beanshell] 
>    [beanshell] commit 57d08f2ed83887bfbdf844736a49a35be910f656
>    [beanshell] Author: liferay-translation-ac <84350547+liferay-translation-ac@users.noreply.github.com>
>    [beanshell] Date:   Wed Jul 13 03:58:55 2022 -0700
>    [beanshell] 
>    [beanshell]     New translations Language.properties (Portuguese, Brazilian)
>    [beanshell] 
>    [beanshell] Executing commands: git branch | grep \*
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] 
>    [beanshell] commit 619bdce97ecc32b38c388b38429a9e1f8b00d869
>    [beanshell] Author: Liferay Translation <lta@liferay.com>
>    [beanshell] Date:   Wed Jul 20 14:44:03 2022 +0000
>    [beanshell] 
>    [beanshell]     LPS-77699 Update Translations
>    [beanshell] 
>    [beanshell] Executing commands: git branch | grep \*
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] 
>    [beanshell] commit 1576ea8c7f4c6b75f39b7a323977ea1d36a4146c
>    [beanshell] Author: Liferay Translation <lta@liferay.com>
>    [beanshell] Date:   Thu Jul 21 10:13:02 2022 +0000
>    [beanshell] 
>    [beanshell]     LPS-77699 Update Translations
>    [beanshell] 
>    [stopwatch] [stop.current.job: 8.367 sec]
>    BUILD SUCCESSFUL
>    Total time: 10 seconds
>    
>    * echo 'Exit shell.'
>      Exit shell.
>      Finished: FAILURE
> 2. [functional-tomcat90-mysql57-jdk8/3/23](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116881//consoleText)[beanshell] Executing commands: git clean -dfx
>    [beanshell] Executing commands: git log -n 1
>    [beanshell] Executing commands: git log -n 1
>    [beanshell]
>    [beanshell] commit c71a9c1a9c556f40b9a3a202b34158d5cd9026cb
>    [beanshell] Author: Leslie Wong <[leslie.wong@liferay.com](mailto:leslie.wong@liferay.com)>
>    [beanshell] Date:   Thu Jul 14 18:30:31 2022 -0700
>    [beanshell]
>    [beanshell]     LRAC-11481 Update test resources
>    [beanshell]
>    [beanshell]
>    [beanshell] commit 57d08f2ed83887bfbdf844736a49a35be910f656
>    [beanshell] Author: liferay-translation-ac <[84350547+liferay-translation-ac@users.noreply.github.com](mailto:84350547+liferay-translation-ac@users.noreply.github.com)>
>    [beanshell] Date:   Wed Jul 13 03:58:55 2022 -0700
>    [beanshell]
>    [beanshell]     New translations Language.properties (Portuguese, Brazilian)
>    [beanshell]
>    [beanshell] Executing commands: git branch | grep *
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell]
>    [beanshell] commit 9a482017d2fb59f6f8ce13569835cc4c50a783b2
>    [beanshell] Author: Liferay Continuous Integration <[continuous-integration@liferay.com](mailto:continuous-integration@liferay.com)>
>    [beanshell] Date:   Wed Jul 20 02:48:12 2022 -0700
>    [beanshell]
>    [beanshell]     Commit cache
>    [beanshell]
>    [beanshell] Executing commands: git reset --hard 22411abd9875742b0d5eeb0c54ea8f94c0741166
>    [beanshell] Executing commands: git clean -dfx
>    [beanshell] Executing commands: git reset --hard 619bdce97ecc32b38c388b38429a9e1f8b00d869
>    [beanshell] Executing commands: git branch | grep *
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell]
>    [beanshell] commit 22411abd9875742b0d5eeb0c54ea8f94c0741166
>    [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>    [beanshell] Date:   Wed Jul 20 10:11:42 2022 +0000
>    [beanshell]
>    [beanshell]     LPS-77699 Update Translations
>    [beanshell]
>    [beanshell] Executing commands: git clean -dfx
>    [beanshell] Executing commands: git branch | grep *
>    [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>    [beanshell] Executing commands: git log -n 1
>    [beanshell]
>    [beanshell] commit 619bdce97ecc32b38c388b38429a9e1f8b00d869
>    [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>    [beanshell] Date:   Wed Jul 20 14:44:03 2022 +0000
>    [beanshell]
>    [beanshell]     LPS-77699 Update Translations
>    [beanshell]
>    [stopwatch] [stop.current.job: 12.608 sec]
> BUILD SUCCESSFUL Total time: 14 seconds
> 
> * echo 'Exit shell.'
>   Exit shell.
>   Finished: FAILURE
> * [functional-tomcat90-mysql57-jdk8/8/22](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115426//consoleText)[beanshell] Date:   Fri Jul 15 10:32:34 2022 -0400
>   [beanshell]
>   [beanshell]     [maven-release-plugin] prepare for next development iteration
>   [beanshell]
>   [beanshell]
>   [beanshell] commit 9c4099e6a0ec05851f4aa05d9d11ba31945a64b6
>   [beanshell] Author: Neil Griffin <[neil.griffin.scm@gmail.com](mailto:neil.griffin.scm@gmail.com)>
>   [beanshell] Date:   Fri Jul 15 12:03:11 2022 -0400
>   [beanshell]
>   [beanshell]     [maven-release-plugin] prepare for next development iteration
>   [beanshell]
>   [beanshell] Executing commands: git log -n 1
>   [beanshell] Executing commands: git log -n 1
>   [beanshell] Executing commands: git clean -dfx
>   [beanshell] Executing commands: git log -n 1
>   [beanshell]
>   [beanshell] commit c71a9c1a9c556f40b9a3a202b34158d5cd9026cb
>   [beanshell] Author: Leslie Wong <[leslie.wong@liferay.com](mailto:leslie.wong@liferay.com)>
>   [beanshell] Date:   Thu Jul 14 18:30:31 2022 -0700
>   [beanshell]
>   [beanshell]     LRAC-11481 Update test resources
>   [beanshell]
>   [beanshell]
>   [beanshell] commit 9a482017d2fb59f6f8ce13569835cc4c50a783b2
>   [beanshell] Author: Liferay Continuous Integration <[continuous-integration@liferay.com](mailto:continuous-integration@liferay.com)>
>   [beanshell] Date:   Wed Jul 20 02:48:12 2022 -0700
>   [beanshell]
>   [beanshell]     Commit cache
>   [beanshell]
>   [beanshell]
>   [beanshell] commit 57d08f2ed83887bfbdf844736a49a35be910f656
>   [beanshell] Author: liferay-translation-ac <[84350547+liferay-translation-ac@users.noreply.github.com](mailto:84350547+liferay-translation-ac@users.noreply.github.com)>
>   [beanshell] Date:   Wed Jul 13 03:58:55 2022 -0700
>   [beanshell]
>   [beanshell]     New translations Language.properties (Portuguese, Brazilian)
>   [beanshell]
>   [beanshell] Executing commands: git branch | grep *
>   [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>   [beanshell] Executing commands: git log -n 1
>   [beanshell] Executing commands: git branch | grep *
>   [beanshell]
>   [beanshell] commit 619bdce97ecc32b38c388b38429a9e1f8b00d869
>   [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>   [beanshell] Date:   Wed Jul 20 14:44:03 2022 +0000
>   [beanshell]
>   [beanshell]     LPS-77699 Update Translations
>   [beanshell]
>   [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>   [beanshell] Executing commands: git log -n 1
>   [beanshell]
>   [beanshell] commit 22411abd9875742b0d5eeb0c54ea8f94c0741166
>   [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>   [beanshell] Date:   Wed Jul 20 10:11:42 2022 +0000
>   [beanshell]
>   [beanshell]     LPS-77699 Update Translations
>   [beanshell]
>   [stopwatch] [stop.current.job: 8.456 sec]
> 
> BUILD SUCCESSFUL Total time: 9 seconds
> 
> * echo 'Exit shell.'
>   Exit shell.
>   Finished: FAILURE
> * [modules-semantic-versioning-jdk8/0/4](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/139151//consoleText)[beanshell]
>   [beanshell]
>   [beanshell] commit ae2b8981c18b22953e5d4407678c23892eba9abc
>   [beanshell] Author: Liferay Continuous Integration <[continuous-integration@liferay.com](mailto:continuous-integration@liferay.com)>
>   [beanshell] Date:   Thu Jul 14 23:34:38 2022 -0700
>   [beanshell]
>   [beanshell]     archive:ignore Update 'data-archive-remote-staging-with-blogs-entries' for '7.1.10.5' at 4678d8e.
>   [beanshell]
>   [beanshell]
>   [beanshell] commit 57d08f2ed83887bfbdf844736a49a35be910f656
>   [beanshell] Author: liferay-translation-ac <[84350547+liferay-translation-ac@users.noreply.github.com](mailto:84350547+liferay-translation-ac@users.noreply.github.com)>
>   [beanshell] Date:   Wed Jul 13 03:58:55 2022 -0700
>   [beanshell]
>   [beanshell]     New translations Language.properties (Portuguese, Brazilian)
>   [beanshell]
>   [beanshell]
>   [beanshell] commit c71a9c1a9c556f40b9a3a202b34158d5cd9026cb
>   [beanshell] Author: Leslie Wong <[leslie.wong@liferay.com](mailto:leslie.wong@liferay.com)>
>   [beanshell] Date:   Thu Jul 14 18:30:31 2022 -0700
>   [beanshell]
>   [beanshell]     LRAC-11481 Update test resources
>   [beanshell]
>   [beanshell] Executing commands: git branch | grep *
>   [beanshell] Executing commands: git clean -dfx
>   [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>   [beanshell] Executing commands: git log -n 1
>   [beanshell]
>   [beanshell] commit 9a482017d2fb59f6f8ce13569835cc4c50a783b2
>   [beanshell] Author: Liferay Continuous Integration <[continuous-integration@liferay.com](mailto:continuous-integration@liferay.com)>
>   [beanshell] Date:   Wed Jul 20 02:48:12 2022 -0700
>   [beanshell]
>   [beanshell]     Commit cache
>   [beanshell]
>   [beanshell] Executing commands: git clean -dfx
>   [beanshell] Executing commands: git branch | grep *
>   [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>   [beanshell] Executing commands: git log -n 1
>   [beanshell]
>   [beanshell] commit 619bdce97ecc32b38c388b38429a9e1f8b00d869
>   [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>   [beanshell] Date:   Wed Jul 20 14:44:03 2022 +0000
>   [beanshell]
>   [beanshell]     LPS-77699 Update Translations
>   [beanshell]
>   [beanshell] Executing commands: git branch | grep *
>   [beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
>   [beanshell] Executing commands: git log -n 1
>   [beanshell]
>   [beanshell] commit 1576ea8c7f4c6b75f39b7a323977ea1d36a4146c
>   [beanshell] Author: Liferay Translation <[lta@liferay.com](mailto:lta@liferay.com)>
>   [beanshell] Date:   Thu Jul 21 10:13:02 2022 +0000
>   [beanshell]
>   [beanshell]     LPS-77699 Update Translations
>   [beanshell]
>   [stopwatch] [stop.current.job: 15.896 sec]
> 
> BUILD SUCCESSFUL Total time: 17 seconds
> 
> * echo 'Exit shell.'
>   Exit shell.
>   Finished: FAILURE
> * [functional-tomcat90-mysql57-jdk8/3/6](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/139148//consoleText)1. [LocalFile.Audit#VerifyCorrectClientIP](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/139148//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Audit_VerifyCorrectClientIP_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4091/functional-tomcat90-mysql57-jdk8/3/6/LocalFile.Audit_VerifyCorrectClientIP/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4091/functional-tomcat90-mysql57-jdk8/3/6/LocalFile.Audit_VerifyCorrectClientIP/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4091/functional-tomcat90-mysql57-jdk8/3/6/jenkins-console.txt.gz)
> * ...

No unique failure in ci:test:security run.

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@RenanUmV sorry we missed this PR for so long. Looks good.

**Comment by RenanUmV** [comment]
No problem, I didn't know I had to assign the LPS for the Product Team App Security

**Comment by stian-sigvartsen** [comment]
Sometimes we don't review PRs until CI tests have passed, because it is not clear if these have passed already on another fork without some comment or similar. So assigning the ticket helps make the status/intent clearer.

Thanks for fixing the issue 👍

**Pull request closed without merging**
