### PR TITLE
LPS-111617 Adding optimized matchers

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
hey Arthur, I pushed the branch to liferay-appsec repo so we can both push commits if we need to

**Comment by csierra** [comment]
you don't have to if you don't want to :sweat_smile: , just in case you find it useful

**Comment by arthurchan35** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/33

**Pull request closed without merging**
