### PR TITLE
[TS] LPS-115406 use unique id for input dates

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-115406

Hi Team,

Can you help review this PR regarding the Audit portlet? From my understanding, this part of the component is under Application Security. 

Please let us know if you have any questions.
Thanks!

/cc  @NemethNorbert

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
LGTM, thanks @ericyanLr and @NemethNorbert

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
