### PR TITLE
LPS-156903,LPS-153615 | Cookie configuration adjustments

### PR DESCRIPTION
**Pull request by oliverkecskemety**
**[LPS-156903](https://issues.liferay.com/browse/LPS-156903) Order the configuration menu entries better** - Move `Banner` and `Consent Panel` configuration interfaces into their own package to make `Preference Handling` always appear as first item in the sidebar.
**[LPS-153615](https://issues.liferay.com/browse/LPS-153615) Consent Panel can be saved with blank title and description** - Mark all fields as required (even checkboxes to avoid changing the order of items)

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:cookies

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
@oliverkecskemety could you please split up the PR, as [LPS-153615](https://issues.liferay.com/browse/LPS-153615) issue is still reproducible, thank you!

**Pull request closed without merging**
