### PR TITLE
[TS] LPS-136273 Profile picture is missing frontend side size validation

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by stian-sigvartsen** [comment]
Looks good @IstvanD . It highlighted a related issue which I will raise another ticket for.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
