### PR TITLE
LPS-159334 Add audit message for a failed authentication when the user does not exist and refactor AuthFailure

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPS-159334](https://issues.liferay.com/browse/LPS-159334)
A previous PR was already reviewed and forwarded. This PR only contains additional refactoring.

------
Reviewed [PR](https://github.com/liferay-appsec/liferay-portal/pull/1133)
Next [PR](https://github.com/liferay-appsec/liferay-portal/pull/1156)
Forwarded [PR and notes](https://github.com/brianchandotcom/liferay-portal/pull/136182#issuecomment-1588732735) on refactoring

----
Note:
The keys (`auth.failure`,`auth.max.failures`) of all the `AuthFailure` implementations are required because of `AuthPipeline._onFailure` as this method can be called in `UserLocalServiceImpl.handleAuthenticationFailure` with any of the keys. So we need to be able to select specific services by their respective keys otherwise we end up executing all three implementations of `AuthFailure.onFailureByEmailAddress` when in reality only the ones related to `auth.failure` or the one related to `auth.max.failures` should be called, resulting in unwanted behaviour.

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:security

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
