### PR TITLE
[TS] LPS-130609 prefix and suffix are not exported to LDAP

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-130609](https://issues.liferay.com/browse/LPS-130609)
Dear Team,

Please review my changes.

The issue is that user prefix and suffix are not exported to LDAP. Prefix and suffix are of type ListType. In Contact we store only the ids (prefixId and suffixId fields) but we should export the actual values to LDAP.

A conversion is already implemented for import ([in DefaultLDAPToPortalConverter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security/portal-security-ldap-impl/src/main/java/com/liferay/portal/security/ldap/internal/exportimport/DefaultLDAPToPortalConverter.java#L178-L190)) and my changes do the conversion for the opposite direction.

Thank you,
István

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant:norebase

**Comment by istvansajtos** [comment]
ci:test:ldap:norebase

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
