### PR TITLE
LPD-18448 Increase field values to be compatible with SHA-384/hex mix

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-18448](https://liferay.atlassian.net/browse/LPD-18448)

Increased the field values that can contain the result of SHA-384/hex mix (values that come from PasswordEncryptor.Encrypt()):

- User - _password
- PasswordTracker - _password
- Ticket - _key

Original comment:
> **Description:**
> When using SHA-384 as encryption algorithm and hex as digest encoding, it generates a string that is over the size set for it on the database (75 characters).
> 
> 
> **Proposed solution:**
> To solve this, I increased the password_ column size so it can support the SHA-384/Hex mix, which generates a 96 long string plus 9 characters from the prefix("{SHA-384}") resulting in a 105 characters string.
>
> Original PR: https://github.com/liferay-appsec/liferay-portal/pull/1668

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
Triggering relevant to check if any other field needs to have their value increased.

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:upgrade

**Comment by manuelecastro** [comment]
Failures don't seem related to the changes. Triggering tests again with the default portal properties now

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
Failures are not related to the changes :)

**Comment by cdbm** [comment]
Hi @manuelecastro , looks good to me, however there are conflicting files

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
@cdbm I just noticed that CI did not triggered the relevant suite and the branch has conflicts again... I'm going to rebase this and try re-triggering CI :)

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:stable

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
I'm opening a new PR to this due to the issues we're having with CI here.

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
resent here: https://github.com/liferay-appsec/liferay-portal/pull/1754

**Pull request closed without merging**
