### PR TITLE
LPD-23115

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-23115

Last PR: https://github.com/liferay-appsec/liferay-portal/pull/1766

I've reworked the logic quite a bit, and added a few tests. Poshi tests mostly work locally, and only fail due to local issues (I hope). I'll run and adjust them here until everything works.

Resending since CI wasn't liking the force-push

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:ldap

**Comment by ChrisKian** [comment]
ci:test:ldap

**Comment by ChrisKian** [comment]
ci:test:ldap

**Comment by ChrisKian** [comment]
ci:test:ldap

**Comment by ChrisKian** [comment]
ci:test:ldap

**Comment by ChrisKian** [comment]
For reference, I removed the LDAP attribute "description" in favor of "title" because it comes after the objectClass definitions for SF checks, and having it before doesn't work for whatever reason.

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,
All failing stable/relevant/ldap tests seem unrelated to my changes, and you can see [the new poshi test passes here](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112099/).  Please let me know if you have questions or concerns about the changes here, thanks!

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Review by stian-sigvartsen — APPROVED** [review]
The changes look good @ChrisKian .
I've triggered ci:test:stable so hopefully we can get a pass on that before forwarding. It will rebase to latest master before executing so if there was a temporary situation upstream then we should see it.

If it passes, please feel free to ci:forward:force

**Comment by ChrisKian** [comment]
ci:forward:force

**Pull request closed without merging**
