### PR TITLE
LPD-19754

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-19754

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@ChrisKian this looks excellent. As soon as CI passes we can forward.

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by ChrisKian** [comment]
ci:reevaluate:1407401_8915

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @stian-sigvartsen,
Id like for you to examine two additional commits I've added for the fix [1](https://github.com/liferay-appsec/liferay-portal/pull/1660/commits/ed6b898cd54feebb85a51fee84389b3f18094b83), and [2](https://github.com/liferay-appsec/liferay-portal/pull/1660/commits/ce6859ba25ef68a4bdc6499359878f4fd42901d5).

I found during testing, the same error was reproduced upon logout, however the same fix could not be applied, since the `SamlSloContext` class (the class needing to be serialized) could not be adjusted for serialization, like the `SamlSsoRequestContext` class could.

So, my solution was to stop including the `SamlSloContext` class in the session, and instead only include the one variable actually required across session replication, the `Map<String, SamlSloRequestInfo> _samlRequestInfos` variable.  I've found this fix works during logout from both the IdP and SP, and has the least impact.

Please let me know if you have any questions, or would otherwise like to discuss the fix further.  I know it's a bit more involved than the initial fix, so it's understandable if you want to chat.  Thanks!

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:stable

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
Hi @ChrisKian . It looks like these changes break the SLO process when multiple SPs are logged into the same IDP SSO session.

In my testing when I trigger a SLO from one SP, both SPs and the IDP are logged out. However the SLO webflow ends at the IDP instead of returning to the SP that initiated the SLO.

Please can you check?

**Comment by stian-sigvartsen** [comment]
Just noticed that `LocalFile.SAML#ViewSingleLogoutAndForceAuthWithMultipleSPs` is failing. I suspect that is actually the same underlying issue.

**Comment by ChrisKian** [comment]
Hi @stian-sigvartsen, 
this issue is happening because we lose some some context stored in the [MessageContext](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/saml/saml-opensaml-integration/src/main/java/com/liferay/saml/opensaml/integration/internal/servlet/profile/SamlSloContext.java#L131-L133) object.  The problem is I'm not sure how to Serialize this object, and to make things more complicated, it belongs to a third-party lib.

I looked into the option of wrapping the MessageContext class with a Serializable version, but I'm not sure how to actually implement this or if it will even work.

I'll continue investigation to see if we can properly regenerate the MessageContext (so we don't need to store it in the session), but any insight would be greatly appreciated, thanks!

**Comment by ChrisKian** [comment]
New PR: https://github.com/liferay-appsec/liferay-portal/pull/1697

**Pull request closed without merging**
