### PR TITLE
LPD-6605 play wright test

### PR DESCRIPTION
**Pull request by tomibiro**

### CODE REVIEW

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:test:stable

**Comment by tomibiro** [comment]
ci:test:stable

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:stop

**Comment by tomibiro** [comment]
ci:test:relevan

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
https://github.com/liferay-appsec/liferay-portal/pull/1803

**Pull request closed without merging**
