### PR TITLE
Lps 131194

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by lipusz** [comment]
It'd be nice to cover this with tests.

**Comment by arthurchan35** [comment]
@lipusz 
Let's see what @topolik thinks first.
I can add test for it once Tomas reviews and agrees my change.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen @martamedio 
Tomas has replied last week, I think we should review it by ourselves and try to forward it as it's a customer issue.
Should not let it sit for too long.
Please help review it and I think it's good to go.

**Comment by topolik** [comment]
b15357f is a very good improvement. Please fwd to Brian. Thank you.

@arthurchan35 @martamedio @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
