### PR TITLE
LPS-148698 Add missing deleteOAuth2Application(OAuth2Application) method in the OAuth2ApplicationLocalServiceImpl class to also handle the ResourcePermission deletion - LPS-145396 Subtask

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This is a subtask of [LPS-145396](https://issues.liferay.com/browse/LPS-145396) where I am handling the correct ResourcePermission deletion in the Liferay code.

In parent [LPS-145396](https://issues.liferay.com/browse/LPS-145396)  I am implementing some changes in DataGuardTestRule to detect orphan ResourcePermission records, avoiding the bug in the future and I have detected that if you call the current `deleteOAuth2Application(OAuth2Application)` method that is implemented in OAuth2ApplicationLocalServiceBaseImpl, it is not correctly handling the ResourcePermission deletion.

To solve it, I am adding it to OAuth2ApplicationLocalServiceImpl and reusing the current code of `deleteOAuth2Application(long)` that is working correctly.

The `deleteOAuth2Application(long)` method was corrected in my previous PR https://github.com/liferay-appsec/liferay-portal/pull/580

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:test:stable

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
