### PR TITLE
LPS-165207 smartly handle npe

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:oidc

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:oidc

**Comment by arthurchan35** [comment]
ci:reevaluate:1397401_859

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:oidc

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:oidc

**Pull request closed without merging**
