### PR TITLE
LPD-15723

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-appsec/liferay-portal/pull/1654

Original message:

> Resent from https://github.com/liferay-appsec/liferay-portal/pull/1653
> 
> Resent from https://github.com/ChrisKian/liferay-portal/pull/323 with https://github.com/brianchandotcom/liferay-portal/pull/147670#issuecomment-1971026475 added.
> 
> See diff here: https://github.com/liferay-appsec/liferay-portal/compare/f7d91c391be6c8e8c1aca55b3692f05aa414717d...9a09b8558814f96ffdcb28cfae38336aaf89af25

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
Test failures look unrelated.  @stian-sigvartsen, are we good to force-forward?

**Comment by stian-sigvartsen** [comment]
@ChrisKian looks sensible. But you need to get a clean run of the stable suite (or manually send the PR if you are 100% sure)

**Comment by ChrisKian** [comment]
Stable [passed](https://github.com/liferay-appsec/liferay-portal/pull/1658#issuecomment-1977931192) and [failed](https://github.com/liferay-appsec/liferay-portal/pull/1658#issuecomment-1977949303) within the same hour, so I'll re-run it for verification.

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
I've rebased the fix, hoping that will resolve the stable errors

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
sf error looks unrelated, only present because I've modified portal.properties

**Comment by stian-sigvartsen** [comment]
@ChrisKian That exact same SF error was happening on the other PR mentioned above, so I would go ahead and manually forward the PR to BChan with a comment.

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by ChrisKian** [comment]
Sent to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/147884

**Pull request closed without merging**
