### PR TITLE
LPS-146238 Force flush on JSPWriter

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-146238

Using Wildfly, turning on Multi-Factor-Authentication and Email One-Time Password Configuration, the Submit button of the MFA is being created first and then the form. This causes the button to not register the submit click and the user is not able to log in.

A solution for this is to force a flush on the JSPWriter. This makes it so the form is created first with the buttons nested inside.

Let me know if there are questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:security

**Comment by fortunatomaldonado** [comment]
ci:test:stable

**Comment by fortunatomaldonado** [comment]
ci:test:sf
ci:test:relevant
ci:test:security
ci:test:stable

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:security

**Comment by fortunatomaldonado** [comment]
ci:test:stable

**Comment by fortunatomaldonado** [comment]
ci:test:security

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Hi @fortunatomaldonado . Thanks creating and proposing a solution to this issue!

It sounds like this is a client side issue, so isn't client side solution that is needed, to handle the page lifecycle properly. I would only expect flushing the buffer early to only improve the situation, not fix it in all cases?

**Comment by fortunatomaldonado** [comment]
Hello @stian-sigvartsen,

Thank you so much for taking the time to look at this.

Yeah, I agree that this would be be an improvement rather than a full fix. I have also thought of adding a `form` attribute to the button referencing the form id. This way no matter where the button is created, it would link to the form. 
What are your thoughts on this approach?

Thank you again!

**Comment by stian-sigvartsen** [comment]
I am struggling to see how that button would not be added within the `<form>`.  Because the `/mfa_verify/view.jsp` which adds that, then calls `includeBrowserVerification()` which includes said button is using the same `HttpServletResponse` object. The JSP actually doing it is `verify_browser.jsp` . 
Or did you mean something different by "created first and then the form"

**Comment by fortunatomaldonado** [comment]
Hello @stian-sigvartsen,

Yeah it doesn't make much sense to me either, but using Wildfly the buttons are displayed first and then the form.
WildflyMFA

Using tomcat, the form is created and the buttons are in the form.
TomcatMFA

I'm not sure what exactly is causing this and any push in the right direction is much appreciated.

**Pull request closed without merging**
