### PR TITLE
LPS-150091 oauth client admin web

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hey @arthurchan35 . I'm still reviewing this but one thing stands out...
Shouldn't all mentions of OAuth actually be OAuth 2.0? Including the module directory names etc. ?
Or will this also cover some kind of OAuth 1.0a client registration?

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen 
No, OAuth, instead of OAuth 2.0, is intentionally used for all occurrences through backend to frontend. This project is intended to be (hopefully) future proof for OAuth 2.1, OAuth 3.0 and any upcoming OAuth specs.

In fact, I have a plan to rename OAuth 2.0 provider to OAuth Authorization server and OAuth resource server when the task of spliting provider comes along.

**Comment by stian-sigvartsen** [comment]
Hi @arthurchan35 . 

Thanks for discussing the OAuth vs. OAuth 2 naming this morning. I have some reservations about that given how these are so different protocols, but let's go with this for the time being.

I've reviewed the code from a functional perspective. Please can you address the following and send me a new PR. 

* OAuth Authorization Server metadata
	* Client side JSON validation errors no validation messages. Giving impression that the save button does nothing.
	* Server side validation errors throw the user back to the OAuth Clients search container, losing all inputs . Should stay with the form.
	* Missing validation error messaging in general. The only clue is found in the system logs.
	* Missing title when adding/updating authorization servers. It is very hard to know if you are adding a OAuth client or an Authorization Server because of that. Especially as the two screens are very similar.
* OAuth Client 
	* Same issues as above

Also can you share the metadata you have been using for testing this because trying to find one which is valid is challenging without sensible error messaging. Alternatively provide unit test. Thanks! 👍

**Comment by stian-sigvartsen** [comment]
@arthurchan35 shouldn't all the commits be keyed to the story and not the sub-task?

**Pull request closed without merging**
