### PR TITLE
LPD-34165 Add playwright test

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-34165

Hi @evibudai,

I've added a few changes to your original commit, so please look over them and make sure everything makes sense.  I'll re-review on Monday, but I just wanted to have CI run over the weekend since it's the end of my day.

One thing to note, I see on [this PR](https://github.com/evibudai/liferay-portal/pull/11) Manu added some commits, however you've squashed them down.  It's a good idea to leave a "commit trail" so we have additional context of what is happening, and so other developers can get credit where it's due.

Also, I've pushed this branch to the appsec repo, so you can add additional commits if you feel they are necessary.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:Login

**Comment by ChrisKian** [comment]
ci:test:security

**Comment by evibudai** [comment]
Thank you @ChrisKian !

I usually squash my commits to keep a cleaner look when it's a first time change. As you can see, there's already a lot of difference between the [PR](https://github.com/evibudai/liferay-portal/pull/11/commits) where Manu sent commits and [this one](https://github.com/liferay-appsec/liferay-portal/pull/2065). But I'll make sure in the future to not squash the commits if they come from someone else.

**Comment by stian-sigvartsen** [comment]
Thanks @evibudai . Avoiding squashing commits will also help you get your PR reviews processed quicker because the review can then start where they left off, instead of reviewing the full change again.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:security

**Review by stian-sigvartsen — APPROVED** [review]
Great job @evibudai @ChrisKian @manuelecastro !

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
