### PR TITLE
[TS] LPS-135534 Send redirect if parameter is present

### PR DESCRIPTION
**Pull request by JavierMoral**
https://issues.liferay.com/browse/LPS-135534

Hi team,
Could you please review this pull request?
Thanks

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:sf

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @JavierMoral . Solving this issue is important, I agree! Thanks for your solution.
Issuing a redirect from a portlet's render phase is not good practice generally, though we allow it. I am wondering though if this solution meets end-user expectations if the login portlet is put on a page alongside other portlets/content. Of course it requires there to be a "redirect" parameter, and it should ignore such a parameter targeting another portlet. But curious if you have tested this scenario?

**Comment by JavierMoral** [comment]
Hi @stian-sigvartsen ,
I see your point. I added this redirect in the render command because I could not find a better place for it and because I saw other few cases in the source code in which this was done. This issue was raised in a use case in which a user is clicking a link in a third party application that leads to the download of an image uploaded to Documents and Media. This image does not have guest permissions. When they click in the link they end up being redirected to this kind of url:
`/web/guest/home?p_p_state=maximized&p_p_mode=view&saveLastPath=false&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Flogin&p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&_com_liferay_login_web_portlet_LoginPortlet_redirect=%2Fdocuments%2F20127%2F0%2FSelecci%25C3%25B3n_078.jpg%2F67235817-7c95-1345-144f-5c26891d5cf1%3Ft%3D1624617271912%26download%3Dtrue`
 and:

- If they were not previously logged in, they enter user/pass and are redirected to the image.
- If they were previously logged in, they are stuck with the "you are logged in as" message.

To be honest, I did not test that scenario so thank you for the pointer. I tried it in master adding the login portlet to a page along with other widgets such as an asset publisher. If I render the page, debugging the MVCPortlet class I see that it does not execute the render method but the doView method. This seems to render the jsp directly without executing the LoginMVCRenderCommand.
The problem with the redirect parameters I thought that it was not possible. My understanding is that in the renderCommand I have access to a RenderRequest addressed to the loginPortlet that filters the parameters using the portletId. In this case the parameter in the original url is called `_com_liferay_login_web_portlet_LoginPortlet_redirect`. If it were a redirect meat for another portlet I think it would be called something like `_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_skbe_redirect`.
Thank you

**Comment by JavierMoral** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
Just capturing our followup offline conversation...

We found that this issue is caused by SameSite cookie policy. The JSESSIONID cookie was not sent when requesting the document by URL, causing portal to believe the user is not authenticated. So it redirects to the login portlet. Because this 2nd request is considered as coming from the "same site", the JSESSIONID cookie is then sent, and the portlet just says that you are signed in already. 

We discussed various ways to work around this, but for the moment we will not change the portal  behavior itself.

**Pull request closed without merging**
