### PR TITLE
LPS-175232 Support parameterized algorithms in CompositePasswordEncryptor

### PR DESCRIPTION
**Pull request by nikolettabuza**
Updated https://github.com/liferay-appsec/liferay-portal/pull/999

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
For reference, the ticket structure is like:

- LPS-175232 (Story)
  - LPS-176160 Add FF (sub-task)
- LPS-177326 (epic)
  - LPS-185196 Define FF (task) 

So that means:

1. 
f2a799d3ee change commit message to:

> LPS-176160 Feature flag.
> 
> For LPS-175232.

Here you are linking a story to the epic level defined FF. We need to use the sub-task key at the start of the message, and mention the parent (story) task also so that we can find the commit when looking for the story related commits.

2.

3e346fd change commit message to:

> LPS-185196 Release feature flag.
> 
> For LPS-177326.

Same pattern but using the keys for the Epic related tickets. I'm not 100% sure about the "For LPS-177326" bit because LPS-177326 is not a sub-task. However it is helpful to mention the epic because the feature flag uses its key in code, I think.

**Comment by stian-sigvartsen** [comment]
Forgot one thing. With 3e346fd you are actually defining a "development feature flag" , not a "release feature flag". That is because you are missing the other portal properties that are required for "release" (and "beta" also FYI) feature flags:

```
feature.flag.LPS-177194.description=English localized message describing the message, agreed with PM
feature.flag.LPS-177194.type=release
```

What I would suggest is just change your commit message to say "Feature Flag" only. We can work on the bits above with Zsigmond in parallel to BChan reviewing.

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
So close now! See my commit message comments :)

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
We found that matching on the full algorithm string is going to create problems. Going back to original approach, please see https://github.com/liferay-appsec/liferay-portal/pull/1190

**Pull request closed without merging**
