### PR TITLE
LPS-183610, LPS-184520 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-183610
https://issues.liferay.com/browse/LPS-184520

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 Could you please rebase your changes?

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 Could you please rebase your changes?

Done

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
Sent to BChan directly:
https://github.com/brianchandotcom/liferay-portal/pull/136074

**Pull request closed without merging**
