### PR TITLE
LPD-40343

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-40343

Initial PR for CI, will update description once it's ready.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Relevant test failure looks unrelated: https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044519/testReport/com.liferay.site.initializer.extender.internal.test/BundleSiteInitializerTest/testInitializeFromBundle/

Requesting review from @stian-sigvartsen

**Comment by ChrisKian** [comment]
Added minor SF change, re-running tests

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@jgarcialr is reviewing the expectations of the ticket.
Whilst this is going on I will close this PR, but we can re-open if they are correct.

**Pull request closed without merging**
