### PR TITLE
LPS-200030 As an Instance Administrator, I want my User Groups to be automatically un/provisioned using the SCIM protocol

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-200030](https://liferay.atlassian.net/browse/LPS-200030)

Previous PRs:
https://github.com/liferay-appsec/liferay-portal/pull/1473
https://github.com/liferay-appsec/liferay-portal/pull/1556

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
Split into parts:
- https://github.com/liferay-appsec/liferay-portal/pull/1569

**Pull request closed without merging**
