### PR TITLE
LPS-132754 DB2 & SQLServer Fix

### PR DESCRIPTION
**Pull request by martamedio**
@stian-sigvartsen Please, take a look. As we have discussed we were missing a field in the `INSERT into SamlPeerBinding` and for some databases is mandatory to add it even if it can be `null`,  we also had a typo in an update execution and I changed the other update execution to use table names.

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Review by stian-sigvartsen — APPROVED** [review]
Looks great. Well done tracking down this quirky null handling requirement with DB2! 🥇

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
