### PR TITLE
LPS-180466 Support group context for audit events - rebased

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Actually the SemVer failure is related. I have pushed a commit.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
CI problems with ci:forward:force so I manually forwarded to brianchandotcom/liferay-portal/pull/135011

**Pull request closed without merging**
