### PR TITLE
LPD-28294

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:reevaluate:1317401_10979

**Comment by ChrisKian** [comment]
Hey @daiazius,
I have two changes I'd like to see:

1. `StringPool.BLANK` rather than `""`.
2. Test(s)

If you have trouble with test writing, let me know and we can figure it out.

**Comment by ChrisKian** [comment]
Rebased and resent here: https://github.com/liferay-appsec/liferay-portal/pull/1854

**Pull request closed without merging**
