### PR TITLE
LPD-39612 As an Instance Administrator, I want to get an email notification when the access token getting near to the expiration date

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPD-39612](https://liferay.atlassian.net/browse/LPD-39612)

Adding change ([commit](https://github.com/brianchandotcom/liferay-portal/pull/155430#issuecomment-2430043276)):
* renaming vars

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Hi @rafaprax ,

Could you review it please?

cc/ @stian-sigvartsen

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:tes:sf

**Comment by alvarosaugarlr** [comment]
This https://github.com/liferay-appsec/liferay-portal/pull/2043/commits/5456162892b05c6eec1ed297c1ddc7620fd702bf change is done because 
image

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
Test passed
image

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/2048

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
