### PR TITLE
LPS-147809 Make consistent UX

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Comment by JoyceWang08211** [comment]
> 1. SecurityUsecase#UserCanAccessPermissionsWindowWithPermissionFromAdmin

The above functional failures are not related to the current PR.

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by stian-sigvartsen** [comment]
@JoyceWang08211 I just noticed I miskeyed the last commit. That's the only change in my force-push.

**Comment by JoyceWang08211** [comment]
I will add a new testcase to cover the new radio buttons and using Upload Metadata XML functionality later.

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
