### PR TITLE
LPD-39324 Investigate flaky OIDC tests failing at prepare-selenium-keycloak-server

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-39324](https://liferay.atlassian.net/browse/LPD-39324)

Add a curl request to assert that keycloak server is up and running

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
Test has passed:

image

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Good solution to solve the flaky test.

The solution of validating if the Keycloak is available allows us to know if the problem is in the test or before. 

The affected tests have all passed except [OpenIDConnect#OpenIDConnectOnInstanceLevelSmoke](https://testray.liferay.com/#/project/35392/routines/45357/build/44563855/case-result/44615682), which fails later and is resolved in the https://liferay.atlassian.net/browse/LPD-38737 ticket.

**Comment by stian-sigvartsen** [comment]
LGTM @jgarcialr @alvarosaugarlr .
This will give us more information when tests fail!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
