### PR TITLE
Lps 138428 depcreate digest authen

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey @stian-sigvartsen 

I tested WebDav URL, and it was not triggering AuthVerifier process at all.

Here I sent a pull to mark related code as deprecated.

The only part I am not able to mark deprecated is the get/setDigest() in UserModel class, as serviceBuilder wont auto mark it even if I did in UserImpl

Search portal history, I found for more general model deprecation, people has modified model.ftl/model_impl.ftl, but I dont think it's the case for us.

Can you take a look?

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Thanks @arthurchan35 . I'll have a try to deprecate the model methods also.
Besides from that I noticed we need a space character before "(deprecate)" and maybe capitalize it also?

I'm a bit concerned about what you said about WEBDAV... has the recent refactor caused a regression there do you think? If so we should raise a new ticket.

**Comment by stian-sigvartsen** [comment]
@arthurchan35 it looks like there have been considerable changes to both portal language architecture (gw buildLang doesn't work for me) and the Service Builder in the last couple of days. I'm building another commit for tomorrow.

In the meantime I've pushed a minor change, maybe you can push a buildLang for it.

**Comment by arthurchan35** [comment]
ci:close

**Comment by arthurchan35** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/476

**Pull request closed without merging**
