### PR TITLE
LPD-16371

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-16371

Previous pull: https://github.com/liferay-appsec/liferay-portal/pull/1617

CC @stian-sigvartsen, @cdbm

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@cdbm thanks for offering to review the CI results!

**Comment by cdbm** [comment]
@ChrisKian @stian-sigvartsen beyond the upgrade error related before as far as i reviewed the ci errors are unrelated, all of them seem to be related to a cdn or network error when retrieving external libraries.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
In the tests, I see the following lines:

> ...
>      [java] 2024-02-23 02:05:03.766 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.oauth2.provider.internal.upgrade.registry.OAuth2ServiceUpgradeStepRegistrator$4
>      [java] 2024-02-23 02:05:03.767 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.oauth2.provider.internal.upgrade.registry.OAuth2ServiceUpgradeStepRegistrator$4 in 1 ms

So it looks like the upgrade process works as intended

**Comment by stian-sigvartsen** [comment]
@ChrisKian thanks for the analysis! I think you can forward at your discretion.

**Comment by ChrisKian** [comment]
ci:forward:force

**Comment by ChrisKian** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
