### PR TITLE
LPS-201090 Remove DictionaryWordTextProducer from the default text producers configuration because it can produce offensive words

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-201090](https://liferay.atlassian.net/browse/LPS-201090)
Solution discussed on [PTR-4486](https://liferay.atlassian.net/browse/PTR-4486)

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by mbowerman** [comment]
Closing PR since a new PR has been sent at https://github.com/liferay-appsec/liferay-portal/pull/1513

**Pull request closed without merging**
