### PR TITLE
LPD-37463

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
@cdbm there are quite a few seemingly related SCIM test failures when I run this locally. The new group assert for unconfigured SCIM expecting HTTP 404, is in fact receiving HTTP 403 for example.

I've triggered the ci:test:scim suite because the relevant suite passed

**Comment by stian-sigvartsen** [comment]
It must just have been a local environment issue since this is passing.
I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
