### PR TITLE
LPD-30596 Using PortalUtil.getLayoutFullURL

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Sorry @istvansajtos , I got some branches mixed, it should be back to how it was when the PR was created 2 hours ago now

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:stop

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:stop

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:84387135

**Comment by stian-sigvartsen** [comment]
ci:report:84387135

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:report:85284460

**Comment by istvansajtos** [comment]
ci:report:85284460

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:report:87520861

**Comment by istvansajtos** [comment]
ci:stop

**Comment by istvansajtos** [comment]
Rebased and resent to https://github.com/liferay-appsec/liferay-portal/pull/2116

**Pull request closed without merging**
