### PR TITLE
[TS] LPP-46584 > LPS-164371 Fix lockout issue

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,
Please help review this PR and leave your comment. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-164371
@quanhuynhces

### CODE REVIEW

**Comment by noraszel** [comment]
Hi @chileces, next time please set the LPS status to "In Review" and the LPS assignee to the " Product Team App Security" in JIRA, because in this way we can identify the review task earlier. Thanks in advance!

**Comment by chileces** [comment]
dear @noraszel,

Thanks for your feedback, I have changed its status.
This [LPS](https://issues.liferay.com/browse/LPS-164371) is a security ticket related to an LPP, so please give it a priority,
thank you,
Chi

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by chileces** [comment]
hello @alvarosaugarlr  	
please let me know if is there anything I can help with the preview process.

**Comment by alvarosaugarlr** [comment]
ci:test:relevant
ci:test:security

**Comment by quanhuynhces** [comment]
Hi @alvarosaugarlr,
Can you take a look at this PR? Thank you very much

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
@alvarosaugarlr if the relevant fails or aborts again, we should forward this directly.
Testing has passed already, see my ticket message on [LPS-164371](https://issues.liferay.com/browse/LPS-164371)

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
Closing as this was forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/126112

**Pull request closed without merging**
