### PR TITLE
LRQA-82365 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LRQA-82365

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:um:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/139198

**Pull request closed without merging**
