### PR TITLE
LPD-32208

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-32208

Covers all TCs in LPD-32208.  If TC1 needs to be explicitly defined, please let me know, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Review by stian-sigvartsen — APPROVED** [review]
This is beautiful @ChrisKian . Well done!

**Comment by stian-sigvartsen** [comment]
@ChrisKian please follow up on the SF test failure and then we can forward

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
All tests now passing @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
