### PR TITLE
LPS-174593

### PR DESCRIPTION
**Pull request by jonathanmccann**
After sending this pull it seems there are some concerns about the increase in rounds due to performance issues. If a different approach is desired (less rounds, different algorithm, etc.) please feel free to close this.

### CODE REVIEW

**Review by oliverkecskemety — APPROVED** [review]
LGTM! Thanks @jonathanmccann

**Comment by oliverkecskemety** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
Already merged under LPD-2273

**Pull request closed without merging**
