### PR TITLE
LPD-25377

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-25377

The ticket may change, assuming it needs to be under a Story ticket rather than Bug ticket.

I also adjusted the `isFilterEnabled` methods for the `AssertionConsumerServiceSamlPortalFilter` and `SameSiteLaxCookiesSamlPortalFilter` filters for consistency, however those changes may not be necessary since both filters are only used when explicitly using `SAML` related URLs.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failure is relevant, but only because the test class doesn't explicitly have SAML enabled before running.  I've updated the test class to have SAML enabled via configuration, so now the tests proceed as expected.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Looks great @ChrisKian ! Let's get it through CI

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failure is relevant; it should be resolved now.

For reference, here's the relevant CI error:

> Incorrect configuration of dependency {compileOnly project(":dxp:apps:saml:saml-api")} in modules/dxp/apps/saml/saml-test/build.gradle, use one of these instead: "testIntegrationImplementation", "testIntegrationRuntimeOnly"

I had the `saml-api` dependency as `compileOnly` instead of `testIntegrationImplementation` for the test class.

**Comment by ChrisKian** [comment]
ci:forward

**Pull request closed without merging**
