### PR TITLE
LPS-124898 OIDC refresh token - single request auth

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi @arthurchan35. I think it is best if we just remove that legacy interface so customers get compile time errors instead of limping along and possibly seeing odd/unexplainable behavior.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
... also I think we need to keep `com.liferay.portal.security.sso.openid.connect.OpenIdConnectAuthenticationHandler#processAuthenticationResponse` exported so customers can implement it should they want to provide a custom OIDC integration in a 3rd party module. Though as we discussed we think this is unlikely to happen in reality so I'm not 100% sure about this.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/105290

**Pull request closed without merging**
