### PR TITLE
LPD-26416 Review & adapt tests using hard-coded values 

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-26416](https://liferay.atlassian.net/browse/LPD-26416)
Modify harcoded values in tests in favor of values defined in properties file.
Retrieve those values from PropsValues instead using the hardcoded ones.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:oauth2

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:oauth2

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:reevaluate:1387401_10762

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:reevaluate:1377401_17141

**Comment by stian-sigvartsen** [comment]
I sent a second PR to liferay-appsec/liferay-portal/pull/1812 to get some fresher CI results. The results look good there, so I will close this PR.

**Pull request closed without merging**
