### PR TITLE
LPD-36707

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-36707

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Review by ChrisKian — APPROVED** [review]
Looks good to me, requesting review from @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
Great job @daiazius @ChrisKian ! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
