### PR TITLE
LPS-204744

### PR DESCRIPTION
**Pull request by ChrisKian**
See https://github.com/liferay-appsec/liferay-portal/pull/1585

This is the safest way I could determine if the current user is being properly impersonated.  The `PortalImpl.getUserId()` method isn't helpful in this situation, since it doesn't tell us if the user is actually impersonated.  And the `PortalImpl.getDoAsUserId()` method is `protected`, so I didn't want to completely expose it.  Instead, I created the `PortalImpl.isImpersonated()` method which uses the `getDoAsUserId()` method to validate impersonation, and only returns a boolean value.

Please let me know which approach we should go with, and I will close out the opposite PR, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@ChrisKian  Adding the `isImpersonated` method into `PortalImpl` is a good approach I think. It maintains a clean separation of concern. 

1. Because we are seeing a number of conditions being added now, I did some refactoring to make it more human readable.
2. I generalized the checks a little
3. Finally I restricted the functionality and will update LPD-2280 with the reasoning.

liferay-appsec/liferay-portal/pull/1645

**Pull request closed without merging**
