### PR TITLE
[TS] LPS-200609

### PR DESCRIPTION
**Pull request by MirnaGama**
### Context:
[LPS-200609 - Edit client credentials modal causes blank space above page and collapses screen](https://liferay.atlassian.net/browse/LPS-200609)

### Steps to reproduce:

1. Go to Control Panel > Security > OAuth 2 Administration
2. Select any "OAuth 2 Administration"
3. Click "Edit" button on "Client ID" or "Client Secret"

Actual result: An unnecessary blank space appears at the top of the screen.
Expected result: Unnecessary blank space is not displayed.

### Implementation details:
It was discovered that the property "position: relative" from modal-dialog class in [clay_admin.scss](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-css/frontend-css-cadmin-web/src/main/resources/META-INF/resources/clay_admin.scss#L44) was affecting this element. This would make the modal appear above the page. To avoid this, it was necessary to emphasize that this edit modal should have the absolute position on the page.

### Commits included:
- LPS-200609 Set position absolute for oauth2 modal so it does not appear above the page

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Review by oliverkecskemety — CHANGES_REQUESTED** [review]
Hey @MirnaGama,

I think there are still some issues. For me the modal was behind the content tab which is because they are on the same `z-index`. You can change the `z-index` of the modal to `1` for example which solves the problem partially however, I think the content part and the header should be behind the grey filter. I tried to set that part to `z-index: -1` but that makes the buttons unusable. Can you look into it?

This is what is see with your changes:
Screenshot 2023-11-10 at 15 28 13

That's how it looks like when I change the `z-index` of the modal:
Screenshot 2023-11-10 at 15 28 30

And I think this is how it's supposed to look:
Screenshot 2023-11-10 at 15 29 06

**Comment by stian-sigvartsen** [comment]
Discussed with @MirnaGama offline. She will explore if we can improve our interaction with `A.Modal` so we don't need to get involved in the position of modals created by the API.

**Pull request closed without merging**
