### PR TITLE
LPD-33598 Fix errors in ScimUtil

### PR DESCRIPTION
**Pull request by daiazius**
Hi, when testing SCIM's behavior I found out that the commit https://github.com/liferay-appsec/liferay-portal/commit/56876455ca013cd7acd7eb7506650d6fce91ccb5 was causing some errors due to an incompatibility with the pattern used in FastDateFormatFactoryUtil and to fix that I instead used DateFormatFactoryUtil, that accepts the pattern, inside the method that uses it.
cc. @rafaprax

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:scim

**Comment by daiazius** [comment]
ci:report:74745204

**Comment by rafaprax** [comment]
@daiazius  LGTM

**Comment by daiazius** [comment]
ci:forward

**Pull request closed without merging**
