### PR TITLE
LPD-32812, LPD-32824, LPD-32821, LPD-32825, LPD-32826, LPD-33165, LPD-35171

### PR DESCRIPTION
**Pull request by daiazius**
Related issues: https://liferay.atlassian.net/browse/LPD-34638 and https://liferay.atlassian.net/browse/LPD-32811

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:scim

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:scim

**Comment by ChrisKian** [comment]
Hey @daiazius,
It looks like your new playwright test isn't being picked up when you run "ci:test:scim".  This is likely because [the component name is listed as "Security"](https://github.com/liferay-appsec/liferay-portal/blob/5440e596a46890ea9347fc40c68a7e0afc77af54/modules/test/playwright/tests/scim-configuration-web/test.properties#L5).

Since the test you are replacing comes from [the SCIM testray component](https://github.com/liferay-appsec/liferay-portal/blob/5440e596a46890ea9347fc40c68a7e0afc77af54/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/security/SCIM.testcase#L9), could you please adjust the testray component in Playwright and force-push your changes here?  Thanks!

**Comment by daiazius** [comment]
ci:test:scim

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
Not sure why the SCIM test suite didn't pickup the new playwright test.  Running playwright suite now.

**Comment by daiazius** [comment]
I think the test I added is failing because the virtual instance created doesn't have the SCIM feature flag, looking on how I can add it to it.

**Comment by daiazius** [comment]
ci:test:playwright

**Comment by daiazius** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
SCIM related playwright tests passing: https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041759/testReport/

**Review by ChrisKian — APPROVED** [review]
Looks good, requesting review from @stian-sigvartsen

**Review by stian-sigvartsen — APPROVED** [review]
This is excellent work @daiazius . I will forward

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
