### PR TITLE
LPS-186524 Avoid running SAML Login logic on an already-logged-in user

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-186524](https://issues.liferay.com/browse/LPS-186524)

### CODE REVIEW

**Comment by mbowerman** [comment]
What is with these weird SF checks that force us to censor our own commit messages? Is that intended?

**Comment by mbowerman** [comment]
I've censored the word "login" in my commit message and force-pushed.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Thanks @mbowerman . The SF rule is there because hackers scan git histories for ideas on how to compromize products. It is similar to the reasoning for releasing sec fixes to all x-branches simultaneously.

Your change works great, but I think we can simplify it. Please see liferay-appsec/liferay-portal/pull/1157

**Pull request closed without merging**
