### PR TITLE
[TS] LPS-151394 Users are not unassigned from Liferay groups if the LDAP user group is empty

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-appsec, 
this pull fixes [LPS-151394](https://issues.liferay.com/browse/LPS-151394).

The `continue;` has been removed so that empty LDAP groups can be processed, and users can be unassigned from the user group in Liferay as well.

We have doubts whether the following log messages should be modified in case LDAP groups are empty:
   "No users found in ..." 
   "Importing 0 users from LDAP server ..."

Please let me note if you have any questions.

### CODE REVIEW

**Comment by danielmijarra** [comment]
ci:test:sf

**Comment by danielmijarra** [comment]
ci:test:relevant

**Comment by danielmijarra** [comment]
ci:test:ldap

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1357401_1353

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:ldap

**Comment by JoyceWang08211** [comment]
The above failures of functional tests under ci:test:ldap are caused by [LPS-151977](https://issues.liferay.com/browse/LPS-151977).
Not related to the current PR.

**Comment by stian-sigvartsen** [comment]
@danielmijarra Thanks for the PR, we are reviewing 👍

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Looks great @danielmijarra . Thanks!

**Pull request closed without merging**
