### PR TITLE
Lps OIDC refresh token performance

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @jonathanmccann, @holatuwol

I have prepared a solution to completely replace the mechanism of using scheduler to refresh access token(aka extending oidc session) with a new mechanism that:
after oidc session expires(aka access token expires), the next receiving request(s) will try to handle refresh access token task.

This is the behavior before introducing scheduler, see:
https://github.com/liferay-appsec/liferay-portal/blob/bdc243a93c21440a2348552d44a82f8fe24ddd72/modules/apps/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectServiceHandlerImpl.java#L115

The only difference is that, this time, I synchronized requests that after access token expires, allowing only 1st request processing thread to refresh access token, which also resolves the issue in [LPS-124900](https://issues.liferay.com/browse/LPS-124900).
Obviously there is a small performance impact with it, but comparing to what you demonstrated with scheduler implementation, I think it's acceptable.

[LPS-124898](https://issues.liferay.com/browse/LPS-124898) and [LPS-124900](https://issues.liferay.com/browse/LPS-124900) is essentially about:
When Liferay receives multiple requests after access token expires, all these requests processing thread will try to refresh access token, but some providers will fail multiple refresh token requests in short amount time.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
I believe this implementation is not cluster-aware, so if there is session replication enabled and all requests end up on different nodes, you might still have parallel refresh token requests. I do not know if this is important or related to why the original scheduler implementation was MEMORY_CLUSTERED instead of just MEMORY.

If a cluster-aware implementation is needed, it should be possible to use locks, similar to what Liferay does to avoid parallel imports of site templates, in order to have a cluster-aware synchronization mechanism.

**Comment by arthurchan35** [comment]
Hi @holatuwol 
Thanks for the analysis! Could you point me to the code of site template import? I am not familiar with that part.

**Comment by holatuwol** [comment]
@arthurchan35 https://github.com/liferay/liferay-portal/blob/7.4.0-ga1/portal-impl/src/com/liferay/portlet/sites/util/SitesImpl.java#L1350-L1462

**Pull request closed without merging**
