### PR TITLE
[TS] LPS-191531 - Unable to assign users to organizations after disabling SPA

### PR DESCRIPTION
**Pull request by MirnaGama**
**Steps to reproduce:**
1. Create portal-ext.properties with this property to disable SPA: `javascript.single.page.application.enabled=false`
2. CP → Users & Organizations → Organizations → Add Organization → Name it & Save it
3. CP → Users & Organizations → Users → Add user → Fill in the necessary fields & Save it
4. CP → Users & Organizations → Organizations → Assign user to the organization created in step 1

_Expected result:_ The user is assigned correctly
_Actual result:_ The process simply froze and this WARN is logged:

> 2023-07-20 07:21:47.287 WARN [http-nio-8080-exec-1][SecurityPortletContainerWrapper:404] User 20123 is not allowed to access URL http://localhost:8080/group/guest/~/controlpanel/manage and portlet comliferayusersadminwebportlet_UsersAdminPortlet: User 20123 did not provide a valid CSRF token for com.liferay.portlet.SecurityPortletContainerWrapper

**Implementation details:**

When the single page application property is disabled, a request call made in javascript goes through a validation in the [SecurityPortletContainerWrapper](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/SecurityPortletContainerWrapper.java#L269) class. 

By debug, it was discovered that the final step of this validation is done by calling the SessionAuthToken class, which [checks if the request contains a CRPF token, it could be stored in the p_auth parameter OR in the X-CSRF-Token header of the request](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/auth/SessionAuthToken.java#L156). 

With that in mind, [another parameter was added to the request action url ](https://github.com/liferay-appsec/liferay-portal/pull/1251/commits/bad371e03d968c7240ccffe03d3cb63bf456a23d) in the javascript file responsible for open the modal and selecting the users associated to that organization.

**Commits included:**
- LPS-191531 Set missing auth token in select users modal request

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Thanks @MirnaGama ! LGTM. Thanks for taking the time to summarize the analysis you have done on this and your other PRs.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
ci:test:um

**Comment by JoyceWang08211** [comment]
No regression was found.

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
