### PR TITLE
LPS-154744 Unit tests

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-154744](https://issues.liferay.com/browse/LPS-154744)

Test cases made:

- Happy path - _testBothPropertiesDefinedAndCorrectRole_

- Test cases defined in [LPS-156733](https://issues.liferay.com/browse/LPS-156733)
   -  TC1: _testIssuerPropertyDefinedSoRoleNotExists_
   -  TC2:  _testBothPropertiesDefinedAndFakeRole_
   -  TC3: _testBothPropertiesDefinedAndRoleNotRegularType_
   -  TC4: _testBothPropertiesDefinedAndRoleCorrectAndUserAlreadyExists_
   -  TC5: _testBothPropertiesDefinedButRoleNameWrong1_
   -  TC6: _testBothPropertiesDefinedButRoleNameWrong2_

- Changing the issuer:
   -  Issuer defined in property is different that the request - _testBothPropertiesDefinedAndRoleExistsButDifferentIssuers_
   -  the issuer property is blank - _testRoleNamePropertyDefinedAndRoleExists_

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
LGTM. Wait for the double check of LPS-158385.
Note: After these unit tests are merged, we only need to add one more functional test to cover part of TC-4:
1. Set the following properties in portal-ext.properties:
```
open.id.connect.user.info.processor.impl.issuer=https://dev-5081331.okta.com/
open.id.connect.user.info.processor.impl.regular.role=My Custom Regular Role
```
2. Set up Okta as OpenID Connect identity provider on System level
3. Enable OIDC
4. Add a regular role named as _My Custom Regular Role_.
5. Login with OpenID Connect with oktauser@liferay.com
6. Navigate to account setting
7. Assert the _My Custom Regular Role_ is assigned to oktauser.

**Comment by JoyceWang08211** [comment]
I think it's safety to forward. 
cc @alvarosaugarlr and @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
@alvarosaugarlr LPS-158385 is merged into master: https://github.com/liferay/liferay-portal/commit/51d1fca98798abcd235f5e66512b303d29a27867
Please rebase the current PR, then we could forward to BChan.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Pull request closed without merging**
