### PR TITLE
LPD-40838 UserGroups are overwritten when logging in via saml even when userGroup mapping is not being configured

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-40838](https://liferay.atlassian.net/browse/LPD-40838)

Prior PR: https://github.com/liferay-appsec/liferay-portal/pull/2042

//cc @stian-sigvartsen 
I'll do a quick test tomorrow mapping the userGroups twice and checking the behavior to remove or keep the loop

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
Hi @jgarcialr . Looks like you dug deep into the core of the attribute mapping logic when analyizing this one! That's great knowledge to have going forward.

When reviewing I found that we could avoid introducing a new concept/method to the `UserFieldExpressionHandler` SPI whilst also avoiding a change to the `UserResolver` SPI also. The latter might have been OSGi replaced by some customers with custom logic. So it is good if we can avoid them receiving an incomplete fix.

I only moved your test because with my change it is now only testing `UserProcessorFactory`. I also refactored your test so it is a single test method and removed some unnecessary mappings (because the user is not being provisioned by the SAML logic). However I kept all 3 of your test cases, and they are still passing.

Another small thing (for future reference) was that we should avoid putting refereenes of the prefix of "membership:" in the `MembershipsUserFieldExpresionHandler`. i.e. "membership:userGroups". That should only appear in the component annotation so that we can handle fields (expressions) duplicated across duplicate `FieldExpressionHandler`s .

I sent brianchandotcom/liferay-portal/pull/156570

**Pull request closed without merging**
