### PR TITLE
LPD-28319 Invalidate WebDAV session

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPD-35766 Set user in WebDAVServlet. HttpSession user setting is not duplicated when it is a WebDAV request, partial revert of 033ba596
- LPD-28319 If digest changed, invalidate the session, generate challenge and return HTTP 401
- LPD-28319 Add unit tests
- LPD-28319 comparation using StringUtil
- LPD-28319 Update tests after resolving the WebDAV related merge conflicts

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:report:29484776

**Comment by jgarcialr** [comment]
ci:report:29363484

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Good fix and test @nikolettabuza @jgarcialr , but I had to revert change the latter to follow the same approach as the other test methods that were introduced for the user deactivation scenario. See [2818ccc](https://github.com/liferay-appsec/liferay-portal/pull/1985/commits/2818cccb266d103aba8337d470fe987342b8a2d7) .

I will forward after CI.

**Comment by stian-sigvartsen** [comment]
ci:report:35729269

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by nikolettabuza** [comment]
Original PR: pull/1892

Thank you @stian-sigvartsen! Just for the record, @istvansajtos was who worked on the fix and I worked on the test + resolving conflicts.

**Pull request closed without merging**
