### PR TITLE
[TS] LPS-176757

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-176757

https://issues.liferay.com/browse/PTR-3640

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hi @ChrisKian ! This looks great for a corrected behaviour, but I fear it will be a breaking change for many customers. I think we need to add a configuration property to `LDAPServerConfiguration` like `ignoreUserSearchFilterForAuth` defaulting to false (to avoid the need for an upgrade process). Did you already consider this?

Also it would be good to provide some log statement to differentiate between failed auth, and success auth + failed import scenarios. To help admins determine the cause of auth failures.

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,
I didn't consider this causing a breaking-change (or rather, a "fixing", thus "breaking" change), so I think a configuration is a great idea; I'll work on that now.

I'll also create additional debug logging.  Thanks!

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/1028

**Comment by stian-sigvartsen** [comment]
Thanks @ChrisKian . Found your new PR /iferay-appsec/liferay-portal/pull/1028

**Pull request closed without merging**
