### PR TITLE
LPD-39334 Add new ci:test:security-playwright suite

### PR DESCRIPTION
**Pull request by manuelecastro**
Related ticket: [LPD-39334](https://liferay.atlassian.net/browse/LPD-39334)

As requested, I'm adding a new CI suite, for running only playwright tests from Application Security components.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
SF failure seems odd, I've opened a slack thread to check on this.
see: [Slack Thread](https://liferay.slack.com/archives/C1SJ64S9X/p1731599619356649)

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:help

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:security-playwright

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
All 42 playwright tests were successfully ran on the new suite. :heavy_check_mark: 
see: [Testray Results](https://testray.liferay.com/#/project/35392/routines/45357/build/74207470?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)

Also, only Application Security related SemVem tests are being run at the Security suite now. :heavy_check_mark: 
see: [Testray Results](https://testray.liferay.com/#/project/35392/routines/45357/build/72609579?filter=%7B%22testrayCaseTypeIds%22%3A%5B47562%5D%7D&filterSchema=buildResults&page=1)

cc: @stian-sigvartsen

**Review by stian-sigvartsen — APPROVED** [review]
LGTM @manuelecastro , thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
