### PR TITLE
LPS-145190 JWT assertion as grant type for OAuth provider - PART II

### PR DESCRIPTION
**Pull request by arthurchan35**
https://issues.liferay.com/browse/LPS-145190

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
All the new added functional testcases are [passed](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1632335510&testrayCaseTypeId=101949&testrayTeamId=1310723571&testrayComponentId=1310733455) on Jenkins.

@arthurchan35

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
