### PR TITLE
Lps oidc fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@arthurchan35 Nicely done. We really need to flesh out tests for OIDC in general. It is too much to deal with as part of this ticket, so let's start a thread on Slack.

**Pull request closed without merging**
