### PR TITLE
LPS-189573 TOTP reuse | send email to user functionality

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-189573](https://liferay.atlassian.net/browse/LPS-189573)

Sending this to implement the "Account holder is notified by email that there was an attempt to reuse a TOTP." ticket requirement.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
Thanks @manuelecastro . Looking better! Please make the following names consistent with the renaming:

Files:

1. email_totp_sent_body.tmpl
2. email_totp_sent_subject.tmpl

Language keys:
1. email-totp-from-field
2. email-totp-from-name
3. email-totp-sent-body
4. email-totp-sent-subject

Methods on `MFATimeBasedOTPConfiguration` (should be consistent with the language keys, see `MFAEmailOTPConfiguration` as an example):
1. emailFromAddress();
2. emailFromName();

---

FYI the names of the other methods are good 👍 
1. emailTOTPReplayBody()
2. emailTOTPReplaySubject()

**Comment by manuelecastro** [comment]
Hi @stian-sigvartsen 

I just pushed the changes that you requested :)

Thank you for the review!

**Comment by manuelecastro** [comment]
ci:test:sf

**Review by stian-sigvartsen — COMMENTED** [review]
@oliverkecskemety will help with the review of this one. Thanks Oliver!

**Comment by oliverkecskemety** [comment]
Rebased and did some minor adjustments. Continued in https://github.com/liferay-appsec/liferay-portal/pull/1563

**Comment by oliverkecskemety** [comment]
Sorry, I forgot to mention that you did a good job on this PR, well done @manuelecastro! :) I've just inlined the `_sendNotificationEmail` function because I don't think it has any benefit on being a separate function and renamed everything to the same pattern because you were using `replay` in variables and `reuse` in texts so I wanted them to be consistently `reuse attempt warning`.

**Pull request closed without merging**
