### PR TITLE
LPD-6608 Add test

### PR DESCRIPTION
**Pull request by istvansajtos**
Add test for LPD-6608 

cc @stian-sigvartsen @zsigmondrab

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
Looks great @istvansajtos !

**Comment by stian-sigvartsen** [comment]
Manually forwarded to brianchandotcom/liferay-portal/pull/149946

**Pull request closed without merging**
