### PR TITLE
LPS-150388 Rebased to fix conflicts

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Also separated out to new commits
* Blanking default.admin.password (because it is our feature release flag)
* Generated code. Because if we need to rebase the PR again, it is safest to regenerate those changes in case of upstream changes to Service Builder
* Re-keyed some commits for consistency as we discussed

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
@alvarosaugarlr , could you please resolve the conflict and rebase?

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:bundle
ci:test:relevant
ci:test:stable

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
@drewbrokke
Commit https://github.com/liferay-appsec/liferay-portal/pull/823/commits/bb422e3e5e5c7782081966f59112a1e6db74653a added with the description

**Comment by weller0246** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
@weller0246 could you please try out the test cases using the properties we talked about, thanks in advance!

**Comment by weller0246** [comment]
ci:test:security

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:usm

**Comment by weller0246** [comment]
@gaborlovasdotcom  @JoyceWang08211  please review my test cases, thank you

**Comment by gaborlovasdotcom** [comment]
@weller0246 as soon as you add us as reviewers ;)

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
@stian-sigvartsen or @alvarosaugarlr could you please review the version increase issue, or we might need to send this directly?

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
Running while we have 1k+ nodes free at CI :)

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
To merge this PR (with some minor tweaks), I squashed renaming style commits and split the PR into 3 batches of commits. Those PRs are:

1. The default instance https://github.com/brianchandotcom/liferay-portal/pull/132628
2. Integration tests https://github.com/brianchandotcom/liferay-portal/pull/132943
3. Virtual instances https://github.com/brianchandotcom/liferay-portal/pull/133477

The last PR required some additional SF rounds:

1. https://github.com/brianchandotcom/liferay-portal/pull/133622
2. https://github.com/brianchandotcom/liferay-portal/pull/133711 (currently in review)

**Comment by stian-sigvartsen** [comment]
The last PR was sent a 3rd time to brianchandotcom/liferay-portal/pull/133822 but that required further changes. I am currently working on sending liferay-appsec/liferay-portal/pull/1167

**Pull request closed without merging**
