### PR TITLE
LPS-185213 Utilize Simple CAPTCHA via Headless API

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi team,
This PR is linked to this: https://liferay.atlassian.net/browse/LPS-185213

Summary, in this PR we implement a Headless API to generate SimpleCaptcha for the usage of validating form, etc. Users can switch choosing between this new SimpleCaptcha Headless API or the old one by configuration which is enable/disable by feature flag. 

Please review and leave your comment.
Thanks,
Quan
cc @locpham97 @tototrinh

### CODE REVIEW

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:security

**Comment by ces-quanhuynh** [comment]
ci:test:stable

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Pull request closed without merging**
