### PR TITLE
LPD-40224

### PR DESCRIPTION
**Pull request by daiazius**
Previous PR: https://github.com/liferay-appsec/liferay-portal/pull/2105

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:security-playwright

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:security-playwright

**Comment by daiazius** [comment]
Probably because I force pushed to the PR the tests are breaking, re running

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
All the tests are passing!

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/2112

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
