### PR TITLE
[TS] LPS-142611

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-142611

Hi Team,

As discussed in [PTR-2666](https://issues.liferay.com/browse/PTR-2666), the goal of this PR is to:
- Remove the timeout restriction for setting up a JAX-WS Provider
- Preserve the current behavior 

**Additional Changes**
I also added some additional changes, regarding the cleanup for CXF resources:
- Move: `BusFactory.clearDefaultBusForAnyThread(_bus);` 
  - To execute when we unregister the created JAX-WS Provider, instead of only when the configuration is modified
- Add: `BusFactory.setDefaultBus(null);` 
  - To me, adding this seems logical.

Feel free to remove these additions, if you think they shouldn't be added. I have also included links to additional resources below, in case you would like to look into this some more.

**Additional Note**
Also, I'm not familiar with the portal-osgi-configuration.properties file.
I just ran the ant command to regen the file, please amend it, if needed.

Feel free to let us know if you have any questions.
Thanks!

/cc @peterpetrekanics

----

**Additional Resources - BusFactory cleanup**
- https://cxf.apache.org/javadoc/latest/org/apache/cxf/BusFactory.html
- https://docs.jboss.org/author/display/WFLY/Apache%20CXF%20integration.html#108626169_ApacheCXFintegration-UsingexistingBusinstances

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:help

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:headless

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:headless

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
