### PR TITLE
LPD-40224

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-40224

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:security-playwright

**Comment by daiazius** [comment]
ci:test:security-playwright

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
The new playwright tests didn't run in our suite, had to add it to test.properties. The errors in the other suites don't seem to be related, running CI again

**Comment by daiazius** [comment]
The playwright test failures are unrelated, the new test is working fine

**Comment by rafaprax** [comment]
Hey @daiazius,

This fix has an issue. The filter by date is working, but the filter by resource action is not. (I believe that there might be more options that are not working.) 

Can you please check that and resend the fix?

Also, try to cover this scenario in your test.

Thanks, Pedro

**Pull request closed without merging**
