### PR TITLE
Sequence diagram for DefaultUserResolver

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@gaborlovasdotcom I've tried to keep it brief, but there was a fair amount to capture in this flow

**Comment by stian-sigvartsen** [comment]
ci:stop

**Review by gaborlovasdotcom — APPROVED** [review]
Looks good to me, as it's code level this will be very useful for debugging sequence errors we will have in test cases

**Comment by gaborlovasdotcom** [comment]
@stian-sigvartsen Are we want to push this type of documentation to master, or we could close this PR as an experiment?

**Comment by stian-sigvartsen** [comment]
@gaborlovasdotcom it would be good to push it I think. I am wondering if we should tweak it in any way before doing so.

**Comment by gaborlovasdotcom** [comment]
@stian-sigvartsen One thing, I wonder if there is an out-of-the-box documentation solution that could build up the same or similar graphs for java code?

**Comment by stian-sigvartsen** [comment]
I have seen such tools before. UML generators for Java. But I think the result is usually very verbose and I doubt there is a tool that understands OSGi. I want to be proved wrong though :) 

I think if we make sequence diagrams like this they should focus on the SPIs specifically. To avoid simply duplicating/rendering the Java implementation which will not be very stable over time.

**Comment by gaborlovasdotcom** [comment]
As we discussed this with Brian the outcomes are:
- We should not put time into documentation, we should improve our code readability better
- It's better to put such time into learning the code paths than checking an outdated documentation
- Integration tests are also a good form of describing what these paths are about, and improves code readability

**Pull request closed without merging**
