### PR TITLE
LPS-148320 [Dev] Site level OSGI configs and LPS-152452 [Dev] Dynamic Banner View

### PR DESCRIPTION
**Pull request by jkappler**
[LPS-152452](https://issues.liferay.com/browse/LPS-152452)
[LPS-152844](https://issues.liferay.com/browse/LPS-152844)
[LPS-148320](https://issues.liferay.com/browse/LPS-148320)

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@gaborlovasdotcom, rebased again, language keys....

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
> ### ✔️ ci:test:stable - 26 out of 26 jobs passed
> ### ❌ ci:test:relevant - 75 out of 77 jobs passed in 1 hour 18 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3259) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1297401_2898
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [d82674bf6b0e14486ad224f38de4258a80a44f88](https://github.com/liferay/liferay-portal/commit/d82674bf6b0e14486ad224f38de4258a80a44f88)
> 
> #### Upstream Comparison:
> Branch GIT ID: [df6998d96dcf7af48fe15f08cd51de7f0ef88aae](https://github.com/liferay/liferay-portal/commit/df6998d96dcf7af48fe15f08cd51de7f0ef88aae)Jenkins Build URL: [Acceptance Upstream DXP (master) #3258](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3258)
> 
> **ci:test:stable - 26 out of 26 jobs PASSED**
> **ci:test:relevant - 75 out of 77 jobs PASSED**
> ##### For more details click [here](https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2898/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/1/5](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/3581//consoleText)1. [LocalFile.DatabasePartitioning#AddNewCompany](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/3581//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DatabasePartitioning_AddNewCompany_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2898/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.DatabasePartitioning_AddNewCompany/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2898/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.DatabasePartitioning_AddNewCompany/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2898/functional-tomcat90-mysql57-jdk8/1/5/jenkins-console.txt.gz)
> 
> #### For upstream results, click [here](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

The above unique functional failure is not related to the current changes, it's caused by [LPS-153083](https://issues.liferay.com/browse/LPS-153083). This is an intermittent issue.

**Comment by jkappler** [comment]
Thanks @JoyceWang08211! I'm sending directly to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/117325

**Pull request closed without merging**
