### PR TITLE
LPD-6757 First pr

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
First pr of [LPD-6757](https://liferay.atlassian.net/browse/LPD-6757)

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:scim

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
running again `ci:test:security` because the Playwright tes is :

> Unable to run build on CI

[TestRay](https://testray.liferay.com/#/project/35392/routines/45357/build/24363111/case-result/24364683)

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:24518509

**Comment by stian-sigvartsen** [comment]
The new SCIM Playwright test is not passing. @daiazius can you have a look?

**Comment by stian-sigvartsen** [comment]
I prepared a separate PR to run test for some SF tweaks however CI would not execute until I sent a PR to a different fork. please see stian-sigvartsen/liferay-portal/pull/303

**Comment by daiazius** [comment]
> The new SCIM Playwright test is not passing. @daiazius can you have a look?

That is strange, the test was working locally the last time I ran it, maybe its something with the CI environment, I'll take a look

**Pull request closed without merging**
