### PR TITLE
Lpd 38816  v3

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
move UI login to jsp and create jspf
add debault.admin.password logic

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
If we only have 1 point where we are including a JSPF, then there is little benefit to splitting that out I think.

**Comment by alvarosaugarlr** [comment]
This is because I have made a new pr with the same change but without using jspf - https://github.com/liferay-appsec/liferay-portal/pull/2098

**Comment by alvarosaugarlr** [comment]
no following this approach

**Comment by stian-sigvartsen** [comment]
The reason is that liferay-appsec/liferay-portal/pull/2098 should be a straight forward solution.
The approach in this current PR could be developed further to make better use of JSPF (fragments) I think. But unless the other PR becomes more complex than currently envisaged, it does not make sense to do this.

**Pull request closed without merging**
