### PR TITLE
[TS] LPS-124963 OpenID Connect breaks session replication

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-124963](https://issues.liferay.com/browse/LPS-124963)
Dear Application Security Team,

Please review my changes.

In short, login with OpenID Connect breaks session replication, because
- OpenIdConnectSessionImpl has non-serializable property -> **NotSerializableException** and
- Deserialization of OpenIdConnectSessionImpl would require OSGi classloader -> **ClassNotFoundException**.

To resolve the ClassNotFoundException I consulted with the Core Infrastructure team who suggested to store OpenIdConnectSessionImpl in HttpSession as byte array.

For more information please see [LPS-124963](https://issues.liferay.com/browse/LPS-124963) or the related PTR. Also, feel free to contact me with any concerns or questions.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:reevaluate:1112004_8325

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . These changes look good. The only change I've made is to hide the implementation detail by creating an interface for your util. In so doing I ended up renaming it to OpenIdConnectSessionHelper, because we don't appear to have many examples of *UtilImpl in the codebase. Maybe I could have left out "Session" in the name, but I thought it would assist devs in discovering this type when they're looking how to obtain the OpenIdConnectSession.

Please see https://github.com/liferay-appsec/liferay-portal/pull/268

**Pull request closed without merging**
