### PR TITLE
LPD-18037

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
@cdbm please can you review the CI results?

**Comment by cdbm** [comment]
@stian-sigvartsen relevant test failures are unrelated, same tests are failing with same exceptions in other prs, see [this](https://github.com/liferay-appsec/liferay-portal/pull/1635#issuecomment-1952411010) and [this](https://github.com/liferay-appsec/liferay-portal/pull/1632#issuecomment-1946396979)

**Comment by stian-sigvartsen** [comment]
Thanks for checking @cdbm and the fix also. I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
