### PR TITLE
LPS-175232 Support parametarized algorithms in CompositePasswordEncryptor

### PR DESCRIPTION
**Pull request by dnebing**
LPS-175232 This change updates the CompositePasswordEncryptor to ignore optional parameters (separated by slashes) when looking up encryption algorithms. This will allow for a custom PasswordEncryptor implementation that supports parameterizing key size and rounds just like the PBKDF2 encryptor supports. There is only a small change to the _select() method to strip parameters off of the algorithm prior to lookup.

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
ci:test:bundle

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
Hi @dnebing . This looks great except for one thing. If customer have already registered `PasswordEncryptors` with `"type=ALGORITHM/ARGUMENTS"` (because they have to currently) then these should continue to be used as a preference over new `PasswordEncryptors` registered only with `"type=ALGORITHM"`. Can you send a commit?

Also please can you could add an integration tests for
1. the new functionality 
1. maintaining the existing behaviour for existing customers (as above)

Because this is a story ticket, our convention is to key those commits like

```
LPS-176957 ANY REASONABLE COMMIT MESSAGE.

For LPS-175232.
```

**Comment by stian-sigvartsen** [comment]
Please see  liferay-appsec/liferay-portal/pull/1190

**Pull request closed without merging**
