### PR TITLE
LPS-96845 LPS-201399 Decorate the charon UserResourceManagerI implementation to give support to handle the ConflictExpection into the updateWithPUT method. it was required to cover the the AC-15 from the https://liferay.atlassian.net/browse/LPS-97345

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey all, the last push fixed the rest builder's related failure. Thx

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
I have added my commits for AC-1 & AC-2 and sent to liferay-appsec/liferay-portal/pull/1515

@rafaprax tagged a 2nd line on each of your commits to say "For LPS-97345" so we can easily filter commits by the story later.

Leaving this PR open to allow the test runs to complete.

**Comment by stian-sigvartsen** [comment]
CI testing looks good on both PRs. Closing this one because it is the subset

**Pull request closed without merging**
