### PR TITLE
LPD-26723

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-26723

Also resolves [LPD-41188](https://liferay.atlassian.net/browse/LPD-41188)

Without my changes, when the user navigates back to the SP, [PortalImpl.getUser() will return the previously authenticated user](https://github.com/liferay/liferay-portal/blob/bd8371069d06f7c3738f40f1d92732529e6a4692/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L5142-L5146), even after they have logged out.  This affects the portal in a few ways, the most noticible is in the [ServiceContextFactory class](https://github.com/liferay/liferay-portal/blob/bd8371069d06f7c3738f40f1d92732529e6a4692/portal-kernel/src/com/liferay/portal/kernel/service/ServiceContextFactory.java#L207), where if we have a valid USER or USER_ID attribute, then [we set the ThemeDisplay to signedIn and give it the User Id](https://github.com/liferay/liferay-portal/blob/bd8371069d06f7c3738f40f1d92732529e6a4692/portal-kernel/src/com/liferay/portal/kernel/service/ServiceContextFactory.java#L221-L222), which later on bites us, because [we set the signedIn value](https://github.com/liferay/liferay-portal/blob/bd8371069d06f7c3738f40f1d92732529e6a4692/portal-kernel/src/com/liferay/portal/kernel/service/ServiceContextFactory.java#L191) to true, and therefore [the initial check in login.jsp passes](https://github.com/liferay/liferay-portal/blob/bd8371069d06f7c3738f40f1d92732529e6a4692/modules/apps/login/login-web/src/main/resources/META-INF/resources/login.jsp#L11), rendering the user icon.

For tests, I've actually just removed some existing code which bypassed this issue.  I initially believed this to be a front-end bug, so I chose to workaround the tests, since it seemed trivial enough (the user is fully un-authenticated, just the icon shows up).  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
Thanks for the quick analysis and solution @ChrisKian !
I don't think we can go with this as a final solution because it is not a good practice to recycle a session for different users. In this case it would be going from an authenticated user session to a guest user session. Which is particularly dangerous.

However now that we have a way to determine the affected commits (using your test!) we can do a bisect analysis to find the commit which caused the regression! 👍

**Comment by stian-sigvartsen** [comment]
Hi @ChrisKian. I think we can close the PR whilst we look at different solutions. If you would prefer to continue on this one, we can reopen.

**Pull request closed without merging**
