### PR TITLE
[TS] LPS-135014 Correct the capacity of the StringBuilder

### PR DESCRIPTION
**Pull request by IstvanD**
https://issues.liferay.com/browse/LPS-135014

Dear Team,

Could you please review this pull request?

I added a small correction to the StringBuilder, so it has the correct capacity for the added String in https://github.com/liferay-appsec/liferay-portal/pull/437/commits/d21d07e3b0c5dbd5098985da71349c13551ffea2

Thank you and best regards,
István

Previous pull: #437

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:security

**Review by lipusz — APPROVED** [review]
:+1: LGTM. You can forward it @IstvanD once the IT team fixes the CDN issues. Just hit `ci:forward`.

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
