### PR TITLE
[prio]LPD-32903 Change upgrade process to prepare for backports

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-32903](https://liferay.atlassian.net/browse/LPD-32903)

This changes are needed so we're able to backport a SEV ticket that contains an upgrade process. [(LPD-1909)](https://liferay.atlassian.net/browse/LPD-1909)

Changes were made based on Alberto Chaparro's guidance on [PTR-5252](https://liferay.atlassian.net/browse/PTR-5252)

cc: @daiazius

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Look good @manuelecastro . Please review the CI test failures and then we can forward

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by manuelecastro** [comment]
ci:report:50026956

**Comment by manuelecastro** [comment]
ci:report:50122425

**Comment by manuelecastro** [comment]
ci:report:50026956

**Comment by manuelecastro** [comment]
resent here: https://github.com/liferay-appsec/liferay-portal/pull/1877

**Pull request closed without merging**
