### PR TITLE
LPD-34901 Cache metadata

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi,

I'm sending this for an initial review to see if the solution is good enough. I will send another pull request as soon as I implemented the automated tests as well.

The story in short is that with [LPS-150092](https://liferay.atlassian.net/browse/LPS-150092) we removed OpenIdConnectMetadataFactoryImpl that was responsible for metadata caching. Now I'm giving back metadata caching.

Thank you for checking!
István

cc @stian-sigvartsen @alvarosaugarlr

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:report:13252791

**Comment by stian-sigvartsen** [comment]
ci:report:13252791

**Pull request closed without merging**
