### PR TITLE
LPS-129441 CXF Upgrade

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1037401_9602

**Comment by arthurchan35** [comment]
ci:reevaluate:1037401_9602

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
