### PR TITLE
LPD-30593 | The create account URL page remains accessible after disabling this feature

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
https://liferay.atlassian.net/browse/LPD-30593

Issue:
The create account form is accessible even if the `company.security.strangers=false`

Solution:
If the `company.security.strangers=false` then we redirect to login page.

Best regards,
Évi

### CODE REVIEW

**Comment by evibudai** [comment]
ci:test:sf

**Comment by evibudai** [comment]
ci:test:sf

**Comment by evibudai** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci errors are not related with the changes.

**Comment by alvarosaugarlr** [comment]
reviewed and tested and it is ok for me

**Comment by stian-sigvartsen** [comment]
Just needed some SF. Please see liferay-appsec/liferay-portal/pull/1855

**Pull request closed without merging**
