### PR TITLE
[TS] LPS-174987

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://issues.liferay.com/browse/LPS-174987

IBM Security Verify can produce session indexes that exceed the current 75 character limit. I'm unsure of the best size but thought 200 would be sufficient.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
LGTM @jonathanmccann . I can't find any limit on SessionIndex in the specification, but we don't expect a huge number of records in this table so it should be fine to make it 200 chars. Once CI passes I will forward.

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
