### PR TITLE
LPS-181517 Allow the MailTemplate to decide whether to escape the value for these tokens, instead of forcing the escaped value to always be used

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Ticket: [LPS-181517](https://issues.liferay.com/browse/LPS-181517)

I decided to send this PR here, since it's related to [LPS-83304](https://issues.liferay.com/browse/LPS-83304). 
- For additional details, please see: [LPS-181517#comment-2889839](https://issues.liferay.com/browse/LPS-181517?focusedCommentId=2889839&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2889839)

Please let me know if you have any questions or concerns.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:security

**Comment by ericyanLr** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1407401_1582

**Comment by stian-sigvartsen** [comment]
Hi @ericyanLr . This looks good but I wanted to ask if you have CI tested it elsewhere already?

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @stian-sigvartsen ,

Nope, I haven't had CI test it elsewhere, this is the first PR.

**Comment by stian-sigvartsen** [comment]
@ericyanLr The failures appear to be unrelated. It is a good solution, thanks! I will forward now.

For future PRs please can you wait with assigning the ticket to us until CI tests pass or you have verified CI failures are unrelated, or you require our input to check that.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
