### PR TITLE
LPS-162282 User enumeration attack with password expiration.

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comment. Thanks.
Ticket: Ticket: https://issues.liferay.com/browse/LPS-162282
cc @chileces

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
@alvarosaugarlr could you please review the unique relevant failures?

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
Local tests successfully run

**Comment by alvarosaugarlr** [comment]
ci:reevaluate:1397401_951

**Comment by alvarosaugarlr** [comment]
ci:forward

**Pull request closed without merging**
