### PR TITLE
LPS-193844

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
Original [pr](https://github.com/liferay-appsec/liferay-portal/pull/1324)

### Original description
Ticket: [LPS-193844](https://liferay.atlassian.net/browse/LPS-193844)

Previously discussed with @stian-sigvartsen on [PTR-3993](https://liferay.atlassian.net/browse/PTR-3993).

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
Reviewed the changes and tested.

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JessieZhao0714** [comment]
Resolved conflict and continued in [#1340](https://github.com/liferay-appsec/liferay-portal/pull/1340)

**Pull request closed without merging**
