### PR TITLE
LPS-126598 Archive NTLM

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@arthurchan35 and I believe the `ViewPortalSmokeArchive*` tests relate to x-branches and should not be failing this PR to master.

The other failures are not unique.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/106749

**Pull request closed without merging**
