### PR TITLE
LPS-134954 Hidden mappings 

### PR DESCRIPTION
**Pull request by liferay-appsec**
This PR goes a little beyond just fixing the specific bug of implicit mappings not being overridden by explicit ones. It would be straight forward to reduce the fix to just that, if desirable, however I think we should also demystify the implicit mappings behavior in general. Because this is poorly documented and can have considerable impact ...

I implemented a new checkbox on the admin UI for SAML IDP connections.

- When checked, implicit mappings are used as before (but with the bug fixed of course)
- When unchecked, there are no implicit mappings 

For new SAML IDP connections it is unchecked by default, because it should be a conscious decision by the admin to allow implicit mappings.

For existing SAML IDP connections, it is checked (see upgrade process). So existing customers do not see any behavioral change.

So essentially it is a release feature flag.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
I ran out of time to review the existing tests. The failed tests presumably rely on implicit mappings and need tweaking.

**Comment by ferenconodiD** [comment]
ci:test:build

**Comment by ferenconodiD** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:help

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle:norebase

**Comment by ferenconodiD** [comment]
ci:test:bundle:norebase

**Comment by gaborlovasdotcom** [comment]
@arthurchan35 Could you please resolve the conflict, as the bundle created without rebase is not starting up at  @ferenconodiD's

**Comment by stian-sigvartsen** [comment]
Conflicts resolved and rebased: liferay-appsec/liferay-portal/pull/615

**Pull request closed without merging**
