### PR TITLE
LPS-166489

### PR DESCRIPTION
**Pull request by istvansajtos**
Resending as per Brian's request: https://github.com/brianchandotcom/liferay-portal/pull/125814#issuecomment-1304373973

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:forward

**Comment by istvansajtos** [comment]
ci:help

**Comment by stian-sigvartsen** [comment]
Thanks @istvansajtos

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:reevaluate:1297401_5333

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
