### PR TITLE
LPS-206231 DXP SP does not correctly handle RelayState provided via IDP Initiated SSO

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-206231](https://liferay.atlassian.net/browse/LPS-206231)

Hi @stian-sigvartsen !

I did what you suggested on the ticket description, but I couldn't think of a way to handle the scenario where  `_relayStateTokensToRedirects` is expired. Can you take a look? 

Thanks :)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
Hi @manuelecastro . Thanks for looking into it. If there is no cleverer solution to the SP issue, then can you add a prefix to the value of `relayStateToken` so that it can be differentiated from a manually provided URL?

For example RDR_{CURRENT_UUID}.

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
Hey @stian-sigvartsen ! 

I just sent the changes. Also, that was a good catch that you suggested, I didn't though about doing so.

Thanks for the review! :smile:

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@manuelecastro looks good now I think. Will forward if CI passes it.

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Asked for QA assistance to review the Poshi test failures.

**Comment by JessieZhao0714** [comment]
No unique failure was found.
cc @stian-sigvartsen and @manuelecastro

**Comment by stian-sigvartsen** [comment]
Thanks for checking @JessieZhao0714 ! I will then forward.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
