### PR TITLE
LPS-128578 

### PR DESCRIPTION
**Pull request by martamedio**
@stian-sigvartsen Thank you for your help in solving this issue 👏

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:saml

**Comment by jpince** [comment]
ci:test:saml

**Comment by jpince** [comment]
@pyoo47 git clean issue on [this axis](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/466304//consoleText). not sure if this is the same issue as yesterday.
```
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:195: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:9684: Sourced file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : Method Invocation gitWorkingDirectory.clean : at Line: 100 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : gitWorkingDirectory .clean ( ) 
```

**Comment by jpince** [comment]
semver passed on the first test run, so I'm not going to retest.

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
