### PR TITLE
LPS-185213

### PR DESCRIPTION
**Pull request by locpham97**
Hi @alvarosaugarlr , 
Please help me review this PR.
This PR is the same as the previous PR https://github.com/liferay-appsec/liferay-portal/pull/1429. However, I made some changes in SimpleCaptchaImpl to fit AuthVerifierFilter in this commit https://github.com/liferay-appsec/liferay-portal/pull/1465/commits/e38afa1728dfbf971ea195fc7b3af11f81567de6.
Many thanks,
Loc
cc: @tototrinh, @ces-quanhuynh

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by locpham97** [comment]
ci:test

**Comment by locpham97** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:secuirty

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
The requested change has been applied
Functionality has been tested and works correctly
Ci errors have been reviewed and it is not related to the functionality

It would be convenient that the pr only shows the commits related to the feature.

**Comment by locpham97** [comment]
Hi @Álvaro Saugar , 
The other commits come from rebasing the master upstream.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
