### PR TITLE
LPS-174593 Rounds

### PR DESCRIPTION
**Pull request by liferay-appsec**

### CODE REVIEW

**Comment by liferay-appsec** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1407401_9986

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@victorhcunha @slnn can the login test be executed on this change with PW encryption enabled? compare to master.

The portal property will just need to be different
Master: `passwords.encryption.algorithm=PBKDF2WithHmacSHA1/160/720000`
This Branch: `passwords.encryption.algorithm=PBKDF2WithHmacSHA1/160/1300000`

**Comment by stian-sigvartsen** [comment]
@vicnate5 I have rebased the PR to the latest master as we discussed

**Comment by slnn** [comment]
@victorhcunha is running the tests on login with fixed pressure like what we did for whitepaper

**Comment by victorhcunha** [comment]
Hi @vicnate5 !
Here are partial results for login test case.

Portal Version | Git Id | passwords.encryption.algorithm | Session Count | Mean Time of Login | Mean Time Change (%) | Portal CPU Usage (%) | DB CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 4ff2fca | PBKDF2WithHmacSHA1/160/720000 | 4596 | 54500 | - | 99,99,99 | 2,1,2
PR | - | PBKDF2WithHmacSHA1/160/1300000 | 5122 | 111000 | 11.44473455 | 99,99,99 | 1,1,1

These are the results of our test without fixed pressure, as @slnn said I am running the tests with fixed pressure and will update you with the new results when they are ready. More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1X2OwZFX39cXWAgMKd8M-Lk0oudkIPAhcpp7fx80N3Kg/edit#gid=0).

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
I have manually forwarded the PR to brianchandotcom/liferay-portal/pull/151732

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by victorhcunha** [comment]
Hi @vicnate5  @stian-sigvartsen 
Here are the results with fixed pressure:

Portal Version | Git Id | passwords.encryption.algorithm | Fixed Session Count | Mean Time of Login | Mean Time Change (%) | Portal CPU Usage (%) | DB CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 4ff2fca | PBKDF2WithHmacSHA1/160/720000 | 200 | 472 | - | 19,20,20 | 1,1,1
PR | - | PBKDF2WithHmacSHA1/160/1300000 | 200 | 955 | 102.3305085 | 42,42,43 | 1,1,1

More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1X2OwZFX39cXWAgMKd8M-Lk0oudkIPAhcpp7fx80N3Kg/edit#gid=0).

**Comment by slnn** [comment]
Hi @vicnate5 

From the test result, with the same fixed pressure, the mean time of this pr is bigger than master, it means poor performance.


Thanks
Lily

**Pull request closed without merging**
