### PR TITLE
[TS] LPS-133585

### PR DESCRIPTION
**Pull request by cleydyr**

### CODE REVIEW

**Comment by cleydyr** [comment]
ci:test:sf

**Comment by cleydyr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @cleydyr ! Forwarding under liferay-appsec/liferay-portal/pull/425

**Comment by stian-sigvartsen** [comment]
Original change was better. Forwarding...

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Needed some additional work: Please see liferay-appsec/liferay-portal/pull/427

**Pull request closed without merging**
