### PR TITLE
[TS] LPS-173082

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-173082

SAML URLs (`/portal/saml/acs` and `/portal/saml/auth_redirect` at least in my testing) should be counted as login requests, otherwise it's possible for the portal to redirect to the login portlet if the "Prompt Enabled" is checked for guest user authentication during SAML auth.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by jpince** [comment]
@ChrisKian 
1. Please see SF error:
`The commit 'LPS-173082 Allow SAML URLs to be considered login requests as well' contains the word 'login', which could reveal potential security vulnerablities. Please see the vulnerability keywords that are specified in source-formatter.properties in the liferay-portal repository.`
2. The connection errors in other test batches were caused by a CI network issue ([Slack thread](https://liferay.slack.com/archives/C19PWQ74J/p1674000079597179)), so you can retest once the SF error is resolved.

Thank you!

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
HI @ChrisKian ! Sorry it has taken a while to get back to you. This change required a lot of testing. I think you found the correct solution, thanks! The only change I made is to preserve SAML as a modular app. Please see liferay-appsec/liferay-portal/pull/981

**Pull request closed without merging**
