### PR TITLE
[TS] LPS-148409 Allow video tag and src attribute for source tag in AntiSamy configuration

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hello,

Please let me know if you need help testing the solution.
Thank you,
István

**Comment by oliverkecskemety** [comment]
Hi @IstvanD,

Thanks for your fix! I checked it and I like the solution overall but I have 2 remarks:

1. There is a part in each file for `<!-- Image & image related tags -->`. I would put the video related tags under that, under a new `<!-- Video & video related tags -->` part.
2. I think the available `video` attributes are very limited and I'm pretty sure a user would not just want to use `width` and `controls`. Please refer to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video). I think the best would be to support non-experimental attributes as restricted as we can.

They would be the following:
- `autoplay` - boolean but if defined it's always true so the possible values should be `true` or nothing
- `controls` - same as `autoplay`
- `crossorigin` - `anonymous` or `use-credentials`
- `height` - numbers only
- `loop` - same as `autoplay`
- `muted` - same as `autoplay`
- `poster` - onsite or offsite URL
- `preload` - `none`, `metadata` or `auto`
- `src` - onsite or offsite URL
- `width` - numbers only

In my opinion supporting only `controls` and `width` would cause problems later, so please add these as well.

Thanks!

**Comment by IstvanD** [comment]
Hi @oliverkecskemety 

Thank you for reviewing and your observations so far!
I have force-pushed the suggested changes.

Please note that the values "boolean but if defined it's always true so the possible values should be `true` or nothing" can only be enabled with the "anything" regex. See the `nowrap` or `disabled` attributes for examples.

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
Hi @IstvanD,

It looks good to me, thanks!

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
