### PR TITLE
LPS-120270 cleaned up

### PR DESCRIPTION
**Pull request by arthurchan35**
From:https://github.com/liferay-appsec/liferay-portal/pull/231

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Pull request closed without merging**
