### PR TITLE
LPS-175232 Support parameterized algorithms in CompositePasswordEncryptor - Don't match full algorithm

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:forward:force

**Comment by nikolettabuza** [comment]
ci:forward:force

**Pull request closed without merging**
