### PR TITLE
LPS-204341 Change in LDAP Settings at System Scope

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-204341](https://liferay.atlassian.net/browse/LPS-204341)

When fetching the LDAP configuration, the configuration is retrieved at instance level, but if it does not exist it tries to retrieve it at Systema level. The problem is that it is not fetched in the same way it is stored. 

## Problem
The problem is because the way the system level configuration is stored and how it is retrieved are different. 

To store the configuration it is done as a company level configuration, so the `service.Pid` property is used as an identifier indicating the configuration value.

On the other hand, to fetch it is used a provider (all cases extends of `CompanyScopedConfigurationProvider`) that filters by `factoryPid`. This property is not generated by OSGi when it stores the configuration at system level, so, even if you try to fetch the corresponding configuration in the code, it is never found. 

For example, the Authentication configuration ([LDAPAuthConfiguration](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security/portal-security-ldap-api/src/main/java/com/liferay/portal/security/ldap/authenticator/configuration/LDAPAuthConfiguration.java)) in System settings is save as a system configuration In database is store as:

```
 :org.apache.felix.configadmin.revision:=L"1"
companyId=L"0"
enabled=B"false"
method="bind"
passwordEncryptionAlgorithm="NONE"
passwordPolicyEnabled=B"false"
required=B"true"
service.bundleLocation="?"
service.pid="com.liferay.portal.security.ldap.authenticator.configuration.LDAPAuthConfiguration"
```

But to get the configuration, it is used a provider ([LDAPAuthConfigurationProviderImpl](https://github.com/liferay/liferay-portaltLDAPAuthConfigurationProviderImpl)) that get the configurations with:

`factoryPid=com.liferay.portal.security.ldap.authenticator.configuration.LDAPAuthConfiguration`

as the System configuration (Authentication tab) is store as system without `factoryPid`, it is not recovered.

This problem occurs with configurations:

- LDAPAuthConfiguration
- LDAPExportConfiguration
- LDAPImportConfiguration
- SystemLDAPConfiguration

### Solution  
To solve it, what has been done, at the time of retrieving the system configuration, is to make a filter by the properties that the configuration must have:

- `service.Pid` with the value of the configuration class.
- `companyId = 0`

### Manual

the following cases have been tested:

- If no configuration is defined, the default configuration is restored.
- If a configuration is defined at the System Settings level, the system level configuration is restored.
- If a configuration is defined at instance level, the Instance Settings configuration is retrieved, even if another configuration exists at system level. 

- It has also been tested to start a clean bundle  to verify that the configuration is recovered correctly.
- After starting this clean bundle, the connection to an LDAP (Apache DS) was configured to verify that it connects correctly. 

### Integration

Four tests have been created, one for each configuration. 

- `LDAPAuthConfigurationProviderImplTest`
- `LDAPExportConfigurationProviderImplTest`
- `LDAPImportConfigurationProviderImplTest`
- `SystemLDAPConfigurationProviderImplTest`

In each test there are three tests covering the cases:

- `testGetDefaultSettings` - You have to retrieve the default settings. 
- `testGetSystemSettings` - You have to retrieve the configuration defined at system level (System Settings)
- `testGetInstanceSettings` - You have to retrieve the settings defined at instance level (Instance Settings)

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
I believe some of these test failures are relevant, as I was not able to start a clean bundle with the changes from this PR.

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
reviewed the ci errors and are not related with this feature.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
New [pr](https://github.com/liferay-appsec/liferay-portal/pull/1607) with a new solution.

**Pull request closed without merging**
