### PR TITLE
LPD-40120 DB query used to retrieve OAuth2 grants during headless API…

### PR DESCRIPTION
**Pull request by rotty3000**
… calls is not cached

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:oauth2

**Comment by jgarcialr** [comment]
ci:report:50471934

**Comment by stian-sigvartsen** [comment]
Looks great @rotty3000 . Thanks!

**Comment by stian-sigvartsen** [comment]
The failures are caused because when `OAuth2ScopeGrant` is persisted, it then expects there to exist a field `accessTokenContent` on that entity. But that's not there, by design the `OAuth2ScopeGrantFinderImpl` does a 3 way inner join to filter on `accessTokenContent`.

I'm looking at options, but I don't think the proposed solution is possible.

**Comment by stian-sigvartsen** [comment]
I have sent an alternate solution leveraging existing caches for testing at liferay-appsec/liferay-portal/pull/2033

**Comment by stian-sigvartsen** [comment]
The linked alternative solution was merged. I am closing this PR.

**Pull request closed without merging**
