### PR TITLE
LPS-130594 Saml Lang

### PR DESCRIPTION
**Pull request by martamedio**
Hey Brian

We have detected that the solution you had proposed for `saml-lang` does not work correctly and does not read some properties. 
Also note that the functionality that we are removing (I mean `extends ResourceBundle...`, which I think it's present in Commerce modules) would not work in any case where there is a language change, as it only reads the properties for one language (`LocaleThreadLocal.getDefaultLocale()`).

I think with this solution we cover all available languages and also reads the properties correctly in this special case of SAML.
Note that we need to add a reference to the resource bundle of the `saml-api` and `saml-lang` modules to force the Registrator to wait until when all SAML modules are already loaded in the Portal.

I don't know if there is another way to do this, let me know what you think! Thanks!

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1047401_8002

**Comment by gaborlovasdotcom** [comment]
ci:test:saml:nocompile

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:saml:nocompile

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
