### PR TITLE
LPD-23110 integration tests

### PR DESCRIPTION
**Pull request by tomibiro**
I added 2 integration tests which are checking the failure count reset and lockout reset.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
We discussed offline that we should isolate the test methods between each other (and a non-vanilla dev's DXP) by creating the PasswordPolicy dynamically. I will hold off reviewing the PR until then.

**Comment by tomibiro** [comment]
Sorry for pushing half-ready tests to my branch, I wanted to share the ongoing job with István.

**Comment by tomibiro** [comment]
The Dynamic PasswordPolicy setting was applied and works well.

**Comment by tomibiro** [comment]
I removed the previous commits which modified the @TearDown method for a dynamic creation/removal users and passwordPolicy, because it made the test unstable.
If I checkout this latest commit it gives stable testing results.

**Comment by tomibiro** [comment]
ci:help

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:stop

**Comment by tomibiro** [comment]
this last result was due to testing my setup in github (am I able to run ci commands or not)

**Comment by tomibiro** [comment]
Hi @stian-sigvartsen, I checked the last ci test failures, and none of them were relevant to my modifications: https://github.com/liferay-appsec/liferay-portal/pull/1761#issuecomment-2134151073

**Comment by stian-sigvartsen** [comment]
Great with @tomibiro . I will forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
