### PR TITLE
LPD-34901

### PR DESCRIPTION
**Pull request by istvansajtos**
Sending new PR with the changes requested at https://github.com/brianchandotcom/liferay-portal/pull/156529#issuecomment-2512318279

cc @stian-sigvartsen

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
@stian-sigvartsen , can you please take a look at my changes? Thank you!

**Comment by stian-sigvartsen** [comment]
Looks great @istvansajtos ! Once CI passes I will forward.

**Comment by istvansajtos** [comment]
ci:report:84387133

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by istvansajtos** [comment]
@stian-sigvartsen , FYI, there is no unique failure in relevant test suite. 

The upgrade test suite failed to run, it looks like a CI infrastructure problem. I will make another attempt, but I also ran my upgrade test locally and it passed.

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by stian-sigvartsen** [comment]
Thanks @istvansajtos . Since it is only a small tweak to the previously CI tested PR I think we have enough confident to proceed. I will forward it.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
