### PR TITLE
LPS-130870 CXF Upgrade

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1247401_664

**Comment by martamedio** [comment]
ci:reevaluate:1247401_664

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
😎

**Comment by martamedio** [comment]
Same changes applied using a different ticket issue number, see: https://github.com/liferay-appsec/liferay-portal/pull/355

**Pull request closed without merging**
