### PR TITLE
LPD-6085 The target server failed to respond on IsolationAcrossCompaniesTest

### PR DESCRIPTION
**Pull request by jgarcialr**
Default behavior was changed in https://github.com/brianchandotcom/liferay-portal/commit/37ba4251cd2cedb8a9e35c799c5fe4ee1034b5c6

Prior to that change, an error returned a forbidden status (403), nowadays we return an unauthorized response status (401).

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Review by stian-sigvartsen — APPROVED** [review]
LGTM! Thanks @jgarcialr

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
