### PR TITLE
[TS] LPS-158622

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Can you help review this PR?

https://issues.liferay.com/browse/LPS-158622

**PR Commits**
- The majority of the commits are to refactor the unit test
- The test case to illustrate this issue: 
  - **AuthVerifierPipelineTest#testVerifyRequestWithContextPathAndPortalPathContextAndPortalProxyPath**
- The fix is the last commit: 
  - [LPS-158622 Account for portal proxy path when providing a context path for AuthVerifierPipeline](https://github.com/liferay-appsec/liferay-portal/commit/cbdfcb3f2ea32dffffb1c7069fc08edf03748365)

**Issue**
The current usage / implementation of AuthVerifierPipeline does not account for the Portal Proxy Path property when preparing the AuthVerifierPipeline and when verifying a request.

**The proposed fix:**
- Will now expect the provided **_contextPath** to account for Portal Proxy Path
- Will now account for portal proxy path when verifying a request

I figured this would be the more consistent approach, since many places in Liferay code already account for the proxy path when referring to the context path.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ericyanLr see 1bb8e9151696bf97dad1d95a08df226aac72b8b7 and 32ce6f1a2d73a9b4312fadd1daadd8cb503c7b08

I merged this to master and the temp branch.

**Comment by brianchandotcom** [comment]
@ericyanLr see 1bb8e915 and 32ce6f1a merged to master and temp branch.

**Comment by stian-sigvartsen** [comment]
@ericyanLr I'm reviewing these changes at the moment. Will send follow up commits if I find any issues.

**Comment by stian-sigvartsen** [comment]
Thanks for reporting, exploring, and fixing this issue with me @ericyanLr !
As discussed, your fix functions correctly, but it would be a little more succinct to avoid proxy path awareness because incoming requests are not. 

We found that `PortalUtil.getPathContext()` is used in some places where awareness of the proxy path is not strictly needed, and this has resulted in other bugs which we need to investigate separately.

Sent some additional commits under LPS-159485 liferay-appsec/liferay-portal/pull/772

**Pull request closed without merging**
