### PR TITLE
LPD-21445 - Editing Global Web Contents triggers site template propagations

### PR DESCRIPTION
**Pull request by DaniSzimko**
[JIRA ticket](https://liferay.atlassian.net/browse/LPD-21445)

Reason: the LayoutLocalServiceUtil.getLayout(plid) method triggers siteTemplatePropagation

Please review the change that I've made in the SessionAuthToken.java class from a security point of view.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless

**Comment by dacousalr** [comment]
ci:test:headless

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
[Pr](https://github.com/liferay-appsec/liferay-portal/pull/1718) sent to Brian.

**Pull request closed without merging**
