### PR TITLE
LPS-148619 Custom parameters for OIDC

### PR DESCRIPTION
**Pull request by arthurchan35**
[LPS-148619](https://issues.liferay.com/browse/LPS-148619)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
The above unique functional failures are due to the following errors:
```
[exec] 2022-03-10 11:51:10.004 ERROR [CM Configuration Updater (Update: pid=com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration~default)][LogService:93] [org.osgi.service.cm.ManagedServiceFactory, com.liferay.portal.security.sso.openid.connect.OpenIdConnectProviderRegistry, id=8277, bundle=302/file:/opt/dev/projects/github/liferay-portal/bundles/osgi/portal/com.liferay.portal.security.sso.openid.connect.impl.jar]: Unexpected problem updating configuration com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration~default {org.osgi.service.cm.ConfigurationAdmin}={service.description=Configuration Admin Service Specification 1.6 Implementation, service.id=51, service.bundleid=59, service.scope=bundle, service.vendor=The Apache Software Foundation, service.pid=org.apache.felix.cm.ConfigurationAdmin}
     [exec] java.lang.RuntimeException: Unable to create snapshot class for interface com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration
     [exec] 	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:99) ~[?:?]
     [exec] 	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil.createConfigurable(ConfigurableUtil.java:50) ~[?:?]
     [exec] 	at com.liferay.portal.security.sso.openid.connect.internal.OpenIdConnectProviderRegistryImpl.lambda$_rebuild$1(OpenIdConnectProviderRegistryImpl.java:318) ~[?:?]
     [exec] 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[?:1.8.0_121]
     [exec] 	at com.liferay.portal.security.sso.openid.connect.internal.OpenIdConnectProviderRegistryImpl._rebuild(OpenIdConnectProviderRegistryImpl.java:304) ~[?:?]
     [exec] 	at com.liferay.portal.security.sso.openid.connect.internal.OpenIdConnectProviderRegistryImpl._rebuild(OpenIdConnectProviderRegistryImpl.java:286) ~[?:?]
     [exec] 	at com.liferay.portal.security.sso.openid.connect.internal.OpenIdConnectProviderRegistryImpl.updated(OpenIdConnectProviderRegistryImpl.java:152) ~[?:?]
     [exec] 	at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.updated(ManagedServiceFactoryTracker.java:159) ~[bundleFile:?]
     [exec] 	at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.provideConfiguration(ManagedServiceFactoryTracker.java:93) [bundleFile:?]
     [exec] 	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1391) [bundleFile:?]
     [exec] 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [bundleFile:?]
     [exec] 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [bundleFile:?]
     [exec] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
     [exec] Caused by: java.lang.reflect.InvocationTargetException
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
     [exec] 	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:96) ~[?:?]
     [exec] 	... 12 more
     [exec] Caused by: java.lang.IllegalStateException: Attribute is required but not set customTokenRequestParameters
     [exec] 	at aQute.bnd.annotation.metatype.Configurable$ConfigurableHandler.invoke(Configurable.java:83) ~[com.liferay.portal.bootstrap.jar:?]
     [exec] 	at com.sun.proxy.$Proxy1564.customTokenRequestParameters(Unknown Source) ~[?:?]
     [exec] 	at com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfigurationSnapshot.<init>(Unknown Source) ~[?:?]
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
     [exec] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
     [exec] 	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:96) ~[?:?]
     [exec] 	... 12 more
```
I've notified Arthur and he fixed the above issue immediately. 
Rerun relevant run and wait for the new results.

cc @gaborlovasdotcom

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
@weller0246 Please commit your functional tests to this branch when you're ready.

**Comment by weller0246** [comment]
ci:test:oidc:nocompile

**Comment by gaborlovasdotcom** [comment]
@weller0246, in these new developments, please **don't use the :nocompile** suffix, as it will skip the building of the Portal with the new feature.
Use regular command like ci:test:oidc alone.

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc

**Comment by gaborlovasdotcom** [comment]
@arthurchan35, @weller0246 added the functional tests, we only need the additional debug log function to complete the functional test round

**Comment by arthurchan35** [comment]
@weller0246 the commit is missing ticket number.

**Pull request closed without merging**
