### PR TITLE
LPD-5975 Revert "LRQA-81639 Blocked by LPS-160489"

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPD-5975](https://liferay.atlassian.net/browse/LPD-5975)

Reverting `@Ignore` since `com.liferay.oauth2.provider.client.test.DisabledUserClientTest` is not failing anymore.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
running tests to check if `com.liferay.oauth2.provider.client.test.DisabledUserClientTest` still fails

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
`com.liferay.oauth2.provider.client.test.DisabledUserClientTest` passed on security test build successfully, I think it's good to forward. :)
[Testray result](https://testray.liferay.com/home/-/testray/case_results/2535629691?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2535628355%26testrayRunId%3D2535628372%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
