### PR TITLE
LPS-164103, LPS-171571 | Release cookies module

### PR DESCRIPTION
**Pull request by oliverkecskemety**
Rebased #953 on master.

[LPS-164103](https://issues.liferay.com/browse/LPS-164103)
[LPS-171571](https://issues.liferay.com/browse/LPS-171571)
cc @JoyceWang08211, @stian-sigvartsen and @gaborlovasdotcom

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
Seems like Brian's master is not that stable. I'm waiting 'till I can rebase the commits to the original master.

**Comment by JoyceWang08211** [comment]
> Seems like Brian's master is not that stable. I'm waiting 'till I can rebase the commits to the original master.

Hi @oliverkecskemety, did you forget to cherry-pick this [commit](https://github.com/liferay-appsec/liferay-portal/pull/953/commits/3293d098d74c246b436b05213cdb387cf25b25a7)?

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:security

**Comment by oliverkecskemety** [comment]
Hi @JoyceWang08211,

I rebased the PR again and hopefully didn't miss anything. If it wouldn't be so, let me know. :)

**Review by stian-sigvartsen — APPROVED** [review]
LGTM! There is no immediate change to UI by removing the feature flag, and customers can still disable everything if there are any unexpected problems. Perfect! 👍

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
