### PR TITLE
LPS-156903, LRQA-76466

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
- [LPS-156903](https://issues.liferay.com/browse/LPS-156903)
- [LRQA-76466](https://issues.liferay.com/browse/LRQA-76466)

cc @oliverkecskemety

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:stop:security

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Review by oliverkecskemety — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
FYI: @oliverkecskemety I'll forward it directly if stable or relevant fails.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
