### PR TITLE
[TS] LPS-181479 generate cookies with secure flag if portal is considered secure

### PR DESCRIPTION
**Pull request by jvelalr**
- LPS-181479 generate cookies with secure flag if portal is considered secure
- LPS-181479 SF

### CODE REVIEW

**Comment by jvelalr** [comment]
See [#4259](https://github.com/liferay-core-infra/liferay-portal/pull/4259)

Thanks.

**Comment by oliverkecskemety** [comment]
ci:test:cookies

**Review by oliverkecskemety — APPROVED** [review]
Thanks @jvelalr! LGTM

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
