### PR TITLE
LPS-167995 Scope aliases are API

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1337401_2412

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@stian-sigvartsen any updates on this?

**Comment by stian-sigvartsen** [comment]
@jpince the Headless team has been reviewing the CI test failures today. As soon as I hear back I will try to progress as a priority

**Comment by stian-sigvartsen** [comment]
The CI test failures were unrelated. I have added a smaller upgrade process dealing just with `osgi.jaxrs.name` of applications themselves and sent to US&A for review at liferay-headless/liferay-portal/pull/861

**Pull request closed without merging**
