### PR TITLE
[TS] LPS-127037 setting Accept header explicitly to avoid default value

### PR DESCRIPTION
**Pull request by linolaoj**
https://issues.liferay.com/browse/LPS-127037

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Please, see my comment on LPS-127037: sorry to say that this fix does not solve the problem.

**Comment by martamedio** [comment]
See: https://github.com/liferay-appsec/liferay-portal/pull/252

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
