### PR TITLE
LPD-31793 PP should be overriden by user reset field

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:report:7105737

**Comment by stian-sigvartsen** [comment]
There are no relevant CI test failures.

**Comment by alvarosaugarlr** [comment]
Starting to review and test it. 

The first step have been to test the behavior of [LPSA-53087](https://liferay.atlassian.net/browse/LPSA-53087), because it is related -> It works well (more [detail](https://liferay.atlassian.net/browse/LPD-31793?focusedCommentId=2739539))

**Comment by stian-sigvartsen** [comment]
In conversation @alvarosaugarlr we will stop looking for regressions now. The CI results look good.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
There is actually a SF error so will need to make a tweak.

**Comment by stian-sigvartsen** [comment]
I only changed a commit message in the last force push.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
