### PR TITLE
LPS-198057 Sign in button does not work correctly

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-198057

Hi Team :wave: 
In Echo's repo, we have received [a PR](https://github.com/liferay-echo/liferay-portal/pull/13909) to fix this bug.
IMHO, as the bug occurs in the login portlet is there where the solution should be applied in order to prevent consequences on other components. Although it may be to use clay instead of aui in the views could be a better solution.
Could you please review it?
Thanks in advance!
Regards

cc: @henriquelimadotcom

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @lfbesada . This fix is strange because we should not be messing with the AUI internals from a module like `login-web` where we are simply **using** the AUI taglib.

I can see the argument of applying it here to reduce the impact on other components. But the same issue is likely to occur for those other components.

Istvan's comment on 28 Sept on the LPP suggests similarly, I think. Maybe I am not understanding everything correctly.

**Comment by lfbesada** [comment]
Hi @stian-sigvartsen
Thank you very much for your feedback. You are right, I did not understand the problem correctly but @dacousalr has helped me understand it..
I am closing this PR and will resubmit the original solution through the Echo's repo
Sorry for the disruption!
Regards

**Comment by stian-sigvartsen** [comment]
That's great. Glad we have a way forward, thanks for letting me know 👍

**Pull request closed without merging**
