### PR TITLE
LPS-148320 [Dev] Site level OSGI configs and LPS-152452 [Dev] Dynamic Banner View

### PR DESCRIPTION
**Pull request by jkappler**
@gaborlovasdotcom, [LPS-152452](https://issues.liferay.com/browse/LPS-152452) depends on [LPS-148320](https://issues.liferay.com/browse/LPS-148320), so sending both at once. To make the banner visible we still need to enable the FF in portal-ext.properties

feature.flag.LPS-142518=true

Please let me know what you think.

Thanks!

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by jkappler** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Comment by gaborlovasdotcom** [comment]
@jkappler could you please rebase the changes? Thanks!

**Comment by jkappler** [comment]
ci:test:cookies

**Comment by jkappler** [comment]
@gaborlovasdotcom, PR rebased and ci command triggered. Thanks for the help

**Comment by gaborlovasdotcom** [comment]
Thanks @jkappler , I'm testing the new test cases at https://github.com/gaborlovasdotcom/liferay-portal/pull/384

**Comment by gaborlovasdotcom** [comment]
(@jkappler , These test will fail at the moment, as they will need the updates from https://github.com/gaborlovasdotcom/liferay-portal/pull/384.)

**Comment by gaborlovasdotcom** [comment]
Continuing in https://github.com/gaborlovasdotcom/liferay-portal/pull/384

**Pull request closed without merging**
