### PR TITLE
LPD-28294

### PR DESCRIPTION
**Pull request by daiazius**
Resent from: https://github.com/liferay-appsec/liferay-portal/pull/1930

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hi @daiazius ,
I've opened a new PR with some SF changes, see https://github.com/liferay-appsec/liferay-portal/pull/2080

**Pull request closed without merging**
