### PR TITLE
LPS-152126 LPS-157406 LPS-150933 LPS-162107 LPS-170861 | SAML Admin REST tests (+ follow ups) - rebased

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@JoyceWang08211 the `LocalFile.SAML#ImportJSONFileToConfigureSAMLIDP`, `LocalFile_SAML_ImportJSONFileToConfigureSAMLSP` and `LocalFile.SAML#ImportJSONFileToConfigureSAMLSPOnNonDefaultPort` test failures are presumably related. Can you check?

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 the `LocalFile.SAML#ImportJSONFileToConfigureSAMLIDP`, `LocalFile_SAML_ImportJSONFileToConfigureSAMLSP` and `LocalFile.SAML#ImportJSONFileToConfigureSAMLSPOnNonDefaultPort` test failures are presumably related. Can you check?

Thanks for the info. I will update test cases to choose "Only Add new Records" instead of using the default strategy.

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/990

**Pull request closed without merging**
