### PR TITLE
LPD 17826

### PR DESCRIPTION
**Pull request by rotty3000**
- LPD-17826 ignore unknown window messages to prevent token request failure
- LPD-17826 add CSRF protection
- LPD-17826 add debugging flag
- LPD-17826 formatSource

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Confirmed the fix resolves the issue described in the shortened steps here: https://liferay.atlassian.net/browse/LPD-17826?focusedCommentId=2579109

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1397401_9426

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
