### PR TITLE
master | LPS-151195 

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi team,

This PR solve the problem described in the LPS-151195.

The solution implemented is easy. We only need to pass the parameter ui_locales to the AuthenticationRequest.Builder.

To get the current locale I chose the PortalImple.getLocale method. 

Please, let me know if you have any doubt regarding PR.

Regards.

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:oauth2

**Comment by jcampoy** [comment]
hey @liferay-appsec 

is there any progress / question about this PR? we need to move forward in order to provide a solution , could you help us with the review?

Thank you,
Jose

**Comment by jcampoy** [comment]
cc @stian-sigvartsen :)

**Comment by stian-sigvartsen** [comment]
@jcampoy @davidtellolr Thanks for the PR! We're reviewing this today :)
Don't forget to assign us in Jira as soon you want to request review so it appears on our radar. I suspect you intended this on Friday when most tests passed.

**Comment by jcampoy** [comment]
ok! thank you @stian-sigvartsen !

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
