### PR TITLE
[TS] LPS-193127

### PR DESCRIPTION
**Pull request by nikolettabuza**
PR updated with build-services commit. More information on the original PR: [#1344#issue-1873654819](https://github.com/liferay-appsec/liferay-portal/pull/1344#issue-1873654819)

----
Previous PRs: [#1344](https://github.com/liferay-appsec/liferay-portal/pull/1344), [#1317](https://github.com/liferay-appsec/liferay-portal/pull/1317)
[LPS-193127](https://liferay.atlassian.net/browse/LPS-193127)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
Hi team, this is a blocker in a LXC project, can you take care of it asap?

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
Forwarded manually in https://github.com/brianchandotcom/liferay-portal/pull/140484

**Pull request closed without merging**
