### PR TITLE
LPD-31188 ClassCastException after non-graceful shutdown using SimpleSAML

### PR DESCRIPTION
**Pull request by jgarcialr**
Rebased from #1835 

[LPD-31188](https://liferay.atlassian.net/browse/LPD-31188)

There's a ClassCastException due to org.apache.xerces.xni.parser.XMLParserConfiguration is in different ClassLoaders along the portal:

context "ShieldedContainerClassLoader" and classloader "com.liferay.shielded.container.internal.ShieldedContainerClassLoader@457c9034"

context "com.liferay.saml.opensaml.integration_6.2.17" and classloader "org.eclipse.osgi.internal.loader.EquinoxClassLoader@158d9ed3[com.liferay.saml.opensaml.integration:6.2.17(id=1112)]"

If we use CompileOnly, the ClassCastExceptions disappears.

This change (compileOnly to compileInclude) was made as a workaround to solve: https://liferay.atlassian.net/browse/LPS-142409.
I've tested this change in a local websphere and it works as expected.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
Test  passed - [Testray](https://testray.liferay.com/#/project/34754/routines/34756/build/40734121/case-result/40737779)

**Review by alvarosaugarlr — COMMENTED** [review]
### Code

The error occurs basically the problem is the compileInclude and that we have the same library in the portal and in the module, in different classLoaders.

To solve the ticket we have taken into account the classloader load (changes made in `ConfigurationServiceBootstrapUtil`).

Jorge saw that the changes that could be made could affect the ticket [LPS-142409](https://liferay.atlassian.net/browse/LPS-142409) so, although Websphere is no longer supported, as in the version in which the error occurs, it was verified that it is also solved in Websphere. 

### Test

Manually it has been tested that solves the ticket [LPS-142409](https://liferay.atlassian.net/browse/LPS-142409)

To prepare the test to validate the test, it has been tested to reproduce the exception with Tomcat and configuring SAML in Liferay without using SimpleSAML (to facilitate the tests in the ci environment). It was verified that it could be reproduced as well. 

In addition, as the test needs to kill the server, it is not enough to stop it for the exception to occur, a Poshi test has been created (in Poshi it can be done while in Playwright it is not available, we also asked in the Slack channel).

**Comment by stian-sigvartsen** [comment]
Good work @jgarcialr @alvarosaugarlr ! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by jgarcialr** [comment]
ci:forward:force

**Pull request closed without merging**
