### PR TITLE
LPD-37943

### PR DESCRIPTION
**Pull request by ChrisKian**
Story: https://liferay.atlassian.net/browse/LPD-32187
Technical Task: https://liferay.atlassian.net/browse/LPD-37943

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
I'm not sure how this unrelated test is now failing.  Maybe it's been failing for some time, but we haven't ran the SAML suite recently?

**Comment by stian-sigvartsen** [comment]
After reviewing TestRay history for this test, it appears to have been failing on PRs related to [LPD-41377](https://liferay.atlassian.net/browse/LPD-41377) . That ticket was merged last Friday (22nd Nov) so could be causing upstream failure.

I will forward this PR.

**Comment by stian-sigvartsen** [comment]
@ChrisKian . I just noticed the commits are not keyed to the story. The only exception for this is for the application of Feature Flags.

I have rekeyed and sent brianchandotcom/liferay-portal/pull/156397

**Pull request closed without merging**
