### PR TITLE
LPS-167995 Adds upgrade process to OAuth2 Service Module to upgrade to the new application name/scope aliases for custom objects

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-167995](https://issues.liferay.com/browse/LPS-167995)

In [LPS-163728](https://issues.liferay.com/browse/LPS-163728), we modified the name of the OSGi JAX-RS name of custom objects to include the company ID of the object. This caused the names of many services that were generated by custom objects to also get renamed with this same company ID naming scheme.

One such generated service that was renamed is the OAuth2 Application Scopes. Previously, these had been named without the company ID, but as of [LPS-163728](https://issues.liferay.com/browse/LPS-163728), their names now include the company ID.

The problem is that there was no upgrade process to upgrade the existing data that was referencing the old naming scheme. This means that if the user had previously granted any permissions on custom object scopes to an OAuth2 Application, those permissions will essentially be lost upon upgrading to a version of Liferay that includes [LPS-163728](https://issues.liferay.com/browse/LPS-163728).

This fix adds an upgrade process to update the names of these scopes in the database to match the new naming scheme.

### CODE REVIEW

**Comment by jpince** [comment]
@zsigmondrab @noraszel can you please prioritize review for this pull request? This is a blocker for Customer Portal 2.0 launch.

@mbowerman thank you!

**Comment by stian-sigvartsen** [comment]
Hey @mbowerman . If the existing scope names can be maintained that would be favourable correct?
I would expect that because the scope names are API in the sense that customers may have OAuth 2 clients that request specific scopes already (via URL parameter). So the upgrade process would be a breaking change for those clients.

**Comment by mbowerman** [comment]
Hi @stian-sigvartsen,

Correct me if I'm wrong but I don't think it would be feasible to retain the previous scope aliases without making significant modifications to our OAuth2 Scope Aliasing logic. From what I saw debugging through the [ScopeLocatorImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-scope-impl/src/main/java/com/liferay/oauth2/provider/scope/internal/liferay/ScopeLocatorImpl.java class and the [PrefixHandlerFactoryImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-scope-impl/src/main/java/com/liferay/oauth2/provider/scope/internal/spi/prefix/handler/PrefixHandlerFactoryImpl.java) class, the Scope Aliases are directly based on the `osgi.jaxrs.name` property of the deployed service. We _need_ to include the companyId in the `osgi.jaxrs.name`; otherwise, there are all sorts of bugs that occur with Objects becoming visible on other companies (which is a huge problem for LXC especially, given that we want to eventually support multitenancy and not have clients who share the same bundle be able to see each other's custom objects). See [LPS-163728](https://issues.liferay.com/browse/LPS-163728) for more information about that.

From a purely OAuth2 perspective, if we retained the existing scope names, then you could have multiple scopes on different companies that share the same name but point to entirely different APIs. I don't know enough about OAuth2 to know whether this would be an issue, but it seems to me like it would be strange at least.

**Comment by stian-sigvartsen** [comment]
You've done good research into this! It makes perfect sense that `companyId` is included into the `osgi.jaxrs.name` for the reasons you stated.

The OAuth 2 provider is designed with multi-tenancy in mind so there shouldn't be an issue in relation to its OSGi services. The `PrefixHandlerFactoryImpl` is our default implementation of `PrefixHandlerFactory`, driven by configuration. We are using `ScopedServiceTrackerMap` to allow different `PrefixHandlerFactory` services per company, `osgi.jaxrs.name`, or the combination.

What you said about scopes from entirely different APIs sharing the same scope names is actually a feature we call "global scopes". If you remove the bundled "Default" configuration for `BundlePrefixHandlerFactoryConfiguration`, you will experience how that is.

I think it is actually necessary to have the same scope aliases for the same Objects application between different environments like dev/uat/prod. Including `companyId` makes that tricky.

I will continue to explore this tomorrow, but you can have a look liferay-appsec/liferay-portal/pull/903 and let me know if there is anything fundamentally wrong with it?

**Comment by mbowerman** [comment]
Hi @stian-sigvartsen,

Thanks for the explanation! I'm not fully sure if I understood the "global scopes" feature that you mentioned. I guess my one fear is still if the following situation occurs:

* Multitenant LXC environment that has two different customers on the same bundle (let's call them "Customer 1" and "Customer 2".
* "Customer 1" creates an Object on their instance named "Product" with its own fields, relationships, APIs, etc.
* "Customer 2" creates an Object on their instance named "Product", completely separate/different from Customer 1's "Product", with its own fields, etc.
* The generated scope alias will be "C_Product" for _both of these different "Product" Objects.
* "Customer" 1 creates an OAuth2 Application and grants some permissions on the various "C_Product" scopes.

At this point, does "Customer 1" now have access to "Customer 2"'s Product APIs, via their own OAuth2 Application? Or odes the "global scopes" feature handle this case well?

Yeah, I get your point about dev/uat/prod needing to all have the same scope aliases, to facilitate easier migration/duplication between those environments.

I guess I just want to be absolutely sure about the first question I mentioned. Is there any chance that "Customer 1" and "Customer 2" could gain access to each other's Objects if they share the same scope alias? If not, then I think we can go ahead and proceed with your solution.

**Comment by stian-sigvartsen** [comment]
Hi @mbowerman . Thanks for that interesting scenario. You had me frightened there for a while, but I have carefully checked the code and believe this scenario is not possible. The OAuth 2 provider provides complete isolation between portal instances at both access token verification and scope checking. I can elaborate offline.

I have been discussing the way forward with this with the Headless/Objects team and we agreed to review the PR together on Monday.

**Comment by stian-sigvartsen** [comment]
@mbowerman today we agreed the `PrefixHandlerFactory` approach with US&A and I have modified your upgrade process to omit the scope alias upgrade parts. I preserved your commits and added those changes on top. Please see liferay-headless/liferay-portal/pull/861

**Comment by mbowerman** [comment]
Thanks @stian-sigvartsen!

**Comment by stian-sigvartsen** [comment]
Thanks for your deep analysis and work on this. btw I think [497339a](https://github.com/liferay-headless/liferay-portal/pull/861/commits/497339a5d9a3b233bbf77712e8a86b0e1a1732dd) is fine, but great if you could check over also 👍

**Comment by mbowerman** [comment]
497339a5d9a3b233bbf77712e8a86b0e1a1732dd looks reasonable to me.

**Pull request closed without merging**
