### PR TITLE
Lps 145191 jwt client authentication oauth provider

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
@gaborlovasdotcom 
Let me know what you think of my comment in previous PR.
If you agree, I am going to move this PR forward once tests are passed.

**Comment by gaborlovasdotcom** [comment]
@arthurchan35 I wonder if we want to add integration tests for the various catching points defined in bd01c650d636cf79d10160f020f736fec6b99d36 and in 89407cc97b6c6d0384323b9d00fae71b472dd89e, or it's a subject of the functional tests?

cc @JoyceWang08211

**Comment by arthurchan35** [comment]
For the 1st one, it's configuration usage code, used to be in the same class of authorization code handling, but I now I splitted them into 2 classes.
For the 2nd one, I have created integration tests already.

**Comment by arthurchan35** [comment]
ci:test:oauth2

**Comment by arthurchan35** [comment]
See https://github.com/liferay-appsec/liferay-portal/pull/607

**Pull request closed without merging**
