### PR TITLE
LPS-179688 As an Instance Administrator, I want to be able to configure that if the users have the option to give their password at registration

### PR DESCRIPTION
**Pull request by hhtank**

### CODE REVIEW

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:security
ci:test:sf

**Comment by hhtank** [comment]
ci:test:security
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Thanks @hhtank, looks good. I can see from the ACs that there was an expectation to migrate from properties to configuration, but it was presumably not known at the time that the existing `Instance Settings > Users > Fields` UI does not use that. So the PR makes sense. 

I will assign it to our QA team for testing.

**Comment by stian-sigvartsen** [comment]
Forgot to mention, I sent a followup PR to liferay-appsec/liferay-portal/pull/1098 . 
Because the commit messages will still not pass.

**Pull request closed without merging**
