### PR TITLE
LPS 147809

### PR DESCRIPTION
**Pull request by antonio91dev**
- LPS-147809 set url metadata field to empty when loading xml file
- LPS-147809 buildLang

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:saml

**Comment by antonio91dev** [comment]
Hi @arthurchan35 

Has the application passed review? :)

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
