### PR TITLE
[TS] LPS-132536 Add back null check removed accidentally by LPS-130609

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-132536](https://issues.liferay.com/browse/LPS-132536)

Dear Reviewer,

With LPS-130609 I removed a necessary null check by mistake, causing NPE if attributeValue is null.

At the moment I don't have steps to trigger the issue, but obviously the null check should be given back. To the LPS I attached relevant log coming from a patched 7.2 fp11. Line number are different on master, but I identified the root based on that.

Sorry for the inconvenience caused by this. Please let me know if I can be of any help.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf:norebase

**Comment by istvansajtos** [comment]
ci:test:relevant:norebase

**Comment by istvansajtos** [comment]
ci:test:ldap:norebase

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
no problem from me.
@stian-sigvartsen 
if you see no problem, please help forward, thanks.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
That will only improve things, so I will forward. Thanks @istvansajtos @arthurchan35 !

It's also a reminder that we need to improve our LDAP test coverage.

**Pull request closed without merging**
