### PR TITLE
[TS] LPS-125588 Deactivated users should not be imported from LDAP

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-125588](https://issues.liferay.com/browse/LPS-125588)
Dear Application Security Team,

Pease review my changes.

**Issue:** Deactivated users get reactivated at next LDAP import.

**Solution:** We should check the user's status before re-importing from LDAP.

Thanks in advance,
István

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:ldap

**Comment by istvansajtos** [comment]
Also, could you please confirm if my changes can go out in an SDH? Thank you!

**Comment by istvansajtos** [comment]
I start investigating a different approach: enable exporting deactivate users to LDAP to properly keep users sync between portal and LDAP.

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . Just to record our conversation offline conversations... we must allow for LDAP to be the single point of administration for activating and deactivating users when LDAP import is enabled. We believe this is the expectation. So we cannot exclude deactivated users in the import process.

We then explored exporting deactivated users to LDAP. Unfortunately the customer who hit the issue cannot enable LDAP export. But we discussed in our team that it is a bug that such users are not exported. However we will deal with it in a different ticket.

Finally we discovered a solution which we believe should meet the customer's requirements. Please see liferay-appsec/liferay-portal/pull/270

**Comment by istvansajtos** [comment]
Thanks for your work on this @stian-sigvartsen !

**Pull request closed without merging**
