### PR TITLE
LPS 199721 solving

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
The error is due to the changes that were made in the [CookieManagerUtil](https://github.com/shuyangzhou/liferay-portal/blob/2a368a71d14218a456848a165ca6afd50d5202ca/portal-kernel/src/com/liferay/portal/kernel/cookies/CookiesManagerUtil.java) class by the ticket [LPS-199721](https://liferay.atlassian.net/browse/LPS-199721).

After the changes, to resolve the exception in the test, the `CookiesManager` service has been registered in the tests. 

Tickets:

- [LPS-200601](https://liferay.atlassian.net/browse/LPS-200601) -> WebSsoProfileIntegrationTest
- [LPS-200599](https://liferay.atlassian.net/browse/LPS-200599) -> CookiesPreActionTest
- [LPS-202837](https://liferay.atlassian.net/browse/LPS-202837) -> CookiesDomainTest
- [LPS-203046](https://liferay.atlassian.net/browse/LPS-203046) -> XMLSecurityTest

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
@alvarosaugarlr the CI failure is genuine so we need to fix it.

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
There is a rebasing issue with 0d997ac0109a1

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
See https://github.com/liferay-appsec/liferay-portal/pull/1551

**Pull request closed without merging**
