### PR TITLE
[TS] LPS-187776 Remove build ignore

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
[LPS-187776](https://issues.liferay.com/browse/LPS-187776)
In preparation of releasing [LPS-179549](https://issues.liferay.com/browse/LPS-179549), [LPS-179550](https://issues.liferay.com/browse/LPS-179550), [LPS-179552](https://issues.liferay.com/browse/LPS-179552), [LPS-179901](https://issues.liferay.com/browse/LPS-179901) as an enableable feature, I'd like to propose the removal of the .lfrbuild-releng-ignore files of the 2 new modules so that builds would include these modules.

The Feature Flags in place should provide the safety of not incidentally enabling the feature yet.

### CODE REVIEW

**Review by oliverkecskemety — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
> 3 CSP related test case failed in the security run. I'm waiting for QA approval before forwarding.

Two of them are TF issue which will be fixed under https://issues.liferay.com/browse/LRQA-80963.
Retrigger ci:test:security to rule out the possibility of flaky issue of [ContentSecurityPolicy#VerifyCSPConfigurationCanBeLoadedFromOSGiFile](https://testray.liferay.com/home/-/testray/case_results/2352385233)

**Comment by JoyceWang08211** [comment]
> > 3 CSP related test case failed in the security run. I'm waiting for QA approval before forwarding.
> 
> Two of them are TF issue which will be fixed under https://issues.liferay.com/browse/LRQA-80963. Retrigger ci:test:security to rule out the possibility of flaky issue of [ContentSecurityPolicy#VerifyCSPConfigurationCanBeLoadedFromOSGiFile](https://testray.liferay.com/home/-/testray/case_results/2352385233)

The previous test has been passed on the latest run: 
https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2353075969&testrayComponentId=2301382452&testrayRunId=2353076106

It's safe to forward.
cc @oliverkecskemety

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
