### PR TITLE
LPD-40486

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-40486

Resent from https://github.com/liferay-appsec/liferay-portal/pull/2074 with rebasing and several revisions.

Info: by setting the SAML filters to come after the `VirtualHostFilter` (or more importantly, the `AbsoluteRedirectsFilter`), we allow the `session` and `CompanyThreadLocal` to be initialized with the current instance before hitting the SAML filters.  So, when we pull the SAML configuration values in the `isEnabled()` methods, `CompanyThreadLocal` will return the current instance's `companyId`, instead of the `System` level `companyId` value (0).  In cases where SAML is enabled at the `Instance` level but not `System` level, the filters will incorrectly be skipped.

@cdbm, I pushed these changes to the appsec repo, so you can pull/push commits as needed.  Please look over my commits and let me know if you have any questions.

@stian-sigvartsen, I am not terribly confident on the `SameSiteLaxCookiesSamlPortalFilter` and accompanying test changes, mostly because I don't fully understand the purpose of the filter.  It's possible we are completely undermining the filter's purpose, so I understand if those changes need to be reverted.  I included those changes, because now all SAML filters come after the `VirtualHostFilter`, which seems correct.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
@cdbm, once you have looked over the changes and approve, and CI is passing, you can assign this to Stian for review.  I will be on Holiday until 12/02.

**Comment by cdbm** [comment]
LGTM

**Comment by jgarcialr** [comment]
closing, continuing in #2099

**Pull request closed without merging**
