### PR TITLE
LPS-132754 Test DB2 Java

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:upgrade

**Comment by martamedio** [comment]
@stian-sigvartsen looks like this is finally working on DB2: https://testray.liferay.com/reports/production/logs/2021-06/test-1-25/test-portal-acceptance-pullrequest(master)/1354/functional-upgrade-tomcat90-db2111-jdk8/2/23/liferay-log.txt.gz 

> 2021-06-15 19:00:14.981 INFO  [main][LoggingTimer:44] Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 36 ms
2021-06-15 19:00:14.982 INFO  [main][LoggingTimer:44] Completed com.liferay.saml.persistence.internal.upgrade.v2_3_0.SamlSpIdpConnectionUpgradeProcess#doUpgrade in 37 ms
2021-06-15 19:00:14.982 INFO  [main][UpgradeProcess:126] Completed upgrade process com.liferay.saml.persistence.internal.upgrade.v2_3_0.SamlSpIdpConnectionUpgradeProcess in 39 ms
2021-06-15 19:00:14.987 INFO  [main][UpgradeProcess:111] Upgrading com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlPeerBindingUpgradeProcess
2021-06-15 19:00:14.987 INFO  [main][LoggingTimer:83] Starting com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlPeerBindingUpgradeProcess#doUpgrade
2021-06-15 19:00:15.262 INFO  [main][LoggingTimer:44] Completed com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlPeerBindingUpgradeProcess#doUpgrade in 275 ms
2021-06-15 19:00:15.263 INFO  [main][UpgradeProcess:126] Completed upgrade process com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlPeerBindingUpgradeProcess in 275 ms
2021-06-15 19:00:15.267 INFO  [main][UpgradeProcess:111] Upgrading com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlIdpSpSessionUpgradeProcess
2021-06-15 19:00:15.268 INFO  [main][LoggingTimer:83] Starting com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlIdpSpSessionUpgradeProcess#doUpgrade
2021-06-15 19:00:15.288 INFO  [main][LoggingTimer:83] Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
2021-06-15 19:00:15.317 INFO  [main][LoggingTimer:44] Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 29 ms
2021-06-15 19:00:15.339 INFO  [main][LoggingTimer:44] Completed com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlIdpSpSessionUpgradeProcess#doUpgrade in 71 ms
2021-06-15 19:00:15.339 INFO  [main][UpgradeProcess:126] Completed upgrade process com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlIdpSpSessionUpgradeProcess in 72 ms
2021-06-15 19:00:15.343 INFO  [main][UpgradeProcess:111] Upgrading com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlSpSessionUpgradeProcess
2021-06-15 19:00:15.344 INFO  [main][LoggingTimer:83] Starting com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlSpSessionUpgradeProcess#doUpgrade
2021-06-15 19:00:15.363 INFO  [main][LoggingTimer:83] Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
2021-06-15 19:00:15.396 INFO  [main][LoggingTimer:44] Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 33 ms
2021-06-15 19:00:15.412 INFO  [main][LoggingTimer:44] Completed com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlSpSessionUpgradeProcess#doUpgrade in 67 ms
2021-06-15 19:00:15.412 INFO  [main][UpgradeProcess:126] Completed upgrade process com.liferay.saml.persistence.internal.upgrade.v3_0_0.SamlSpSessionUpgradeProcess in 69 ms

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Looks good. Thanks for your perseverance with this issue @martamedio !

**Pull request closed without merging**
