### PR TITLE
LPD-17998 ldapadd command fails due deprecated -h switch

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-17998](https://liferay.atlassian.net/browse/LPD-17998)
Hi Team,

This is a fix for several LDAP related functional test failures. Please let me know if you have any questions.

Regards,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:help

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:ldap

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:ldap

**Comment by istvansajtos** [comment]
I've rebased to current master.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:ldap

**Comment by alvarosaugarlr** [comment]
ci:test:ldap

**Comment by alvarosaugarlr** [comment]
For me it is ok, but the ci:test:ldap is giving error when I try to watch it. I have run it again.

**Comment by alvarosaugarlr** [comment]
ci errors are not related.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
