### PR TITLE
LPD-26931

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-26931

Adding test for recently added ResourcePermission as requested by BChan here: https://github.com/brianchandotcom/liferay-portal/pull/153102#issuecomment-2276910195

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
Looks like the new upgrade test is passing: https://testray.liferay.com/#/project/34754/routines/174485/build/63653882/case-result/63876269

This PR should be good to forward @rafaprax

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
