### PR TITLE
LPD-18681

### PR DESCRIPTION
**Pull request by holatuwol**
https://liferay.atlassian.net/browse/LPD-18681

Not sure if this passes source formatter.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
Will re-run after https://github.com/brianchandotcom/liferay-portal/pull/147646 is merged

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
I tested compile but not startup, so this is a real issue. Will re-send.

**Comment by holatuwol** [comment]
ci:stop

**Pull request closed without merging**
