### PR TITLE
LPS-155728, LPS-140258 | master

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-155728](https://issues.liferay.com/browse/LPS-155728)
[LPS-140258](https://issues.liferay.com/browse/LPS-140258)

[LPS-158992](https://issues.liferay.com/browse/LPS-158992)
[LPS-160177](https://issues.liferay.com/browse/LPS-160177)
[LPS-160240](https://issues.liferay.com/browse/LPS-160240)
[LPS-161370](https://issues.liferay.com/browse/LPS-161370)

Developer comments:

- Plain text emailAddress and userLogin in AuditLogContext & AuditMessage
- Removed sessionId from AuditLogContext

cc @stian-sigvartsen, @JessieZhao0714, @gaborlovasdotcom

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Looks good @oliverkecskemety !

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/124113

**Pull request closed without merging**
