### PR TITLE
LPS-133386 Prevent invalid attribute mapping selection for user matching

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
@martamedio

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Thanks for reviewing @martamedio . I've rebased and fixes SemVer issue here: See liferay-appsec/liferay-portal/pull/414

**Pull request closed without merging**
