### PR TITLE
LPD-34901 OIDCProviderMetadata seems to be not cached.

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi,

My changes intend to bring back the OIDC provider metadata cache that was removed accidentally by [LPS-150092](https://liferay.atlassian.net/browse/LPS-150092). We cannot bring back the original caching solution, because OpenIdConnectMetadataFactoryImpl where it took place was completely removed.

I took the following considerations into account:
- OAuthClientEntry serves as a proxy for OpenId Connect provider configuration. The "Discovery Endpoint Cache in Milliseconds" value specified for the latter therefore should be captured in the corresponding OAuthClientEntry as well.
- The admin should be able to define the caching time on OAuth Client Configurations UI as well.
- PortalCache is used to store the values. We keep the original approach: if 0 is provided as caching time, the entry is never evicted from cache.
- We need an upgrade process that adds the required column to OAuthClientEntry table and updates existing entries.

**Caution**: This is just for an initial review. Do not try to forward because it does not contain automated test coverage!

Thank you,
István

cc @alvarosaugarlr @stian-sigvartsen

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:upgrade

**Comment by istvansajtos** [comment]
@alvarosaugarlr , may I ask you to review my changes? Thank you!

**Comment by istvansajtos** [comment]
I'm looking into the test failures.

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:upgrade

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:upgrade

**Comment by istvansajtos** [comment]
Hey @jgarcialr , Thanks for your suggestions, those totally make sense. I've added the requested changes.

**Comment by jgarcialr** [comment]
Latest changes looks good to me, great work @istvansajtos  :smile: 

cc @stian-sigvartsen @alvarosaugarlr

**Comment by alvarosaugarlr** [comment]
Hi @istvansajtos ,

I agree with the solution. 

I only have made one change and have one doubt:
* Change. - sort the name of the parameter  in the [resolveOIDCProviderMetadata](https://github.com/liferay-appsec/liferay-portal/pull/1990/commits/68b9bfc8284c8ed1e9aab7295be501f99a84ea19) method - (to add this change I have created a [new pr](https://github.com/liferay-appsec/liferay-portal/pull/1990), but feel free to continuos working here and close the other)
* Doubt - how to solve when the user set 0 as value of the cache time. In this case I think the Core-infra team could take a look.

**Pull request closed without merging**
