### PR TITLE
LPD 41377 v1

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
Not finished yet

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:tes:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:tes:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Superseded by liferay-appsec/liferay-portal/pull/2076

**Pull request closed without merging**
