### PR TITLE
LPS-200561 The scope is missing after restarting portal

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-200561](https://liferay.atlassian.net/browse/LPS-200561)
@JoyceWang08211

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
