### PR TITLE
LPS-191052 Add option to configure SCIM client via a config file

### PR DESCRIPTION
**Pull request by oliverkecskemety**

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Review by stian-sigvartsen — COMMENTED** [review]
Hi @oliverkecskemety . Looks like a good approach! I like what you ended up doing with the OAuth 2 application name & Client ID.

* Renamed `ScimClient` > `SCIMClient` after looking at CORS examples
* Tweaked DEBUG messages so they represent the action that takes place and not the component lifecycle. Also made less verbose
* Minor SF
* Split your commit [2e2a16a](https://github.com/liferay-appsec/liferay-portal/pull/1414/commits/2e2a16a7438f12b5110457bf7ed7f5a92f8aeb39) so that we can separate out defining the FF (epic related) and applying it (story related). For this I used the sub tasks IDs for both with epic & story keys respectfully on the 2nd line with whitespace between.

Because of that last change I had to send a new PR, please see liferay-appsec/liferay-portal/pull/1422

**Pull request closed without merging**
