### PR TITLE
LPD-36964 Update test path

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-36964](https://liferay.atlassian.net/browse/LPD-36964)

Password Policies integration tests are not on security suite because they have changed files (from test.js to Test.java), so we need to update that.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by ChrisKian** [comment]
Looks like the password policy related integration tests are now running: 
https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1207057/testReport/com.liferay.password.policies.admin.uad.anonymizer.test/
https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1207057/testReport/com.liferay.password.policies.admin.uad.exporter.test/

Although two of the tests were skipped, they've been that way for the past 1 million + builds, so I think the scope of this PR has been reached.

https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1207057/testReport/com.liferay.password.policies.admin.uad.anonymizer.test/PasswordPolicyUADAnonymizerTest/testAutoAnonymizeStatusByUserOnly/
https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1207057/testReport/com.liferay.password.policies.admin.uad.anonymizer.test/PasswordPolicyUADAnonymizerTest/testAutoAnonymizeUserOnly/

**Review by ChrisKian — APPROVED** [review]

**Comment by manuelecastro** [comment]
I did some investigation on the skipped tests and I believe this is expected. This test class extends `BaseUADAnonymizerTestCase.java` 

the skipped tests only run if  `WhenHasStatusByUserIdField` is being implemented. since `PasswordPolicyUADAnonymizerTest.java` doesn't do that, the tests are skipped.

see: https://github.com/liferay-appsec/liferay-portal/blob/6df78b7469eeb2b04f177ecaf67aae5130dc3c3e/modules/apps/user-associated-data/user-associated-data-test-util/src/main/java/com/liferay/user/associated/data/test/util/BaseUADAnonymizerTestCase.java#L69
[Junit documentation on Assume.assumeTrue](https://junit.org/junit4/javadoc/latest/org/junit/Assume.html#assumeTrue(boolean))

**Review by stian-sigvartsen — APPROVED** [review]
LGTM @manuelecastro @ChrisKian , thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
