### PR TITLE
LPS-196728 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-196728

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:um

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Review by gaborlovasdotcom — APPROVED** [review]

**Review by alvarosaugarlr — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
