### PR TITLE
LDP 6757 Second pr

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
Second pr of [LPD-6757](https://liferay.atlassian.net/browse/LPD-6757)

First pr - https://github.com/liferay-appsec/liferay-portal/pull/1977

Adding changes ([commit](https://github.com/brianchandotcom/liferay-portal/pull/154814#issuecomment-2394028010)):
* Renaming for vars
* Don't use loop

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
The unit test is passed - https://testray.liferay.com/#/project/35392/routines/45357/build/38827403/case-result/38829107

**Comment by rafaprax** [comment]
Hey guys, I resent these changes with some little changes here. https://github.com/liferay-appsec/liferay-portal/pull/2017

@stian-sigvartsen feel free change or skip the changes I made.

Thx guys

**Pull request closed without merging**
