### PR TITLE
[TS] LPS-171082 Only update emailAddressVerified to true...

### PR DESCRIPTION
**Pull request by markgulacsy**
…if the user is newly created during LDAP import

Hi appsec team,
I was working on [LPS-171082](https://issues.liferay.com/browse/LPS-171082).
Could you review my changes, please?

Thanks in advance!

### CODE REVIEW

**Comment by markgulacsy** [comment]
ci:test:ldap

**Comment by alvarosaugarlr** [comment]
The pr has been verified to resolve the bug. 
More info in the [comment](https://issues.liferay.com/browse/LPS-171082?focusedCommentId=2823992&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2823992) of the ticket.

**Comment by alvarosaugarlr** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:test:ldap

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
pr sent directly to Brian - https://github.com/brianchandotcom/liferay-portal/pull/128086

**Comment by markgulacsy** [comment]
Thank you @alvarosaugarlr!

**Pull request closed without merging**
