### PR TITLE
LPS-164521 small refinements & upgrade process 

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Following on from stian-sigvartsen/liferay-portal/pull/278

Now that we have switched to finders with smalled indexes, do we still need [5e4810a](https://github.com/liferay-appsec/liferay-portal/pull/945/commits/5e4810af7206942cfe78165970a8efce025773fa) ?

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
@alvarosaugarlr up to [899e0ea](https://github.com/liferay-appsec/liferay-portal/pull/945/commits/899e0ea196cc56b0107145a1b584ffb241347b8f) the combined contents of the commits are the same as your previous PR (with the exception of some `buildService` generated code)

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Pr with the changes (of this pr and the ones needed to reduce the indexes) - https://github.com/liferay-uniform/liferay-portal/pull/861

**Pull request closed without merging**
