### PR TITLE
LPS-153615 - Mark Cookies fields as required

### PR DESCRIPTION
**Pull request by oliverkecskemety**
**[LPS-153615](https://issues.liferay.com/browse/LPS-153615) Consent Panel can be saved with blank title and description** - Mark all fields as required (even checkboxes to avoid changing the order of items)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
