### PR TITLE
LPS-134954 Implicit mapping fix - rebased to verify functional tests

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by gaborlovasdotcom** [comment]
ci:reevaluate:1277401_2992

**Comment by gaborlovasdotcom** [comment]
Functional tests are updated, and works, the 2 upgrade test case fails due layout upgrade issue, not related tho this Pr.
cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
We discovered that there was an edge case which saw a regression. Which is when a field is mapped to a SAML attribute, but it is not received at runtime, then it should try to implicit map an attribute named identically to the user field expression.

Please see liferay-appsec/liferay-portal/pull/636

**Pull request closed without merging**
