### PR TITLE
LPD-6865 Add default utility page with portlet

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPD-6865](https://liferay.atlassian.net/browse/LPD-6865)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
This looks great @nikolettabuza , well done! 
As we discussed, we need to include a `LayoutUtilityPageEntryViewRenderer` which is being introduced by LPD-6870 . I have prepared commits for that, but I am waiting for the FF application which @oliverkecskemety is working on currently.

**Comment by stian-sigvartsen** [comment]
Thanks @oliverkecskemety for the FF application commit for LPD-6870. I have integrated the bare minimum code from that ticket.

Please see liferay-appsec/liferay-portal/pull/1651

**Pull request closed without merging**
