### PR TITLE
LPS-135892

### PR DESCRIPTION
**Pull request by istvansajtos**
Dear Team,

These commits are patching cxf-rt-rs-json-basic. The patched library is required only for maintenance branches 7.3.x and below where bumping cxf version is not possible. Please see related PTR ticket for more info on this.

As soon as the patched library is available in Nexus repository, I will send "backport" PR for 7.3.x that uses this lib.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Force pushed modified commit message to make it clear the patched lib is required on 7.3.x and below. Nothing else changed.

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . Just saw this PR. The ticket key of the commits is for a closed ticket. I think you meant to use LPS-129441 which would then need to be re-opened? 

I don't know if re-opening that ticket is possible also because the other commits there will have been released already. So we may need another ticket.

**Comment by istvansajtos** [comment]
Hi @stian-sigvartsen ,

You must be right regarding the administration difficulties of closed LPS tickets, so I opened a new LSP that we can use to commit the patched library and send PRs for branches 7.3.x and below. New master PR: https://github.com/liferay-appsec/liferay-portal/pull/878

Regarding the ticket ID used in commit message, we are working with LPS-135892 and LPS-129441 was the blocker dependency. But PM me if you have any questions.

Thanks!

**Pull request closed without merging**
