### PR TITLE
[TS] LPS-178212 Resource permissions popup should search for roles by visible information only

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
I update the code based on https://github.com/brianchandotcom/liferay-portal/pull/133823#issuecomment-1521188842.
Please help review this PR and leave your comments.
Ticket: https://issues.liferay.com/browse/LPS-178212
Thanks.

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
ci:test:security

**Review by oliverkecskemety — APPROVED** [review]
Thank you @tototrinh! LGTM

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
