### PR TITLE
LPD-27221 Fix SAML#AssertSSOWithSignAuthnRequests test

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:report:43059545

**Comment by jgarcialr** [comment]
Test now is passing:
imagen

**Comment by jgarcialr** [comment]
The test was failing because when we visit www.able.com:9080 after performing logout on the idp and finishing slo for all sp's the window in www.able.com:9080 was still shown a logged in user.

After the refresh it shows the real status, reflecting that logout operation was performed correctly.

**Review by stian-sigvartsen — APPROVED** [review]
Thanks @jgarcialr . Thanks for sharing that analysis which gives good context to the change. I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
