### PR TITLE
LPD-30298

### PR DESCRIPTION
**Pull request by ChrisKian**
I used @jgarcialr's [branch](https://github.com/liferay-appsec/liferay-portal/pull/1863) and added [an additional commit](https://github.com/liferay-appsec/liferay-portal/commit/79ae5215fb46f59cd36c49ea4cb347b5dd72d3de) which should add the new playwright tests to the `SAML` and `Playwright` test suites.  I also included [a dummy commit](https://github.com/liferay-appsec/liferay-portal/commit/f0ae5e00482308ffadc1d010bd47b3255ccb95a3) which should be picked up by the `Relevant`, test suite, so we can verify if it works.  I'll run those tests now.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by stian-sigvartsen** [comment]
Thanks @ChrisKian . The new test is running on both relevant and playwright suites now. 
Because the new test is failing I will manually forward this PR to BChan without you latest 2 commits to enable us to merge this.

**Pull request closed without merging**
