### PR TITLE
LPS-196993 | Master

### PR DESCRIPTION
**Pull request by GergoMathe**
[LPS-196993](https://liferay.atlassian.net/browse/LPS-196993)

### CODE REVIEW

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
@GergoMathe could you please refer the Subtask ID in your commit title?

**Comment by GergoMathe** [comment]
@gaborlovasdotcom I fixed the titles.

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Comment by GergoMathe** [comment]
I'm currently fixing rebase errors.

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:account:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
