### PR TITLE
LPS-124876 Add localized errorMenssage for Captcha validator

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-124876

### CODE REVIEW

**Comment by danvb112** [comment]
The CI test results were approved in this PR: https://github.com/liferay-forms/liferay-portal/pull/851

**Comment by danvb112** [comment]
Hi @liferay-appsec team, do you mind to take a look on this pull request related to Simple Captcha?

I visited the section The workflow in a nutshell of the article How to send Pull Request to the Application Security Team liferay-appsec, but I'm not sure if the proposed change demands to run some specific CI command, like ci:test:security, or ci:test:relevant is enough.

Thanks in advance for your assistance.

cc: @natocesarrego

**Comment by stian-sigvartsen** [comment]
Hey @danvb112 ! I'm wondering what is the expected behavior when the user chooses to render the form in a different locale than his/her display settings. 

Guilherme raised this question in a comment but it was never answered?
https://issues.liferay.com/browse/LPS-124876?focusedCommentId=2416153&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2416153

/cc @natocesarrego

**Comment by danvb112** [comment]
Hey @stian-sigvartsen! The expected behavior must be the same as the submit button, that is, it must be translated according to the language the user chooses in the form.

We have a history which will be developed, showing this future behavior : https://issues.liferay.com/browse/LPS-130686

cc: @natocesarrego

**Comment by stian-sigvartsen** [comment]
Hey @danvb112! Sorry for the delay with this, and I have another question...

It looks like the HTTP "languageId" parameter is like API throughout the portal. So why are we not handling this within `<aui:validator>` instead of this specific JSP usage?

**Comment by danvb112** [comment]
Hey @stian-sigvartsen, No problem!

Actually I did it that way just to make it more readable. But it's totally possible to do this the way you said, I'm sending you the changes now!

**Comment by stian-sigvartsen** [comment]
As we discussed offline @danvb112 , I am wondering if the implementation of <aui:validator/> (not usage) could take care of localizing messages? Like it does for default messages. Or is it necessary in this case to override the default message?

**Comment by arthurchan35** [comment]
Hey @danvb112 
What's the status of this PR, is it going to be fixed by the story? Or should we push forward it?
Stian is on PTO until next Wednesday.

**Comment by natocesarrego** [comment]
Hi @arthurchan35,

Can you please give more details why this pull request was closed?

Apparently, it's still waiting for another round of review. :slightly_smiling_face: 

Thanks.

cc @danvb112

**Comment by arthurchan35** [comment]
Hi @natocesarrego 
Because the LPS was closed by Rodrigo

**Comment by natocesarrego** [comment]
Thanks, @arthurchan35! :slightly_smiling_face:

**Pull request closed without merging**
