### PR TITLE
LPS-190692

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPS-190692

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@brianikim It is important to note that this change will create a breaking change, now the queries to the admin user API through GraphQL is going to need the namespace

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Pull request closed without merging**
