### PR TITLE
LPS-175308 Bouncy Castle implementation of PBKDF2

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPS-175308](https://liferay.atlassian.net/browse/LPS-175308#icft=LPS-175308)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @nikolettabuza . I previously reviewed the runtime code and I don't want to hold this up any longer so I've done a quick review of the test. Found just a few issues, but I haven't got access to a build to run the test yet. I think it's fine though, just have a look at liferay-appsec/liferay-portal/pull/1286 . 

If you can integrate these commits and check it l that The test still works as before then I think you can forward.

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
See previous comment

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
Note: PR updated with the requested changes + some additional test changes to check that the correct implementation is used when enabling/disabling BC.

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks @nikolettabuza ! I expanded most test coverage a bit and sent liferay-appsec/liferay-portal/pull/1562

**Pull request closed without merging**
