### PR TITLE
LPS-202716 Wrap all endpoints that does not handle ConflictException

### PR DESCRIPTION
**Pull request by oliverkecskemety**
We use ConflictException to show that an object was provisioned by another SCIM client, however this exception is only handled in Charon during create. We need to wrap the other endpoints to return the proper response instead of a runtime exception.

[LPS-202716](https://liferay.atlassian.net/browse/LPS-202716)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @oliverkecskemety , I think this change is fine. I will add my reasoning to the ticket in a comment, partly because we also need to update the ticket description with the new expectation.

Running CI tests before we forward.

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by oliverkecskemety** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks @gaborlovasdotcom for checking the ci:test:stable failure is unrelated.
I will manually forward this PR.

**Comment by stian-sigvartsen** [comment]
Manually forwarded to brianchandotcom/liferay-portal/pull/144869

**Pull request closed without merging**
