### PR TITLE
LPS-127338 Use of library with known vulnerabilities: guava

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you have a look at this pull request, please?

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
SF error not related to changes in this pull request.

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
@antonio-ortega could you please have a look and fix SF errors above?
Thx!

**Comment by antonio-ortega** [comment]
Fixed, rebased and resent in #299

**Pull request closed without merging**
