### PR TITLE
LPD-1407 it is defined the css file in the portlet property but it does not exist and are in hidden category

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPD-1407](https://liferay.atlassian.net/browse/LPD-1407)

The problem  is because in the [MFAVerifyPortlet portlet is defined the property to set the css file](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-web/src/main/java/com/liferay/multi/factor/authentication/web/internal/portlet/MFAVerifyPortlet.java#L30), but that file does not exit.

How the portlets are hidden, we have removed the property instead of create the css file. 

Based on the LPP we have seen the same problen in other of our portlets:
 * MFAEmailOTPVerifyPortlet
 * OAuthClientAdminPortlet
 * MFAEmailOTPVerifyPortlet

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:report 93954655

**Comment by alvarosaugarlr** [comment]
ci:report:93954655

**Comment by alvarosaugarlr** [comment]
ci:test errors do not look related with the change.

**Comment by alvarosaugarlr** [comment]
@rafaprax , it is ready to review it.
Thanks!

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
