### PR TITLE
[TS] LPS-193127 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Previous pull requests:

- https://github.com/liferay-appsec/liferay-portal/pull/1317
- https://github.com/brianchandotcom/liferay-portal/pull/139758
- https://github.com/liferay-appsec/liferay-portal/pull/1344
- https://github.com/liferay-appsec/liferay-portal/pull/1367
- https://github.com/brianchandotcom/liferay-portal/pull/140484

References:
https://liferay.atlassian.net/browse/LPS-193127
https://liferay.atlassian.net/browse/PTR-4304

Kind regards.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:stop

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
ci:test:security

**Comment by nikolettabuza** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/140704

**Pull request closed without merging**
