### PR TITLE
LPD-44399 Extracting all inline styles in AppSec

### PR DESCRIPTION
**Pull request by jgarcialr**
https://liferay.atlassian.net/browse/LPD-44399

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:stop

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Review by ChrisKian — APPROVED** [review]
Test failures look unrelated.  This passes my review

**Comment by rafaprax** [comment]
Hi @jgarcialr and @ChrisKian , the CSS class names/selectors here are off (they are not meaningful). Also, I did a git grep on the liferay source code and couldn't find this pattern in the *scss files.

Using the recaptcha as an example we have:

1. rec-h-525
2. rec-w-302
3. recaptcha-taglib

but it could be something like this:

1. recaptcha-container
2. recaptcha-inner
3. recaptcha-no-script

JSP:

```
 <noscript>
       <div class="recaptcha-container">
          <div class="recaptcha-inner">
             <div class="recaptcha-no-script">
                <iframe frameborder="0" scrolling="no" src="<%= HtmlUtil.escapeAttribute(captchaConfiguration.reCaptchaNoScriptURL()) %><%= HtmlUtil.escapeAttribute(captchaConfiguration.reCaptchaPublicKey()) %>" class="recaptcha-no-script-iframe"></iframe>
             </div>

             <div class="recaptcha-response">
                <textarea aria-labelledby="<portlet:namespace />g-recaptcha-response-error" class="g-recaptcha-response" id="g-recaptcha-response" name="g-recaptcha-response"></textarea>
             </div>
          </div>
       </div>
    </noscript>
```

CSS

```
.recaptcha-container {
  height: 525px; 
  width: 302px;
}

.recaptcha-inner {
  height: 525px; 
  width: 302px;
  position: relative; 
}

.recaptcha-no-script {
  height: 525px; 
  position: absolute; 
  width: 302px;
}

.recaptcha-no-script-iframe {
  border-style: none; 
  height: 525px; 
  width: 302px;
}

...

```


Please follow this as an example and resend.

Thanks guys

**Comment by ChrisKian** [comment]
Hey @rafaprax,
I am trying to apply your changes, and although everything looks correct in the code, my `scss` file is not found on the browser, so the style changes do not take effect.  I've tried rebuilding the css with `gw buildCss`, as well as renaming the file to `main.scss`, but nothing seems to work.  Do you have any insight on how to resolve this issue?  Thanks!

**Comment by rafaprax** [comment]
> Hey @rafaprax,
> I am trying to apply your changes, and although everything looks correct in the code, my `scss` file is not found on the browser, so the style changes do not take effect.  I've tried rebuilding the css with `gw buildCss`, as well as renaming the file to `main.scss`, but nothing seems to work.  Do you have any insight on how to resolve this issue?  Thanks!

I don't have any insight now but I can try to find something tomorrow.

As far I remember, the workflow-taglib has a specific scss file that is loaded somehow. Maybe you can take a look there so you understand how to fix the captcha one.

PS: Were the styles being loaded in Jorge's version?

**Comment by ChrisKian** [comment]
> As far I remember, the workflow-taglib has a specific scss file that is loaded somehow. Maybe you can take a look there so you understand how to fix the captcha one.

I will check this out, thank you

> PS: Were the styles being loaded in Jorge's version?

After testing, no they were not.  It's likely he initially tested with javascript enabled, which means his changes wouldn't even be rendered, so everything looked correct.

For reference, I tried `gw buildCss` and `gw clean deploy`

**Comment by jgarcialr** [comment]
Hi @ChrisKian ,
buildCss won't work as it was disabled for specific modules.
I'll re-test again but on my tests the styles appeared in the browser when using recaptcha.
I can adjust the class names to the ones referred by @rafaprax .

Regarding the naming, I just followed some class names from clay. 
There are some styles to adjust padding and margin and height, that's why h-XXX but I understand in this specific case, following that pattern is not meaningful.

**Pull request closed without merging**
