### PR TITLE
LPS-156944 As an Instance Administrator, I want to enable or disable Auth Verifiers for my instance

### PR DESCRIPTION
**Pull request by oliverkecskemety**
Previous PR https://github.com/liferay-appsec/liferay-portal/pull/978

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Just adding a comment to say that the ticket relating to this was discarded. The PR is open because it will become relevant again at some point

**Comment by zsigmondrab** [comment]
Discarded

**Pull request closed without merging**
