### PR TITLE
LPD-15723

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @ChrisKian . Please can you peer review this one?

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Reviewing now

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/1646

**Pull request closed without merging**
