### PR TITLE
LPS-189134 make sure the token has the TOKEN_EXPIRED value once it's expired

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Related to: [LPS-189134](https://liferay.atlassian.net/browse/LPS-189134)

### CODE REVIEW

**Comment by ivicac** [comment]
ci:stop

**Comment by ivicac** [comment]
ci:test:sf

**Review by arthurchan35 — COMMENTED** [review]
https://github.com/liferay-appsec/liferay-portal/pull/1203/files#diff-7bde488e6e217317f34582165dab27987b61dd6ebef6e569a6c349274910d0f1L109

Don't have code locally, but looking at it.
Seems already checking the token by bearerTokenProvider.

**Comment by stian-sigvartsen** [comment]
Thanks @thiago-buarqque ! I de-duplicated some code and avoided persisting `EXPIRED_TOKEN` because that is reserved for an explicit revocation.

Having the test to verify the tweaks was very helpful, thanks!

Please see liferay-appsec/liferay-portal/pull/1221

**Comment by thiago-buarqque** [comment]
Thank you @stian-sigvartsen

**Pull request closed without merging**
