### PR TITLE
LPD-34178

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPD-34178](https://liferay.atlassian.net/browse/LPD-34178)

Resolves release blocker described in [LPD-34178](https://liferay.atlassian.net/browse/LPD-34178), which was unintentionally caused by the changes in [LPD-33535](https://liferay.atlassian.net/browse/LPD-33535).  After speaking with Shuyang in [this slack thread](https://liferay.slack.com/archives/C01FP01V5L0/p1723845314863859), it was discovered the `isFilterEnabled()` method (notice no arguments) is for statically determining if a given filter should be completely disabled.  This doesn't work for SAML related filters, since they need to dynamically be enabled/disabled.

So, the solution is to remove the `isFilterEnabled()` method from all SAML related filters, so the `BaseFilter` class's `isFilterEnabled()` method will be used instead, and return `true` by default.  This doesn't mean the filters will always be enabled, it just means we aren't outright skipping the filters when we **_dynamically_** determine if the filter is enabled when using the `isFilterEnabled(HttpServletRequest, HttpServletResponse)` method (notice the request and response arguments).

As for including a test, I'm not sure if it is needed, since our SAML tests caught this issue.  I'm also not entirely sure how to implement a test for this situation, so I'm open to suggestions if tests are required.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
All failing SAML tests were already failing, but now basic SAML SSO is working again.

@RafaPrax, can we please prioritize this review since it's a release blocker?  Thank you!

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Comment by ChrisKian** [comment]
The unique relevant test failure should be unrelated to this PR, as it deals with `DLFileVersionImpl` class, and has nothing to do with SAML.

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward:force

**Pull request closed without merging**
