### PR TITLE
[TS] LPS-176173 & LPS-169817 Tighten AuthVerifier user context & audit - 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
`RefreshTokenAuthorizationGrantTest` failure appears to be unrelated. Just re-running testing to be on the safe side whilst peer review is going on anyway.

**Comment by stian-sigvartsen** [comment]
Hi @MirnaGama . We are peer testing this generic solution right now. If you have time it would be great if you can verify that it covers all the cases that you found also.

**Comment by magjed4289** [comment]
Test failures are not related to the PR. OK to manually forward. ✅

**Review by oliverkecskemety — APPROVED** [review]
LGTM!

**Comment by stian-sigvartsen** [comment]
Thanks for reviewing @magjed4289 & @oliverkecskemety !

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
