### PR TITLE
[TS] LPS-139875

### PR DESCRIPTION
**Pull request by jonathanmccann**
Please let me know if there are any issues with bumping the version.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
The unique failures which related to XSS functional tests are listed and waiting for fix under ticket [POSHI-183](https://issues.liferay.com/browse/POSHI-183).

Looks good to me @arthurchan35 .

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
