### PR TITLE
LPD-32196 File Store Migration tool doesn't migrate saml keystore if it's located within Document library

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-32196](https://liferay.atlassian.net/browse/LPD-32196)
[LPD-32190](https://liferay.atlassian.net/browse/LPD-32190)

This PR aims to solve migration from SAML keystore between different FileStores when DLKeyStoreManager's value is Document Library.

It also solves the problem retrieving the keystore from GCSStore. This is achieved by removing the double slash in the calculated path when trying to retrieve the file. This is caused by having an slash as first character of SAML_Keystore_Path constant.
 
We already added default store version to match save method logic. This avoids delegating the calculation to Store's logic, as we are saving this file with Store.VERSION_DEFAULT.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:report:49789060

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @jgarcialr . Looks good, but you need to key some of the commits to LPD-32190 it looks like.

Curious why did you decide on a new Poshi test for this ticket?

**Comment by jgarcialr** [comment]
> Hi @jgarcialr . Looks good, but you need to key some of the commits to LPD-32190 it looks like.
> 
> Curious why did you decide on a new Poshi test for this ticket?

I end up marking LPD-32190 as duplicate by LPD-32196, but I can change the double slash commit to LPD-32190 if needed.

About the poshi test, as we have to perform data migration + restart with new properties. I think it's the best approach because playwright cannot do this kind of actions.

**Comment by jgarcialr** [comment]
Hi @stian-sigvartsen ,

I've re-keyed the double slash commit. Hope it's ok with this change :)

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:reevaluate:1407401_10536

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Review by stian-sigvartsen — APPROVED** [review]
We discussed it offline and it the tickets are very close to being duplicates of each other so we will keep the commits keyed to only one.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
