### PR TITLE
[TS] LPS-190666

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-190666

Previous PRs:
https://github.com/liferay-appsec/liferay-portal/pull/1240
https://github.com/liferay-appsec/liferay-portal/pull/1274

Following directions from [this comment](https://liferay.atlassian.net/browse/LPS-190666?focusedCommentId=2440417), I've implemented a solution with the following behavior:
1. Role **assignment** will remain exactly the same as it is.
2. Role **filtering** will be dependent on VIEW permission of the given role. In other words, we are able to filter on the roles we can VIEW.
3. Team filtering will also be added, exactly like Role filtering.
4. Teams and Roles will be two separate columns in the Table view.
5. Table view will still display all roles and teams, regardless of the current user's permission towards them.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:security

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Hi @ChrisKian 

According to the code and point 5 that you indicate in the changes,

> Table view will still display all roles and teams, regardless of the current user's permission towards them.

 I think I did not explain myself well in the changes I indicated. 

When I was talking about the table view of the roles and teams (points 3 and 4) I meant that this behavior was incorrect.

> In the roles column all roles are shown, 

(as it is now)

> it does not check if the user has VIEW permissions

(why it is wrong)


In short, the roles and teams that have to be shown in the column are the ones that the user has VIEW permissions. In this way, the behavior is the same as in the filters and in the Teams section.

Sorry for the misunderstanding.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @alvarosaugarlr,
I've made the change you requested in [this commit](https://github.com/liferay-appsec/liferay-portal/pull/1325/commits/60536cd43c91c79bfc9348b5b4c718fdb7562681).  I don't really like how the permission checking happens in the JSP, but I'm not sure where else to put it, since the list of users is generated upon each request.

Please let me know if this solution is acceptable, or otherwise, what a better approach would be.  Thanks!

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:security

**Comment by ChrisKian** [comment]
ci:test:stop

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
Hi @ChrisKian 

I have reviewed the changes and tested it and the roles and teams do not appear correctly. 
I'm adding a [comment in the ticket ](https://liferay.atlassian.net/browse/LPS-190666?focusedCommentId=2441552)to better explain what I think the problem is. 

Review on the code I agree with the solution (changing the permissions issue). 

Thanks!

**Comment by ChrisKian** [comment]
Thanks @alvarosaugarlr,
I have commented on the LPS ticket as to why you've found these issues. To summarize, the team view issue is caused by an additional permission which I have now accounted for in the steps to reproduce, and the Site Admin/Owner issue is actually correct behavior.  Please let me know if you have any questions or concerns, thanks!

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
No regression or unique backend failure was found.

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
