### PR TITLE
LPS-189573 TOTP reuse

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-189573](https://liferay.atlassian.net/browse/LPS-189573)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by zsigmondrab** [comment]
Hi @manuelecastro,

Have you analized it already whether the failures are bacause of the changes here?

Otherwise the fix looks fine.

Zsigmond

**Comment by manuelecastro** [comment]
Hi @zsigmondrab,

Fixed the rebase conflicts and resent the PR here: https://github.com/liferay-appsec/liferay-portal/pull/1393 

I'm going to trigger the tests again there to check for any failures that might been caused by the changes.

**Pull request closed without merging**
