### PR TITLE
LPS-193862 - CAPTCHA verification is always failing 

### PR DESCRIPTION
**Pull request by MirnaGama**
### Steps to Reproduce:

1. Go to Content&Data → Forms
2. Create a form with a text field
3. In the created Form screen, go to Settings → enable Require Captcha → Save
4. Copy the shared form link, and  go to the shared link
5. Input  captcha text corresponding with the image
6. Submit form

✅  Expected Result: The form is submitted successfully
 ❌  Actual Result: The form appears with the error: “Error: Text verification failed.”.
 
### Results of investigation: 
It was discovered the request parameter “captchaText” is null in the [validateChallenge method from the SimpleCaptchaImpl class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/captcha/captcha-api/src/main/java/com/liferay/captcha/simplecaptcha/SimpleCaptchaImpl.java#L405). 
 
The cause commit: https://github.com/brianchandotcom/liferay-portal/pull/139100/commits/4e84bd5808d0071d02e5c3b7d0c6d12733b69144.

We can notice that the aui:input tag has been changed to the input tag. After inspecting the generated html on the browser page and comparing it to the older generated html, it was discovered that the "name" attribute was incomplete and did not include the portlet namespace in it.

### Commits included:

- LPS-193862 Add missing portlet namespace in input captcha text name attribute

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by zsigmondrab** [comment]
@MirnaGama, this could be forwarded, however the CI tests fail. Could you please check if they are relevant. Otherwise, you can forward also.

Thanks

**Comment by MirnaGama** [comment]
@zsigmondrab done ! 
https://github.com/liferay-core-infra/liferay-portal/pull/5547

**Comment by MirnaGama** [comment]
It looks like these ci test failures are unrelated

**Comment by MirnaGama** [comment]
ci:forward:force

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
