### PR TITLE
LPD-4056

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-4056](https://liferay.atlassian.net/browse/LPD-4056)

Hi Team,

Please review my changes.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:stop

**Comment by daiazius** [comment]
Hi @istvansajtos, there were some tests failing in the relevant suite, I think related to commerce. I tested locally with your changes and got the same results as CI, can you take a look? Thank you

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
@daiazius , some of the failures are indeed related. Commerce related functional tests may rely on the unrestricted access of CommerceCountryManager.

I'm closing the PR and will send another one once I resolved the failures.

**Pull request closed without merging**
