### PR TITLE
Lpd 30298 2

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by jgarcialr** [comment]
ci:report:43468502

**Comment by ChrisKian** [comment]
Looks like the tests didn't run.  I've added another commit, and sent a new PR here: https://github.com/liferay-appsec/liferay-portal/pull/1864

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@ChrisKian 's new PR confirms the tests will run with his changes there. It confirmed that 
1) CI host knows the www.able.com and www.baker.com hostnames
2) The new test we are developing on top of LPD-30298 executes with those changes, but needs further work

To avoid delay to LPD-30298 I will forward the current PR.

**Pull request closed without merging**
