### PR TITLE
LPS-125272 Allow ID matching using SAML attributes

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
@martamedio 

/cc @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by martamedio** [comment]
I didn't think it was that easy to fix 👏

**Comment by stian-sigvartsen** [comment]
Neither did I initially. Small change for devs, giant leap for behavioral change!

**Comment by stian-sigvartsen** [comment]
Just thought we should definitely add a new test for this before sending

**Comment by csierra** [comment]
I was just going to ask how difficult would be to add a test given that we already have `DefaultUserResolverTest`

**Comment by stian-sigvartsen** [comment]
We need to review DefaultUserResolverTest anyway actually. Because it is building using attributeMapping including screenName and emailAddress attributes, which means we are no longer testing the default behavior of matching against the NameID received.

@martamedio would you like to review & create the new test? I can also do it.

**Comment by martamedio** [comment]
@stian-sigvartsen I've just added the test that resolves the user using `screenName`, take a look

Should we add a a new one that tests a default behaviour? Isn't this already done in the `_initMessageContext`method?

**Comment by stian-sigvartsen** [comment]
@martamedio Unfortunately all the existing tests, and the new one, create a new user instead of matching an existing one. So in reality we never had tests for matching existing users :(

**Comment by martamedio** [comment]
@stian-sigvartsen I've just checked the code, understood: we don't test anything related to matching, so...
- Is this something we should add in this task?
- Do you have any ideas or hints on how to approach such a test?

**Comment by stian-sigvartsen** [comment]
I think it makes sense to add it as part of this task because we are now transitioning from supporting only one matching logic, to supporting two. The switching between the two needs to be well understood.

To implement it I think we need to add a 2nd mock User which is returned when UserLocalService.getUserBy*() is called for some screenName like "existingUser". Two tests for the two matching logics should differentiate in attributes only. The existing logic test is stimulated by not receiving any screenName attribute at all. We must take care to ensure that the NameID value in the SAML Authn Response is not "existingUser" to ensure the match wasn't incorrectly made via NameID.

**Comment by martamedio** [comment]
I have just added a new logic with two tests that are checking the matching (expected to use `updateUser` method and not `addUser` method)
Please @stian-sigvartsen, have a look at it 🤓

**Comment by stian-sigvartsen** [comment]
Looking good @martamedio ! Looks like you had to mock quite a few methods, but it should be maintainable I think.
We're still missing tests for the old matching behavior I think? Meaning when no screenName is sent via SAML attribute, so the matching is done between the portal user's screenName and the SAML NameID value received.

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:saml

**Comment by martamedio** [comment]
ci:reevaluate:112null_4189

**Comment by martamedio** [comment]
ci:test:saml

**Comment by martamedio** [comment]
ci:test:saml

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@martamedio the tests approach looks good to me. I just tweaked it to avoid false positives. I think we need to wait on the fix to  LPS-127030 and then re-run CI

**Comment by martamedio** [comment]
@stian-sigvartsen Thanks for your changes!
I have applied a rebasing and, as you pointed out, we should wait for LPS-127030 because test aren't working

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1232004_7356

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
