### PR TITLE
pr 1840

### PR DESCRIPTION
**Pull request by rafaprax**
- LPD-30790 Be able to return all registered AuthVerifier ordered by service.ranking.
- LPD-30790 AuthVerifier should be applied taking into account their service.ranking
- LPD-30790 Provide service.ranking so that they can follow the same order as before with auth.verifier.pipeline property. Mainly the important one is BasicAuthHeaderAuthVerifier because:
- LPD-30790 Prepare test to be able to work with several AuthVerifiers to check which one is executed first.
- LPD-30790 Check that order (defined by service.ranking) is taken into account in the pipeline.
- LPD-30790 SF, sort if/else statements

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:report:67180475

**Comment by marianoalvarosaiz** [comment]
No unique failures.

**Comment by marianoalvarosaiz** [comment]
ci:forward:force

**Pull request closed without merging**
