### PR TITLE
LPS-133646 Initial support for log context

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Review by stian-sigvartsen — APPROVED** [review]
@arthurchan35 This looks good to me!
I previously thought the Log Context API would deal with the ThreadLocal stuff, but I can now see there is no API, just a SPI. I guess it was done this way to shift the field lifecycle management to the `LogContext` implementor. I can imagine some `LogContext` that uses the same field values for all threads.

**Comment by stian-sigvartsen** [comment]
Hi @arthurchan35 . I've added my proposal for handling the X-Request-Id field.
I also made a suggested rename for the configuration itself. We can discuss 👍

**Comment by stian-sigvartsen** [comment]
Glad you liked them @arthurchan35 !
Splitting it makes sense, but shouldn't the `enabled` property also go to the other ticket?

**Comment by stian-sigvartsen** [comment]
Also we may want to add some tests for this before sending I think?

**Comment by arthurchan35** [comment]
> Glad you liked them @arthurchan35 !
> Splitting it makes sense, but shouldn't the `enabled` property also go to the other ticket?

The other ticket?
According to the tickets Zsigmond created, there are only two of them: one is for audit log itself, the other is for audit configuration.
I think the enabled property should go under the configuration ticket, that is LPS-133653

**Comment by arthurchan35** [comment]
> Also we may want to add some tests for this before sending I think?

Sure, but what kind of tests are we expecting?

**Comment by arthurchan35** [comment]
> Also we may want to add some tests for this before sending I think?

Sure, but what kind of tests are we expecting?

**Comment by stian-sigvartsen** [comment]
Sorry, I didn't spot that you used 2 ticket keys in your commits for this PR. LPS-133653 was the "other".

I think we should test the enable/disable for the `X-Request-Id` via header. Because it is a new feature.

Maybe an integration test would be useful for testing that a HTTP request to the portal results in population of the `AuditLogContext` . To test that we could register a `Filter` (that executes after the `AuditFilter`), and it would track the `AuditLogContext` service, and call `AuditLogContext.getContext()` to asset that our various fields have expected values.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Looking good @arthurchan35 . I like your addition to send the header also in the response. Curious if this an industry practice? I wasn't able to find any good resources on it.

One thing though, it introduces a CRLF Injection vulnerability without improving our X-Request-Id validation. Can you add some stricter validation or alternatively sanitization before outputting it to the response?

Also I think because we're validating and potentially rejecting received X-Request-Id values, we should also add some logging for when invalid values are received. To assist system admins. Suggest log level should be DEBUG.

Finally, could we add two more tests where the client sends the header and it is either ignored or accepted into the logs, based on the configuration?

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
Regarding to writing x-request-id to response header:
https://www.youtube.com/watch?v=SgOqdwPs6Yg and
https://hackerone.com/reports/798686

In the second link, there are people actually reporting CRLF injection attack like you suggested.
After thinking about it, I believe CRLF is not only affecting response but also log, because the root problem is really that we want to have the feature to accept x-request-id from incoming request.

So I have added a commit to validate that.

Also I have updated configuration to better refelct the purpose of x-request-id configuration.
Also I have added log.

Regarding to the tests, I am thinking if we need to add them in this pull, as you can see poshi test is failing again, on ci, for something I couldn't reproduce locally. Also the tests you want require to add header to the request, we would need Gabor's help with that.

I am going drop the test commit for now.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:reevaluate:1087401_7558

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
