### PR TITLE
[TS] LPS-146787

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@gaborlovasdotcom 
Do you think the ci failure is real?

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
Hi @jonathanmccann,
I reviewed the failing functional MFA test cases. As the PR changes the default algorithm, when the End User tries to save the TOPT with QR code entered, we receive the following error at liferay.log:

> 2022-02-07 13:37:49.512 ERROR [http-nio-8080-exec-2][PortletServlet:119] javax.portlet.PortletException: java.lang.IllegalArgumentException: Invalid algorithm SHA1
javax.portlet.PortletException: java.lang.IllegalArgumentException: Invalid algorithm SHA1
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65) ~[portal-kernel.jar:?]
	

> Caused by: java.lang.IllegalArgumentException: Invalid algorithm SHA1
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil._generateHMAC(MFATimeBasedOTPUtil.java:105) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil._generateTimeBasedOTP(MFATimeBasedOTPUtil.java:114) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil.verifyTimeBasedOTP(MFATimeBasedOTPUtil.java:75) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.checker.TimeBasedOTPBrowserSetupMFAChecker.setUp(TimeBasedOTPBrowserSetupMFAChecker.java:201) ~[?:?]
	at com.liferay.multi.factor.authentication.web.internal.portlet.action.SetupUserAccountMVCActionCommand.doProcessAction(SetupUserAccountMVCActionCommand.java:113) ~[?:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:57) ~[portal-kernel.jar:?]
	... 171 more
Caused by: java.security.NoSuchAlgorithmException: Algorithm SHA1 not available
	at javax.crypto.Mac.getInstance(Mac.java:181) ~[?:1.8.0_191]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil._generateHMAC(MFATimeBasedOTPUtil.java:87) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil._generateTimeBasedOTP(MFATimeBasedOTPUtil.java:114) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.util.MFATimeBasedOTPUtil.verifyTimeBasedOTP(MFATimeBasedOTPUtil.java:75) ~[?:?]
	at com.liferay.multi.factor.authentication.timebased.otp.web.internal.checker.TimeBasedOTPBrowserSetupMFAChecker.setUp(TimeBasedOTPBrowserSetupMFAChecker.java:201) ~[?:?]
	at com.liferay.multi.factor.authentication.web.internal.portlet.action.SetupUserAccountMVCActionCommand.doProcessAction(SetupUserAccountMVCActionCommand.java:113) ~[?:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:57) ~[portal-kernel.jar:?]
	... 171 more

**Comment by arthurchan35** [comment]
Hey @jonathanmccann 
With Garbor's test anaylysis, I took  a look at your change.
Most of them is good except that you have changed HmacSHA1 to SHA1 in the [MFATimeBasedOTPUtil.java](https://github.com/liferay-appsec/liferay-portal/pull/556/commits/4c94bd2bf60c90f6ae5aa8d50f45917eea8d256e#diff-8c081c00f01ea7bd0736e7a787a55acd3fb7b3dd72b1e66a805fb2f9f1525428) class.

It's my fault that I didnt explain it clear in the PTR,
what I meant was change HmacSHA1 to SHA1 **ONLY** for the TOTP uri in the frontend, so nothing should changed in the backend logic.

I think a proper place would be:
https://github.com/liferay-appsec/liferay-portal/blob/6218e7295b0fb5e4a466568e2ceafd6bdbf10439/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-timebased-otp-web/src/main/java/com/liferay/multi/factor/authentication/timebased/otp/web/internal/checker/TimeBasedOTPBrowserSetupMFAChecker.java#L115

**Comment by jonathanmccann** [comment]
@arthurchan35 Thank you for catching that. I've updated the changes so please let me know what you think.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:mfa

**Comment by gaborlovasdotcom** [comment]
MFA test passed, closing.

**Pull request closed without merging**
