### PR TITLE
 [TS] LPS-188149 | Master - App Security 

### PR DESCRIPTION
**Pull request by MirnaGama**
**Steps to reproduce:**
1. Set up SMTP
2. Log in as admin user
3. Control panel → Instance settings → Login → Prompt Enabled →  
4. Product menu → Content & Data → Documents and Media → open tree.png → bookmark the page
5. Control panel → Instance settings → Multi-Factor Authentication → Enabled   
6. Log out
7. Open the bookmarked link
8. Log in & insert OTP

_Expected Behavior:_ Get redirected to the bookmarked page
_Actual Behavior:_ A green confirmation banner shows that the process was successful, but the page does not redirect anywhere

**Implementation Details:**

It was discovered that the redirect value [was missing in the view jsp file when the MFA is validated when the request redirect was overwritten](https://github.com/liferay-appsec/liferay-portal/pull/1229/commits/af7f859b32c5142d8e542f9175907b71a76600f4#diff-cd4794b72c830f978dafceedae2dc732fa81a3598ac2f9e5d3dd20a45b3da140R387).  

After it is filled in, the portal is redirected to the login page - This happens because the login is not resumed after MFA is validated, so [it was necessary to call the login mvc action class again to resume the flow](https://github.com/liferay-appsec/liferay-portal/pull/1229/commits/c735bc52eff9e4d1c5406690b9f4a3bc9edf4655#diff-099defccc6530fcce412e2dc404b84f487a97664e8579913a3c2baf77ab301eeR99).

Furthermore, it was observed that the user's credentials are not persisted in the request after the verify class is called, so it was necessary to [store them in the session in order to be able to fetch them and place them in the next render request](https://github.com/liferay-appsec/liferay-portal/pull/1229/commits/3e6c8bf67ae32bac58000c77612c3806bd8ab5d7#diff-285e713e6eff25805ea13b04446600b15c2450708fc12ca6b8066701a42f63e3R125) when the login flow is resumed.

And lastly, when the login flow is resumed, the user id is null because the user was not authenticated yet in the super login mvc action class, so it was not possible to fetch the id in the first place. To fix this, another verification was added to [check by the MFA user id](https://github.com/liferay-appsec/liferay-portal/pull/1229/commits/76a2418140a120690d0a5e251deb3db91d5aece8#diff-cd4794b72c830f978dafceedae2dc732fa81a3598ac2f9e5d3dd20a45b3da140R131) which was demonstrably fulfilled.

**Commits Included:**

- LPS-188149 Set value of redirect in the http session and portlet param in view file
- LPS-188149 Prevent redirect to auth screen by default and proceed to authenticate the user in mvc action class
- LPS-188149 Add user credentials on the request
- LPS-188149 Check if MFA User is satisfied when VerifyMVCActionCommand calls the super method
- LPS-188149 SF
- LPS-188149 Simplify

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
Hi @MirnaGama . Thanks for working on this solution. I could see that your solution works, but as I mentioned offline it is important that we do not store the user's credentials into the guest `HttpSession`. Also storing the "redirect" parameter there will have some unexpected behaviours, especially if someone is browsing with multiple tabs open.

In exploring the code I found the root cause to be a request URL length issue (4000 chars), and I found a way to reduce that given that when generating portlet URLs, the portlet API will preserve the current page / render context.

We were also sending the `redirect` parameter twice in the request which manifested the issue.

Please see liferay-appsec/liferay-portal/pull/1277

**Pull request closed without merging**
