### PR TITLE
LPS-199150 Remove ContentSecurityPolicyConfigurationVisibilityController in favor of using the featureFlag attribute

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-199150](https://issues.liferay.com/browse/LPS-199150).

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @stian-sigvartsen, just checking to see if you saw this one. LMK if you want to see anything changed. Thanks!

**Comment by stian-sigvartsen** [comment]
Hi @drewbrokke . This looks good, thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
