### PR TITLE
LPS-118086 CryptoVerifierRegistry followup

### PR DESCRIPTION
**Pull request by csierra**
hey Brian, /cc @arthurchan35

here comes a followup pull with the changes you asked for.

I am not sure if we should keep CryptoHashVerifierImpl as inner class, so that last commit could be removed. 

Bests. 
Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
