### PR TITLE
LPS-133082 Avoid exposing implementation detail

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @arthurchan35 . I've added a new portal property but for some reason it doesn't appear to be set when I set it in `portal-ext.properties`? Can you take a look?

Did you consider moving your catch block into the `toResponse(SecurityException)` method?

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
1. I have looked into the toResponse() method, and I agree it's a better place to add the change.

2. I am not sure how useful to report the exception to the front-end during development, especially we already have log that can be enabled to display the exception, also in order to support the properties you added, there are tons of semver bump. TBH, I dont think it's worth it.

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:reevaluate:1277401_747

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
As we just discussed offline, in this case it is important to preserve the original HTTP response for dev/test environments. Simply because this messaging is really well known and encountered frequently when deploying code into a new Liferay non-production environment. Though the same detail can be gotten from the system logs, this requires developers to work with the system admin to work out what's needed. And in a SaaS environment there might be no access to system logs by the customer.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
The unique failures for these tests appear to unrelated:

- JaxWsComponentHandlerRegistrationTest.testHandlerIsRegistered
- JaxWsApiRegistrationTest.testGreeter
- JaxWsApiHandlerRegistrationTest.testHandlerIsRegistered

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1327401_7

**Comment by arthurchan35** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/105165

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
Please see liferay-appsec/liferay-portal/pull/458

**Pull request closed without merging**
