### PR TITLE
LPS-190442 Remove company.security.auth.requires.https

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-190442](https://liferay.atlassian.net/browse/LPS-190442)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@manuelecastro that looks very good! I'm just re-running CI testing because it has been 3 weeks and there were a high number of failures.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by zsigmondrab** [comment]
Hi @manuelecastro,

Sorry for the late response on this. Could you please analyze the test failures if you haven't done that yet?

After that please rebase and send again and we will review as soon as possible.

Thanks,
Zsigmond

**Pull request closed without merging**
