### PR TITLE
LPD-40224

### PR DESCRIPTION
**Pull request by ChrisKian**
Changes look good @daiazius, but see my final commit.  I've also rebased the branch.

Please verify my changes look fine, and once CI passes, we can forward to Stian, thanks!

Original message:

> Ticket: https://liferay.atlassian.net/browse/LPD-40224
> 
> Hi, this problem was happening because when the portlet namespace was removed from the date parameters, the resourceURL tag stopped returning these parameters because it needs a namespace.
> 
> I solved this by moving the auditDisplayContext to init.jsp and using it to put these parameters back in the exportURL and making _getParamWithOrWithoutNamespace() accept the portlet namespace.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:report:63342302

**Comment by daiazius** [comment]
I tested locally and everything is working fine. Also, the relevant failures are not related.

@ChrisKian @stian-sigvartsen

**Comment by ChrisKian** [comment]
Hey @daiazius, these changes are acceptable for an SDH, but we still need tests to merge the PR.

**Comment by daiazius** [comment]
Resent with test and rebase here: https://github.com/liferay-appsec/liferay-portal/pull/2072

**Pull request closed without merging**
