### PR TITLE
[TS] LPS-125311 Use Apache Batik 1.13

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-125311](https://issues.liferay.com/browse/LPS-125311)
Dear Team,

Please review my changes and let me know if you have any questions or concerns.

Thank you,
István

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
