### PR TITLE
LPS-183481 - Confirm before deactivating or deleting users from the management toolbar.

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-183481

Add back confirm messages that were missed when refactoring.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:um

**Comment by JoyceWang08211** [comment]
No regression was found.

**Comment by stian-sigvartsen** [comment]
Looks good. Thanks @ethib137 !

**Pull request closed without merging**
