### PR TITLE
LPS-170791 Create filter for the ScopedServiceTrackerMapFactory class and move it to a proper module

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to:

- Include a new `filterString` parameter that can be used to filter all the Services that are desired to be tracked by the `ScopedServiceTrackerMap`.
- Move the `ServiceTrackerMapFactory` and its implementation from the `oauth2-provider-scope-liferay-api` OSGi module to the `osgi-service-tracker-collections` module and update the dependencies.
- In order to match the current pattern of the `osgi-service-tracker-collections` module, the `ServiceTrackerMapFactory` and `ServiceTrackerMapFactoryImpl` will be transformed into a class `ServiceTrackerMapFactory` with static methods

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @stian-sigvartsen @4lejandrito

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
@ccorreagg please let me know when you think the CI results are good, and I will complete my review on this.

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:security

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1297401_5827

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
Ran fresh tests against upstream and compared results with the latest nightly ci:test:security : https://testray.liferay.com/home/-/testray/runs/compare?formDate=1672827943690&testrayRunIdA=2147954352&testrayRunIdB=2134044677 

There were some unique failures for OAuth 2 tests, however these are passing locally when I rebase this PR on latest master.

The PR looks good to me.

**Comment by stian-sigvartsen** [comment]
ci:help

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Manually forwarded to brianchandotcom/liferay-portal/pull/128410

**Pull request closed without merging**
