### PR TITLE
LPS-127338 

### PR DESCRIPTION
**Pull request by antonio-ortega**
Previous pull request #295

More info: [LPS-127338](https://issues.liferay.com/browse/LPS-127338)

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
SF error not related to this pull request

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
please see: https://github.com/liferay-appsec/liferay-portal/pull/317

**Pull request closed without merging**
