### PR TITLE
LPD-37463 follow up

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by cdbm** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
Good catch @cdbm ! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
