### PR TITLE
LPS-145190 OAuth 2 JWT Grant (with disabled release flag)

### PR DESCRIPTION
**Pull request by liferay-appsec**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:nocompile

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:relevant:nocompile

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
