### PR TITLE
LPD-30298

### PR DESCRIPTION
**Pull request by ChrisKian**
Hey all, this is my fairly clean SAML playwright PR.  I'm hoping to get this merged asap, so the rest of the team can begin utilizing it.  I am open to any and all feedback.

Please note, the second test requires "idp" and "sp" to be added to the hosts file; I'll work on having this automatically included in tests, but for now, please manually add them yourselves.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
To help subteam 1 collaborate on this PR I have pushed its branch to the liferay-appsec repo and opened a replacement PR: liferay-appsec/liferay-portal/pull/1862

**Review by stian-sigvartsen — COMMENTED** [review]
Opened a new PR as per last comment.

**Pull request closed without merging**
