### PR TITLE
LPD-25363 use virtualHostname instead of host (Failing Test Case with Fix)

### PR DESCRIPTION
**Pull request by gamerson**
- **LPD-25363 add failing test case**
- **LPD-25363 use company.getVirtualHostname() for issuer which is more accurate than request host**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:oauth2

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
hey @stian-sigvartsen 

Here is the failing test case: 
https://github.com/liferay-appsec/liferay-portal/pull/1773
https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/889294/testReport/com.liferay.oauth2.provider.token.endpoint.test/JWTClaimsIssuerTest/

Screenshot 2024-05-23 at 11 45 18 PM

<hr>
For this PR, the same test passes
https://github.com/liferay-appsec/liferay-portal/pull/1774#issuecomment-2128197045
https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/994135/testReport/com.liferay.oauth2.provider.token.endpoint.test/JWTClaimsIssuerTest/

**Comment by stian-sigvartsen** [comment]
The test is failing, most likely because of an upstream change. The overall requirements may have changed also, so I am closing this PR for now.

**Pull request closed without merging**
