### PR TITLE
Lps 124898 oidc refresh token

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@arthurchan35 I need to do some more runtime testing with this change (let's talk offline), but... 

Can you explain why we need to change the portal core for this change?
It means we cannot backport the changes, and as you discovered we likely have refresh token grants issues in older versions.

SAML has a similar portal session refresh mechanism (tracking via SamlSpSession) that doesn't require any core changes. Maybe you could have a look?

I've pushed a couple of commits to avoid a SemVer major bump. I think those make sense?

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
1. We need to unschedule when session goes expired, so the only way I see is using a session listener.
2. Using a sessionListener does not require the change in core, but we have a authentication manager class that manually expires a life session and recreates a same one. Meaning the sessionListener created will be invoked and unnecessary unscheduling will happened. The change in core providers a mechanism to let listener know that a session is not really expired but recreates.
3. I have not seen the implementation in saml, I will take a look.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen 
I have made the changes to store session into persistence, though I didnt have time test them in runtime.
Let me know what you think with the changes.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @arthurchan35 . This is looking good. I can see that you have successfully migrated from the POJO to the SB model, mostly able to do it with drop in replacements 👍 

I will review the code a bit tomorrow but wanted to give you some feedback where I can...

I am wondering if now that we've got the DB layer and this can easily be iterated upon. Maybe it would simplify the code (and debugging it) if we just have 1 repeating scheduled task which does all the token refreshing instead of individual jobs?
This way you don't even need to schedule and unschedule individual OIDC sessions and this helps with decoupling the synchronous activities (request handling) with the background activity of refreshing tokens.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
@arthurchan35 I've pushed a couple of commits to avoid introducing a new ThreadLocal. Can you test?
The approach relies on the fact that `OPEN_ID_CONNECT_AUTHENTICATING_USER_ID` is not reserved when the HttpSession gets renewed.

I think we need to test more for any paths where `AutoLoginFilter` fails to login the user AND leaves the guest session in tact.

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
