### PR TITLE
LPD-29411 Ensure user setup is complete prior to rendering regular pages

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Review by alvarosaugarlr — COMMENTED** [review]
With the changes, works well ->LPSA-53087

The behavior now is an infinite loop when updating the password. When loading localhost:8080, the screen to change the password is shown (because it is in database), when trying to change, an exception is thrown in the password policy validation because the policy says not to update. Then you are still on the screen to change the password.

The change does not work because the logic we have in the code now is that the PP is more important, that is, in the validation of the password policies it checks that if the policy says not to change the password, then we should not be changing it and throws an exception ([here the validation](https://github.com/liferay/liferay-portal/blob/master/modules/apps/user-associated-data/user-associated-data-web/src/main/java/com/liferay/user/associated/data/web/internal/security/pwd/PasswordPolicyToolkit.java#L164)), regardless of whether the user indicates that he has to change the password in the database.

I have added a [commit](https://github.com/liferay-appsec/liferay-portal/pull/1836/commits/7f95c502bbcac634dc04c59ae52ae509c8fa85ff) with a change to check the value in the database of the user (Password Policy of the user).

**Comment by stian-sigvartsen** [comment]
Thanks @alvarosaugarlr ! I will take look 👍

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
@alvarosaugarlr  Sorry I wasn't able to review that commit yet. Maybe Rafael can assist with that in my absence.

**Comment by stian-sigvartsen** [comment]
The commit was fine, but we also need to revert the earlier commit I made to set reset to false during login.
Rebased and continued on liferay-appsec/liferay-portal/pull/1937

**Pull request closed without merging**
