### PR TITLE
[TS] LPS-144563

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi AppSec Team,

I hope you can review my changes. 

Related PTR discusses the potential solutions. I chose this approach because we don't really have control on how and when CharSetEncoder is created.

Please let me know if you have any questions or concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hey @istvansajtos 
Thanks for the fix!

I have three things in mind, can you help verify?
1. this check should happen only when web server configures to use utf 8(or maybe any utf encoding?)
- some like
```
if (webserver.encoding == utf8) {
   // your fix here
}
```
2. Can we find the constant of REPLACEMENT character from some existing servlet classes, instead of creating one?
3. Brian usually likes to see tests added for such fix, I think we can create at least one test case in redirect test class.

Arthur

**Comment by istvansajtos** [comment]
Thanks @arthurchan35 ! I've added test and now I'm forwarding the PR as you suggested.

**Comment by istvansajtos** [comment]
ci:forward

**Comment by istvansajtos** [comment]
Hi @arthurchan35 ! It seems forward is pending on your approval. Could you please take a look at it? Thanks!

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
