### PR TITLE
LPS-123218 SAML Persistence Changes (follow up)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
@martamedio I've pushed commits on top of yours.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
As discussed, we need to ask BChan if he wants SamlSpSessionLocalService method parameters revised following the XML re-ordering. It's difficult because all the parameters are String type and hence we cannot deprecate the current methods.

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by martamedio** [comment]
Please, see: https://github.com/brianchandotcom/liferay-portal/pull/102020

**Pull request closed without merging**
