### PR TITLE
LPS-168507 Change column size for better readability

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-168507

The text are overlapping and making it difficult to read clearly. Changing the size of the columns is able to fix this issue and make it readable.
Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
@fortunatomaldonado could you please rebase your branch? thank you!

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:security

**Comment by fortunatomaldonado** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
Relevant failure doesn't relate, forwarding manually in https://github.com/brianchandotcom/liferay-portal/pull/126689

**Pull request closed without merging**
