### PR TITLE
[TS] LPS-169808 LDAP login issue in case of clock difference

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-169808](https://liferay.atlassian.net/browse/LPS-169808)
Hi Team,

Please review my changes. This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/1095, taking Stian's suggestions into consideration.

Thank you,
Istvan

cc @stian-sigvartsen

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by istvansajtos** [comment]
I've updated the PR with SF and semver changes.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Reviewed and tested following the steps indicated in the description.
Also tested the import of users in case there is an infinite loop, as discussed in [github](https://github.com/liferay-appsec/liferay-portal/pull/1095/files#r1185961074).

**Comment by alvarosaugarlr** [comment]
Errors do not look like they are functionality related.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
