### PR TITLE
LPS-193844 SAML session remains active indefinitely if JSesssion is not expired properly

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-193844](https://liferay.atlassian.net/browse/LPS-193844)

Previously discussed with @stian-sigvartsen on [PTR-3993](https://liferay.atlassian.net/browse/PTR-3993).

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by jpince** [comment]
@alvarosaugarlr any updates on the review for this ticket?

**Comment by alvarosaugarlr** [comment]
Hi!

Reviewed (following [PTR-3993](https://liferay.atlassian.net/browse/PTR-3993)) and tested.

Create a [new pr](https://github.com/liferay-appsec/liferay-portal/pull/1333) to solve the conflicts.

**Pull request closed without merging**
