### PR TITLE
[WIP] LPD-27188 Invalidate WebDAV session when the user is deactivated

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPD-27188](https://liferay.atlassian.net/browse/LPD-27188)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hi @nikolettabuza . I found one key issue:
BaseAuthFilter#processFilter will get the user from the session via:

`user = PortalUtil.initUser(httpServletRequest);`

Which means the following condition can be met... 
`if (!user.isGuestUser()) {`

And result in bypassing your changes in `BaseAuthFilter#digestAuth` & `BaseAuthFilter#basicAuth`

**Comment by nikolettabuza** [comment]
Hi @stian-sigvartsen,

thanks for the input!
> `BaseAuthFilter#processFilter` will get the user from the session via:
> 
> `user = PortalUtil.initUser(httpServletRequest);`
> 
> Which means the following condition can be met... `if (!user.isGuestUser()) {`
> 

---
`PortalUtil.initUser(httpServletRequest)` always returns the `GuestUser` when it is a `WebDAV` request.
This is where I saw the session mentioned, you probably meant this part in `PortalUtil.getUser`:
```
if ((remoteUser == null) && !PropsValues.PORTAL_JAAS_ENABLE) {
	HttpSession httpSession = httpServletRequest.getSession();

	remoteUser = (String)httpSession.getAttribute("j_remoteuser");
}
```
Even though we have a `userId` from the request, the `remoteUser` is `null` in our case and the next lines return that instead of a `User` object:
```
if (remoteUser == null) {
	return null;
}
```
And that results in `PortalUtil.initUser` returning the GuestUser.

**Comment by stian-sigvartsen** [comment]
Hi @nikolettabuza . That condition in `getUser()` does not get executed if `getUserId()` return valid `userId`. And it will do so if it finds a `USER_ID` attribute in the `HttpSession`. Can you check?

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
Continued in [pull/1850](https://github.com/liferay-appsec/liferay-portal/pull/1850)

**Pull request closed without merging**
