### PR TITLE
LPD-41707 Stray </div> inside simplecaptcha.jsp breaks styles if taglib is placed into a form

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-41707](https://liferay.atlassian.net/browse/LPD-41707)

//cc @stian-sigvartsen

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
