### PR TITLE
[TS] LPS-178212 Resource permissions popup should search for roles by visible information only

### PR DESCRIPTION
**Pull request by tototrinh**
Here is the PR for fixing https://issues.liferay.com/browse/LPS-178212.
Please help review this PR and leave your comments.
Thanks.

Notes:
As recommended in the ticket, overloading the finder method is preferred. However, I found that the current method is no longer used anywhere so I decided to refactor it by adding a boolean parameter. Because the added parameter is a boolean type, the refactoring method can cover the current method's logic. It also removes the redundant method.
So, I figured refactoring would be fine.
Previous PR:
https://github.com/liferay-appsec/liferay-portal/pull/1043

### CODE REVIEW

**Comment by tototrinh** [comment]
Hi team, could you please help take a look at the PR? Thanks.

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Review by oliverkecskemety — APPROVED** [review]
LGTM! Thank you @tototrinh!

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
