### PR TITLE
[TS] LPS-194720 

### PR DESCRIPTION
**Pull request by MirnaGama**
### Reproduction steps:

1. Setup DXP environment with a fake SMTP service
2. Configure the standard ‘out of the box’ Multi Factor One Time Password
For this, first check if it is not disabled at Control Panel > System Settings > Security > Multi-Factor Authentication (If it is unchecked, then it is enabled)
Then navigate to Control Panel > Instance Settings > Security > Multi-Factor Authentication > Multi-Factor Authentication and Email One-Time Password Configuration
3. Navigate to Time-Based One-Time Password Configuration option > Enable and Save
4. Navigate to User Profile Menu > Account Settings > Multi-Factor Authentication tab > Connect the user with an authenticator app (e.g. Google Authenticator) - use the QR code or the Shared Secret > After paired, enter the time based code to the portal
_Checkpoint:_ if it is successful, you will see a huge red info container after the page re-render itself
To make sure it is working > Log out > Log in, and use the authenticator app for the time-based code
5. If it is working, log out again > At logging in, select Forgot Password > Fill out the necessary information
6. Receive 'Forgot Password' email
7. Select the link in the email beware the "dot" (.) at the end of the link, set up new password > Submit

**Results:**
 _Expected:_ The user is redirected to the login page to be able to sign in, after the password change.
_Actual:_ The user is not redirected to the login page to be able to sign in after the password change. They just got auto signed in to the portal.

### Implementation details: 
- Create a Java filter in a web module. This filter is executed when the request arrives, that is to say, when the password update request arrives (when we paste the url from the mail in the browser). At this time, we can check if MFA is enabled and add a parameter in the request.
- When the password update is executed (UpdatePasswordAction.java), the Java filter will have already been executed, so it should be enough to try to retrieve the parameter and if it exists, not to execute the login

### Commits included:

- LPS-194720 Create a web key to check if mfa is enabled
- LPS-194720 Create a filter to check if MFA Policy is enabled in web module
- LPS-194720 Check if mfa is enabled in session before auto sign in
- LPS-194720 SF
- LPS-194720 Move filter class to internal package
- LPS-194720 SF
- LPS-194720 Add missing author

### CODE REVIEW

**Review by oliverkecskemety — COMMENTED** [review]
Hi @MirnaGama,

Can you help me with some insights why do we need to use a filter to solve this? 

Thank you!

**Comment by MirnaGama** [comment]
Hi @oliverkecskemety 

Currently, the information that MFA is enabled cannot be easily fetched outside the multi-factor authentication module, so I created this filter, inside the module, to be executed everytime the request contains the update password path and set the information in the session, so it can be fetched later in the portal implementation package when the action class is executed. 

Let me know if more information needs to be provided.If you have another approach in mind, I'm also open to feedback. 😃

**Comment by oliverkecskemety** [comment]
I see, it makes sense now. Thank you @MirnaGama!

Last question: can you not use the `/c/portal/update_password` url path inside the filter's component properties `url-pattern` to check for a valid call?

**Comment by MirnaGama** [comment]
Hi @oliverkecskemety 

It's done ! -> https://github.com/liferay-appsec/liferay-portal/pull/1341/commits/66afe2d710f0b886bee527256ab768bec5f95987

Sorry for the late response. While testing this modification, I discovered a regression bug when the user had to reset the password when logging in for the first time, but it's now fixed here -> https://github.com/liferay-appsec/liferay-portal/pull/1341/commits/8e85ad2fbe2662050fcfdb6330993e71f42dcc27

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Review by oliverkecskemety — APPROVED** [review]
Good job! Thank you @MirnaGama!

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
