### PR TITLE
LPD-40224

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-40224

Hi, I had to wrote a functional test for this one as writing a integration/unit test was proving to be difficult because of some manual type casts that exist in `AuditDisplayContext` and `ExportAuditEventsMVCActionCommand`

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
Hey @daiazius,
The test is a good start, but I think it should be a bit more robust.  Could you try a similar approach, but for **every** field?  Even though LPD-40224 only mentions start/end dates, there were no fields being used in the export process before your fix.  I think one test to cover all fields is fine; you don't need to make an individual test for each field.

And, could you also verify with another test the URL doesn't get over 2048 characters (max URL length) for rendering the page or for the export event?  This will show we aren't regressing the fix from LPS-192555 or encountering it for the export event.

If you need any help or have any questions, please let me know, thanks!

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
I'm not sure how a new test is failing, since I've only added tests with this PR.

**Comment by stian-sigvartsen** [comment]
Hi @daiazius @ChrisKian . Has this change been discussed with CoreInfra because it changes the `LiferayPortletURL` interface?

I'm concerned we may be bleeding portlet container implementation detail into our implementation of the portlet API .
If the namespaces are not required, then the our portlet API implementation should not be adding them ever. Having this new "useNamespace" parameter is pushing this complexity to the API consumer.

**Comment by ChrisKian** [comment]
I'll need to revisit this later and try to figure out a better way to resolve this issue.  We may be able to use the previous resourceRequest, to grab all the parameters we need.

**Comment by daiazius** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/2093

**Pull request closed without merging**
