### PR TITLE
LPS-206370

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-206370

I have a few issues with the PR, but I'm not sure if they are possible to improve upon.  The solution completely works, and I've seen no regressions, however the fix just seems messy.

1. I am unable to create a single REGEX which matches the exact entries needing to be replaced.  Instead, the code returns all potential entries, then performs further analysis to determine if they should be escaped or not.  I don't think it's possible to create a REGEX like this, because the number of leading open curly braces could be variable.
2. The names I gave to the related variables seem descriptive, but not as simple as I'd like.  I'm not sure what else to name them.
3. Lastly, I'm not sure how to add tests for this issue.  We need to edit a content page which has some fragments added to it, but [the existing test class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security/portal-security-content-security-policy-test/src/testIntegration/java/com/liferay/portal/security/content/security/policy/test/ContentSecurityPolicyFilterTest.java) just uses [the default landing page](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security/portal-security-content-security-policy-test/src/testIntegration/java/com/liferay/portal/security/content/security/policy/test/ContentSecurityPolicyFilterTest.java#L202) for existing tests.

Any help is appreciated, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
CI failures are unrelated and I have tested the latest changes locally. A unit test has been developed but will be sent separately.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
