### PR TITLE
LPD-27188 Invalidate WebDAV session when the user is deactivated - follow up

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Sharing https://github.com/stian-sigvartsen/liferay-portal/pull/300 for visibility and collaboration with the team.

The PR is to follow up on brianchandotcom/liferay-portal/pull/152872

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Looks good @tomibiro ! If CI passes I will forward.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
I checked the relevant test failure report and did not find relevant failure connected to the change.

**Comment by stian-sigvartsen** [comment]
Thanks for checking @tomibiro . I will forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
