### PR TITLE
LPS-195762 - XSS with tabs2 in role assignment

### PR DESCRIPTION
**Pull request by manuelecastro**
related issue: [LPS-195762](https://liferay.atlassian.net/browse/LPS-195762)

### CODE REVIEW

**Comment by zsigmondrab** [comment]
ci:forward

**Comment by manuelecastro** [comment]
relevant failures are not related to the PR

**Comment by zsigmondrab** [comment]
Hi @manuelecastro,

We were just wondering with @stian-sigvartsen that basically it's better to do this in in the JSP that uses the display context. Is there any reason why you haven't chosen that way?

Thanks,
Zsigmond

**Comment by manuelecastro** [comment]
Hi @zsigmondrab,

I did it this way because the getSelectAssigneesNavigationItems() method returns a list and I wasn't sure of how I could escape the tabs2 value from the list directly on the J[SP file](https://github.com/liferay-appsec/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_assignees.jsp) (see line 38). Would there be a turn around to do this on the JSP?

Thanks!

**Comment by manuelecastro** [comment]
Hi @zsigmondrab!

I took another look to see if I could manage to find a way to make the escape at the JSP and updated the PR with a possible solution. What do you think? :eyes:

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by zsigmondrab** [comment]
new pr: https://github.com/liferay-frontend/liferay-portal/pull/3709

**Pull request closed without merging**
