### PR TITLE
LPD-19662 simplify

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@daiazius please can you review my changes and forward if you agree. Thanks!

**Review by daiazius — APPROVED** [review]
LGTM!

**Comment by daiazius** [comment]
ci:forward

**Comment by daiazius** [comment]
ci:stop

**Comment by daiazius** [comment]
ci:forward

**Comment by daiazius** [comment]
ci:forward:force

**Comment by daiazius** [comment]
ci:forward:force

**Pull request closed without merging**
