### PR TITLE
LPD-22074

### PR DESCRIPTION
**Pull request by daiazius**
Issue: https://liferay.atlassian.net/browse/LPD-22074
Hi, after some time debugging I noticed that the problem with updating the custom fields in `LdapUserImporterImpl` is that when a new custom field is added to the portal the users don't get their `modifiedDate` changed. So, if a user has been imported before and therefore their `modifyTimestamp` in the LDAP server is the same as their `modifiedDate` in Liferay, that user won't be updated. So the only way the custom fields can be updated is if something changes one of these dates, via Liferay or LDAP. My solution is to check the user's currently populated custom fields, and if there are fewer fields than the ones mapped in the LDAP server configuration, proceed with the update.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @daiazius,
Your solution is decent, but there is a similar scenario which would result in the same bug.  Imagine this scenario: we have two custom user fields, `Location` and `Postal Address`.
1. Setup LDAP without custom field mapping and import users
2. Reconfigure LDAP to account for `Location` custom field.
3. Reimport users -> your solution works here
4.  **Reconfigure LDAP to remove `Location` custom field mapping while adding `Postal Address` custom field mapping.**
5. Reimport users -> your solution does not work here

My suggestion is to compare the last import date with the LDAP configuration modified date (if possible).  Otherwise, you may need to compare the expando column names with the mapped attributes, to see if they make sense.  Please let me know if you disagree or have any questions, thanks!

**Comment by daiazius** [comment]
Hey @ChrisKian, I followed your suggestion and now this fix should work for all the cases. Let me know if you have any questions or more suggestions, thanks!

**Comment by ChrisKian** [comment]
Hey @daiazius, this approach is much better.  ~~I'm just concerned with what happens if we attempt to import an LDAP user from a server configuration we have not modified since your changes.  It seems the `modifiedDate` value in the configuration won't be present, and thus will return an empty String.  If we use this empty string in date parsing, will any errors be thrown?  Will the portal incorrectly believe the configuration is newer than the last import time (and thus, attempt to import the user)?~~

~~I believe the best action is to make sure an empty/null `modifiedDate` value does not re-import the user, and ask client's to re-save their LDAP server configurations if they experience this problem.~~

I believe there may be some customers who do not want this functionality I.E. they adjust something trivial like the LDAP server name, and now all their users get re-imported.  Could we hide this functionality behind an LDAP configuration, something like "Reimport users upon LDAP configuration change", and default it to `false`?  This way, we don't break anything for customers, and the `modifiedDate` value will be properly set for customers who do want to use this functionality (since they will need to re-save their LDAP configuration to adjust the new configuration).

Let me know if you have questions/concerns about this, thanks!

**Comment by daiazius** [comment]
Hey @ChrisKian, just updated the PR addressing the issues you mentioned. Now the server configuration `modifiedDate` only updates when a custom mapping is changed and I'm checking for an empty `modifiedDate` also

**Comment by ChrisKian** [comment]
Hi @daiazius,
Your changes looks good, so I've added a couple SF commits and forwarded the pull here: https://github.com/liferay-appsec/liferay-portal/pull/1735

Please give it a quick test to make sure everything still works as intended.  Once you've done that, we can forward the pull to Brian.  Thanks!

**Pull request closed without merging**
