### PR TITLE
Update Apache JAX-RS Whiteboard 2.0.0

### PR DESCRIPTION
**Pull request by csierra**
#

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
rebased to latest master

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
one of the soap-extender-tests is incorrectly waiting for 10 minutes upon termination, but that's seems unrelated to this PR.

**Comment by martamedio** [comment]
Follow up: https://github.com/liferay-appsec/liferay-portal/pull/340

**Pull request closed without merging**
