### PR TITLE
LPS-157790 Multiple BearerTokenProviders

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hi Stian,
> Are you convinced about the reorganization? 

What is the reorganization you refered to?

> I mean if we didn't want to store only the JWT ID, would you still do it? The previous state seemed to let the base class drive the logic more, but I'm not decided.

Do you mean store the whole JWT access token as token key instead of JWT ID as token key? If so, I am fine with the idea, in fact, i would prefer it to storing only JWT ID.

 
> I see you left out the TOCTOU. Which is fine probably because we haven't got the consumer side yet.
TOCTOU is left out because Tomas suggested to store the state of the JWT access token so that RS(comsumer) can ask AS for detailed/updated state of which, so that it's okay to store just the initial state(initial scope aliases etc) of access token into JWT.
Unless you don't want to store the state?

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen 
I was reviewing your changes. I would appreciate if we can discuss about it if you had such big changes. And I am not sure about if we need to involve token providers at all.

**Comment by arthurchan35** [comment]
I believe:
commits until https://github.com/liferay-appsec/liferay-portal/pull/816/commits/356eb0f0613a8436981931c489d2ecaed4b2fe95 is good for forwarding if we whole JWT.
commits until https://github.com/liferay-appsec/liferay-portal/pull/816/commits/e620ef338c961a72fcc22559dd118d05ae5da764 is good for forwarding if we store JWT id.

**Comment by stian-sigvartsen** [comment]
> I understand it's adding more code, but i believe it's worth it, and I have sent PR to CXF Repo to extract out the opaqueToken generation. Hopefully I can get some feedback quickly.

That's a great way to assess if this is better. Because if CXF are developing in another direction, then the lack of super.X() calls is likely to cause new logic by them to be skipped in our next upgrade etc.  Let's see what they say!

> ALSO: I would much prefer storing whole JWT to storing just the id (in the same column not a separate table). There are multiple benefit:
> * is that the RS can just send the JWT back to AS, and AS can use the JWT to look up token state in a same manner as opaque token. If you store the id, then AS has to parse the JWT first to get the ID and then use the id to look up token state.
> * I can drop https://github.com/liferay-appsec/liferay-portal/commit/e620ef338c961a72fcc22559dd118d05ae5da764 this commit.
> * There are some other reason from cxf, but I have not investigate deep enough, so I am not listing it as reason for now.

I would agree. The only benefit we are getting by not storing the whole JWT is disk space. And given that JWTs are short lived (at least the access token variety which is all we are focussed on for now), those records will be short also.
Let's consider if there are other benefits in a future ticket.

> TOCTOU is left out because Tomas suggested to store the state of the JWT access token so that RS(comsumer) can ask AS for detailed/updated state of which, so that it's okay to store just the initial state(initial scope aliases etc) of access token into JWT.
> Unless you don't want to store the state?

For the moment our main objective is scalable performance. My interpretation of what Tomas wanted to highlight is simply that statelessness doesn't automatically translate into performance gain. And also that sometimes it is not appropriate to be fully stateless, for security reasons.

So in the context of that, I would say stateful JWT tokens are not necessary, and actually creates a poorer developer UX and performance because of the needed introspection callbacks. But more importantly after a deeper review it actually doesn't solve the problem. Because the introspect response only provides only the scope aliases also! Those may not have changed, but the ScopeGrants they resolve to may have. So there is still TOCTOU.

The concept of scope aliases is a local concept to DXP, and we don't have an immediate need to support separating the DXP AS & RS servers into separate JVMs. Also we discussed only supporting one "aud", the local DXP RS.

So to make progress we could replace that callback with a local AS server check, for now. This is possible because the JWT carries the date/time it was created "iat" claim. And also we have the createDate of the OAuth2ApplicationScopeAliases.createDate table column. So we can retrieve the record immedately before that time and get the ScopeGrants to use. Maybe we could discuss this further offline.

**Comment by arthurchan35** [comment]
> So in the context of that, I would say stateful JWT tokens are not necessary, and actually creates a poorer developer UX and performance because of the needed introspection callbacks. But more importantly after a deeper review it actually doesn't solve the problem. Because the introspect response only provides only the scope aliases also! Those may not have changed, but the ScopeGrants they resolve to may have. So there is still TOCTOU.


I am not saying I prefer stateful JWT at all, but I am pretty sure the decision was made by the agreements from 3 of us... So it's bit confusing to me that you seem to switch back to stateless JWT again(again, I prefer stateless JWT myself).
Regarding introspection response, it's not necessary to invoke introspection endpoint for state check, we can simply use the JWT itself in same manner as opaque token to look up state.

We can discuss the rest on zoom.

**Comment by arthurchan35** [comment]
See:
https://github.com/liferay-appsec/liferay-portal/pull/817

**Pull request closed without merging**
