### PR TITLE
[TS] LPS-196784 Do not restore current view to avoid showing the forgot pass or create account screens when navigating back

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-196784

Previous fix reviewed under https://github.com/liferay-appsec/liferay-portal/pull/1401
Previous fix reverted under https://github.com/liferay-appsec/liferay-portal/pull/1419 due to https://liferay.atlassian.net/browse/LPS-197914

This fix instead of trying to maintain the redirect simply disables the _Restore Current View_ functionality. This makes it so that when going from a maximized Sign In widget back to the normal sized widget it renders the sign in fields instead of the Forgot Password or Create Account fields.

Please let me know if there are any concerns with this change. Based on the previous fix causing a regression for Commerce it seems this flow is rather fragile so I want to make sure nothing else is depending on the current view being maintained.

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:commerce-functional

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by GergoMathe** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
