### PR TITLE
LPD-23110 integration tests source formatting

### PR DESCRIPTION
**Pull request by tomibiro**
Some source formatting was asked by Brian (https://github.com/brianchandotcom/liferay-portal/pull/150746#issuecomment-2135168367) which I added to this PR.

### CODE REVIEW

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:test:sf

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:stable

**Comment by tomibiro** [comment]
I checked the failures in the ci run (ci:test:relevant) and they are irrelevant to the modifications.

**Comment by ChrisKian** [comment]
Rebased and forwarded here: https://github.com/liferay-appsec/liferay-portal/pull/1777

Applying attempting to forward now.

**Comment by tomibiro** [comment]
Resolved on https://github.com/brianchandotcom/liferay-portal/pull/150874

**Pull request closed without merging**
