### PR TITLE
LPS-176161 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-176161

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:cookies:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies:nocompile

**Comment by melodywu** [comment]
ci:test:cookies:nocompile

**Comment by melodywu** [comment]
ci:test:cookies:nocompile

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
