### PR TITLE
Lps 135063 audit test

### PR DESCRIPTION
**Pull request by arthurchan35**
https://issues.liferay.com/browse/LPS-135063

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@gaborlovasdotcom 
It's bit painful to test locally as it requires to download specific google chrome, I have left it for CI to run the test.
I would like you to review and test it.

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
Hi @arthurchan35 , I reviewed and fixed the test data, and they pass.
I forward it from https://github.com/gaborlovasdotcom/liferay-portal/pull/192, and close this one.
Thank you for adding these new test cases!

**Pull request closed without merging**
