### PR TITLE
Lps 126598 remove ntlm

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hey @arthurchan35 . As we discussed I think we should only archive NTLM SSO in this ticket. We need to work with product teams to remove NTLM where portal is acting as client. i.e. Analytics Cloud & S3 Stores.

Please see liferay-appsec/liferay-portal/pull/481

p.s. Once agreed with teams we can rebase your PR for the full removal 👍

**Pull request closed without merging**
