### PR TITLE
LPD-30298 (just pushed Chris's brach to liferay-appsec for team swarming)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
From Chris: 

> Hey all, this is my fairly clean SAML playwright PR. I'm hoping to get this merged asap, so the rest of the team can begin utilizing it. I am open to any and all feedback.
> 
> Please note, the second test requires "idp" and "sp" to be added to the hosts file; I'll work on having this automatically included in tests, but for now, please manually add them yourselves.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks for everyone's contributions! @ChrisKian will review and considering forwarding it. Great team effort yesterday / today team!

**Comment by stian-sigvartsen** [comment]
This PR was superseded by liferay-appsec/liferay-portal/pull/1935

**Pull request closed without merging**
