### PR TITLE
LPS-76246 Fix "Relay state exceeds 80 bytes" error

### PR DESCRIPTION
**Pull request by mbowerman**
Not sure if this is the best way to do this, but it seemed to work well in my testing.

For the third commit, I'm not sure if there is a better/more "recommended" way to create a `ConcurrentMap` with a time-based expiration mechanism in Liferay code. The closest thing I could find was `ConcurrentReferenceKeyHashMap`, but this is a reference-based expiration mechanism, not a time-based one. I don't think a reference-based mechanism will work since there seems to be the potential for there to be a brief moment between `set` and `get` where no one has a reference to the UUID, as `set` and `get` happen in different threads. So in a reference-based expiration mechanism, the map entry could expire before we call `get`.

I'm not sure if we want to make the "10 Minutes" configurable, but I imagine the vast majority of clients aren't going to care about such a thing. They may only care about it if they find that this map is consuming an excessive amount of memory. If we do decide to make it configurable, we'd need a way to recreate the Map when the configuration has changed, or else we'd need to warn the user that they need to restart the portal after updating the configuration.

I tested the third commit by altering the expiration time to 1 minute, putting a "Suspend Thread" breakpoint after the entry was placed in the Map, and waiting over a minute. When it got to the `get` method, sure enough, the entry was not present in the Map and it got a null value. If it gets a null value, it's not really a big deal. The user just gets redirected to the home page on login instead of where they were logging in from previously. And with a 10-minute expiration time, it's hard to imagine this ever happening unless SAML is being extraordinarily slow (in which case, you've got way bigger problems).

Ticket: [LPS-76246](https://liferay.atlassian.net/browse/LPS-76246)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
Regression issue:
1. Create a virtual instance "www.able.com"
2. Configure localhost:8080 as IdP
3. Configure www.able.com as SP
4. Create a new user for IdP
5. Link IdP and SP to each other to create a SAML link
6. Ensure two instances log out
7. Navigate to http://www.able.com:8080 and click Sign In button
8. Sign in the portal as new user

Expected result: New user successfully logs in to the virtual instance.
Actual result: Login fails, UI redirects to able.com:8080. And an error message "Error:Your request failed to complete." appears in the UI.
Console log:
`2023-08-15 11:17:15.041 ERROR [http-nio-8080-exec-3][WebSsoProfileImpl:216] null
com.liferay.portal.kernel.exception.UserScreenNameException$MustNotBeNull: Screen name must not be null for user 39258
	at com.liferay.portal.service.impl.UserLocalServiceImpl.validateScreenName(UserLocalServiceImpl.java:6948) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.validate(UserLocalServiceImpl.java:6696) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.addUserWithWorkflow(UserLocalServiceImpl.java:1104) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.addUser(UserLocalServiceImpl.java:932) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1172.addUser(Unknown Source) ~[?:?]
	at com.liferay.portal.kernel.service.UserLocalServiceWrapper.addUser(UserLocalServiceWrapper.java:317) ~[portal-kernel.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1173.addUser(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy119.addUser(Unknown Source) ~[?:?]
	at com.liferay.saml.opensaml.integration.internal.field.expression.handler.DefaultUserFieldExpressionHandler._addUser(DefaultUserFieldExpressionHandler.java:201) ~[bundleFile:?]
`

**Comment by gaborlovasdotcom** [comment]
This change breaks the following integration tests:
com.liferay.saml.opensaml.integration.internal.servlet.profile.SingleLogoutProfileIntegrationTest
testSendSpLogoutRequestValidSpSession
Error:
	java.lang.NullPointerException
		at com.liferay.portal.kernel.uuid.PortalUUIDUtil.generate(PortalUUIDUtil.java:19)
		at com.liferay.saml.opensaml.integration.internal.util.RelayStateUtil.setRelayState(RelayStateUtil.java:51)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.SingleLogoutProfileImpl.sendSpLogoutRequest(SingleLogoutProfileImpl.java:610)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.SingleLogoutProfileIntegrationTest.testSendSpLogoutRequestValidSpSession(SingleLogoutProfileIntegrationTest.java:304)
com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileIntegrationTest
testDecodeAuthnRequestIdpInitiatedSsoAfterAuthentication, testDecodeAuthnRequestStageAuthenticated, testDecodeAuthnRequestIdpInitiatedSso, testDecodeAuthnRequestVerifiesSignature, testDecodeAuthnRequestStageInitial, testForceAuthn
Error:
	java.lang.NullPointerException
		at com.liferay.portal.kernel.uuid.PortalUUIDUtil.generate(PortalUUIDUtil.java:19)
		at com.liferay.saml.opensaml.integration.internal.util.RelayStateUtil.setRelayState(RelayStateUtil.java:51)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileImpl.doSendAuthnRequest(WebSsoProfileImpl.java:496)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileIntegrationTest.testDecodeAuthnRequestStageAuthenticated(WebSsoProfileIntegrationTest.java:403)
com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest
testXMLBombQuadraticBlowup, testXXEGeneralEntities1, testXMLBombBillionLaughs, testXXEGeneralEntities2, testXXEParameterEntities
Error:
	Caused by: java.lang.NullPointerException
		at com.liferay.portal.kernel.uuid.PortalUUIDUtil.generate(PortalUUIDUtil.java:19)
		at com.liferay.saml.opensaml.integration.internal.util.RelayStateUtil.setRelayState(RelayStateUtil.java:51)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileImpl.doSendAuthnRequest(WebSsoProfileImpl.java:496)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest._getAuthnRequestRedirectURL(XMLSecurityTest.java:337)
		at com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest.testXXEGeneralEntities1(XMLSecurityTest.java:179)

**Comment by stian-sigvartsen** [comment]
@mbowerman please can you analyze the cause of those failing integration tests?

I'm surprise that Jessie's steps fail, because that is essentially the happy path for SAML SSO. 
@JessieZhao0714 please can you check that you enabled and added the usual SAML attributes on the IDP's SP connection?

**Review by stian-sigvartsen — COMMENTED** [review]
I forgot to mention that I think your approach is probably reasonable, and the implementation of it is clean.

I had some reservations with relying on server state, because that might mean that if ...

1) the user initiates SSO from the SP
2) then leaves the browser tab upon seeing the IDP login portlet
3) later the user authenticates in another browser tab
4) finally the user refreshes the original tab, expecting to complete the SSO successfully (if after 10 mins) without authentication prompt

This scenario is a typical behaviour in other product (Jira for example), and is a good UX IMHO.

However I found that we are already reliant on server state for the `SamlSsoRequestContext`.

So I'm only sharing this for future thought :)

**Comment by mbowerman** [comment]
I tested @JessieZhao0714's steps [here](https://github.com/liferay-appsec/liferay-portal/pull/1273#issuecomment-1678788279) with my changes deployed, but I didn't see any issue. The user was able to log in successfully, and I saw no errors in the logs. I agree with @stian-sigvartsen's comment [here](https://github.com/liferay-appsec/liferay-portal/pull/1273#issuecomment-1679060823); please double-check that you added the usual SAML attributes on the IDP's SP connection, including screenName.

@gaborlovasdotcom My bad I didn't know we had to explicitly set the _portalUUID objects in our tests. I will fix those tests and let you know when I am finished.

**Comment by mbowerman** [comment]
Fixed unit test failures and re-sent at https://github.com/liferay-appsec/liferay-portal/pull/1302

**Pull request closed without merging**
