### PR TITLE
LPD-32903 Change upgrade process to prepare for backports - resend

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-32903](https://liferay.atlassian.net/browse/LPD-32903)

This changes are needed so we're able to backport a SEV ticket that contains an upgrade process. [(LPD-1909)](https://liferay.atlassian.net/browse/LPD-1909)

Changes were made based on Alberto Chaparro's guidance on [PTR-5252](https://liferay.atlassian.net/browse/PTR-5252)

cc: @daiazius

### CODE REVIEW

**Comment by manuelecastro** [comment]
I did the changes from scratch again and the failure seemed to be gone locally... I'll run relevant again to check.

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:report:52420595

**Comment by manuelecastro** [comment]
Hi @stian-sigvartsen, 

The previous failures are passing now, and regarding the upgrade suite there were no unique failures on the previous PR, so I think this is good to forward. :)

Thank you

**Comment by stian-sigvartsen** [comment]
Thanks for being so thorough @manuelecastro ! I will forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
