### PR TITLE
LPD-26151

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPD-26151](https://liferay.atlassian.net/browse/LPD-26151)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/1787

I squashed your SF commit, since it was unnecessary to include on it's own.  Test failures look unrelated, but please double-check.  I'll attempt to forward now, and force if still failing (and you agree failures are unrelated).  Thanks!

**Pull request closed without merging**
