### PR TITLE
LPS-165963 | master

### PR DESCRIPTION
**Pull request by arthurchan35**
[LPS-165963](https://issues.liferay.com/browse/LPS-165963)

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
bump! :)

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by rotty3000** [comment]
@gaborlovasdotcom does this mean I can ci forward this?

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
@rotty3000 yes, we checked it and passed manual QA.

**Pull request closed without merging**
