### PR TITLE
LPD-23115

### PR DESCRIPTION
**Pull request by ChrisKian**
Sent from https://github.com/liferay-appsec/liferay-portal/pull/1756

Original message:

> This PR was first sent to @ChrisKian for review: https://github.com/liferay-appsec/liferay-portal/pull/1719#issuecomment-2059664863. That PR was commented on and closed.
> 
> This new PR contains modifications according to discussions with Chris Kian for the following:
> 
> Import/export localized Strings. Ldap does not handle this, Liferay must handle it as Custom fields can be set for this type.
> Repeating values can be sent from Ldap to Liferay. In this case, the first sent value is handled only.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:reevaluate:1267401_13376

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant (I need to reinvoke this build because the Jenkins master that this is queued on is frozen)

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @tomibiro,
Even though everything was wokring as we tested, something didn't feel right with our changes in the `ExpandoValueLocalServiceImpl` class, specifically when we no longer [expected a Map](https://github.com/liferay-appsec/liferay-portal/pull/1763/files#diff-8490ffd9f48a99a93a6e65c914c6c136a4f476a64e7f7c22b1f81a244eeceb30L850) and instead [expect a String](https://github.com/liferay-appsec/liferay-portal/pull/1763/files#diff-8490ffd9f48a99a93a6e65c914c6c136a4f476a64e7f7c22b1f81a244eeceb30R860).

I ran through the tests in the [ExpandoValueLocalServiceTest class](https://github.com/liferay/liferay-portal/blob/6cb31200eda5752c4d276424f64abf0dbb2fe7a1/modules/apps/expando/expando-test/src/testIntegration/java/com/liferay/expando/service/test/ExpandoValueLocalServiceTest.java) and found none of them actually touch the `addValues()` method, specifically during the `STRING_LOCALIZED` portion.

So, I added [a new method](https://gist.github.com/ChrisKian/0c8b9b08f68adad004b0ede48a6fed7f) to the test class which specifically tests the code we touch.  I've found that with our changes in this PR, we now fail this test.

I'm looking into how to fix this issue properly, since it's a bit complex and it's fresh on my mind.  Likely, we will need to convert the attribute coming from `LDAP` into the expected `Map<Locale, String>` datatype **_before_** we add it as an expando value.  If I do not complete the solution before you start your day, and you'd like to contribute some code, you're more than welcome to.

**Comment by tomibiro** [comment]
Hi @ChrisKian,
Thanks for spending much time and effort on this PR. I will look at your test and try to develop the converter that you mentioned.
Br,
Tomi

**Pull request closed without merging**
