### PR TITLE
LPD-29518 Fix SAML#SSOLoginLogoutWorkSameWhenSitesConfiguredAsSP test failure

### PR DESCRIPTION
**Pull request by jgarcialr**
This PR fixes both test's 
[LPD-29518](https://liferay.atlassian.net/browse/LPD-29518) and [LPD-25310](https://liferay.atlassian.net/browse/LPD-25310)

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:report:72363476

**Comment by jgarcialr** [comment]
ci:report:72363476

**Comment by jgarcialr** [comment]
ci:report:72363476

**Comment by jgarcialr** [comment]
ci:report:72363476

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
Both tests passed:
* [LocalFile.SAML#SSOLoginLogoutWorkSameWhenSitesConfiguredAsSP](https://testray.liferay.com/#/project/34754/routines/34756/build/75631868/case-result/75649667) -> [LPD-29518](https://liferay.atlassian.net/browse/LPD-29518)
* [LocalFile.SAML#SAMLConfigurationNotApplyToSitesAfterACSDisabled](https://testray.liferay.com/#/project/34754/routines/34756/build/75631868/case-result/75649322) -> [LPD-25310](https://liferay.atlassian.net/browse/LPD-25310)

**Comment by stian-sigvartsen** [comment]
These Poshi tests were converted to Playwright. See liferay-appsec/liferay-portal/pull/1935

**Pull request closed without merging**
