### PR TITLE
LPS-75030

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @stian-sigvartsen, 

please have a look at the changes (I hope I did not break anything) and let me know what you think. 

Carlos.

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
hey @stian-sigvartsen, I don't know what the SF error is about... it is not failing on my local

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Review by stian-sigvartsen — COMMENTED** [review]
All changes except the using existing verification looks good to me. And that one highlighted a need to separate MessageContext building and processing as discussed. I've pushed commits.

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
thx for fixing it @stian-sigvartsen!

**Comment by stian-sigvartsen** [comment]
Forwarding as discussed. Thanks for reviewing!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by csierra** [comment]
ci:reopen

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
