### PR TITLE
LPS-188746 Cannot update another user's screen name or email if "Require password for email or screen name updates?" is unchecked

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-188746](https://liferay.atlassian.net/browse/LPS-188746)

### CODE REVIEW

**Comment by mbowerman** [comment]
I've censored the word "password" in the commit message and force-pushed.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Review by stian-sigvartsen — APPROVED** [review]
Looks good to me. Will forward if CI agrees.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
