### PR TITLE
LPS-206534 / LPD-4254 - Removing the default.admin.password value from portal-ext.properties

### PR DESCRIPTION
**Pull request by jgarcialr**
prior PR: https://github.com/liferay-appsec/liferay-portal/pull/1627

[LPD-4254](https://liferay.atlassian.net/browse/LPD-4254)

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:reevaluate:1327401_4534

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
@jgarcialr I will close this PR because even if it needed, it will need a rebase. The ticket is only "selected for development" so this PR I guess was just for some explorative CI testing anyway.

**Comment by jgarcialr** [comment]
Hi @stian-sigvartsen ,

This PR aim to solve the issue with default admin pwd and adding some extra tests to check the new behavior.
 I think the LPD is in selected to development because of the block of ci to change the default password and some tests with hardcoded passwords.

**Comment by stian-sigvartsen** [comment]
Thanks @jgarcialr, understood. I can see some SF issues like needing to inline variables, so please can you cover that in a follow up PR?

**Pull request closed without merging**
