### PR TITLE
[TS] LPS-145129

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi team, please let me know if this PR is not for you to review. I'm trying to solve case described in https://issues.liferay.com/browse/LPS-145129 without bring the StaleObjectStateException up again.

Let me know if you have any doubts about the fix.

Thanks in advance!

**Comment by crodriguezy** [comment]
Hi @liferay-appsec , did you have the time to review the changes?

Thanks

**Comment by stian-sigvartsen** [comment]
Hi @crodriguezy . We haven't yet, but hopefully today.

**Comment by crodriguezy** [comment]
Hey @stian-sigvartsen , any updates about this? I keep asking because the customer is using the fix as workaround for the moment, and if you see any potential problem with it I should warn them.

Thanks! :)

**Comment by stian-sigvartsen** [comment]
Hi @crodriguezy. Thanks for that fix and the very helpful description of reproduction steps & groovy script!
The only tweak I made is to handle plain text passwords using the current logic. Otherwise `Encrypter` implementations might have difficulty parsing data from such passwords. Do you think that will be ok?

Please see liferay-appsec/liferay-portal/pull/549

**Comment by crodriguezy** [comment]
Hi @stian-sigvartsen ,
Sorry, I supposed the encryptors would still manage plain passwords properly by invoking that method. Your change makes total sense for me.
Thanks for reviewing it!

**Comment by stian-sigvartsen** [comment]
Your original approach might be perfectly fine also. I just went for this defensive approach because `Encryptor` is SPI and 3rd parties implementing it might not take such care. Thanks for reviewing my tweak :)

**Pull request closed without merging**
