### PR TITLE
LPD-33706 Use of library with known vulnerability: cxf 3.4.10

### PR DESCRIPTION
**Pull request by alvarosaugarlr**

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by riccardo-alberti** [comment]
ci:test:playwright

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by jgarcialr** [comment]
closing as #1916 was forwarded

**Pull request closed without merging**
