### PR TITLE
LRQA-84189 Login fix

### PR DESCRIPTION
**Pull request by martonakarczub**
[LRQA-84189](https://liferay.atlassian.net/browse/LRQA-84189)

### CODE REVIEW

**Comment by martonakarczub** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
@martonakarczub Could you please fix the SF issues thank you!

**Comment by martonakarczub** [comment]
ci:test:security

**Comment by martonakarczub** [comment]
ci:test:security

**Comment by martonakarczub** [comment]
ci:test:sf

**Comment by martonakarczub** [comment]
ci:test:security

**Review by gaborlovasdotcom — APPROVED** [review]

**Pull request closed without merging**
