### PR TITLE
LPD-16002

### PR DESCRIPTION
**Pull request by daiazius**
Hi, this solution is doing 2 things: 1) Adding a new check in `AuditPortlet` that prevents users from changing the URL of the page to see an audit event from another company and 2) Also check in the service layer if the companyId passed in the parameters of the remote APIs is of the same company of the user that is requesting them.

The new behavior with those changes is that no user can access other company's audit events through the portlet by manually changing the URL. And for the Audit API endpoints, prevent users getting events from other companies unless they're admins from the default company (Omni Admins). This is due to the logic in `permissionChecker.isCompanyAdmin(long companyId)` as this method always returns true if the user is an Omni Admin. This is acceptable because an Omni Admin user already has access to another company's Audit through the On-Demand Admin functionality for example.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
Relevant failures not related

**Comment by cdbm** [comment]
Looks good to me

**Comment by daiazius** [comment]
ci:forward:force

**Pull request closed without merging**
