### PR TITLE
LPS-115732 CORS for developers

### PR DESCRIPTION
**Pull request by martamedio**
Hey @csierra 

Could you please take a look 👀 ? 
Feel free to change anything you might consider.

Thanks!

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
hey @stian-sigvartsen, would you say this is accurate use of CSRF term? https://github.com/liferay-appsec/liferay-portal/pull/159/commits/346d9bc53d356c30862cad378dba54fdd6252e35

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
"test"

**Comment by csierra** [comment]
"test"

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
test comment

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:stop

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
