### PR TITLE
LPS-197701

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPS-197701](https://liferay.atlassian.net/browse/LPS-197701)

I've included all the group types as well as one additional one for the "User" group type.  This is included as an additional commit, and can be easily dropped if needed.

I do have quite a few follow-up questions though:

1. Are we only concerned with the inherited User Group pages viewable on the User sites, or **do we also care about "User Group" groups themselves**?  This is group.isUserGroup() condition, and will return `true` when Admins are adjusting the page template for the "User Group" site pages.  I have not added this functionality to the current PR, but I can with relative ease.
2. Should we treat Page Templates and Site Templates similarly to User Group inherited pages?  Basically, if a user visits a normal site which uses one of these templates, what should be added to the header?
3. Are we concerned with **staging vs live groups**, or just staged in general?
4. Are we concerned **with control panel PAGES, or just the control panel GROUP**?  For example, `InstanceSettingsPortlet` pages actually belong to the default site, so they would match option `1`, `Site Open`.  However these pages aren't accessible by normal users, only admins, and they have "control_panel" in the URL.  Whereas the control panel GROUP only has a few access points, like `LicenceManager`.
5. **I've added an additional option, 10x, for the "User" group type** (not to be confused with "User Groups" group type).  These are Public pages of the user site, similar to User Personal pages (these are private).  Should we include this option, or lump together all "User" group types (public and private) into one type?  IF we do include this option, should I leave it as "10x", or would a different number be better?  ("5ax" and "5bx", just "5x" and shift all others up, etc).
6. **Should only the "best matching" group type be added to the header, or all applicable types**?  For example, should a "private" "child" site only add "2x" to the header, or should it also add "3"?

Please let me know the answers to the following questions, or any other code feedback, and I will make the necessary changes.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
I've updated the solution with the following changes:
1. GroupTypeId generated is for all matching group types.  For example, a live-staging child site page derived from a page template will have the groupTypeId "2x, 3x, 8x, 1".
2. Basic site type is now dependent on the group being an actual site.  If it's not a site, "4" is used, however this can be removed if needed.
3. Control panel pages and pages derived from page templates are also included, instead of just the groups themselves.  The way to differentiate between the two will be the "site" type (1-3 and 5 when related to a specific site, 4 when accessing through the control panel group).

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @ChrisKian ! LGTM.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:stop

**Pull request closed without merging**
