### PR TITLE
LPS-118649 Add optimized impls

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hey @csierra,
The commit ticket is not quite right.. It's 118649

**Comment by csierra** [comment]
oops... thx!

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
