### PR TITLE
LPS-185213 Utilize Simple CAPTCHA via Headless API

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi team,
This PR is linked to this: https://liferay.atlassian.net/browse/LPS-185213

Summary, in this PR we implement a Headless API to generate SimpleCaptcha for the usage of validating form, etc. Users can switch choosing between this new SimpleCaptcha Headless API or the old one by configuration which is enable/disable by feature flag.

Please review and leave your comment.
Thanks,
Quan
cc @locpham97 @tototrinh

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by ces-quanhuynh** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by locpham97** [comment]
ci:test:relevant

**Comment by locpham97** [comment]
ci:test:security

**Comment by locpham97** [comment]
ci:test:stable

**Comment by locpham97** [comment]
ci:test:relevant

**Comment by locpham97** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
Close the pr. It was reviewed on the [pr](https://github.com/pei-jung/liferay-portal/pull/864)

**Comment by locpham97** [comment]
Hi @alvarosaugarlr ,
I rebased the code to follow the guide for Pei-jung. However, I found a bug related to using the captcha headless API with the captcha tag. The session called from the headless API is an IsolatedHttpSession, which cannot be validated by the captcha tag.
Do you have any recommendation to handle with this case ?
The cause is from LPS-176173

**Pull request closed without merging**
