### PR TITLE
LPS-193052 Semantic versioning

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-193052](https://liferay.atlassian.net/browse/LPS-193052)

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
@alvarosaugarlr I think this PR is no longer needed. If you think different, let's reopen

**Pull request closed without merging**
