### PR TITLE
[7.4-only] LPS-122191 Removes unnecessary FlashMagicBytes checks

### PR DESCRIPTION
**Pull request by jbalsas**
Based on the analysis done at [Analyze security relevance of FlashMagicBytes check](https://issues.liferay.com/browse/LPS-121737):

> DXP uses a FlashMagicBytesUtil to check verify if some files are Adobe Flash movies (regardless of their extension). This was added for securtiy reasons to protect from CSRF attack using uploaded flash files

From @topolik:

> [...] this would be relevant as long as we support browsers that supports flash. Once all supported browsers discard flash we can remove. Thanks.

All browsers in our possible compatibility matrix for 7.4 will have dropped Flash by the time we release as per their roadmaps:
* **[Chrome](https://www.chromium.org/flash-roadmap#TOC-Flash-Player-blocked-as-out-of-date-Target:-All-Chrome-versions---Jan-2021-)**: Flash Player blocked as "out of date" (Target: All Chrome versions - Jan 2021) 
* **[Firefox](https://developer.mozilla.org/en-US/docs/Plugins/Roadmap)**: In January 2021, Firefox 85 will completely remove Flash support. Adobe will stop shipping security updates for Flash at the end of 2020.
* **[Safari](https://www.techspot.com/news/83681-apple-completely-remove-flash-support-next-version-safari.html)**: Apple just released the latest Safari Technology preview. It comes with many changes, most notably the removal of support for Adobe Flash.

Based on this, I think it's safe to remove the `FlashMagicBytes` checks.

**The solution:**
- `FlashMagicBytesUtil` uses a `PushbackInputStream` to read the first bytes of an `InputStream` and then simply rewinds it and provides means to access it. That means that when removing the usage, we can simply use the original `InputStream` to keep the same behaviour.
- To avoid a major kernel breaking change, we're simply deprecating both `FlashMagicBytesUtil` and `FlashMagicBytesUtilTest` instead of deleting them.

PS: I've added an additional commit fixing a wrong deprecation notice I myself pushed yesterday 🙏

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
PS: I'll be on PTO until next monday, so feel free to push this forward (or amend it as necessary).

**Comment by jbalsas** [comment]
Hey @adolfopa, could you or anyone from @liferay-lima help me decode the failing test?

In the past, `FlashMagicBytesUtil` used a `PushbackInputStream` to read the first bytes of an InputStream and then simply rewind it. In here we should be simply removing that intermediate step, so my feeling is that either something in D&M (or the tests) depended on this or was making wrong assertions? 

I'll try to pinpoint the issue, but I would appreciate any help on your side.

Thanks!

**Comment by jbalsas** [comment]
Hey @csierra, @liferay-appsec, I sent this here for security validation. Could you take a look regardless of CI state based on security considerations?

If all is good with you I can route this through other teams for final approval.

Thanks!

**Comment by adolfopa** [comment]
@jbalsas The ServletResponseUtil._copyRange method makes a lot of assumptions about the input stream. My guess is that previously it was running the fallback case, but now the input stream is of a different kind (probably an array backed input stream).

Can you rerunning the test with different wrappers? If that nasty conditional logic is the problem, wrapping it in a BufferedInputStream should give you the old results.

**Comment by jbalsas** [comment]
Hey @adolfopa, that might be a reason, but it doesn't really add up.

Previously, we were simply passing down the `inputStream`. Our `FlashMacigBytes` was simply creating a temporary `PushbackInptStream` but the `getInputStream` method always returned the original `InputStream`, so types shouldn't have changed here.

See https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/flash/FlashMagicBytesUtil.java#L52

How should I run these tests? `gradlew testIntegration` from `document-library-test`? I tried earlier but it catastrophically failed 😭

**Comment by jbalsas** [comment]
Going to retest again, just to verify this is a valid test failure

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I'm looking at this error :point_up:

**Comment by csierra** [comment]
hey @jbalsas, unless @topolik corrects me, it looks we are good with this :+1:

**Comment by izaera** [comment]
I think the PR doesn't break anything, it simply makes execution flow pass through places it never visited before because `FlashMagicBytesUtil` was converting all types of `InputStream`s to `PushBackInputStream`s, so [this method](https://github.com/liferay/liferay-portal/blob/3cbc7b6f8c0b5fa02eb01107d31e65645f55bf65/portal-kernel/src/com/liferay/portal/kernel/servlet/ServletResponseUtil.java#L565) was never entering to any of the `if`s (which contain the incorrect code).

I.e: that method was always executing [this code](https://github.com/liferay/liferay-portal/blob/3cbc7b6f8c0b5fa02eb01107d31e65645f55bf65/portal-kernel/src/com/liferay/portal/kernel/servlet/ServletResponseUtil.java#L622-L633), whereas, when removing `FlashMagicBytesUtil`, the failing test was running [the second if](https://github.com/liferay/liferay-portal/blob/3cbc7b6f8c0b5fa02eb01107d31e65645f55bf65/portal-kernel/src/com/liferay/portal/kernel/servlet/ServletResponseUtil.java#L589-L603).

@csierra No you are not. It is failing CI :sweat_smile: . I'm fixing it.

**Comment by izaera** [comment]
I will try to push the fix tomorrow (if I can, because we are in the middle of the Spanish Symposium). If not, it will be delayed to next Monday (I hope not).

If any other one wants to continue with this, it should be easy to fix, I guess.... This is the [key](https://github.com/liferay-appsec/liferay-portal/pull/143#issuecomment-713662990)

**Comment by izaera** [comment]
The code causing the currently wrong behavior was introduced in [LPS-22759](https://issues.liferay.com/browse/LPS-22759).

**Comment by izaera** [comment]
I assume the code was not wrong from the very beginning, so I think that the issue is due to someone having played with the `start` variable and without having updated the code that transfers `FileChannel`s. I will try to find out if that is the case...

A trivial solution to this issue would be stop using `FileChannel`s. They were probably introduced for performance reasons, but the fact is that we were not using them since Flash support was added (because of `FlashMagicBytesUtil`) and nobody has complained so I guess it wasn't such a big optimization :thinking: .

**Comment by izaera** [comment]
I have forwarded this PR to Shuyang because the fix for the CI error requires a major version increase in `portal-kernel`. The new PR is at https://github.com/shuyangzhou/liferay-portal/pull/9531.

I'm closing this now, we'll resend a new one as needed.

**Comment by izaera** [comment]
ci:close

**Comment by topolik** [comment]
Thanks @izaera

**Pull request closed without merging**
