### PR TITLE
LPS-156599

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-156599](https://issues.liferay.com/browse/LPS-156599)

See prior discussion on [PTR-3201](https://issues.liferay.com/browse/PTR-3201) regarding this fix.

Re-sent from https://github.com/liferay-appsec/liferay-portal/pull/803

I've renamed the `portal-security-ldap-impl` module to `portal-security-ldap-service` per the discussion on the Slack thread here: https://liferay.slack.com/archives/C1SJ64S9X/p1660231687320169

### CODE REVIEW

**Comment by mbowerman** [comment]
Hi @stian-sigvartsen,

I've just force-pushed additional changes to the upgrade based on further discussion that I had with Alberto in [this Slack thread](https://liferay.slack.com/archives/CUQP9C673/p1660585699337189). They look perfect in my testing (I've tested both cases: (1) Upgrading from an earlier 7.4 to a later 7.4, and (2) Upgrading from 7.2 to 7.4).

I've asked Alberto to review my upgrade-related changes as well, but I see he is OOO until Friday so I am not sure when he will be able to review them.

**Comment by stian-sigvartsen** [comment]
Hey @mbowerman . The rename of the portal-security-ldap-impl module to portal-security-ldap-service might cause some backporting challenges? At least it is unusual, I think.

I can see LPS-156243 and LPS-142044 are requested for 7.3 already.

I can see the SF split package reason why you did it on the Slack thread. Have you considered following the SAML modules example ? See [`saml-impl` & `saml-persistence-service`](https://github.com/liferay/liferay-portal/tree/87c5941d706534a30f50e73264804aacaa7d6a41/modules/dxp/apps/saml) co-existing with ModelListeners etc.

**Comment by mbowerman** [comment]
Hi @stian-sigvartsen,

Thanks for the suggestion. I'll try it by creating a new `portal-security-ldap-persistence-service` module, along with a new `portal-security-ldap-persistence-api` and `portal-security-ldap-persistence-test` module. Please be patient as it may take me a few days to complete this.

**Comment by mbowerman** [comment]
Hi @stian-sigvartsen,

I've applied your suggested change and re-sent the pull request at https://github.com/liferay-appsec/liferay-portal/pull/819

**Pull request closed without merging**
