### PR TITLE
[TS] LPS-166489

### PR DESCRIPTION
**Pull request by istvansajtos**
Dear Team,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/867.

These commits are patching cxf-rt-rs-json-basic. The patched library is required only for maintenance branches 7.3.x and below where bumping cxf version is not possible. Please see related PTR ticket for more info on this.

As soon as the patched library is available in Nexus repository, I will send "backport" PR for 7.3.x that uses this lib.

Thank you,
Istvan

cc @stian-sigvartsen

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . This looks good, thanks for persevering with the issue!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
