### PR TITLE
LPD-34165 Fix Login#TokenBasedSSOSmoke

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPD-34165](https://liferay.atlassian.net/browse/LPD-34165)

Saving the configuration after the reset step seems to have fixed this test's flakyness.

### CODE REVIEW

**Comment by manuelecastro** [comment]
#### Test is passing.
see: [Testray result](https://testray.liferay.com/#/project/35392/routines/45357/build/38348010/case-result/38350222)

**Comment by jgarcialr** [comment]
Hi @manuelecastro ,
Could you test in local if changing the line 5 in build-test-token-based-sso.xml
from
`                       <arg line="-H SM_USER:${user.token} ${portal.url}" />
`
to
`                       <arg line="-H 'SM_USER:${user.token}' ${portal.url}" />
`

make the test pass without adding this SaveConfiguration?

This should fix https://liferay.atlassian.net/browse/LPD-38356 related to TokenBasedSSO as well

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
passed test:
imagen

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:report:39401746

**Review by stian-sigvartsen — APPROVED** [review]
LGTM. But we need to wait on CI before forwarding.

**Comment by manuelecastro** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:report:42796790

**Comment by stian-sigvartsen** [comment]
Just checking one thing before forwarding.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
