### PR TITLE
Lps 138428 depcreate digest authen

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hey @arthurchan35 . Just checking that this PR isn't waiting on me?
Did you have a chance to check why the DigestAuthenticationAuthVerifier isn't executing for WEBDAV?

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
I checked the other day, Auth Verifier flow was not triggered when downloading file using webdav link as you described.

**Pull request closed without merging**
