### PR TITLE
LPS-169367 Fix OAuthClientEntry exists with the primary key 0

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team!

Could you plesae check my fix?

**Summary:**
Whenever an OIDC login is initiated, there is an error appearing in Liferay log: Unable to process the OpenID Connect login: No OAuthClientEntry exists with the primary key 0

**Fix:**
Check if oAuthClientEntryId  is not zero

https://issues.liferay.com/browse/LPS-169367

Thanks, Roland

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
@rolandpakai looks reasonable to me.


Please go ahead and manually forward it if ci fails for unrelated faliures

**Comment by arthurchan35** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Forwarded to https://github.com/liferay-appsec/liferay-portal/pull/924

**Pull request closed without merging**
