### PR TITLE
LPD-15723

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-appsec/liferay-portal/pull/1653

Original message:

> Resent from https://github.com/ChrisKian/liferay-portal/pull/323 with https://github.com/brianchandotcom/liferay-portal/pull/147670#issuecomment-1971026475 added.
> 
> See diff here: https://github.com/liferay-appsec/liferay-portal/compare/f7d91c391be6c8e8c1aca55b3692f05aa414717d...9a09b8558814f96ffdcb28cfae38336aaf89af25

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
I retriggered the stable suite to take advantage of the low CI load at this time. But looking at the failures now, @ChrisKian it looks like the SB classes may need to be regenerated following a rebase.

**Comment by ChrisKian** [comment]
Resent: https://github.com/liferay-appsec/liferay-portal/pull/1658

**Pull request closed without merging**
