### PR TITLE
LPS-190192 XSS with Service Class in edit Service Access Policy

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-190192](https://liferay.atlassian.net/browse/LPS-190192)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @manuelecastro ! Because we are escaping an attribute here (AUI will pass it through to the HTML), we need to use escapeAttribute() . Please see liferay-appsec/liferay-portal/pull/1248

**Comment by manuelecastro** [comment]
Thanks for the review @stian-sigvartsen ! I'll check that out!

**Pull request closed without merging**
