### PR TITLE
LPS-133178 SAML Fix user UUID field updating

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
The problem is a misalignment with how `UserProcessor` prepares the call to `UpdateFunction`, which is provided by the call to `UserProcessorContext.bind(...)`.

The `UpdateFunction` is called with a `currentUser` and `newUser`. The difference between the two is patching by applying the mappings that are registered by invocations on the `UserBind` object returned by aforementioned `bind(...)` .

There are no such invocations so `currentUser` and `newUser` are equal!

So the fix is to swap `currentUser` with the currently persisted user. This is because the whole reason for this `UpdateFunction` invocation is to do a single User persistence call after all `UserFieldExpressionHandler`s have done their patching. That is why it is provided with `Integer.MAX_VALUE` as the `processingIndex`. 

@martamedio

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
