### PR TITLE
LPD-29195

### PR DESCRIPTION
**Pull request by ChrisKian**
Initial PR, mostly for CI testing

Previous ticket flaky test fixtures: https://liferay.atlassian.net/browse/LPD-30298
Epic: https://liferay.atlassian.net/browse/LPD-29195
Resolves test fix: https://liferay.atlassian.net/browse/LPD-25307

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
Looks like playwright tests are passing in CI

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Looks good @ChrisKian ! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@ChrisKian I closed the PR to Brian because I found that some of the commits are keyed to the epic. I will let you review before we forward again.

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,
I've renamed the commits, so general playwright commits are under LPD-30298 (ticket titled "Write Playwright Macros for SAML general configuration"), and commits specific to a test are under LPD-25307 (ticket titled "Fix SAMLPortlet#addIdentityProviderConnectionCustomFieldAttributeMappingWithCustomAttributes macro, as it leads to three test failures").

I wasn't sure which to place the final commit under, as it removes one related and one unrelated poshi test.  I just left it under LPD-25307, as I believe we may be splitting hairs.

Please let me know if I should rename them to something else, thanks!

**Comment by stian-sigvartsen** [comment]
Looks good now @ChrisKian . I've manually forwarded to brianchandotcom/liferay-portal/pull/153111

**Pull request closed without merging**
