### PR TITLE
LPD-33706 commerce tests

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
Motivation: #1894 (comment)
and  problems in Commerce's team tests (rebased https://github.com/liferay-appsec/liferay-portal/pull/1914).

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by jgarcialr** [comment]
ci:report:74429802

**Comment by smottal** [comment]
Hey @jgarcialr , the failing test are unrelated to the changes

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
@jgarcialr force-pushed a rebase so I will forward once CI gives the all clear

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by jgarcialr** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
There was a rebase error so we are re-forwarding this

**Comment by jgarcialr** [comment]
ci:forward:force

**Pull request closed without merging**
