### PR TITLE
LPD-6869 6870 6871 playwright tests

### PR DESCRIPTION
**Pull request by istvansajtos**
Playwright tests for [LPD-6869](https://liferay.atlassian.net/browse/LPD-6869), [LPD-6870](https://liferay.atlassian.net/browse/LPD-6870) and [LPD-6871](https://liferay.atlassian.net/browse/LPD-6871).

cc @zsigmondrab

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:stop:relevant

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:playwright

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:help

**Comment by istvansajtos** [comment]
ci:stop:playwright

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:playwright

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:forward

**Pull request closed without merging**
