### PR TITLE
LPS-158385 the role is added to the user when the issuer is the same that is defined in property

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-158385](https://issues.liferay.com/browse/LPS-158385)

### Changes
In the _getRoleIds method (OpenIdConnectUserInfoProcessorImpl) the condition is modified, so that if the issuer is not equal to the one defined in the properties, the role is not assigned to the user.

### Manual test
The steps indicated in the ticket have been followed (and the opposite case to validate the code).

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
@gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
All the failures of ci:test:security are the same with daily run.
All the failures of ci:test:relevant should be fluke issues.
Working on validate the fix on local.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
Test steps:

1. Set the following properties in portal-ext.properties:
open.id.connect.user.info.processor.impl.issuer=https://dev-5081331.okta.com/
open.id.connect.user.info.processor.impl.regular.role=Power User
2. Start up portal
3. Navigate to OAuth Client Administration
4. Add a configuration entry as above.
5. Enable OIDC
6. Login with OpenID Connect with oktauser@liferay.com
7. Navigate to account setting

Actual result: The Power User role isn't assigned to oktauser.

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
See https://github.com/liferay-appsec/liferay-portal/pull/768

**Pull request closed without merging**
