### PR TITLE
LPD-36145 Do not add leading period to cookie domains

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-36145](https://liferay.atlassian.net/browse/LPD-36145)

When calling [CookiesManagerImpl.getDomain](https://github.com/liferay/liferay-portal/blob/master/modules/apps/cookies/cookies-impl/src/main/java/com/liferay/cookies/internal/manager/CookiesManagerImpl.java#L319) the domain is prepended by a period. This was previously the correct convention in order to allow access to subdomains but now is no longer necessary. Now if a domain is specified, then subdomains are always included.

see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#domaindomain-value

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Updated tests are passing: https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773484/testReport/com.liferay.cookies.internal.manager/CookiesDomainTest/

**Review by ChrisKian — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
Thanks @manuelecastro @ChrisKian !

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
