### PR TITLE
LPD-38916 Move JSONWebServiceClient tests to App Sec team

### PR DESCRIPTION
**Pull request by julschong**
Hi Team,

This is for issue: https://liferay.atlassian.net/browse/LPD-38916
Same kind of issue as https://github.com/liferay-appsec/liferay-portal/pull/2020

This PR adds a test.properties file to `portal-json-web-service-client` module to categorize the tests to `Security` component.

I have also investigated the test failure in `JSONWebServiceClientImplSSLGetTest`, see the ticket for details. But basically, jdk dropped support for TLSv1 and TLSv1.1 but test tries to use them. This can be found in `Java_HOME/jre/lib/security/java.security` `jdk.tls.disabledAlgorithms=`

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by julschong** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:56656043

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
Thanks @julschong !

@manuelecastro please can you integrate Julius' analysis into new/existing daily quality analysis tasks?

**Pull request closed without merging**
