### PR TITLE
LPS-123038 Ask for CertificateStatus only if EntityID it's present

### PR DESCRIPTION
**Pull request by martamedio**
Hey @stian-sigvartsen, could you please take a look? 👀 

Thanks!

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hey @martamedio . I think we should try to isolate the web module from the implementation detail that the entity ID has to be configured before resolution of the certificates can succeed.

It's not perfect because general.jsp will still check if entityId is set before rendering the sections, but if that check was removed, updating the certificate will result in an exception from the backend so validation logic is in the right place nevertheless.

I'm not 100% convinced by my solution because it make the KeyStoreCredentialResolver.getLocalEntityCertificate() method less useful by not throwing the exception anymore. Let me spend a bit more time on it...

**Comment by stian-sigvartsen** [comment]
@martamedio I've pushed another commit that brings back visibility through exception throwing. The saml-web module was already inspecting the `SamlException` received so I expanded on that. The code might benefit from a bit of refactoring/simplification. Thoughts?

**Comment by martamedio** [comment]
Hey @stian-sigvartsen 

Your solution is much more elegant :necktie:
I've given some thought to the code on `GeneralTabDefaultViewDisplayContext` but I don't see a way to refactor it that is more readable than what we already have... 😅

**Comment by stian-sigvartsen** [comment]
@martamedio I've pushed another commit. Small oversight. 
As discussed offline, we should consider sending both solutions together.

**Comment by csierra** [comment]
hey @martamedio, @stian-sigvartsen, 

what the status on this one? anything we need to do to push this ahead?

**Comment by martamedio** [comment]
@csierra I was just re-organising our commits, I think it's ready to go

cc/ @stian-sigvartsen

**Comment by martamedio** [comment]
ci:forward

**Comment by csierra** [comment]
hey @martamedio @stian-sigvartsen , are these test failures real? I think I have seen them in another pull as well...

**Comment by stian-sigvartsen** [comment]
I think that looks environmental and unrelated to the changes

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:reevaluate:1032004_9002

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
