### PR TITLE
LPD-6757 (LPS-201376) - SCIM notifications

### PR DESCRIPTION
**Pull request by alvarosaugarlr**

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
Needed rebasing. Next PR: liferay-appsec/liferay-portal/pull/1958

**Pull request closed without merging**
