### PR TITLE
LPS-123218 Make DefaultUserResolver methods private

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
/cc @martamedio

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
