### PR TITLE
LPD-35470

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-35470

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:scim

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
Hi @daiazius . This PR needs a rebase. Please resend.

**Comment by stian-sigvartsen** [comment]
We have decided to add this test coverage as an integration test.

**Pull request closed without merging**
