### PR TITLE
LPS-145190 OAuth 2 JWT Grant (with disabled release flag) + upgrade process

### PR DESCRIPTION
**Pull request by liferay-appsec**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1307401_2115

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@arthurchan35 that LocalFile.OAuth2#GrantedAuthorizationsCanBeRevoked test appears to be flaky (it failed and then passed on the previous PR also), but it appears to be repeatedly failing now :/

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant:nocompile

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant:nocompile

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
