### PR TITLE
LPS-200600 Update Interface

### PR DESCRIPTION
**Pull request by kevenleone**
Hey guys, can you help me reviewing and move this PR forward?

Here's the context: https://github.com/liferay-frontend/liferay-portal/pull/3797

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:liferay-samples-workspace

**Comment by kevenleone** [comment]
ci:help

**Comment by kevenleone** [comment]
ci:test:liferay-sample-workspace

**Comment by marianahuggins** [comment]
Hi @liferay-appsec could you please prioritize this review? thank you :)

**Review by oliverkecskemety — APPROVED** [review]

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
