### PR TITLE
[TS] LPS-143783 Handle all type of exceptions thrown during the decryption…

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-143783](https://issues.liferay.com/browse/LPS-143783)
Hi AppSec Team,

I am sending this to you for review as discussed with @stian-sigvartsen. It's a small improvement to [LPS-135724](https://issues.liferay.com/browse/LPS-135724) ensuring that all type of exceptions are handled when decrypting the user ID. The same is done in PortalImpl: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7675-L7695

Please let me know if you have any concerns or questions.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
I've fixed the SF issue. Sorry for that.

**Comment by oliverkecskemety** [comment]
@istvansajtos It looks good to me. [LPS-136609](https://issues.liferay.com/browse/LPS-136609) will probably change the thrown exception from unchecked StringIndexOutOfBoundsException to something else but this solution will handle that as well.

**Comment by oliverkecskemety** [comment]
ci:forward

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:forward

**Pull request closed without merging**
