### PR TITLE
LPD-1245

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPD-1245](https://liferay.atlassian.net/browse/LPD-1245)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . Please can you review this one?

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
Looks like [PortalSmoke#Smoke](https://testray.liferay.com/home/-/testray/case_results/2540838888?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2540838437%26testrayRunId%3D2540838602%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and [PortalLogAssertorTest-functional-smoke-tomcat90-mysql57-jdk8_stable/0/0](https://testray.liferay.com/home/-/testray/case_results/2540838653?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2540838437%26testrayRunId%3D2540838554%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) were both affected by the code change.

The tests do an attempt to a redirect, but since the code now is blocking any redirect from domains other then "localhost", they are not able to proceed. If we decide to keep the code like this, I believe we'll need to adjust those poshi tests.

**Comment by manuelecastro** [comment]
While checking the security build, I also found a lot of tests that failed due to the code changes. These changes will definitely break any poshi test that does a redirect to other domains.

**Comment by istvansajtos** [comment]
@manuelecastro , you are right, we are breaking many tests with this change. We should prevent that by either finding a proper configuration or updating the redirect validation logic in PortalImpl.

**Comment by manuelecastro** [comment]
Hey @istvansajtos ! 

I sent a new PR [here](https://github.com/liferay-appsec/liferay-portal/pull/1699) with the changes you made and started testing it. :)

**Pull request closed without merging**
