### PR TITLE
LPD-37452

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-37452

Hey @cdbm, I made a couple changes, nothing drastic, but I'd still like for you to review them and understand why the changes are there.
Also, I'm having trouble running the upgradeProcess test.  I'd like for it to be ran against a DB without the expandoTable or expandoColumn for the User and UserGroup entries.  If the upgrade process test runs first, it will throw a NPE without my changes.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:scim

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
All upgrade failures are either related to DB partitioning or this error:
`Portal log assert failure, see above log for more information:  No theme found for specified theme id classic_WAR_classictheme. Returning the default theme.`

So upgrade failures are unrelated.

[New upgrade process test is passing](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1237453/testReport/com.liferay.scim.rest.internal.upgrade.v0_0_1.test/UserManagerUpdateExpandoColumnUpgradeProcessTest/).

[All playwright tests (and new ones) are passing](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431345/testReport/scim-configuration-web_scim.spec/ts/).

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:scim

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
After confirming with @cdbm the new changes (except for one) were working properly and tests are passing, this has passed our review.  Assigning to @stian-sigvartsen for final AppSec review.

**Comment by stian-sigvartsen** [comment]
In my local testing, 
`PasswordEncryptorUtil#encrypt(String, String)` is failing to authenticate the user via the BasicAuthHeaderAuthVerifier , causing the upgrade test to fail. I think can deal with that separately if it is not a local environment issue only.

**Review by stian-sigvartsen — COMMENTED** [review]
This PR needed a considerable amount of source formatting to meet our conventions, but the runtime change looks good. I made the changes, please see liferay-appsec/liferay-portal/pull/2050

**Pull request closed without merging**
