### PR TITLE
LPS-168771 - Migrate Role Permission Navigation to Clay Vertical Nav (With Final Changes For Brian)

### PR DESCRIPTION
**Pull request by ethib137**
@drewbrokke, @stian-sigvartsen As per Brian's request this makes the ClayVerticalNavItem an internal class and renames it to NavigationItem.

https://issues.liferay.com/browse/LPS-168771

This PR seeks to solve accessibility issues that relate to the Role Permissions Navigation. Initially we wanted to only update the markup in the jsp, but this resulted in more complexity trying to keep the javascript working that depended on the old markup. As a result it made more sense to move towards the best option of using the Clay Vertical Nav component directly.

What has changed:

Due to it being React, there is a slight lag and the navigation loads slightly after the page.
The old behavior had all panels open when filtering and all panels close when the filter input is emptied. This is currently not possible with the Clay component. All panels now open when filtering and when done filtering it reverts back to the initial state when loaded. This makes more sense to me than closing all the panels after filtering.
There is an existing bug with the Clay Vertical Nav that causes some children to overlap when multiple levels deep. This will be fixed https://github.com/liferay/clay/issues/5513. Fixed
At some point the persistence after refresh of the currently selected item was lost. This PR adds that functionality back.
Since this is a larger rewrite I'm asking for additional testing by @john-co to make sure we don't have any regressions.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reevaluate:1277401_8733

**Review by drewbrokke — APPROVED** [review]
Looks good. The last couple of commits match Brian's preferences from our DM conversation:
- Implementation is fine
- Match the class name of what is found in clay already (e.g. [NavigtaionItem](https://github.com/drewbrokke/liferay-portal/tree/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/util/NavigationItem.java) in `frontend-taglib-clay`
- Make it an inner class of the DisplayContext since the class itself is an implementation detail.

**Comment by stian-sigvartsen** [comment]
Thanks @drewbrokke !
Thanks @ethib137 , will you follow up?

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @stian-sigvartsen, yeah, if you have no objections, I'll have our QA double check that any failing tests are unrelated and then I'll forward it to Brian.

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Hey @ethib137, I've analyzed the failures and they look unrelated to your pull request. 🎉 

[compare case matrix](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687178282507&testrayRunIdA=2353392589&testrayRunIdB=2354354743)

[testray-results.csv](https://github.com/liferay-appsec/liferay-portal/files/11788367/testray-results.3.csv)

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/136582

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
ci:test:relevant

**Pull request closed without merging**
