### PR TITLE
LPS-191052 Add option to configure SCIM client via a config file - 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
Manually forwarded as it is very low risk and urgent. Please see brianchandotcom/liferay-portal/pull/141714

**Comment by zsigmondrab** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/141714

**Pull request closed without merging**
