### PR TITLE
LPS-126600 Archive CAS (8) 

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@stian-sigvartsen I verified the upgrade test failure is a known issue, [LPS-138315](https://issues.liferay.com/browse/LPS-138315). If there are no other failures, please manually forward to Brian Chan.

**Comment by stian-sigvartsen** [comment]
Thanks @jpince !

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
