### PR TITLE
LPS-204744

### PR DESCRIPTION
**Pull request by Mikellorza**
bug: https://liferay.atlassian.net/browse/LPS-204744

Description
-----------
We are getting an error when we want to impersonate a user and create a web content with all required permissions. The problem is that we are checking in the AuthVerifierPipeline class, if the user has his email address verification complete and if his password is reset, without taking into account if the user is impersonated or not. We have many customer or even our company that we have some users to test some functionalities, and for that reason we have to exclude those conditions if we are impersonating a user.  So, with this PR we are excluding both conditions if we are impersonating a user. 

For more info see this comment: https://liferay.atlassian.net/browse/LPS-204744?focusedCommentId=2547683

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @Mikellorza . Thanks for your PR!
This fix is bypassing the protection that was put in place to avoid `AuthVerifier` authenticated requests to have access to the portal session user as identified by the session cookie. Because it is unwrapping the `HttpServletRequest`.

It would also not be ideal to add impersonation handling logic elsewhere than in `PortalImpl#getUser` .

@ChrisKian has recent experience with requirements to dispatch to remote API into web requests so I've asked him to review this PR. 

Chris, please can you review with keeping the above in mind. There is another PR very similar to this which is idle whilst we consider how appropriate it is to handle doAsUserId in remote API. Can you review them together? Please see liferay-appsec/liferay-portal/pull/1014

That PR solves the particular issues I highlighted above.

**Comment by ChrisKian** [comment]
I will try to review these issues tomorrow

**Comment by ChrisKian** [comment]
I am able to confirm the solution for LPS-176182 does resolve it's own issue, however I am blocked from testing LPS-204744.  I'll have more updates tomorrow.

**Comment by ChrisKian** [comment]
Hi @Mikellorza and @stian-sigvartsen,
After testing this issue, I am unable to reproduce in the latest master.  To be clear, I cannot reproducible the issue with or without the inclusion of [this commit](https://github.com/liferay-appsec/liferay-portal/pull/1014/commits/d2fdd14ead167ddd1b2f92de197fb8537d179e6f), and also without the changes from this PR.

@Mikellorza, can you please re-test on the latest master and confirm/deny my results?  Or, if there is some other step I am missing, please let me know.  I followed the steps to reproduce, as well as the video attached to the ticket.  Thanks!

**Comment by Mikellorza** [comment]
Hi mates @ChrisKian @stian-sigvartsen ,

yes I will take a look and I will tell you something. 

thanks !

**Comment by ChrisKian** [comment]
Hey @Mikellorza,
I've assigned the associated LPS-204744/LPD-1476 back to you, and I'll also close this PR while we await your findings.  If you need any help or have questions, please let me know, thanks!

**Comment by Mikellorza** [comment]
Hey mats,

I am still able to reproduce it. I have updated the steps to reproduce it, as you cans see: 

1. Steps to reproduce it:
2. Add a site role with all web content permissions.
3. Create a user, add to Liferay DXP site and add the above site role.
4. Impersonate the above user and go to content management.
5. Verify that you have this property company.security.strangers.verify=true

Please, check this:

https://liferay.atlassian.net/browse/LPD-1476?focusedCommentId=2565132

thanks

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
Thanks @Mikellorza for your updated steps to reproduce.  The important change was the `company.security.strangers.verify=true` property.

As far as the actual issue goes, I'm not sure what the correct business logic should be.  Basically, if we are impersonating a user who has not yet verified their email address, should we be allowed to bypass restrictions since we're an admin user, or should we see what the impersonated user sees and not be able to create the web content?

@stian-sigvartsen, do you have any thoughts on this?  I can see both sides being correct in some ways, so I'd rather understand the desired outcome before creating a solution.  Also, your fix from [the other PR](https://github.com/liferay-appsec/liferay-portal/pull/1014) has no effect on this issue.

**Comment by ChrisKian** [comment]
We have confirmed impersonating a user should bypass certain business restrictions, like email verification.  I will continue investigating this issue.

**Review by ChrisKian — COMMENTED** [review]
Hi @Mikellorza,
I've been able to create a different solution which should still resolve your issues, while also adhering to the guidelines Stian mentioned: https://github.com/liferay-appsec/liferay-portal/pull/1601

@stian-sigvartsen, this is the safest way I could determine if the current user is being properly impersonated.  The `PortalImpl.getUserId()` method isn't helpful in this situation, since it doesn't tell us if the user is actually impersonated.  And the `PortalImpl.getDoAsUserId()` method is `protected`, so I didn't want to completely expose it.  Instead, I created the `PortalImpl.isImpersonated()` method which uses the `getDoAsUserId()` method to validate impersonation, and only returns a boolean value.

Please let me know which approach we should go with, and I will close out the opposite PR, thanks!

**Comment by Mikellorza** [comment]
thanks @ChrisKian for your feedback !

**Comment by stian-sigvartsen** [comment]
Closing this PR because the review continues on liferay-appsec/liferay-portal/pull/1601

**Pull request closed without merging**
