### PR TITLE
LPD-32888 When CAPTCHA validation fails, text is not cleared from Text Validation field

### PR DESCRIPTION
**Pull request by jgarcialr**
https://liferay.atlassian.net/browse/LPD-32888 

Re-add ignoreRequestValue param as it was removed in a prior commit by mistake.

Created playwright test to address this behavior

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:report:49732596

**Comment by jgarcialr** [comment]
ci:report:49732596

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
Playwright test passed:
imagen
imagen

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Thanks @jgarcialr . Looks good!

**Pull request closed without merging**
