### PR TITLE
LPS-121128 - Password reminder string modified

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-121128](https://issues.liferay.com/browse/LPS-121128)

The text in the literals that existed in language.properties has been changed. To give uniformity to the keys, the key of the group literals has also been changed.

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle:nocompile

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
Sent the [pr](https://github.com/brianchandotcom/liferay-portal/pull/123122) to Brian.

**Pull request closed without merging**
