### PR TITLE
Lps 120269

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey @brianchandotcom,
1. 
> Those changes to remove dependencies should have come before the move.

I have moved the commit of remove kernel dependency to the first commit

2. 
using
```
new HashMap<String, String>() {
	{
		put("", "");
	}
}
```
and renaming `Map<String, String> pathToPatternMap` to `Map<String, String> urlPaths`
are both done in that commit.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
