### PR TITLE
Lps 136564 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Review by stian-sigvartsen — COMMENTED** [review]
@arthurchan35 The issues described in the ticket appear to be resolved, nice!
But when I click on the "MUST BE..." links that display a modal, it is often collapsed into a thin line. Can you take a look?

I

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
Where is the MUST BE link?

**Comment by stian-sigvartsen** [comment]
After removing the Bundle PrefixHandlerFactory "Default" configuration entry, this link will appear for most scopes. It's actually labelled "This resource scope MUST be assigned via a global scope"

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen 

Thanks for providing reproduce steps,
after comparing before and after the fix, I think it's a different problem.
To reproduce the issue without the fix, you can **not** refresh the page.
Manually go to OAuth2 Admin, choose analitics cloud and **click** the scope tab.
Here once you click the MUST BE link in Portal Service will also trigger the issue you described.

**Comment by stian-sigvartsen** [comment]
I still wasn't able to reproduce it with your steps, but then I noticed that I've got `javascript.single.page.application.enabled=false` . After setting this to true, I can reproduce the modal issue on master like you described.

So the reason why it becomes reproducible must be because some JS resources are loaded ahead of going to "scopes", by the SPA framework (because the page doesn't refresh when navigating). So it is most likely some kind of page load lifecycle issue.

So we can deal with this separately. Forwarding your commits 👍

**Pull request closed without merging**
