### PR TITLE
Lps 150092 alternative core

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:stop

**Pull request closed without merging**
