### PR TITLE
LDP 6757 Second pr

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
Second pr of [LPD-6757](https://liferay.atlassian.net/browse/LPD-6757)

First pr - https://github.com/liferay-appsec/liferay-portal/pull/1977

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@alvarosaugarlr please can you review [75d7b4b](https://github.com/liferay-appsec/liferay-portal/pull/1984/commits/75d7b4bfa57769399d135e35a5a4ec98efd0ae49) onwards. For the earlier commits I just fixed 2 commit message typos

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:29633654

**Comment by stian-sigvartsen** [comment]
Some commits squashed to liferay-appsec/liferay-portal/pull/1984

**Comment by stian-sigvartsen** [comment]
ci:test:playwright

**Comment by stian-sigvartsen** [comment]
CI results look good

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:30714737

**Comment by stian-sigvartsen** [comment]
ci:report:30754610

**Comment by stian-sigvartsen** [comment]
Manually forwarded brianchandotcom/liferay-portal/pull/154814

**Pull request closed without merging**
