### PR TITLE
LPS-185213

### PR DESCRIPTION
**Pull request by locpham97**
Hi Team,
Please help me review[ this ticket](https://liferay.atlassian.net/browse/LPS-185213).
In this ticket, I made some change follow to https://github.com/brianchandotcom/liferay-portal/pull/141909#issuecomment-1753416957.
cc: @alvarosaugarlr , @ces-quanhuynh

### CODE REVIEW

**Comment by locpham97** [comment]
ci:test

**Comment by JoyceWang08211** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
tested and reviewed. 
About the ci errors, is needed to modify the version of catpcha-api module. Please, check [theses](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/784278/testReport/junit/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_captcha_captcha_api_/) [errors](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/642854/testReport/junit/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_captcha_captcha_api_/).

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by ces-quanhuynh** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
No regression was found.

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
