### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by arthurchan35**
https://issues.liferay.com/browse/LPS-147071
https://issues.liferay.com/browse/LPS-143867

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:mfa

**Comment by arthurchan35** [comment]
ci:test:search

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@gaborlovasdotcom 
I have tested fido2 locally.

**Comment by arthurchan35** [comment]
@bryan.engler

**Comment by arthurchan35** [comment]
Hey @BryanEngler

Per Brian Chan's request, I have also bumped jackson dataformat cbor in elastic search, do you see any problem?

**Comment by arthurchan35** [comment]
ci:test:search

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
fyi: @xbrianlee @lipusz

**Comment by BryanEngler** [comment]
> Hey @BryanEngler
> 
> Per Brian Chan's request, I have also bumped jackson dataformat cbor in elastic search, do you see any problem?

looks good, we do these type of bumps fairly often

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
