### PR TITLE
LPD-26978 Login portlet on utility page renders in maximized windowState via "login prompt"

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-26978](https://liferay.atlassian.net/browse/LPD-26978)

Check if there's an utility page and show the portlet in normal state instead of maximized state

Created new test portlet and integration test in order to covering LoginAction execute method.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:reevaluate:1277401_12101

**Comment by jgarcialr** [comment]
failures seem non-related 
/cc @alvarosaugarlr

**Review by alvarosaugarlr — APPROVED** [review]
Tested and reviewed . Looks good to me

**Pull request closed without merging**
