### PR TITLE
LPS-176074 Add first name to email templates

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPS-176074](https://issues.liferay.com/browse/LPS-176074) Add first name to email templates + the new language key

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Looks great @nikolettabuza ! Because this is a story ticket, our QA will review the code prior to us sending it. I will assign.

**Comment by JessieZhao0714** [comment]
No unique failures were found.
cc @JoyceWang08211

**Comment by stian-sigvartsen** [comment]
Forwarding this because this was the intention.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
