### PR TITLE
LPD-37463 prevent NPE when scim is not configured - 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by cdbm** [comment]
cit:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by cdbm** [comment]
ci:report:43747074

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @cdbm ! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
