### PR TITLE
LRQA-71052 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-71052

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
