### PR TITLE
[TS] LPS-177580 Update oauth2-oidc-sdk dependency

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

https://issues.liferay.com/browse/LPS-167751 introduced the usage of CodeVerifier in OpenIdConnectAuthenticationSession, but CodeVerifier is not Serializable until "oauth2-oidc-sdk", version: "8.11"

Can you please review?
https://issues.liferay.com/browse/LPS-177580

Cheers,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@balazssk merged to master and U67

**Pull request closed without merging**
