### PR TITLE
Security Routine Analysis

### PR DESCRIPTION
**Pull request by manuelecastro**
Since Testray 2 is [currently **not** exporting the CSV file](https://liferay.atlassian.net/browse/LRSD-4778), I opened this PR to be able to export the CVS through the ci:report command.

**How to generate the daily report:**
1. go to the testray run link;
2. get the build id at the end of the URL (e.g. for "https://testray.liferay.com/web/guest#/project/34754/routines/90235/build/34689187" it would be `34689187`);
4. trigger the command `ci:report:testray_build_id` (e.g. `ci:report:34689187`);
5. after the build completes, the download link of the CSV will be availabe.

Here's the current [analysis spreadsheet](https://docs.google.com/spreadsheets/d/1Ed7bzc7tZJ3FK2swHv-hDfrDJRmEBqDndz6HiPsFIWY/edit#gid=1550447329)

**OLD METHOD:**

Since Testray 2 is [currently **not** exporting the CSV file](https://liferay.atlassian.net/browse/LRSD-4778), I'm running the security suite here(on the latest master) to be able to export the CVS through the ci:report command.

**How to generate the daily report:**
1. push this branch with the latest master;
2. trigger the `ci:test:security` routine;
3. when the run finishes, wait at least 10 minutes and trigger the command `ci:report:testray_build_id` (e.g. `ci:report:1691519`);
4. after the build completes, the download link of the CSV will be availabe.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:report:17805464

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:report:29496435

**Comment by manuelecastro** [comment]
ci:report:29496435

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
ci:report:33661617

**Comment by stian-sigvartsen** [comment]
ci:report:32126572

**Comment by stian-sigvartsen** [comment]
ci:report:32978912

**Comment by stian-sigvartsen** [comment]
ci:report:31563004

**Comment by stian-sigvartsen** [comment]
ci:report:31106365

**Comment by stian-sigvartsen** [comment]
ci:report:30165549

**Comment by stian-sigvartsen** [comment]
ci:report:29437275

**Comment by stian-sigvartsen** [comment]
ci:report:28653317

**Comment by manuelecastro** [comment]
ci:report:34689187

**Comment by manuelecastro** [comment]
ci:report:35660758

**Comment by manuelecastro** [comment]
ci:report:35660747

**Comment by manuelecastro** [comment]
ci:report:36405097

**Comment by manuelecastro** [comment]
ci:report:46042884

**Comment by manuelecastro** [comment]
ci:report:53079578

**Comment by manuelecastro** [comment]
ci:report:54831097

**Comment by manuelecastro** [comment]
ci:report:54831097

**Comment by manuelecastro** [comment]
ci:report:72037202

**Comment by manuelecastro** [comment]
ci:report:72204328

**Comment by manuelecastro** [comment]
ci:report:78691299

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:report:79319194

**Comment by manuelecastro** [comment]
ci:report:31714586

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:report:32022903

**Comment by manuelecastro** [comment]
This PR has been moved to: https://github.com/manuelecastro/liferay-portal/pull/34

**Pull request closed without merging**
