### PR TITLE
LPS-174421 Audit events export

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
Hi @oliverkecskemety, could you please fix the Semantic versioning [issue](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73206//consoleText)? Thx.  
`clean-up-java-processes:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh
[stopwatch] [run.batch.test.setup: 62:55.785 sec]
     [echo] run.batch.test.action.start.timestamp: 04-27-2023 11:43:19:846 PDT
     [echo] Checking for baseline log files.
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 76.0.0
[beanshell] 
[stopwatch] [run.batch.test.action: 17.672 sec]
     [echo] Semantic versioning is incorrect.`

**Comment by stian-sigvartsen** [comment]
@JoyceWang08211 the SemVer issue is unrelated to this PR also so very likely already fixed upstream already. I think we can ignore it in the context of the PR.

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1107

**Pull request closed without merging**
