### PR TITLE
LPS-134142 Fix typo in a getter

### PR DESCRIPTION
**Pull request by martamedio**
cc/ @lipusz

### CODE REVIEW

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1197401_8468

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@martamedio We should probably shelf this and wait for an opportunity when there is a major bump for more significant reasons :/

**Comment by martamedio** [comment]
> @martamedio We should probably shelf this and wait for an opportunity when there is a major bump for more significant reasons :/

@stian-sigvartsen I'm fine with that, maybe you can take it into account when the OpenIdConnect pending tasks will be developed, I am assigning you this ticket just to not forget about it.

cc/ @lipusz

**Pull request closed without merging**
