### PR TITLE
[WIP] LPD-6865 Integration test

### PR DESCRIPTION
**Pull request by nikolettabuza**
Test for [LPD-6865](https://liferay.atlassian.net/browse/LPD-6865) --> [LPD-18588](https://liferay.atlassian.net/browse/LPD-18588)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:stop

**Comment by nikolettabuza** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
This PR was superseded and the ticket is closed.

**Pull request closed without merging**
