### PR TITLE
[TS] LPS-115694

### PR DESCRIPTION
**Pull request by ChrisKian**
Previous PR: https://github.com/csierra/liferay-portal/pull/802

Sending to @liferay-appsec as per @lipusz's request here: https://github.com/csierra/liferay-portal/pull/800#issuecomment-803137344 

I've squashed the commits down since they mostly revert each other, and it's a bit convoluted to go through all of them.  I've also resolved the issue @Moltam89 found here: https://github.com/csierra/liferay-portal/pull/802#issuecomment-804132608 by adding this commit: https://github.com/liferay-appsec/liferay-portal/commit/835467053abc0d0d807406b8609ed30df52b2449

Please let me know if you have any questions, thanks!

CC @csierra, @achaparro

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @liferay-appsec, is there any update on this issue?  CC @lipusz

**Comment by lipusz** [comment]
Hey @ChrisKian 

Sorry about the delay. Carlos is off and will return after next week so it's better to wait for his review instead of assigning it to someone else from the team.

**Comment by csierra** [comment]
hey folks, it LGTM... let's see what @stian-sigvartsen , @martamedio or @arthurchan35 think

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Looks good to me also

**Pull request closed without merging**
