### PR TITLE
LPS-142095

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-142095

I am upgrading yarn.lock in order to resolve the issue in LPS-142095.
Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Please, forward this to @liferay-frontend or to the InfoSec Engineering (@topolik or @samuelkong).

**Comment by lipusz** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1642

**Pull request closed without merging**
