### PR TITLE
LPS-186583 Country becomes null after calling Headless API

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

https://issues.liferay.com/browse/LPS-186583.

The issue is when changing the attributes of a user with headless api and the ServiceBuilderCountryUtil is looking for the country name to add the country value for the new user, it can't find it, because it is saved with dashes instead of space.

Solution: 
Using the CountryServiceUtil.searchCountries() method to search for the country with the country name. This method can find the title even when we patch the user with a country name in another language.

I considered other solution:
-changed spaces to dash: this worked only in english.
-searched for title in country localization. This solution worked, but at the source format got the : Illegal call to class 'com.liferay.portal.kernel.service.persistence.CountryLocalizationUtil

Tested it locally, and it fixed the problem.

Thank you in advance,
Gege

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
It has been tested and works correctly. 

Tested by following the steps in the ticket description and also by changing the language of the user to be modified and the admin. Also changing the default language of the environment
`company.default.locale=es_ES`

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
Hi @alvarosaugarlr,
changed the variable name for the sf:
Please see on https://github.com/liferay-appsec/liferay-portal/pull/1169
BR,
Gege

**Pull request closed without merging**
