### PR TITLE
Lps 120269

### PR DESCRIPTION
**Pull request by arthurchan35**
/cc @arthurchan35 @csierra
Hey Brian, 

this is a followup pull and some comments on former changes:

regarding 482af40: these test cases are needed in order to cover some specific implementation details of each of the implementations. They would not belong to cases about the factory. We have sent a partial revert here 3d588bf because we need to overflow the initial capacity of the dynamic trie to make sure it grows correctly. 

regarding 0151036: I don't know if you want something to be done around this one. Please let me know if you want some further action. 

we have created the test case for the factory in 104b52f.

Bests. 
Carlos.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
