### PR TITLE
LPS-155728 & LPS-140258 

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
* Plain text emailAddress and userLogin in AuditLogContext & AuditMessage
* Removed sessionId from AuditLogContext

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
With the exception of `LocalFile.Audit#AssertAuditConsoleInformationIsPresentAfterEnabledLog`, the functional tests have been failing for a long time.

The aforementioned test checks for sessionId in the AuditLogContext. This has been removed as required by LPS-140258.

@gaborlovasdotcom can QA review/adjust the test?

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
> With the exception of `LocalFile.Audit#AssertAuditConsoleInformationIsPresentAfterEnabledLog`, the functional tests have been failing for a long time.
> 
> The aforementioned test checks for sessionId in the AuditLogContext. This has been removed as required by LPS-140258.
> 
> @gaborlovasdotcom can QA review/adjust the test?

I filed a task for @jingyuanzhao to review and update the failing Audit test cases

**Comment by gaborlovasdotcom** [comment]
Continued in with tests updated: https://github.com/liferay-appsec/liferay-portal/pull/787

**Pull request closed without merging**
