### PR TITLE
LPD-33727 Enable ignored tests

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-33727](https://liferay.atlassian.net/browse/LPD-33727)

Some tests that were being ignored due to bug tickets can now be enabled again. These were found on: [LRQA-81639](https://liferay.atlassian.net/browse/LRQA-81639)

I wrote a comment with the results [here](https://github.com/liferay-appsec/liferay-portal/pull/1891#issuecomment-2288736952).

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
## **Tests are now passing**

### **Integration tests**

- [com.liferay.oauth2.provider.client.test.TOCTOUTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100408)
- [com.liferay.oauth2.provider.client.test.TokenExpeditionTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100412)
- [com.liferay.oauth2.provider.token.endpoint.test.RefreshTokenAuthorizationGrantTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100436)
- [com.liferay.oauth2.provider.client.test.AnnotatedApplicationClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100164)
- [com.liferay.oauth2.provider.client.test.AnnotatedApplicationPrefixHandlerClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100168)
- [com.liferay.oauth2.provider.client.test.AnnotationsAndHttpApplicationClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100172)
- [com.liferay.oauth2.provider.client.test.AnnotationsAndHttpPrefixApplicationClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100176)
- [com.liferay.oauth2.provider.client.test.HttpMethodApplicationClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100212)
- [com.liferay.oauth2.provider.client.test.OAuth2WebServerServletTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100380)
- [com.liferay.oauth2.provider.client.test.SAPClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100388)
- [com.liferay.oauth2.provider.client.test.ScopeCheckerGuestAllowedTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100392)
- [com.liferay.oauth2.provider.client.test.ScopeFinderTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100396)
- [com.liferay.oauth2.provider.client.test.ScopeMapperNarrowDownClientTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57100400)
- [com.liferay.portal.security.permission.test.ResourcePermissionLocalServiceConcurrentTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57099618)
- [com.liferay.portal.security.membership.policy.site.test.SiteMembershipPolicyMembershipsTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57099016)
- [com.liferay.portal.security.membership.policy.usergroup.test.UserGroupMembershipPolicyMembershipsTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57099032)
- [com.liferay.portal.security.membership.policy.organization.test.OrganizationMembershipPolicyMembershipsTest](https://testray.liferay.com/#/project/34754/routines/34756/build/57098590/case-result/57098988)

### **Functional tests**

- [SAMLUpgrade#ViewSAMLConfigurationAfterUpgrade7412](https://testray.liferay.com/#/project/34754/routines/34756/build/59357237/case-result/59371126)
- [SAMLUpgrade#ViewSAMLWithEncryptionConfigurationAfterUpgrade7412](https://testray.liferay.com/#/project/34754/routines/34756/build/59357237/case-result/59370657)
- [OAuth2#ClientCredentialsShouldBeConfigurableInUserScope](https://testray.liferay.com/#/project/34754/routines/34756/build/60402528/case-result/60406608)

**Comment by ChrisKian** [comment]
Hey @manuelecastro,
The changes look good to me, so I'll ask @rafaprax to forward this to BChan as needed
Thanks!

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
