### PR TITLE
LPD-24968 fix OpenIDConnect#AssertUserIsLoggedOutWhenAccessTokenIsExpiredByOIDCProvider

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-24968](https://liferay.atlassian.net/browse/LPD-24968)

Created a new function within Refresh() class as per advice from members of poshi team.
After using this function the test passed, see: https://github.com/liferay-appsec/liferay-portal/pull/1868#issuecomment-2262183905

Opened this new PR to organize and squash commits. prior pr #1868

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Review by stian-sigvartsen — APPROVED** [review]
Looks great @jgarcialr !

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
