### PR TITLE
LPD-33366 Upgrade to version 0.9.4 (oauth2-provider-rest)

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
Tests looks good.
 /cc @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by jgarcialr** [comment]
rebased in #1932

**Pull request closed without merging**
