### PR TITLE
Lps 120270 apply mapper to auth verifier 2

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey @Brianchandotcom

Here is the pull without creating another class of **AuthVerifierPipeline**.
Regarding to your request to beef up **AuthVerifierPipelineTest**, I think it may not be necessary as the functionality of **AuthVerifierPipeline** is actually well tested in **AuthVerifierTest** and **AuthVerifierFilterTest**.

If we still need more tests, then I think the tests should go to **AuthVerifierTest**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
