### PR TITLE
LPD-39796

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-39796

### CODE REVIEW

**Review by jgarcialr — APPROVED** [review]
Pedro's code looks good

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:scim

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:scim

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:scim

**Comment by alvarosaugarlr** [comment]
the `ci:test:scim `only has failed by other test (semantic versioning)
image
and the error
image

**Comment by alvarosaugarlr** [comment]
The changes look good to me. 

Related to the test (the other code is already reviewed), we call to the `post` to test the logic in the API Headless and  avoid including business logic in the test. We then modify the expando to test that specific case, but it doesn't look like we don't have to make changes to this test (or very small ones) in case we need to modify the behavioural logic.

**Comment by stian-sigvartsen** [comment]
Thanks @daiazius @jgarcialr The runtime changes look good to me!
Like @alvarosaugarlr said, there is a mix of leveraging the existing business logic through utilizing the generated client and also shortcutting that to set the scimClientId (i.e. impl knowledge), but I agree it makes sense to do this because the long term maintenance should be low.

In fact I found that this approach was used in the regular `UserResourceTets#testV2Users` method and your test logic neatly fit into that also. I pushed some commits.

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Review by stian-sigvartsen — COMMENTED** [review]
I will forward if the test still passes on CI

**Comment by jgarcialr** [comment]
test passed:
image

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
