### PR TITLE
LPS-148320 [Dev] Site level OSGI configs

### PR DESCRIPTION
**Pull request by oliverkecskemety**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@oliverkecskemety this looks like the correct approach to me, based on static code review. I am unable to runtime test this right now because of build issues.

If you'd like to send it to BChan then we need to add a feature flag, but I think you just wanted to sanity check your code so far.

**Comment by moltam89** [comment]
Hey guys,

I think the config files shouldn't be in an internal package, because we won't be able to use them from other modules.

Best,
Tamas

**Comment by stian-sigvartsen** [comment]
Hey @moltam89 . It's a good point for consideration. Sometimes it makes sense to export the metatype interface so that other modules can use it with ConfigurableUtil.createConfigurable() to get a strongly typed configuration object. But other times we instead provide a higher level purpose built class which delegates onto that internally. For example when its state is actually built from multiple configurations.

I don't know which design applies best to this set of modules?

**Comment by moltam89** [comment]
Uhm, I'm not sure, I just thought that we won't be able to use the configs this way, but I might miss something.

**Comment by jkappler** [comment]
Please see https://github.com/liferay-appsec/liferay-portal/pull/642

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
