### PR TITLE
[TS] LPS-121228 Authenticate the user prior to checking for an expired password

### PR DESCRIPTION
**Pull request by jonathanmccann**
There was some ambiguity on https://issues.liferay.com/browse/PTR-1945 so I'll leave my notes here. Anything that needs to be changed please let me know and I can send up a new pull.

1. The behavior is now changed when a user's password is expired. Previously, they would always be altered that it is expired. With these changes, if an incorrect password is supplied then they will be told that the authentication failed.

2. https://github.com/liferay-appsec/liferay-portal/commit/f54c261597bb31ced934dc1d12e12957ac43a0c0#diff-2b0cae0e7f9914274883423c68678ea1R5902 - This is wrapped because otherwise it would still throw an expired password exception instead of an authentication exception. I wasn't sure if it should be put into the following check but since that is denoted as the post-authentication pipeline I figured it would be better on its own.

3. https://github.com/liferay-appsec/liferay-portal/commit/f54c261597bb31ced934dc1d12e12957ac43a0c0#diff-2b0cae0e7f9914274883423c68678ea1R1555-R1557 - I assumed in this case if a password isn't required then we shouldn't need to check if it is expired. If this assumption is incorrect then more modifications will be necessary.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:security

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:security

**Comment by csierra** [comment]
ci:test:security

**Comment by csierra** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Closing after investigation and offline conversation with @jonathanmccann .

**Pull request closed without merging**
