### PR TITLE
LPS-158259 Full GraphQL OAuth 2 integration (fresh buildREST)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@ccorreagg can you review the Objects/GraphQL Poshi failures please? Besides this I think it is good to go.

**Comment by magjed4289** [comment]
Test failures are not related. Okay to manually forward. ✅

**Comment by stian-sigvartsen** [comment]
Thanks @magjed4289 ! I will rebase and manually forward to BChan.

**Comment by ccorreagg** [comment]
Forwarded manually here: https://github.com/brianchandotcom/liferay-portal/pull/126680

**Pull request closed without merging**
