### PR TITLE
LPD-1476 AuthVerifier imp.

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
CI relevant failures seems relates:

```
[exec]     Executing commands: curl -X GET -u 'test@liferay.com:test' http://localhost:8080/api/jsonws/company/get-company-by-virtual-host/virtual-host/test-1-40-79.lax.liferay.com
[beanshell] 2024-02-23 20:06:31.874 ERROR [http-nio-8080-exec-4][AuthVerifierFilter:53] com.liferay.portal.kernel.security.auth.AuthException: No User exists with the primary key 0
```

**Comment by ChrisKian** [comment]
Looking into the error.  I'm having trouble compiling master to test locally.

**Comment by jkappler** [comment]
Hi @stian-sigvartsen, @ChrisKian, any news on this? 

Regards

**Comment by ChrisKian** [comment]
Hey @jkappler,
This one slipped through the cracks.  I'll need to revisit and potentially rework the solution

**Comment by stian-sigvartsen** [comment]
The requirements changes. See ticket for details. I am closing this PR, but have archived it to stian-sigvartsen/liferay-portal/pull/311 for future reference.

**Pull request closed without merging**
