### PR TITLE
[TS] LPS-203432

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-203432

By adding the CSRF token in the header during the forward of the `RESTClientHttpRequest`, we prevent [this check](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/auth/SessionAuthToken.java#L150-L157) from failing, allowing locally-executed REST calls to bypass the `AuthVerifierFilter`.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by liferay-appsec** [comment]
ci:reevaluate:1387401_10089

**Comment by liferay-appsec** [comment]
ci:test:sf

**Review by stian-sigvartsen — APPROVED** [review]
This is an excellent solution @ChrisKian ! Simple and targeted.
Please can you review the CI failures and then forward?

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:reevaluate:1387401_10089

**Comment by ChrisKian** [comment]
Test stable/relevant failures look unrelated, as I see this failed test across 2/3 unique failures:
`com.liferay.portal.workflow.metrics.internal.petra.executor.WorkflowMetricsPortalExecutor-2`.  the first failed test also has no mention of related files or modules.
 
However, the SF errors are valid, since my commit message contained vulnerable works.  I've updated the message, and will re-run the test now.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
The first two tests look completely unrelated, but the last one _**could**_ be related.  If you look at the [console output](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/520536/console), the `com.liferay.portal.vulcan.test` fails due to a `java.util.NoSuchElementException`.  I see in the stacktrace `com.liferay.portal.security.auth.verifier.internal.tracker.AuthVerifierFilterTracker$RemoteAccessFilter.doFilter(AuthVerifierFilterTracker.java:213)`, which makes me concerned due to the "RemoteAccess" portion.

@stian-sigvartsen, could you confirm if this is related, or (hopefully) just a false-positive?  Thanks!

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @ChrisKian . It is not easy to determine if that is related, but I also do not think so. I've executed the  portal-vulcan-test module's tests locally also and I don't see a relation in the failures.

Let's forward the PR!

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
