### PR TITLE
LPS-188904 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://liferay.atlassian.net/browse/LPS-188904

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
