### PR TITLE
LPD-19754

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-19754

Resent from https://github.com/liferay-appsec/liferay-portal/pull/1660.  This new solution has two parts: 1) remove service classes from `SamlSsoRequestContext` and `SamlSloContext` so they can become serializable, and 2) patch the `org.opensaml.messaging.context.MessageContext` class so it imports and `implements Serializable`, in order for the `SamlSloContext` class to become completely serializable.

For the latter, here's [my new MessageContext.java](https://gist.github.com/ChrisKian/c36aa5f07f5958ececfe18dc43a8dfe7) file, which only differs from [org.opensaml:opensaml-messaging-api 3.3.0](https://mvnrepository.com/artifact/org.opensaml/opensaml-messaging-api/3.3.0) (which is [the version used in current master](https://github.com/liferay/liferay-portal/blob/66a69efbe765efb18f4f0252905a6884b632fb67/modules/dxp/apps/saml/saml-opensaml-integration/build.gradle#L32)) by importing `java.io.Serializable`, and having the `MessageContext` class implement `Serializable`.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:stable

**Comment by ChrisKian** [comment]
Test failures don't look relevant.  Requesting review from @stian-sigvartsen

**Review by stian-sigvartsen — APPROVED** [review]
Looks good @ChrisKian ! Let me just follow up with you offline before we forward.

**Review by daiazius — CHANGES_REQUESTED** [review]
Regarding the third party patch, the PR is missing the original code and the changes to it along with a .patch file with the diff in code

**Comment by daiazius** [comment]
Resent with some changes here: https://github.com/liferay-appsec/liferay-portal/pull/1700

**Pull request closed without merging**
