### PR TITLE
LPS-192302 Define SCIM REST endpoints based on RFC

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-192302](https://liferay.atlassian.net/browse/LPS-192302)

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Manually forwarded to brianchandotcom/liferay-portal/pull/142840

**Pull request closed without merging**
