### PR TITLE
LPD-38650

### PR DESCRIPTION
**Pull request by daiazius**
Ticket: https://liferay.atlassian.net/browse/LPD-38650

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:help

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by daiazius** [comment]
ci:test:cookies

**Comment by stian-sigvartsen** [comment]
@daiazius @cdbm I will close this PR because it needs a rebase. Please resend.

**Pull request closed without merging**
