### PR TITLE
[TS] LPS-123556 Do not participate in a SLO flow if the SP user setup is not complete

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Because the IDP callback will be intercepted by PortalRequestProcessor and the SLO flow will break down.

/cc @jonathanmccann

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@jonathanmccann your review of this solution would also be very appreciated 👍

**Comment by jonathanmccann** [comment]
@stian-sigvartsen I can confirm that the user is logged out of the SP. The only concern I have is that the user is still logged into the IdP. What explanation can I give to the client when they ask why the user is only logged out of the SP?

Thank you for working on this and refining the solution.

**Comment by stian-sigvartsen** [comment]
@jonathanmccann I had the some concern. I've raised it with our product management but we have yet to discuss it in detail. I'll bring it up for discussion at our standup meeting tomorrow morning.

My personal thought at the moment is that it is fine because the SP hasn't yet fully joined the SSO session from a user perspective. I'd say it is an implementation detail by Liferay that we log the user in ahead of presenting the T&Cs.

Also if you flip the argument, to me it seems a bit undesirably destructive to end the whole SAML SSO session (i.e. the user will be logged out of other SPs also potentially) just because the user does not agree to the T&Cs of a SP they have yet to do anything serious with.

**Comment by jonathanmccann** [comment]
That sounds reasonable. Let me know how the discussion goes.

**Comment by stian-sigvartsen** [comment]
@jonathanmccann We've discussed it and agreed this is the right solution to fix this bug for the reasons I mentioned. So we can send subject to @martamedio 's review.

**Review by martamedio — APPROVED** [review]
I've been reviewing it after the discussions we've had, and I think it's ready to send.

Thanks @stian-sigvartsen and @jonathanmccann

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
