### PR TITLE
LPD-28294

### PR DESCRIPTION
**Pull request by jgarcialr**
Some SF additions: https://github.com/liferay-appsec/liferay-portal/pull/2060

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failure looks unrelated.

This passes my review, now requesting @stian-sigvartsen for final review

**Review by ChrisKian — APPROVED** [review]

**Comment by jgarcialr** [comment]
ci:forward

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @daiazius,

there are some naming issues in the test class. For example, `_setup` instead of `setUp`. Also, check if they are setUp methods indeed. If so, they must be called into a `public void setUp` method. Maybe they are just `_mock` methods. What do you think?

Please take into account those concerns and apply the required changes to the test class.

PS: Try to find these patterns in the liferay code to make sure you are following the existing patterns.

//cc @ChrisKian

**Comment by rafaprax** [comment]
please resend

**Pull request closed without merging**
