### PR TITLE
LPS-190829 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-190829

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
The OAuth2ClientExtension#OAuthApplicationScopesWorkWithClusteredPortals test case requires additional review.

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
