### PR TITLE
[TS] LPS-173047 Anonymous users are exported to LDAP

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-173047](https://liferay.atlassian.net/browse/LPS-173047)
Hi,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/1376.

I removed the commit [15d4e9e](https://github.com/liferay-appsec/liferay-portal/pull/1376/commits/15d4e9e6226d74b6025f84ee762149e874e2ed08) which was responsible for the regression and the test change https://github.com/liferay-appsec/liferay-portal/pull/1376/commits/74c0265348d193d7257b9e0239eb3fde9cb4a416 which was necessary only for the removed commit.

The reason why [15d4e9e](https://github.com/liferay-appsec/liferay-portal/pull/1376/commits/15d4e9e6226d74b6025f84ee762149e874e2ed08) causes regression is coming from UADAnonymousUserProviderImpl.isAnonymousUser(user), which creates an anonymous user when none is found (i.e. no related configuration entry is found). At upgrade, when running at startup, creating an anonymous user (and related configuration) from LDAPUserExporterImpl will cause the failure of the upgrade of the old configuration entry. Therefore I need a check that doesn't create a new configuration entry. 

Please let me know if you have any questions.

Thank you,
Istvan

cc @zsigmondrab @gaborlovasdotcom

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
I'm checking the failures.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
Resolved the regression problem by checking if the configuration exists at scope level. If it does not exist a null is returned (flow used in previous versions) and if it exists the user is returned. 

Tested and works correctly. 

Reviewed the ci errors and they are not related.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
