### PR TITLE
[TECHNICAL SUPPORT] LPS-122319 Pass the ServiceContext containing the URL info provided by the request instead of creating an empty one

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket:
https://issues.liferay.com/browse/LPS-122319

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Thanks @rodrigopaulino . Looks good!

**Pull request closed without merging**
