### PR TITLE
LPD-37452 SF

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:scim

**Comment by stian-sigvartsen** [comment]
ci:test:upgrade

**Comment by stian-sigvartsen** [comment]
@ChrisKian please can you help review the upgrade process refactoring I made? It looks like I broke it somehow

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:scim

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
Upgrade error looks unrelated:
`LIFERAY_ERROR: Ignoring new configuration pid=com.liferay.portal.security.antisamy.configuration.AntiSamyClassNameConfiguration~blogs`

**Review by ChrisKian — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
