### PR TITLE
LPD-6722

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-6722](https://liferay.atlassian.net/browse/LPD-6722)

cc @stian-sigvartsen @alvarosaugarlr @zsigmondrab

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
I've added only SF changes.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @istvansajtos . This test is beautiful! I will integrate my changes to the feature code.

**Comment by stian-sigvartsen** [comment]
Integrated to local branch `audit-wip-i-1`

**Pull request closed without merging**
