### PR TITLE
[TS] LPS-131194

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-131194

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
LGTM.

Previously before LPS-97129 any result, that is not NOT_APPLICABLE, is returned.

One thing I am thinking is that
For result, that is **NOT_APPLICABLE**, and falling into **if ((user != null) && !user.isActive())** category, do we want manually set its state to **UNSUCCESSFUL** if it's **SUCCESSFUL**, instead of letting the process continue to iterate to next Authverifier.

@topolik

**Comment by topolik** [comment]
Thanks for review @arthurchan35, the state can be successful. `not NOT_APPLICABLE` result means the auth verified did process it. And the result depends on the auth verifier result. It can be successful and it can be unsuccessful.

**Comment by arthurchan35** [comment]
Hey @topolik 
Yes, that's what I also understand.
What I meant was in the case of SUCCESS result for an in-active user, shall we:
- instead of return null, and leting it iterate to next AuthVerifier
- but set the state to UNSUCCESS and return this result.

because previously before LPS-97129, any result that is not NOT_APPLICABLE is returned, I think we should preserve this behaivor.

So this change I propose is really an different fix to LPS-97129 rather than this ticket.

**Comment by arthurchan35** [comment]
@topolik 
Here I made a change, let me know what you think.
https://github.com/liferay-appsec/liferay-portal/pull/347
If you think it's not right, we can proceed to forward this pull

**Comment by arthurchan35** [comment]
Hi @topolik 
Have not heard back from you regarding to #347, I had personally tested #347 and it works.
So If you have no objection, I think I will try to forward it.

**Pull request closed without merging**
