### PR TITLE
LPS-159598 Returning 401 when credentials are invalid

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi!

We're working on [LPS-159598](https://issues.liferay.com/browse/LPS-159598). When users make API requests with an expired token the response is a 200 which is not ideal because they can't trigger the login process again. The [linked PTR](https://issues.liferay.com/browse/PTR-3246) contains more specific details on how to reproduce the issue.

This PR does the bare minimum to return a 401 error when an auth token is not valid. I fear this can break many other things that's why I want you guys to have a look and let me know what you think.

Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:security

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks @4lejandrito ! The general approach was fine. I've made some small tweaks..

1. Differntiated between no access token sent and invalid access token. The former must allow all other AuthVerifiers to process (Chain of Responsibility pattern)
2. Moved the response encoding into OAuth 2 related code so other AuthVerifiers (protocols) are free to respond as they require
3. Applied same HTTP 401 responses to the JSON-WS API when invalid access tokens are used

Please see liferay-appsec/liferay-portal/pull/798

On Monday I will ask our QA to review the changes and any functional tests we need to create/change.

**Pull request closed without merging**
