### PR TITLE
[TS] LPS-193127 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi team,

A customer reported it is not possible to update `externalReferenceCode` (`ERC`) in `Organization` entities using headless API through POST and PUT methods.

Analysis showed me that `ERC` field was not 'implemented' to be managed. 

Thus, the fix strategy is to use `ServiceContext` object to pass the `ERC` to insert/update impl methods.

Best regards.

References:
https://liferay.atlassian.net/browse/LPS-193127

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
Hi team,
The SF error seems to be related to https://liferay.slack.com/archives/C1SJ64S9X/p1692584203952789?thread_ts=1692370051.148599&cid=C1SJ64S9X

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
Reviewed and tested. Waiting to pr with the solution of the SF (it has been already sent).

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
Hi @alvarosaugarlr 

It seems that SF test is passed! :-) 

Regards

**Comment by samanzanedo** [comment]
Hi team,

Do we need anything else to forward this PR?
Customer is waiting for this fix.

Regards.

**Comment by alvarosaugarlr** [comment]
ci test errors are not related with the feature.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
