### PR TITLE
LPD-40486

### PR DESCRIPTION
**Pull request by jgarcialr**
Prior PR: https://github.com/liferay-appsec/liferay-portal/pull/2091

Rebased to fix build.gradle conflict.

---------------------------------------------

https://liferay.atlassian.net/browse/LPD-40486

Resent from #2074 with rebasing and several revisions.

Info: by setting the SAML filters to come after the VirtualHostFilter (or more importantly, the AbsoluteRedirectsFilter), we allow the session and CompanyThreadLocal to be initialized with the current instance before hitting the SAML filters. So, when we pull the SAML configuration values in the isEnabled() methods, CompanyThreadLocal will return the current instance's companyId, instead of the System level companyId value (0). In cases where SAML is enabled at the Instance level but not System level, the filters will incorrectly be skipped.

@cdbm, I pushed these changes to the appsec repo, so you can pull/push commits as needed. Please look over my commits and let me know if you have any questions.

@stian-sigvartsen, I am not terribly confident on the SameSiteLaxCookiesSamlPortalFilter and accompanying test changes, mostly because I don't fully understand the purpose of the filter. It's possible we are completely undermining the filter's purpose, so I understand if those changes need to be reverted. I included those changes, because now all SAML filters come after the VirtualHostFilter, which seems correct.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:saml

**Comment by jgarcialr** [comment]
ci:reevaluate:1307401_10519

**Comment by jgarcialr** [comment]
ci:reevaluate:1407401_12027

**Comment by jgarcialr** [comment]
Hi @ChrisKian , @cdbm ,
Changes looks good to me.

seems like ci errors in relevant, stable and saml could be tied to a ckeditor5 change, it should be solved by: https://github.com/liferay-frontend/liferay-portal/pull/4591

//cc @stian-sigvartsen

**Comment by jgarcialr** [comment]
Hi @cdbm , @ChrisKian ,
I just have a question regarding https://github.com/liferay-appsec/liferay-portal/pull/2099/commits/86f73a1f1c36cc60d2cc23825ebcdd3919897e40 I feel I'm missing something, but I don't get why we're removing this and we don't disable this filter if javascript is active and a current session exists.

**Comment by ChrisKian** [comment]
For context, since we are moving the `SameSiteLaxCookiesSamlPortalFilter` after the `VirtualHostFilter`, the session is now always created, thus the check always passes.

**Comment by jgarcialr** [comment]
created #2103 to rebase and get rid of yarnInstall problems on ci.

**Pull request closed without merging**
