### PR TITLE
LPS-134188 Remove x-xss-protection

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:reevaluate:1287401_337

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@arthurchan35 I've pushed some commits to remove the code instead of deprecating it. Can you check my reasoning? Also I don't know if we can major bump the kernel right now, but Brian can decide that I think.

**Comment by lipusz** [comment]
Reading the ticket I see that this header is not supported by modern browsers so it's effectively useless. Thus, I vote on Option 1. But if w do so, we should update https://github.com/liferay/liferay-portal/blob/master/readme/BREAKING_CHANGES.markdown.

**Comment by stian-sigvartsen** [comment]
Rebased and re-sent. Please see liferay-appsec/liferay-portal/pull/457

**Pull request closed without merging**
