### PR TITLE
LPD-29195 | Fixing Test Failures - SAML

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
This PR includes most tickets under the epic [LPD-29195](https://liferay.atlassian.net/browse/LPD-29195). 
It is a subset liferay-appsec/liferay-portal/pull/1927 because I removed the commits for the following 2 tickets, because one made a runtime code change which is causing JS errors:

[LPD-30074](https://liferay.atlassian.net/browse/LPD-30074) - Adds playwright test to cover for SAML.CustomFieldsCanBeUsedForUserMatchingInSAML
[LPD-34973](https://liferay.atlassian.net/browse/LPD-34973) - This is a bug I discovered while testing for LPD-30074.  Without this, the test added for LPD-30074 will fail.

Here's a quick rundown of each ticket covered in this PR:

[LPD-30298](https://liferay.atlassian.net/browse/LPD-30298) - Adds test infrastructure or makes tests less flaky, but doesn't directly add new tests.
[LPD-24989](https://liferay.atlassian.net/browse/LPD-24989) - Adds playwright test to cover for SAML#CustomFieldsCanBeConfiguredForSAMLWithMultipleIdPs
[LPD-24991](https://liferay.atlassian.net/browse/LPD-24991) - Adds playwright test to cover for SAML.CustomFieldUsedMultipleTimesCannotBeSavedInSAML
[LPD-33732](https://liferay.atlassian.net/browse/LPD-33732) - Adds playwright test to cover for SAML#AssertSSOWithSignAuthnRequests.  Also, this test would be partially blocked by the bug which requires the SP to be refreshed after IdP initiated SLO, however I have the test [refresh the page until successful](https://github.com/liferay-appsec/liferay-portal/pull/1927/commits/3bb042915dded9c1f3b01d9c0bf3b7b13a745cea#diff-d33ed65572fc207129fe26a3b3956811383551151eed68b0d0f47e1cb9684ea2R709-R718).  Once this bug is resolved, we should be able to remove the reload logic from the test.
[LPD-35301](https://liferay.atlassian.net/browse/LPD-35301) - Adds playwright test to cover for SAML.SSOLoginLogoutWorkSameWhenSitesConfiguredAsSP
[LPD-30073](https://liferay.atlassian.net/browse/LPD-30073) - Adds playwright test to cover for SAML.SAMLConfigurationNotApplyToSitesAfterACSDisabled
[LPD-35305](https://liferay.atlassian.net/browse/LPD-35305) - Adds playwright test to cover for SAML.ViewIdPSingleLogoutWithMultipleSPs
[LPD-35523](https://liferay.atlassian.net/browse/LPD-35523) - Adds playwright test to cover for SAML.ViewSingleLogoutAndForceAuthWithMultipleSPs

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:playwright

**Comment by stian-sigvartsen** [comment]
@ChrisKian the remaining changes from the previous PR I have pushed to https://github.com/liferay-appsec/liferay-portal/commits/LPD-29195-i-2 . We just need to rebase that following any upstream changes Brian might want to make on this current PR.

**Comment by ChrisKian** [comment]
SAML Playwright tests passing: https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/438438/testReport/

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
