### PR TITLE
LPS-126600 Deprecate CAS

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
LocalFile.Login#CASSSOSmoke passes, which is what is relevant.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hey @arthurchan35 . It would be good if you could look over this when convenient.
The CAS related Poshi smoke test is passing (see above).

/cc @gaborlovasdotcom

**Comment by stian-sigvartsen** [comment]
@arthurchan35 I forgot to mention, that I think we also need to archive CAS in this ticket. I'd just like to make sure we deprecate the code successfully before taking that next step in our final PR to BChan.

**Comment by arthurchan35** [comment]
LGTM.
Just need the conflicts resolved.

**Pull request closed without merging**
