### PR TITLE
LPS-155693 Insecure default: Profile widget on profile page

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPS-155693](https://issues.liferay.com/browse/LPS-155693)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:close

**Comment by manuelecastro** [comment]
resent here: https://github.com/liferay-appsec/liferay-portal/pull/1177

**Pull request closed without merging**
