### PR TITLE
Lps 150092

### PR DESCRIPTION
**Pull request by arthurchan35**
From https://github.com/liferay-appsec/liferay-portal/pull/725

> Is the intention to remove that and other OIDC things from System/Instance settings and utilize this custom portlet only?

Yes, and the _OpenIdConnectProviderConfiguration_ will be marked as "obsolete. use oauth client administrator". It will be left there for a while, because in case of upgrade failures, the customer can also copy over configurations manually.

> I think you are working on an upgrade process for this change.

Yes. Alberto asked me to send him the upgrade code for review.

> Do you envisage this PR being merged to a dev branch?

Sure, as long as this PR be merged to master before I leave for vocation in 2 weeks.

> There has been huge demand to skip IDP selection in some cases to improve UX. So this will be a breaking change. Can we preserve the original URL parameter?

I don't see the connection here, between skip idp selection and preserve original URL parameter. The current code does not allow to skip, I am preserving the existing behavior. And in fact, it's not difficult to skip the selection page with my new approach.

> Is this going to be large enough? I've encountered very large IDs.

Sent PR to Brian to make it bigger. thanks.

> Why do you think this no longer needs to be parameterized?

It's one of the least important configurations, it's going to work with and without... And I have a plan for oauth client to store non-specs configurations in the future, but I don't have time for it now. 

> Is there any chance that a "real" .well-known URI might end with "local"?

In theory, yes, there could be. However 1. in reality, it's close to impossible. 2. If you can come up with a better idea, we could replace the approach.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @arthurchan35 That's fine about  .well-known URI I think. We can evolve this new feature. And the new 256 chars limit for client IDs (brianchandotcom/liferay-portal/pull/119656) should be sufficient 👍 

We need to discuss the other things offline.

**Comment by stian-sigvartsen** [comment]
@arthurchan35 Thanks for 0ad6319. I think this kind of approach should be sufficient until we have the BatchEngine/Headless approach to file based configuration. I notice you didn't implement `deleted()`?

**Comment by arthurchan35** [comment]
Hey @stian-sigvartsen,
I thought about implementing it but I realize it would cause problem, consider:
Someone upgrades their Portal, so that OIDC configs are in OAuth Client, and this person does not want OIDC configs any more, he goes to delete them. If the delete is implemented then the corresponding OAuth Client entry will be deleted.

For update, it would be fine.

**Comment by stian-sigvartsen** [comment]
Sounds like you gave it good thought. It is a good point and caused by having a mixed approach. I'm going to need to think about this a bit and maybe we can discuss. As Ray mentioned, OSGi configuration vs. SB API is Declarative vs. Imperative, so  they come with very different expectations.

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
Let me know when you want to discuss, I am available for next 5hrs

**Comment by arthurchan35** [comment]
See:
https://github.com/liferay-appsec/liferay-portal/pull/732

**Pull request closed without merging**
