### PR TITLE
LPD-40224

### PR DESCRIPTION
**Pull request by rafaprax**
Previous PR: https://github.com/liferay-appsec/liferay-portal/pull/2111

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by rafaprax** [comment]
ci:test:security-playwright

**Comment by daiazius** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/2114

**Pull request closed without merging**
