### PR TITLE
LRQA-81638 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://liferay.atlassian.net/browse/LRQA-81638

### CODE REVIEW

**Comment by melodywu** [comment]
ci:stop:security

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Comment by melodywu** [comment]
ci:stop:security

**Comment by JoyceWang08211** [comment]
Hi @melodywu, please separate Integration tests and functional tests and describe why we need to ignore these integration tests. 
e.g. Commit message: Ignore integration tests due to LPS-XXX

**Comment by melodywu** [comment]
ci:test:um:nocompile

**Comment by melodywu** [comment]
ci:test:sf

**Review by JoyceWang08211 — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1253

**Pull request closed without merging**
