### PR TITLE
LPS-176997

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
**Requested changes applied**
* Renamed the classes so that they start with the same name as the Analytics module.
* Updated configurations and files

[LPS-176997](https://issues.liferay.com/browse/LPS-176997)

### Why this change
Allows you to track requests to measure MALU and APV.

MALU (Monthly Active Loggedin Users): in case of logged in user, we need to log a companyId-userId-siteId hash. So if the user jumps through multiple instances and sites, it counts as different values.
APV (Anonymous Page Views): basically every anonymous page render should return that it was a not logged in user who accessed the page.

### Code
There are two parts to the development

First one, a configuration has been added (AuditHeaderConfiguration ) to enable or disable the following options
Second one, a filter has been created (AuditHeaderFilter) in which, if any of the options in the configuration is active, the values are checked and added to the header of the response so that it can be read by Analytics Cloud.

Previous PRs:
https://github.com/liferay-appsec/liferay-portal/pull/1162
https://github.com/liferay-appsec/liferay-portal/pull/1187

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1196

**Pull request closed without merging**
