### PR TITLE
LPS-176164 

### PR DESCRIPTION
**Pull request by MirnaGama**
#### Context:
https://liferay.atlassian.net/browse/LPS-176164

#### Implementation details: 
Basically, the ticket describes that after declining all cookies from the cookie banner, the non-necessary cookies should not remain in the browser.
I was analyzing the module responsible for the cookies to provide a solution and these are my findings:
- When adding / updating a cookie, the method [addCookie from CookieManagerImpl class](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/cookies/cookies-impl/src/main/java/com/liferay/cookies/internal/manager/CookiesManagerImpl.java#L133) will be called. In this method, it will check if the cookies preference handling configuration is enabled. If it is, then it [will call the method hasConsentType to check if the consent type value of this cookie is set to true](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/cookies/cookies-impl/src/main/java/com/liferay/cookies/internal/manager/CookiesManagerImpl.java#L151). After that, it will return false, but if there is a cookie already stored it will be remained. 

- Analyzing a little more, I found the [CookiePreAction](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/cookies/cookies-impl/src/main/java/com/liferay/cookies/internal/events/CookiesPreAction.java#L67) class that can be called even if I refresh the page, but there is another problem because the stored cookies do not have their consent types explicitly stored together, so there is no way to "filter" which cookies should remain. The only way to know the consent type of the cookie is when it is being added or updated. (Example: [When the GUEST_LANGUAGE_ID cookie is added](https://github.com/liferay/liferay-portal-ee/blob/master/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L1715) )

Based on this findings, it was proposed in this [thread](https://liferay.slack.com/archives/GLX0ZN4QH/p1697647943709669) that we could track the unique cookie names and their consent types when the add method is called and then check them afterwards in the CookiesPreAction class. 

#### Commits included: 
- LPS-176164 Create caching utility class to add and search for cookies and their consent types
- LPS-176164 Insert into the caching hashmap when adding the cookie
- LPS-176164 Check if there are cookies with consent type declined so they can be deleted in the pre-action class
- LPS-176164 Add missing copyright
- LPS-176164 SF

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by oliverkecskemety** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1587

**Pull request merged**
