### PR TITLE
LPD-30074, LPD-34973

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-30074
https://liferay.atlassian.net/browse/LPD-34973

LPD-30074: Includes the final playwright test fix for the epic LPD-29195
LPD-34973: Fixes a bug regarding newly created attribute field selection.  Also handles a couple related edge-cases, which may have arisen due to the new logic.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
SAML playwright suite passing: https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1197667/testReport/

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
SAML playwright tests still passing: https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975286/testReport/

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Relevant test failures look unrelated

**Comment by stian-sigvartsen** [comment]
@ChrisKian in reviewing your changes to the JSP I found that we can preserve the current approach which uses the same name for all the radio control through a single line addition. I would prefer to do that because
1) It is a much smaller change and so easier to backport
2) It seems more respectful to allow the browser to deselect the other radio controls as per the difference between checkboxes and radios

I preserved your commits though because that approach is also a possibility. Nice work!
Please see liferay-appsec/liferay-portal/pull/1966

**Pull request closed without merging**
