### PR TITLE
LPS-151551 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-151551

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
TC1 passes on Jenkins:
https://testray.liferay.com/home/-/testray/case_results/1758075669

All the other SAML testcases pass on Jenkins:
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1755623211

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
