### PR TITLE
LPS-190442 Remove company.security.auth.requires.https

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPS-190442](https://liferay.atlassian.net/browse/LPS-190442)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
Hi all,

after looking at the [Testray Build](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2434880370&testrayRunId=2434880506) (74 fails out of 2744 tests), I couldn't see any failure due to the changes made in this PR. @stian-sigvartsen could you take a look also?

Thanks!

**Comment by manuelecastro** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks @manuelecastro . Those results look good I think. I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
