### PR TITLE
LPS-163950 Lockout mechanism used in a denial of service attack

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-163950](https://liferay.atlassian.net/browse/LPS-163950)

Previous PR:
https://github.com/liferay-appsec/liferay-portal/pull/969

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
