### PR TITLE
[TS] LPS-123556

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://issues.liferay.com/browse/LPS-123556

Please let me know if you have any questions or see any potential issues with this change.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
Hi @jonathanmccann . It is not ideal to include a magic if statement for SAML SLO in portal-impl . Did you explore any fix isolated to the SAML modules?

**Comment by stian-sigvartsen** [comment]
@jonathanmccann further to the above, I have found a solution which only requires a change to the `saml-opensaml-integration` module. Please see liferay-appsec/liferay-portal/pull/175

**Pull request closed without merging**
