### PR TITLE
LPS-157790

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
The following failures are caused by the current PR:
[Unique failures](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1907810216&testrayCaseTypeId=101949&testrayComponentId=1310733455&statuses=3):
OAuth2#AuthCodeShouldWorkWithClusteredPortals
SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithExistingUser
SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithoutExistingUser
OAuth2#JWTAssertionCanBeAcceptedAsGrantTypeWithScreenNameAsUserAuthenticationType
OAuth2#JWTAssertionCanBeAcceptedAsGrantTypeWithEmailAddressAsUserAuthenticationType
OAuth2#InstanceLevelConfigurationWillCoverSystemLevelWhenTheyConfiguredWithSameIssuer
OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel
LocalFile.OAuth2#GrantedAuthorizationsCanBeRevoked

Working on the further investigation.

**Comment by JoyceWang08211** [comment]
> The following failures are caused by the current PR: [Unique failures](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1907810216&testrayCaseTypeId=101949&testrayComponentId=1310733455&statuses=3): OAuth2#AuthCodeShouldWorkWithClusteredPortals SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithExistingUser SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithoutExistingUser OAuth2#JWTAssertionCanBeAcceptedAsGrantTypeWithScreenNameAsUserAuthenticationType OAuth2#JWTAssertionCanBeAcceptedAsGrantTypeWithEmailAddressAsUserAuthenticationType OAuth2#InstanceLevelConfigurationWillCoverSystemLevelWhenTheyConfiguredWithSameIssuer OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel OAuth2#GrantedAuthorizationsCanBeRevoked
> 
> Working on the further investigation.

Reported the above issue in LPS-158417 and LPS-158421.

**Comment by stian-sigvartsen** [comment]
Hi @arthurchan35 . I've sent additional commits to liferay-appsec/liferay-portal/pull/784 which cover missing functionality.
The concurrency issue I mentioned is that your changes are calling setters on the singleton instance of `AbstractOAuthDataProvider` (`LiferayOAuthDataProvider`), with values scoped to company level. This is the first time we have company level configuration for this, which is why it is happening only now.

I see two solutions:

1) Maintain an instance of LiferayOAuthDataProvider per company and ServiceMapperTrackMap track these from the various endpoint services.
2) Avoid the setters and instead override the getters to read from ThreadLocals or derive from local variables (if possible, unlikely)

Let's address this fundamental issue and then we can do another round of peer review.

**Comment by arthurchan35** [comment]
@stian-sigvartsen

Thanks for spotting the multi-threading issue!

I also prefer the idea of per company dataProvider, however I think not only dataProvider needs per company but also accessTokenService needs per company as well. In fact this is one thing I noticed when I was working accepting JWT grant.

Making only dataProvider per company isn't making too much sense in CXF framework, so at this moment, I would rather move the instance configuration to system configuration to avoid the multi-threading issue you mentioned.

**Pull request closed without merging**
