### PR TITLE
[TS] LPS-133585 escapeJSLink() improvement

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by cleydyr** [comment]
Hi, @stian-sigvartsen .

Thanks for checking this out and forwarding it.

I haven't yet run the fix on my machine to check if it's equivalent, but the purpose of the trim I put before the if block is to force the condition in the if block to be true. If the trim is performed only afterwards, as with your amendment, the link won't be escaped.

Am I leaving something out in my reasoning?

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
Sorry, you are correct! 💯  
I'll forward the original PR.

**Comment by cleydyr** [comment]
Cool! Thanks for the quick response!

**Pull request closed without merging**
