### PR TITLE
[TS] LPS-75442 Avoid "User 0 is not allowed to access URL" warn traces when the user has no cookie enabled

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-75442

The `User 0 is not allowed to access URL xxx and portlet xxx: User 0 did not provide a valid CSRF token for com.liferay.portlet.SecurityPortletContainerWrapper` warning is a issue that the customers are reporting repeatedly (the LPS has 9 votes and 8 watchers and in the last 2 years we have 109 tickets in HelpCenter with this trace) 

I have detected that sometimes the issue can be caused by a misconfiguration of the session.timeout.auto.extend, but most of the times the issue is produced by requests received without session information:

- Because an user has blocked the cookies in his browser.
- Because a bot is trying to indexing the site and it is requesting an URL protected by the CSRF validations.

To avoid this issues, I am doing following changes:

1. [`917f28f` (#396)](https://github.com/liferay-appsec/liferay-portal/pull/396/commits/917f28f74f6deb153ce168088eded5899dc02b1c) - In the browser side, I have added a warning message in case the customer tries to login in a browser with the cookies disabled and session.test.cookie.support=true portal-ext.property setting enabled
2. [`92e1928` (#396)](https://github.com/liferay-appsec/liferay-portal/pull/396/commits/92e19289aa5eb3dd683a3012d3eaba75500bd70b) and [`c711416` (#396)](https://github.com/liferay-appsec/liferay-portal/pull/396/commits/c711416ca059d1ae9aab74acd9cb6542e5811ecf) - In the server side, in case the current session doesn't have a CSRF token, I am throwing a new `PrincipalException.MustHaveSessionCSRFToken` exception that will block the access to the requested resource, but no warn trace will be written to the log file to avoid writing warning messages that can be ignored (a debug trace can be enabled anytime)

---

Detected related issue related to the support cookie in the backend:
- Fix: [`549bbeb` (#396)](https://github.com/liferay-appsec/liferay-portal/pull/396/commits/549bbebb199b9df6a73199941d216a827caf9dd0)
- I have detected that the support cookie check is not working correctly: after the LPS-63765 changes, the support cookie is added here https://github.com/liferay-appsec/liferay-portal/blob/ca00c3b11f7a6aa04d7216b586cfdac6b5e88423/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L957-L972 to both httprequest and httpresponse, so the validation that is done in the AuthenticatedSessionManagerImpl.login method will never fail as it was added to the incoming request.
- With this [`549bbeb` (#396)](https://github.com/liferay-appsec/liferay-portal/pull/396/commits/549bbebb199b9df6a73199941d216a827caf9dd0) commit, the support cookie will only be added to the response, so this method will work in the same way than before LPS-63765 changes. 
- However, If the CSRF validations are enabled, all the requests received without the session cookie will fail, so the cookie validation of `AuthenticatedSessionManagerImpl.login` will only catch wrong requests in case the CSRF validations are manually disabled or whitelisted, nevertheless I think it must be fixed.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:security

**Comment by jorgediaz-lr** [comment]
ci:test:security

**Comment by jorgediaz-lr** [comment]
The ci errors of the ci:test:security execution seems to be unrelated to my changes as they are reproduced in a PR without them, see this test PR => https://github.com/jorgediaz-lr/liferay-portal/pull/349

**Comment by stian-sigvartsen** [comment]
Hi @jorgediaz-lr . Just to let you know I am reviewing this PR at the moment

**Comment by jorgediaz-lr** [comment]
Hi @stian-sigvartsen 

Thanks for your message. Let me know in case you have any question.

**Comment by arthurchan35** [comment]
see: https://github.com/liferay-appsec/liferay-portal/pull/404

**Pull request closed without merging**
