### PR TITLE
LPS-128600 ExpandoUserFieldExpressionHandler

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:reevaluate:1047401_8355

**Comment by stian-sigvartsen** [comment]
Upon further consideration, it would not be smart to extend the UserImporter API because that would force all kinds of user importers to support Expando. It is meant to be a simple API. I have sent an alternative which keeps the LDAP code local to the SAML module: liferay-appsec/liferay-portal/pull/504

**Pull request closed without merging**
