### PR TITLE
LPS-150388 - default Administrator password without using the default admin.password property

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-150388](https://issues.liferay.com/browse/LPS-150388)

### Why this change
As shipping a product with a default Administrator password goes against [OWASP Top Ten ](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/)we want to change that behaviour with changing the default value of that property empty.

### The default flow at the first sign in

- Accepting the terms of use (terms.of.use.required=true)
- Setting password 
- Defining password reminder security question and the answer to that (reminder.queries.enabled=true)
- Email verification (company.security.strangers.verify=true)
- MFA (is enabled through instance config)

### Code
Code changes are made in three phases:
- First phase, when creating an instance in DXP (also when creating a virtual instance), an administrator user is created. In the method addDefaultAdminUser (in the UserLocalServiceImpl class), it is checked if the property (default.admin.password) and the environment variable (LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_PASSWORD) has no value. In this case, three modifications are made in the method with respect to the usual behavior
   -   A random password is assigned to the administrator user.
   -   It is indicated that the password must be reset to the user (by default depends on the default policy).
   -   Finally, a value is assigned to the  remindQueryAnswer column  (in User table in data base) to be checked later.

- The second phase is in the login. DXP has a filter (AutoLoginFilter) that checks if there is no user logged in. If there is not, it calls the defined classes to check if it is possible to log in. The AdminPasswordAutoLogin class has been added to perform the necessary checks and, if it is the first execution of the instance, to recover the administrator user of that instance.

- Third phase: Finally, in the flow used for the users (look at Features, What does this feature do?), after assigning the password, the value stored in the remindQueryAnswer column of the User table at the time of creating the administrator user (first point) is removed.
image

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
cc: @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
@alvarosaugarlr , @weller0246 the relates story is closed are we want to keep this PR open?

**Comment by alvarosaugarlr** [comment]
We can close it, all this feature is included in https://github.com/liferay-appsec/liferay-portal/pull/823

**Pull request closed without merging**
