### PR TITLE
LPS-155693 Insecure default: Profile widget on profile page

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPS-155693](https://issues.liferay.com/browse/LPS-155693)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
Thanks @manuelecastro , this looks good to me! I will forward.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
