### PR TITLE
[SRE-LXC] LPS-176534 Whitelist additional classes for deserialization

### PR DESCRIPTION
**Pull request by ZoltanTakacs**

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test:relevant
ci:test:security
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
Thanks @ZoltanTakacs !

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
