### PR TITLE
LPS-121455 Remove SaaS SAML functionality

### PR DESCRIPTION
**Pull request by martamedio**
Hey Brian! 👋 

As we have discussed, we proceed to delete from _master_ this SaaS exclusive module and[ I have prepared a PR to move it to the "_osb_" directory starting on 7.3.x.](https://github.com/liferay/liferay-portal-ee/pull/21286) but looks like it's not updated and it's not allowed to send changes to that branch 🤔 

Please, let us know if we should send this in another way (like directly to your _7.3.x_ branch), thanks!

### CODE REVIEW

**Comment by martamedio** [comment]
@gaborlovasdotcom This is the PR where we are going to delete the SaaS-Saml module in master, is it necessary to add here the elimination of tests or something else relate?

Thanks

**Comment by martamedio** [comment]
ci:test:security

**Comment by martamedio** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
> ### ❌ ci:test:security - 91 out of 98 jobs passed in 2 hours 5 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)
> Branch GIT ID: [b5a410ba533a7ae80112d850306bc6fd52732391](https://github.com/liferay/liferay-portal/commit/b5a410ba533a7ae80112d850306bc6fd52732391)
> 
> #### Copied in Private Modules Branch:
> Branch Name: [master-private](https://github.com/liferay/liferay-portal-ee/tree/master-private)
> Branch GIT ID: [13c59df02738cba7c7387b3490775720676498c7](https://github.com/liferay/liferay-portal-ee/commit/13c59df02738cba7c7387b3490775720676498c7)
> 
> **ci:test:security - 91 out of 98 jobs PASSED**
> ##### For more details click [here](https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7370/jenkins-report.html).
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/19](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363088/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #363088](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/363088//consoleText)1. [LocalFile.SAML#AssertSSOSessionExistsAfterSPSessionTimeout](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/363088//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOSessionExistsAfterSPSessionTimeout_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/19/0/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/19/0/LocalFile.SAML_AssertSSOSessionExistsAfterSPSessionTimeout/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/19/0/jenkins-console.txt.gz)
> 2. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/34](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446721/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #446721](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/446721//consoleText)1. [LocalFile.SAML#AssertSAMLSPUserInformationUpdatesAfterChangingOnIdP](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/446721//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSAMLSPUserInformationUpdatesAfterChangingOnIdP_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/34/0/LocalFile.SAML_AssertSAMLSPUserInformationUpdatesAfterChangingOnIdP/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/34/0/LocalFile.SAML_AssertSAMLSPUserInformationUpdatesAfterChangingOnIdP/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/34/0/jenkins-console.txt.gz)
> 3. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/58](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363090/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #363090](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/363090//consoleText)1. [LocalFile.SAML#AssertInstanceAdminCannotConfigureIdPWhenDisableIdPRole](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/363090//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertInstanceAdminCannotConfigureIdPWhenDisableIdPRole_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/58/0/LocalFile.SAML_AssertInstanceAdminCannotConfigureIdPWhenDisableIdPRole/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/58/0/LocalFile.SAML_AssertInstanceAdminCannotConfigureIdPWhenDisableIdPRole/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/58/0/jenkins-console.txt.gz)
> 4. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/60](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441711/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #441711](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/441711//consoleText)1. [LocalFile.Login#FacebookSSOSmoke](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/441711//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Login_FacebookSSOSmoke_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/60/0/LocalFile.Login_FacebookSSOSmoke/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/60/0/LocalFile.Login_FacebookSSOSmoke/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/60/0/jenkins-console.txt.gz)
> 5. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/66](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313125/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #313125](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/313125//consoleText)1. [LocalFile.SAML#AssertSSOWithSignAuthnRequests](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/313125//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AssertSSOWithSignAuthnRequests_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/66/0/LocalFile.SAML_AssertSSOWithSignAuthnRequests/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/66/0/LocalFile.SAML_AssertSSOWithSignAuthnRequests/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-22/1602001834991/test-portal-acceptance-pullrequest(master)/7370/functional-tomcat90-mysql57-jdk8/66/0/jenkins-console.txt.gz)
> 6. ...
> 
> #### For upstream results, click [here](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

@martamedio 
Those tests failed due to browser crash, except FacebookSSOSmoke, yesterday I sent a test-fix for that to change test data. It's clear this run still contained the old test data.

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
