### PR TITLE
LPS-152126 LPS-157406 LPS-150933 LPS-162107 LPS-170861 | SAML Admin REST tests (+ follow ups)

### PR DESCRIPTION
**Pull request by JoyceWang08211**
[LPS-152126](https://issues.liferay.com/browse/LPS-152126)
[LPS-157406](https://issues.liferay.com/browse/LPS-157406)
[LPS-150933](https://issues.liferay.com/browse/LPS-150933)
[LPS-162107](https://issues.liferay.com/browse/LPS-162107)
[LPS-170861](https://issues.liferay.com/browse/LPS-170861)

cc @stian-sigvartsen, @gaborlovasdotcom

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Review by gaborlovasdotcom — COMMENTED** [review]
Test cases LGTM @JoyceWang08211

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Review by stian-sigvartsen — APPROVED** [review]
Looks good @JoyceWang08211 . I will forward the PR.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@JoyceWang08211 I've rebased this to latest master and sent for CI testing because it has been some time since we tested this. Please see liferay-appsec/liferay-portal/pull/983

**Pull request closed without merging**
