### PR TITLE
LRAC-14795 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14795

Hi team!
This pull aims find a way to manipulate the response body when we get an 401 error in [OAuth2RESTAuthVerifier](https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/security/auth/verifier/OAuth2RESTAuthVerifier.java).

Basically, I need to set a message in the response body, telling the user the token has expired

I talked to Stian via Slack and he had suggested me to implement `ContainerResponseFilter` to cover this. However, it didn't work because, I believe, when we get 401 error in `OAuth2RESTAuthVerifier`, we also set the state of  `authVerifierResultAuthVerifierResult.State.INVALID_CREDENTIALS` and then ends up to prevent `AuthVerifierFilter` from process the next filter (see [AuthVerifierFilter](https://github.com/liferay/liferay-portal/blob/0848120527e55ff5257496f80e8881ee0ddbaff6/portal-impl/src/com/liferay/portal/servlet/filters/authverifier/AuthVerifierFilter.java#L166))

So I created this interface `OAuth2RESTAuthVerifierErrorResponseHandler` and reference it as optional inside of OAuth2RESTAuthVerifier. This interface is implemented on Faro side, so we can manipulate the response and keep current behavior for the other cases.

Look forward to hear your guys thoughts about this.
Thanks in advance!

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @marcosapmf . Thanks for the PR :) 
Before we consider adding a new SPI for this I would like to explore why it is needed. I've commented on the ticket.

**Comment by marcosapmf** [comment]
Hi @stian-sigvartsen! Thanks for answering :smile: 
Yeah, sure! I've written a comment there with my point of view, but I think the AC product guys can explain the benefits of that to you better than me :)

**Comment by zsigmondrab** [comment]
Discarded as it turned to be an expected behaviour.

**Pull request closed without merging**
