### PR TITLE
LPS-123949

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by noraszel** [comment]
Hi @yxingwu,
Based on the component list this issue is not connecting to the Application Security team, it is connecting to the Headless team. Could you sent the review request to them? https://github.com/liferay-headless
Thanks in advance,
Nóra

**Comment by yxingwu** [comment]
Thank you for your info @noraszel .
I'll send it to the Headless team.

**Pull request closed without merging**
