### PR TITLE
LPS-132251 Hash Map Builder

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:help

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
Hey @hhuijser
Per Brian's request, we added support to putAll Dictionary.
Can you help review it?

**Comment by martamedio** [comment]
LGTM, @hhuijser we'll appreciate your opinion on this one 👀

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
See https://github.com/liferay-appsec/liferay-portal/pull/367

**Pull request closed without merging**
