### PR TITLE
LPS-127823

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello @yxingwu 

Can you please send this to the Dev Tools team?

Thanks,
Tibor

**Comment by yxingwu** [comment]
Hello @lipusz 
Could you tell me which git repository I should send the PR to? 

Thanks.

**Comment by lipusz** [comment]
Hi @yxingwu ,

I didn't find a GH user for Liferay Dev Tools so try sending it directly to @gamerson or @david-truong.

**Pull request closed without merging**
