### PR TITLE
LPD-32189

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-32189

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Looks great @ChrisKian !

**Review by stian-sigvartsen — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by ChrisKian** [comment]
New test passing: https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965658/testReport/saml-web_saml.spec/ts/LPD_32189_AC1_TC1__Verify_IdP_initiated_SLO_redirects_user_to_c_portal_saml_slo_logout_where_all_SP_instances_are_logged_out___After__user_should_be_redirected_back_to_Default_Logout_Page_configuration_value_/

**Pull request closed without merging**
