### PR TITLE
Lpd 32862

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-32862

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
@alvarosaugarlr  LGTM

**Pull request closed without merging**
