### PR TITLE
Lps 119169

### PR DESCRIPTION
**Pull request by arthurchan35**
@csierra 
So Brian wanted to merge performance tests first, and he wants to see the performance comparison...
So here the first 3 commits are for merging for the performance tests, and the rest DO NOT MERGE commits are only for demonstrating comparison purpose.

**The first 3 commits are self contained, meaning with these 3 commit themselves, all tests will pass.**

To run the performance tests:
go under */portal-remote-cors-impl directory
run $ ../../../../gradlew test --tests com.liferay.portal.remote.cors.internal.*PerformanceTest
It will generate 3 log files under */portal-remote-cors-impl directory

Here at my local environment:
static impl runs in 10 ~ 11 seconds
dynamic impl runs in 26 ~ 27 seconds
simple impl runs in 50 ~ 51 seconds

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:sf

**Pull request closed without merging**
