### PR TITLE
LPD-41375 Exchange jodd.Paramo dependency with java.lang.reflect.Parameter

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPD-41375](https://liferay.atlassian.net/browse/LPD-41375)

Original pr  - https://github.com/liferay-appsec/liferay-portal/pull/2049

Original message:

> Please see https://liferay.atlassian.net/browse/LPP-56216. The customer uses Java21 on the portal and created a Service builder module, but during runtime, it does not compatible with JsonWS jodd.Paramo dependency. That jodd.paramo.MethodParameter would be replaced with java.lang.reflect.Parameter.

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:report:62489139

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/2089

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
