### PR TITLE
LPS-155048

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @daiazius ! For those RuntimeExceptions it would be useful to add a message like "Method not implemented". Can you push a commit?

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Thanks @daiazius ! LGTM

**Pull request closed without merging**
