### PR TITLE
LPS-199105 Add audit logs for organization and site role assignments

### PR DESCRIPTION
**Pull request by nikolettabuza**
[LPS-199105](https://liferay.atlassian.net/browse/LPS-199105)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:stop

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@nikolettabuza perfect! Forwarding

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Integrated to local branch `audit-wip-i-1`

**Pull request closed without merging**
