### PR TITLE
LPS-176173 & LPS-169817 Tighten AuthVerifier user context & audit

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Rebased to liferay-appsec/liferay-portal/pull/1010

**Comment by gaborlovasdotcom** [comment]
ci:test:commerce

**Pull request closed without merging**
