### PR TITLE
LPS-138193

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:oidc

**Comment by zsigmondrab** [comment]
Hi @daiazius,

I can see a JWT token related exception which may be needed to investigate. In addition to that, however the ObjectFolder related exeptions may not seem to be relevant, it's not there at other pull requests, so that's also suspicious.

Could you please investigate them?

Regards,
Zsigmond

**Pull request closed without merging**
