### PR TITLE
[TS] LPS-193158

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-193158

Recent from https://github.com/liferay-appsec/liferay-portal/pull/1298 with upgrade process included.  I've also dropped [this commit](https://github.com/liferay-appsec/liferay-portal/pull/1298/commits/ccb61c2947a5677c18a9cd699dfe6fff2e5c52ac) since the upgrade process will catch any users who may have selected client_secret_basic before.

Please let @ChrisKian know if you have any questions, thanks!

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
All the relevant OAuth2 tests passed on Jenkins with the TF:
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2406827708&testrayRunId=2406827725

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Review by stian-sigvartsen — APPROVED** [review]
Thanks @ChrisKian ,  LGTM!

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Pull request closed without merging**
