### PR TITLE
LPD-23266

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPD-23266](https://liferay.atlassian.net/browse/LPD-23266)

when using the property `virtual.hosts.valid.hosts=*` the Redirect URL list is used and currently is blocking some actions when navigating on virtual instances.

to resolve this, I added a new default on the RedirectURLConfiguration that will be used to allow any redirects coming from the current portal domain.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
Looks good @manuelecastro!  I added one SF commit, moved the revert commit so it was first, and renamed it to include the LPD value.

See https://github.com/liferay-appsec/liferay-portal/pull/1723

**Comment by manuelecastro** [comment]
Ok @ChrisKian, thanks for the review! :)

**Pull request closed without merging**
