### PR TITLE
LPD-31130 Fix test failures in openid-link/openid-link.spec.ts

### PR DESCRIPTION
**Pull request by jgarcialr**
Fix playwright test for openid connect.
[LPD-31130](https://liferay.atlassian.net/browse/LPD-31130)

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:stop

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
run 10 times in local using:
`npm run playwright -- test tests/openid-link/openid-link.spec.ts --repeat-each 5 -x
`
It passes now:
imagen

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
image

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:playwright

**Comment by alvarosaugarlr** [comment]
After the push -f the tests have passed too
image

**Comment by alvarosaugarlr** [comment]
The changes are fine with me.

It is especially interesting to highlight:
* A [new site is created to perform the tests ](https://github.com/liferay-appsec/liferay-portal/pull/1999/files#diff-f8fd3608b24f5581f325819d5243e9ca0e6c4ae2fd1a5903f8496a8bafb43bdfR94)since this way it is avoided that the test fails after removing the FF. The FF is activated by UI and the functionality affects the site initializer, so when the FF is activated the site has already been created but without creating the utility pages. For this reason a new site has been created in the test. The reason why the tests would fail when removing the FF is because the validations that were made were conditioned to the site being created without the functionality (the FF was disabled). This way it is independent if the functionality is under a FF or not. 
* The configuration ([Login prompt](https://github.com/liferay-appsec/liferay-portal/pull/1999/files#diff-f8fd3608b24f5581f325819d5243e9ca0e6c4ae2fd1a5903f8496a8bafb43bdfR64)) and the [site created](https://github.com/liferay-appsec/liferay-portal/pull/1999/files#diff-f8fd3608b24f5581f325819d5243e9ca0e6c4ae2fd1a5903f8496a8bafb43bdfR65) after the test are removed to leave the environment clean.

cc/ @stian-sigvartsen

**Review by alvarosaugarlr — COMMENTED** [review]
https://github.com/liferay-appsec/liferay-portal/pull/1999#issuecomment-2442860887

**Comment by stian-sigvartsen** [comment]
LGTM! Thanks @jgarcialr @alvarosaugarlr

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
