### PR TITLE
LPS-157194 Add upgrade process for 7.3 to clear out expired OAuth2Authorizations

### PR DESCRIPTION
**Pull request by jonathanmccann**
@oliverkecskemety 

This is a follow up to the idea presented here - https://github.com/liferay-uniform/liferay-portal/pull/996#issuecomment-1449696082

If you wouldn't mind double checking the SQL logic I would appreciate it. It has switched from deleting to saving entries so I had to inverse the logic and want to make sure everything is correct.

I've also included five test cases which cover:
- A valid access token
- An invalid access token
- A valid refresh token
- An invalid refresh token
- A mix of the previous four to ensure it can handle mixed results

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Review by oliverkecskemety — APPROVED** [review]
Thank you @jonathanmccann! It looks good to me. I started a new CI run because the older one is no longer available. I'll check it once it finished and I'll forward it if it looks good.

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:forward:force

**Pull request closed without merging**
