### PR TITLE
dummy for CI test run: LPD-25377revert from master

### PR DESCRIPTION
**Pull request by tomibiro**
This PR will test LPD-29518 solution after reverting LPD-25377 commits. I will check SAML#SSOLoginLogoutWorkSameWhenSitesConfiguredAsSP test failure.

### CODE REVIEW

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:help

**Comment by tomibiro** [comment]
ci:test:poshi

**Comment by tomibiro** [comment]
ci:report:49736194

**Comment by jgarcialr** [comment]
ci:report:49718305

**Comment by stian-sigvartsen** [comment]
@tomibiro I think we can close this PR. If you think differently we can re-open

**Pull request closed without merging**
