### PR TITLE
[TS] LPS-75442 Updated Semver

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same pull than https://github.com/liferay-appsec/liferay-portal/pull/404 but I have updated the Semver commit [`8a4a8fa` (#410)](https://github.com/liferay-appsec/liferay-portal/pull/410/commits/8a4a8fa1222b2713f58a3976754521d45694dd1d)

/cc @stian-sigvartsen

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@jorgediaz-lr this looks really good now. Thanks!

**Pull request closed without merging**
