### PR TITLE
LPD-32210, LPD-32213, LPD-32214

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPD-32210
https://liferay.atlassian.net/browse/LPD-32213
https://liferay.atlassian.net/browse/LPD-32214

Resent from https://github.com/liferay-appsec/liferay-portal/pull/2118 with some changes excluded.

SP SSO redirection with `auth.forward.by.last.path=false` will actually redirect to `/c` in the [AutoLoginFilter](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/filters/autologin/AutoLoginFilter.java#L213-L215) class, which in turn will skip the login processes in the `SpSsoSamlPortalFilter`, [since the path does not match anymore](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/saml/saml-impl/src/main/java/com/liferay/saml/internal/servlet/filter/SpSsoSamlPortalFilter.java#L86).

So, this means redirection of SP SSO with `auth.forward.by.last.path=false` does not behave any differently from normal portal login redirection, so we should not need to add tests here.  It will be a good idea to add login tests with [LPD-44168](https://liferay.atlassian.net/browse/LPD-44168), which would also cover SP SSO.

Because of this, these three epics are now complete, so hopefully we can merge them soon.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:saml

**Comment by ChrisKian** [comment]
Test failures are unrelated

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
