### PR TITLE
LPS-105172

### PR DESCRIPTION
**Pull request by oliverkecskemety**

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:stop

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by oliverkecskemety** [comment]
Hey @rafaprax,

Can you check this please?
```
     [java] 2023-10-12 22:04:54.927 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1164] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.scim.charon.integration.jar
     [java] org.osgi.framework.BundleException: Exception in com.liferay.scim.charon.integration.internal.activator.SCIMCharonIntegrationBundleActivator.start() of bundle com.liferay.scim.charon.integration.
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.Module.start(Module.java:449) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
     [java] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1147) [bundleFile:?]
     [java] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1180) [bundleFile:?]
     [java] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1121) [bundleFile:?]
     [java] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1032) [bundleFile:?]
     [java] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:238) [bundleFile:?]
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.util.FastDateFormatFactoryUtil.getSimpleDateFormat(FastDateFormatFactoryUtil.java:58) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.util.Time.getSimpleDate(Time.java:244) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.util.Time.getTimestamp(Time.java:258) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.util.Time.getTimestamp(Time.java:254) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.util.FileImpl.createTempFileName(FileImpl.java:221) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.util.FileImpl.createTempFileName(FileImpl.java:207) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.util.FileImpl.createTempFile(FileImpl.java:192) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.util.FileImpl.createTempFile(FileImpl.java:183) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.util.FileUtil.createTempFile(FileUtil.java:69) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.scim.charon.integration.internal.activator.SCIMCharonIntegrationBundleActivator._registerLiferayUserSchemaExtension(SCIMCharonIntegrationBundleActivator.java:40) ~[?:?]
     [java] 	at com.liferay.scim.charon.integration.internal.activator.SCIMCharonIntegrationBundleActivator.start(SCIMCharonIntegrationBundleActivator.java:28) ~[?:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) ~[org.eclipse.osgi.jar:?]
     [java] 	... 11 more
```

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/1444

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
