### PR TITLE
[TS] LPS-167400 Additional DEBUG traces for LDAP Import

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-appsec,
this pull fixes LPS-167400.

Added new DEBUG races and a new StopWatch to show the user's complete import time including all operations performed: add, update, etc.

### CODE REVIEW

**Comment by danielmijarra** [comment]
ci:test:ldap

**Comment by stian-sigvartsen** [comment]
Hi @danielmijarra . The new log statements do not include any information about the user being imported, but you are still logging separately for each user. Will the log be useful?

Also I think it would be useful if it consistently logs a "finished" statement following every "Starting" statement?

**Comment by danielmijarra** [comment]
Hi @stian-sigvartsen,
I think that for this case the important thing is the time consumed in the import of each user, independently of the specific user. The user is already shown in other DEBUG traces contained between the new start and end import traces (add, update,...).
At the point where the `stopWatch.start()` has been included, we could show the `fullUserDN` or the `userAttributes` but I am not sure if showing this information could suppose any security risk, since this data is transformed later.
However, the imported user could be shown in the log trace of `stopWatch.getTime()`, I could add the user in this trace.
What do you think?

**Comment by stian-sigvartsen** [comment]
Thanks for further explanation. With that in mind I have made some minor tweaks and sent it for CI testing here: liferay-appsec/liferay-portal/pull/893

Can you have a look if it is satisfactory?

For consistency we should also add similar logging to `_importFromLDAPByGroup()` I think?

**Comment by danielmijarra** [comment]
Hi @stian-sigvartsen,
thanks for your changes, I'll check `_importFromLDAPByGroup()` to add similar traces to it.

**Comment by stian-sigvartsen** [comment]
Great! Thanks @danielmijarra . I'll close this PR and wait for the next one.

**Pull request closed without merging**
