### PR TITLE
[TS] LPS-169318 Reverting usage of DLFileVersion.userId back to ResourcePermission.ownerId in dslQuery due to performance issues

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-169318

**Issue**:
Customer reported that dlapp/get-file-entries API call is significantly slower for non-admin users.
The cause of the performance issue is the change of the userId check in the query.
ResourcePermission.ownerId = {userId} was replaced by DLFileVersion.userId = {userId} in [LPS-136334](https://issues.liferay.com/browse/LPS-136334) when the new DSL queries were introduced.

**Solution**:
On [PTR-3453](https://issues.liferay.com/browse/PTR-3453) it was determined that since the results of the two queries are the same, the current implementation can be changed back to the original query.
I removed the logic that replaced ResourcePermission.ownerId with DLFileVersion.userId, and I also removed "userIdColumn" from the method signature due to SF failure.

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by evibudai** [comment]
ci:test:sf

**Comment by evibudai** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @evibudai . Wrong team I'm afraid, please see comment on LPS. On the presumption the CI test results will be useful to you I will leave this PR open for now, but can you close when convenient? Thanks!

**Comment by evibudai** [comment]
thanks @stian-sigvartsen

**Pull request closed without merging**
