### PR TITLE
LPS-165015 Upgrade to Batik 1.15

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: https://issues.liferay.com/browse/LPS-165015

Resolves security vulnerabilities in Batik 1.14 (see LPS ticket for the list of vulnerabilities).

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:reevaluate:1397401_599

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1397401_599

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @mbowerman . Sent direct because CI failures are unrelated. Please see brianchandotcom/liferay-portal/pull/124458

**Pull request closed without merging**
