### PR TITLE
LPS-118649-REPLACE-SIMPLE-IMPL-WITH-OPTIMIZED-IMPL

### PR DESCRIPTION
**Pull request by arthurchan35**
Hold until tests are merged.

@csierra Can you help review it?

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
yup... I can try

**Comment by csierra** [comment]
Please see https://github.com/liferay-appsec/liferay-portal/pull/30

**Pull request closed without merging**
