### PR TITLE
[TS] LPS-186928

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
Tested following the steps in the description and checked. it works.

**Comment by marianoalvarosaiz** [comment]
@alvarosaugarlr I've rebased the pull (no other changes applied), see https://github.com/liferay-appsec/liferay-portal/pull/1288

**Pull request closed without merging**
