### PR TITLE
LPD-22656 add test

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-22656](https://liferay.atlassian.net/browse/LPD-22656)

Adding integration test for an already fixed issue.

cc @stian-sigvartsen @alvarosaugarlr @zsigmondrab

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
I've updated the failing tests.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
LGTM @istvansajtos . I will forward.

p.s. @alvarosaugarlr has also reviewed.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
