### PR TITLE
LPS 147809

### PR DESCRIPTION
**Pull request by antonio91dev**
- LPS-147809 set url metadata field to empty when loading xml file
- LPS-147809 buildLang

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by antonio91dev** [comment]
Hi @arthurchan35 
why did it open again ?

**Comment by arthurchan35** [comment]
Hey @antonio91dev 
@stian-sigvartsen is working on the review for this PR.

**Comment by antonio91dev** [comment]
Hi @stian-sigvartsen 
any news about this PR

**Comment by stian-sigvartsen** [comment]
Hi @antonio91dev . We are just looking at a way to avoid needing to clear the Metadata URL field when the upload button is pressed. The issue there is that there is nothing preventing new input after that which will get ignored when you submit the form so it is not consistent.

**Pull request closed without merging**
