### PR TITLE
LPD-41375 Replace java8 supported jodd.Paramo dependency with java21 compatible solution

### PR DESCRIPTION
**Pull request by tomibiro**

### CODE REVIEW

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:security

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by tomibiro** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by tomibiro** [comment]
I check the relevant and stable test failures. They are not related to the code modification in JsonWs.

**Comment by tomibiro** [comment]
ci:test:security

**Comment by rafaprax** [comment]
ci:report 84357137

**Comment by rafaprax** [comment]
ciLreport:84357137

**Comment by rafaprax** [comment]
ci:report:84357137

**Comment by rafaprax** [comment]
ci:report:84634183

**Comment by rafaprax** [comment]
ci:report:84634183

**Comment by rafaprax** [comment]
pr forwarded to core-infra here https://github.com/liferay-core-infra/liferay-portal/pull/7707

**Comment by tomibiro** [comment]
closing this one and continue on the forwarded one: https://github.com/liferay-core-infra/liferay-portal/pull/7707

**Pull request closed without merging**
