### PR TITLE
LPD-40486

### PR DESCRIPTION
**Pull request by jgarcialr**
Prior PRs: https://github.com/liferay-appsec/liferay-portal/pull/2091, https://github.com/liferay-appsec/liferay-portal/pull/2099

Rebased to fix build.gradle conflict and yarnInstall problem in tests

---------------------------------------------

https://liferay.atlassian.net/browse/LPD-40486

Resent from #2074 with rebasing and several revisions.

Info: by setting the SAML filters to come after the VirtualHostFilter (or more importantly, the AbsoluteRedirectsFilter), we allow the session and CompanyThreadLocal to be initialized with the current instance before hitting the SAML filters. So, when we pull the SAML configuration values in the isEnabled() methods, CompanyThreadLocal will return the current instance's companyId, instead of the System level companyId value (0). In cases where SAML is enabled at the Instance level but not System level, the filters will incorrectly be skipped.

@cdbm, I pushed these changes to the appsec repo, so you can pull/push commits as needed. Please look over my commits and let me know if you have any questions.

@stian-sigvartsen, I am not terribly confident on the SameSiteLaxCookiesSamlPortalFilter and accompanying test changes, mostly because I don't fully understand the purpose of the filter. It's possible we are completely undermining the filter's purpose, so I understand if those changes need to be reverted. I included those changes, because now all SAML filters come after the VirtualHostFilter, which seems correct.

----------------------------------------------
review passed by @jgarcialr

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:saml

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Review by stian-sigvartsen — COMMENTED** [review]
Removed SameSite cookie policy changes, waiting on CI.

**Comment by jgarcialr** [comment]
@stian-sigvartsen , relevant tests are passing after last changes

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
