### PR TITLE
LPD-29195 | Fixing Test Failures - SAML

### PR DESCRIPTION
**Pull request by ChrisKian**
This PR includes everything under the epic [LPD-29195](https://liferay.atlassian.net/browse/LPD-29195).  Here's a quick rundown of each ticket:

[LPD-30298](https://liferay.atlassian.net/browse/LPD-30298) - Adds test infrastructure or makes tests less flaky, but doesn't directly add new tests.
[LPD-24989](https://liferay.atlassian.net/browse/LPD-24989) - Adds playwright test to cover for SAML#CustomFieldsCanBeConfiguredForSAMLWithMultipleIdPs
[LPD-24991](https://liferay.atlassian.net/browse/LPD-24991) - Adds playwright test to cover for SAML.CustomFieldUsedMultipleTimesCannotBeSavedInSAML
[LPD-33732](https://liferay.atlassian.net/browse/LPD-33732) - Adds playwright test to cover for SAML#AssertSSOWithSignAuthnRequests.  Also, this test would be partially blocked by the bug which requires the SP to be refreshed after IdP initiated SLO, however I have the test [refresh the page until successful](https://github.com/liferay-appsec/liferay-portal/pull/1927/commits/3bb042915dded9c1f3b01d9c0bf3b7b13a745cea#diff-d33ed65572fc207129fe26a3b3956811383551151eed68b0d0f47e1cb9684ea2R709-R718).  Once this bug is resolved, we should be able to remove the reload logic from the test.
[LPD-30074](https://liferay.atlassian.net/browse/LPD-30074) - Adds playwright test to cover for SAML.CustomFieldsCanBeUsedForUserMatchingInSAML
[LPD-34973](https://liferay.atlassian.net/browse/LPD-34973) - This is a bug I discovered while testing for LPD-30074.  Without this, the test added for LPD-30074 will fail.
[LPD-35301](https://liferay.atlassian.net/browse/LPD-35301) - Adds playwright test to cover for SAML.SSOLoginLogoutWorkSameWhenSitesConfiguredAsSP
[LPD-30073](https://liferay.atlassian.net/browse/LPD-30073) - Adds playwright test to cover for SAML.SAMLConfigurationNotApplyToSitesAfterACSDisabled
[LPD-35305](https://liferay.atlassian.net/browse/LPD-35305) - Adds playwright test to cover for SAML.ViewIdPSingleLogoutWithMultipleSPs
[LPD-35523](https://liferay.atlassian.net/browse/LPD-35523) - Adds playwright test to cover for SAML.ViewSingleLogoutAndForceAuthWithMultipleSPs

In general, I added the required infrastructure and surrounding files before adding the related test.  If needed, I can try organizing the commits, just let me know how I should proceed.

I will allow CI some time before requesting a review.  Although everything passes locally, CI may be a different story.

Also for reference,

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
It seems CI doesn't like to use localhost as an IdP or SP.  I'll adjust the tests to remove any dependency on localhost now.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
Tests passing here: https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1081185/testReport/

I'm including two more small changes which have been squashed into previous commits, so I'll re-run the test suite.  They should only make things less flaky if anything

1. Include an extra check [here](https://github.com/liferay-appsec/liferay-portal/pull/1927/commits/8b05f4fb9a2686776459b6186a784c12eccfd631#diff-d33ed65572fc207129fe26a3b3956811383551151eed68b0d0f47e1cb9684ea2R825-R841) which will determine if the test should still pass, even though we don't see an error banner.
2. [Add a waitFor() condition before attempting to reset the SAML System settings](https://github.com/liferay-appsec/liferay-portal/pull/1927/commits/729add17d6222dfe024cf0ca06a3aba11555f786#diff-d5726852a5d9ff91197550def40acbae7a77207cd1aa9cce53ac3862c71d7ce3R186-R188).  In local testing, sometimes the page isn't fully loaded before [this conditional check](https://github.com/liferay-appsec/liferay-portal/pull/1927/commits/729add17d6222dfe024cf0ca06a3aba11555f786#diff-d5726852a5d9ff91197550def40acbae7a77207cd1aa9cce53ac3862c71d7ce3R190-R194), so the SAML configuration is never reset.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:playwright

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
SAML playwright tests passing: https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1081369/testReport/

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Relevant failures look unrelated.  Requesting review from @stian-sigvartsen

**Review by stian-sigvartsen — COMMENTED** [review]
Excellent work @ChrisKian !

I found there were runtime JS errors introduced by the LPD-34973 fix, so I extracted that from this PR and the related test (LPD-30074). We can follow up. This PR was already large so the priority is to get the other commits sent.

Please see liferay-appsec/liferay-portal/pull/1935

**Pull request closed without merging**
