### PR TITLE
[TS] LPS-173047 Anonymous users are exported to LDAP

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-173047](https://liferay.atlassian.net/browse/LPS-173047)

Hi,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/993 which was merged and then reverted due to regressions.

The recent PR contains all the original modifications plus the following additions:

- Fixed regressions in commits https://github.com/liferay/liferay-portal/commit/ca0ae50129214646501e9582f035ef9186710d6a and https://github.com/liferay/liferay-portal/commit/0d0e31b5779c90337db2c9e4b6dfe5d0e785e406
- Fixed up Brian's earlier SF changes into the commits they belong to
- Renamed LDAPUserExporterTest to LDAPUserExporterImplTest as Brian requested in https://github.com/brianchandotcom/liferay-portal/commit/9cabc6fb0accccc2c68aec4e06a2c753f2e19c2c

Please contact me if any question comes up.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:ldap

**Comment by JoyceWang08211** [comment]
Resolved conflict and continued in https://github.com/liferay-appsec/liferay-portal/pull/1339

**Pull request closed without merging**
