### PR TITLE
LPD-21457 Support RESTClient dispatch to AuthVerifierFilter protected resources

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by zsigmondrab** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1975 and https://github.com/brianchandotcom/liferay-portal/pull/149258

**Comment by stian-sigvartsen** [comment]
Because we are seeing some on-going issues in this area and this PR is a different fix approach to what was later merged for this ticket, I have re-opened this PR and labelled it as backlog. So we have a reference.

**Comment by stian-sigvartsen** [comment]
The final solution was implemented differently. I am closing this PR.

**Pull request closed without merging**
