### PR TITLE
LPD-35768 Add playwright tests to security related suites

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-35769](https://liferay.atlassian.net/browse/LPD-35769)

Playwright tests are not included on security related suites and this impacts our daily analysis, since we're not tracking those tests.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:cookies

**Comment by manuelecastro** [comment]
ci:test:oidc

**Comment by manuelecastro** [comment]
ci:test:scim

**Comment by manuelecastro** [comment]
### Playwright tests are now running at the suites :white_check_mark: 

See results:
- [Security Suite](https://testray.liferay.com/#/project/35392/routines/45357/build/4245598?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)
- [Cookies](https://testray.liferay.com/#/project/35392/routines/45357/build/5689238?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)
- [OpenID Connect](https://testray.liferay.com/#/project/35392/routines/45357/build/5689251?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)
- [SAML](https://testray.liferay.com/#/project/35392/routines/45357/build/5697688?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)
- [SCIM](https://testray.liferay.com/#/project/35392/routines/45357/build/5672548?filter=%7B%22testrayCaseTypeIds%22%3A%5B41230%5D%7D&filterSchema=buildResults&page=1)

**Review by ChrisKian — APPROVED** [review]
Looks good, thanks @manuelecastro!

Requesting review from @stian-sigvartsen

**Review by stian-sigvartsen — APPROVED** [review]
LGTM, thanks @manuelecastro

**Pull request closed without merging**
