### PR TITLE
LPD-26785 Add Antivirus and SCIM integration tests to security suite

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-26785](https://liferay.atlassian.net/browse/LPD-26785)

The integration tests for the Antivirus and SCIM modules were missing at the security suite.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:security

**Comment by manuelecastro** [comment]
**Successfully added to the Security suite:** 

:heavy_check_mark: [Antivirus Modules Integration Tests](https://testray.liferay.com/#/project/34754/routines/34756/build/36140151?filter=%7B%22testrayCaseTypeIds%22%3A%5B34071%5D%2C%22testrayComponentIds%22%3A%5B195900%5D%7D&filterSchema=buildResults&page=1)

:heavy_check_mark: [SCIM Modules Integration Tests](https://testray.liferay.com/#/project/34754/routines/34756/build/36140151?filter=%7B%22testrayCaseTypeIds%22%3A%5B34071%5D%2C%22testrayComponentIds%22%3A%5B90639%5D%7D&filterSchema=buildResults&page=1)

**Review by stian-sigvartsen — APPROVED** [review]
Looks great! Thanks @manuelecastro

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
