### PR TITLE
LPS-134954 Implicit mapping fix

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
[LPS-134954](https://issues.liferay.com/browse/LPS-134954)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@arthurchan35 why did you mention the LPS-145191 fix on this PR?

**Comment by stian-sigvartsen** [comment]
ci:reevaluate:1267401_2663

**Comment by stian-sigvartsen** [comment]
@gaborlovasdotcom  We need to review those two failing Poshi tests

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by stian-sigvartsen** [comment]
@gaborlovasdotcom rebased to liferay-appsec/liferay-portal/pull/631 as requested so you can verify the new functional tests

**Pull request closed without merging**
