### PR TITLE
LPS-129283 Store pipeline to ac context, a threadLocal.

### PR DESCRIPTION
**Pull request by arthurchan35**
Storing it in accessControlImpl results in race condition because accessControlImpl is singleton across portal, which can be access by diffrent request threads.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:help

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
