### PR TITLE
LPD-44245 Add expirationDate

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
LPD: https://liferay.atlassian.net/browse/LPD-44245

Issue:
The expirationDate was missing from the email address verification ticket.

Solution:
Added the expirationDate in accordance with the team.

Please review my PR!

Thanks!

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by rafaprax** [comment]
Hey @cdbm, Could you please review this one?
Thx

**Comment by cdbm** [comment]
Other than that i think we need to open a new pr since this one has too many unrelated commits which mess with ci

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/2137

**Pull request closed without merging**
