### PR TITLE
[TS] LPS-137635

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @stian-sigvartsen,

I'm trying to fix regression https://issues.liferay.com/browse/LPS-137635 caused by https://issues.liferay.com/browse/LPS-135470, according to my comment here.

I've checked it does not break https://issues.liferay.com/browse/LPS-135470, and all automatic tests passed in my user. Gut I'm not sure if we should test any extra manual cases, so could you please have a look at it?

Thank you! :)

**Comment by crodriguezy** [comment]
Hi @liferay-appsec team, can anybody have a look at this change?

Thanks.

**Comment by crodriguezy** [comment]
Hi @lipusz , could you please move this on? Is there any other repo I should send it instead?
Thanks

**Comment by lipusz** [comment]
Please resend to @liferay-usm as per Stian's comment on the LPS. Thank you!

**Pull request closed without merging**
