### PR TITLE
Lps 107016 2

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test

**Comment by csierra** [comment]
see https://github.com/liferay-appsec/liferay-portal/pull/263

**Comment by csierra** [comment]
we'll better send name changes and formatting style changes later

**Pull request closed without merging**
