### PR TITLE
LPS-192736 | master

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://liferay.atlassian.net/browse/LPS-192736

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:stop

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:um

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
