### PR TITLE
pr 2043

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @alvarosaugarlr, Can you check if those  variable names makes sense?

Thx

/cc @stian-sigvartsen

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
Hi @rafaprax , Thanks for the review! I think that names can help to understand better the code.

**Comment by stian-sigvartsen** [comment]
@rafaprax thank you for helping us find better variable names! I will forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
