### PR TITLE
LPD-41377 Save only if provided

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-41377

@istvansajtos please review

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:test:acceptance

**Comment by stian-sigvartsen** [comment]
We have tested this further and believe there to be different protections in place to avoid that NPE.

There are some additonal cases we needed to cover so we have sent additional commits here: liferay-appsec/liferay-portal/pull/2071 .

I'm leaving the current PR open for now.

**Comment by stian-sigvartsen** [comment]
Closing this PR now because the additional commits on the other PR are needed.

**Pull request closed without merging**
