### PR TITLE
LPS-144210 update number of rounds 

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-144210 ](https://issues.liferay.com/browse/LPS-144210)

Updated the number of rounds used in the default configuration to 720,000 for PBKDF2.

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
@alvarosaugarlr , The failing test case 
- SAML#AssertSSOWithEncryptionAndDecryption
Is not related to the contents of this PR. [Testray test case history](https://testray.liferay.com/home/-/testray/cases/1310781290)

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:forward

**Comment by arthurchan35** [comment]
ci:forward

**Pull request closed without merging**
