### PR TITLE
LPD-34901 OIDCProviderMetadata is not cached

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPD-34901](https://liferay.atlassian.net/browse/LPD-34901)
Hi Team,

This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/1990
Most of the changes were reviewed previously, only the last six commits are new.

As we agreed, the help text informs the user about the Ehcache default time-to-live value used when setting caching time to 0.

Notes for OAuthClientEntryUpgradeProcessTest:
- The upgrade builds on the fact that the new 'metadataCacheInMillis' column in oAuthClientEntry has null values that must be filled with actual cache times. The upgrade also builds on this precondition, which requires modifying the values with direct SQL updates.
- When adding/deleting/updating OpenId Connect Provider configurations, the related OAuthClientEntry entities are automatically maintained by OpenIdConnectProviderPortalInstanceLifecycleListener. This is asynchronous, requiring delaying the execution of the main thread to make the OAuthClientEntry available.

Please let me know if you have questions and concerns.

Thank you!
István

cc @stian-sigvartsen @alvarosaugarlr @jgarcialr

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by alvarosaugarlr** [comment]
The tests have passed: 
image

image

**Comment by alvarosaugarlr** [comment]
ci:report:51284987

**Comment by alvarosaugarlr** [comment]
ci:test:51257544

**Comment by alvarosaugarlr** [comment]
ci:report:51257544

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
The pr looks good to me. 

I'm running again the test because I have made sf change.

cc/ @rafaprax  @stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Looks good @istvansajtos @alvarosaugarlr ! I just applied the `ConfigurationTestUtil` to the integration test and inlined some constants there.

**Comment by stian-sigvartsen** [comment]
As discussed offline, the solution needs to consider that clientId might not be unique. Because you can have multiple OIDC connections to the same OIDC provider. I will close the PR because it also needs a rebase. @istvansajtos please send new commits on top of the current branch and explain the reasoning for the additional change in the commit messages. Thanks!

**Pull request closed without merging**
