### PR TITLE
LPD-23266

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-appsec/liferay-portal/pull/1722

Original message: [LPD-23266](https://liferay.atlassian.net/browse/LPD-23266)

> when using the property virtual.hosts.valid.hosts=* the Redirect URL list is used and currently is blocking some actions when navigating on virtual instances.
> 
> to resolve this, I added a new default on the RedirectURLConfiguration that will be used to allow any redirects coming from the current portal domain.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:forward

**Comment by manuelecastro** [comment]
Hey @ChrisKian! 

I was having a look at the test results and found this one that might be related to the changes, I'm investigating if it's a testfix or if we need to change something on the code. :)

**Comment by manuelecastro** [comment]
@ChrisKian I was able to run the test locally and it passed successfully! 

Could you rebase the branch and try forwarding again?

Thanks! :)

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-appsec/liferay-portal/pull/1726

**Pull request closed without merging**
