### PR TITLE
LPD-41375 Replace java8 supported jodd.Paramo dependency with java21 compatible solution

### PR DESCRIPTION
**Pull request by rafaprax**
see https://liferay.atlassian.net/browse/LPD-41375

/cc @tomibiro @jgarcialr

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by rafaprax** [comment]
Hey @tomibiro, Can you please check the ci results on Monday and forward this to the core infra repo if everything is ok?

Thanks in advance

**Comment by jgarcialr** [comment]
ci:report:81055216

**Comment by jgarcialr** [comment]
Core-Infra team PR: https://github.com/liferay-core-infra/liferay-portal/pull/7693

**Comment by liferay-upgrades** [comment]
Hey @jgarcialr, I found out that we could improve a little bit more the code here https://github.com/liferay-appsec/liferay-portal/pull/2095/commits/24f1549db1da3b10f124833d79ab4177a2df9d78. 

I'm re-running the tests again.

Thx

**Comment by rafaprax** [comment]
Hey @jgarcialr, I found out that we could improve a little bit more the code here https://github.com/liferay-appsec/liferay-portal/commit/24f1549db1da3b10f124833d79ab4177a2df9d78.

I'm re-running the tests again.

Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by rafaprax** [comment]
@jgarcialr once the tests pass, Can you check the tests again and send to the core infra again?

Thanks in advance

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:stop:stable

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:reevaluate:1387401_11538

**Comment by jgarcialr** [comment]
ci:reevaluate:1377401_18930

**Comment by tomibiro** [comment]
I checked the related failures:
- com.liferay.portal.remote.cors.client.test.AnnotationCORSClientTest fails locally with `ProcessException: java.io.FileNotFoundException: http://localhost:8080/o/test/cors-app` that seems unrelated. This test fails all time in the previous weeks.
- [semantic-versioning/0/0](https://testray.liferay.com/#/project/35392/routines/45357/build/82199276/case-result/82204898) is related to `asset-taglib` module that is unrelated to the change.
- [Top Level Build](https://testray.liferay.com/#/project/35392/routines/45357/build/82199276/case-result/82204906) is a flaky test that fails many times in the previous weeks.
I rebased the changes to the fresh master and restarted a new pr to see that the new results: https://github.com/liferay-appsec/liferay-portal/pull/2101

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-appsec/liferay-portal/pull/2101

**Pull request closed without merging**
