### PR TITLE
LRQA-76039 | Updating Security test cases for Chrome 100

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-76039](https://issues.liferay.com/browse/LRQA-76039)

Updates:
- Bring OAuth 2 test tool under Portal's domain, as a test dependency
- Update corresponding test cases and macros in the Security test suite

cc @weller0246, @JoyceWang08211

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:oauth2:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
Forwarded directly to Brian, due relevant test suite failures are not directly linked to this OAuth2 test suite: https://github.com/brianchandotcom/liferay-portal/pull/121380

Relevant test results at testray: https://github.com/liferay-appsec/liferay-portal/pull/778#issuecomment-1208054499

**Comment by stian-sigvartsen** [comment]
Can't push to your fork so have opened a new PR for the OAuth 2 tester app move as discussed: liferay-appsec/liferay-portal/pull/785

**Pull request closed without merging**
