### PR TITLE
LPS-164103 Release cookies module

### PR DESCRIPTION
**Pull request by oliverkecskemety**
[LPS-164103](https://issues.liferay.com/browse/LPS-164103)

### CODE REVIEW

**Comment by oliverkecskemety** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1297401_5835

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:cookies

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/953

**Pull request closed without merging**
