### PR TITLE
LRQA-76604 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-76604
cc @john-co

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
Due to this PR got stuck in Jenkins, I split LRQA-76604 and LPS-160971 into two PRs. Sent LPS-160971 in https://github.com/liferay-appsec/liferay-portal/pull/814.

cc @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
