### PR TITLE
LPD-38511 Replace Google > KeyCloak OIDC provider for OpenIDConnect#OpenIDConnectSmoke

### PR DESCRIPTION
**Pull request by jgarcialr**
[LPD-38511](https://liferay.atlassian.net/browse/LPD-38511)
Replace Google by Keycloak due to recaptcha validation after login-in.
//cc @tomibiro

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
https://github.com/jgarcialr/liferay-portal/pull/92

**Comment by jgarcialr** [comment]
image

**Comment by alvarosaugarlr** [comment]
I think the changes are fine. The use of Google is changed to Keycloak to test OpenId and thus remove the captcha problem (both ways we test the functionality, and thus remove a problem).

It has also been removed that is https because with Keycloak is not necessary and does not affect the test we are doing. 

@stian-sigvartsen for me it is ok to forward.

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:stop

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:forward

**Pull request closed without merging**
