### PR TITLE
LPD-37463 prevent NPE when scim is not configured

### PR DESCRIPTION
**Pull request by cdbm**

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good @cdbm!

My only hesitation is [the double catches](https://github.com/liferay-appsec/liferay-portal/pull/1987/commits/a8d93f739bf2924b94c092fb1546c408c61265f1#diff-e5eaf74d7f6599448dc6b4392f475e2cad057281bcc4079fc74cf36416c78e4cR324-R329), which seems to do the same thing.  Regardless of the exception, the same method is called afterwards.

But, I see [BChan explicitly added something similar](https://github.com/liferay-appsec/liferay-portal/commit/0d2581fe77a82acc39c06876fcb3b6c7b07ede74), so it should be fine the way you have it.  @stian-sigvartsen, any thoughts on this?

**Review by ChrisKian — APPROVED** [review]

**Comment by stian-sigvartsen** [comment]
Hi @cdbm @ChrisKian 
In that example commit by Brian you can see he tried to remove a huge try block. Do we really need to make have the try like that? It isn't very clear what causes the different exceptions. Did you explore handling the missing configuration in a more targeted way?

You are modifying `Base*TestCase` classes but these are generated. If those modifications were made through regeneration then please extract that out into a separate commit with the message "buildREST"

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
See previous comment

**Comment by cdbm** [comment]
@stian-sigvartsen after talking with @ChrisKian we verified that there's no need to change the base test classes as i manually did before and invoking gw buildRest would not generate any changes.

**Comment by cdbm** [comment]
ci:test:sf

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
The fix approach is good @cdbm ! 
The tests need some work however because they do not respect any current SCIM configuration on DXP.  For example we might use `CompanyConfigurationTemporarySwapper` to achieve that, but please consider if it is appropriate given it is a factory configuration.

Can you review that and add commit(s) to liferay-appsec/liferay-portal/pull/1988 ?

**Pull request closed without merging**
