### PR TITLE
LPS-170425 | Master

### PR DESCRIPTION
**Pull request by MirnaGama**
- LPS-170425 Display LDAP Authentication Error in UI
- LPS-170425 Create new exception for LDAP Invalid Credentials
- LPS-170425 Update language keys
- LPS-170425 SF
- LPS-170425 Update the user info and throw exception before send email notification

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:security

**Comment by liferay-appsec** [comment]
Won't fix. https://issues.liferay.com/browse/LPS-170425

**Pull request closed without merging**
