### PR TITLE
LPS-120269 Move mapper to petra

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35 

hey Brian, 

Shuyang has told us that, given the current usages, the library belongs to apps/petra but, if in the future we are going to use it from portal-kernel as we plan, we will need to move it to core/petra. 

Thanks. 
Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
hi @shuyangzhou,

Brian asked us to ask you whether this library should be under `core` or `apps`. It does not have any dependency.
https://github.com/brianchandotcom/liferay-portal/pull/94724#issuecomment-703042054

Thanks. 
Carlos.

**Comment by shuyangzhou** [comment]
@csierra It should be app/petra, not the core/petra. No one in core consumes it, it should be kept out from global classloader. Global classloader is generally bad, we only do that when we have to.

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Comment by csierra** [comment]
ci:forward

**Pull request closed without merging**
