### PR TITLE
Lps 176997

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-176997](https://issues.liferay.com/browse/LPS-176997)

### Why this change
Allows you to track requests to measure MALU and APV.
* MALU (Monthly Active Loggedin Users): in case of logged in user, we need to log a companyId-userId-siteId hash. So if the user jumps through multiple instances and sites, it counts as different values.
* APV (Anonymous Page Views): basically every anonymous page render should return that it was a not logged in user who accessed the page.

### Code
There are two parts to the development
* First one, a configuration has been added (AuditHeaderConfiguration ) to enable or disable the following options
* Second one, a filter has been created (AuditHeaderFilter) in which, if any of the options in the configuration is active, the values are checked and added to the header of the response so that it can be read by Analytics Cloud.

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:security

**Comment by JessieZhao0714** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:sf

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
Errors reviewed. They are related to other modules.

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Comment by alvarosaugarlr** [comment]
ci:forward:force

**Pull request closed without merging**
