### PR TITLE
LPS-196728, LPS-199038 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-196728
https://liferay.atlassian.net/browse/LPS-199038
cc @gaborlovasdotcom

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:um:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The Integration test passed on Jenkins without regression: https://testray.liferay.com/home/-/testray/case_results/2457560990
cc @alvarosaugarlr

**Review by alvarosaugarlr — APPROVED** [review]
Executed the test in local correctly.
Revised the code:

- The role is created, 
- assigned correctly and 
- the GET request is made to check that the correct roles are returned in the request (it is the modification made in the portal).

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
