### PR TITLE
LPD-32699 | Fix test ContentSecurityPolicyFilterTest

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
https://liferay.atlassian.net/browse/LPD-32699

I'm sending the fix of this failing test. The method was renamed in https://liferay.atlassian.net/browse/LPD-2006
from rewriteContent to _updateContent. It wasn't renamed in the test class.
I renamed the method and changed it back to protected.

Please review!

Thanks!

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:security

**Comment by stian-sigvartsen** [comment]
LGTM @evibudai , Thanks!

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
