### PR TITLE
LPS-169273 HR_409 The label text "Enter Again" should have a more meaningful name like "Re-enter Pasword" instead of "Enter Again"

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://issues.liferay.com/browse/LPS-169273

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
LGTM

**Comment by ethib137** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Looks good @veroglez . I have rebased and resolved conflicts here: liferay-appsec/liferay-portal/pull/1174

**Pull request closed without merging**
