### PR TITLE
LPD-32793

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://liferay.atlassian.net/browse/LPD-32793

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @daiazius,
The changes look good, we just need some tests included.  They will most certainly need to be functional playwright tests, so please let me know if you need help with them.
I'll assign the ticket back to you for tracking purposes, thanks!

**Comment by ChrisKian** [comment]
Rebased and forwarded, see https://github.com/liferay-appsec/liferay-portal/pull/1899

**Pull request closed without merging**
