### PR TITLE
LPD-21445 - Editing Global Web Contents triggers site template propagations

### PR DESCRIPTION
**Pull request by DaniSzimko**
[JIRA ticket](https://liferay.atlassian.net/browse/LPD-21445)

from https://github.com/liferay-appsec/liferay-portal/pull/1688

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:headless-staging

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:stable

**Comment by alvarosaugarlr** [comment]
ci:test:headless-staging

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @DaniSzimko . Just wondering why you opted to not reset the ThreadLocal to its previous value after the related logic executes? Not doing so may have some consequences elsewhere?

**Comment by DaniSzimko** [comment]
Hello @stian-sigvartsen 
I investigated the test results and also tested manually some use cases. I did not experience any regression by this modification, but if you think It would be appropriate to reset the ThreadLocal value, then I will update the PR, just let me know.

**Comment by stian-sigvartsen** [comment]
Hi @DaniSzimko . If there is no need to not reset the ThreadLocal then please can you add it. It would make the code a better citizen then :)

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
* Reset ThreadLocal

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by stian-sigvartsen** [comment]
@DaniSzimko To reset the ThreadLocal you should use a try + finally block, to avoid an exception from preventing the reset from occurring. You will find examples in the codebase.

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
Hello @stian-sigvartsen ,
I've commited the requested change.

**Comment by stian-sigvartsen** [comment]
Hi @DaniSzimko . @alvarosaugarlr will review the requested change and the overall PR soon.

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
The changes indicated in the comments ([pr](https://github.com/liferay-appsec/liferay-portal/pull/1730#issuecomment-2090940718) and [jira](https://liferay.atlassian.net/browse/LPD-21676?focusedCommentId=2651184)) have been implemented.

For us it is ok.

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
Hello @alvarosaugarlr ,
Could you forward this PR please?
Thank you.

**Comment by alvarosaugarlr** [comment]
Hi @DaniSzimko ,

Sorry I didn't mention you in the comment. We already did it here - https://github.com/liferay-appsec/liferay-portal/pull/1730#issuecomment-2141555376

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
