### PR TITLE
LPD-33798 Remove 'emails' from the Claims because it does not arrive at all

### PR DESCRIPTION
**Pull request by tomibiro**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Thanks @tomibiro !
Please can you check the SF error?

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
SF error is real

**Comment by stian-sigvartsen** [comment]
After we met yesterday I think it would be better to take a different testing approach. We should add the missing test coverage to LPD-9397 which checks the successful reading of the email claim in the ID Token when a UserInfo endpoint is not in use. 

Thanks @jgarcialr for offering to work on it in @tomibiro 's absence.

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:report:79128134

**Comment by jgarcialr** [comment]
ci:report:79128134

**Review by stian-sigvartsen — COMMENTED** [review]
The test looks good now. I just applied some SF'ing. Thanks @tomibiro & @jgarcialr !

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by jgarcialr** [comment]
ci:forward:force

**Pull request closed without merging**
