### PR TITLE
LPD-19743  Fix CookiesUseCase#VerifyCookiesLifetime

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPD-19743](https://liferay.atlassian.net/browse/LPD-19743)

Fix CookiesUseCase#VerifyCookiesLifetime Poshi test.

Original pr - https://github.com/liferay-appsec/liferay-portal/pull/2005

### CODE REVIEW

**Comment by alvarosaugarlr** [comment]
ci:test:relevant

**Comment by alvarosaugarlr** [comment]
ci:test:security

**Comment by alvarosaugarlr** [comment]
The test CookiesUseCase#VerifyCookiesLifetime has passed. 
image

**Comment by alvarosaugarlr** [comment]
Hi @nikolettabuza ,

I think the pr is fine.

For me it is better solution to generate the date based on days, which is how the cookie logic works. 

Well done updating the names and functions. 

I just added a small change to make the test run on the ci. 

@stian-sigvartsen , from my side the pr is ready.

**Comment by stian-sigvartsen** [comment]
LGTM also! The commit messages were excellent, well done.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
