### PR TITLE
[TS] LPS-189151

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-189151

Adds `client_secret_basic` as a viable authentication type.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
> ### ✔️ ci:test:stable - 32 out of 32 jobs passed
> ###  ci:test:relevant - 64 out of 78 jobs passed in 1 hour 58 minutes
> Click here for more details.

Caught a regression bug from [LocalFile.OAuth2#GrantedAuthorizationsCanBeRevoked](https://testray.liferay.com/home/-/testray/case_results/2364515135).

Steps to reproduce:
1. Navigate to OAuth 2 Administration
2. Add an OAuth2 applications:
- applicationName: OAuth2 Application
- clientId: abc123
- clientSecret: abc123
- ALLOWED AUTHORIZATION TYPES: uncheck Authorization Code
- scope: liferay-json-web-services.everything.read.userprofile
3. Execute the following curl command:
`curl 'http://localhost:8080/o/oauth2/token' --data 'grant_type=client_credentials&client_id=abc123&client_secret=abc123'`

**Expected result:** 
Receive a valid token in the response.

**Actual result:** 
The following is returned:
{"error":"unauthorized_client"}

cc @ChrisKian and @oliverkecskemety

**Comment by ChrisKian** [comment]
Hey @JoyceWang08211,

I've been able to reproduce your regression, however I believe the test needs to be slightly modified.

Before my changes, the default value of the `Client Authentication Method` was `Client Secret Post`.  After my changes, the default value is `Client Secret Basic`, due to alphabetical ordering.

Your test case doesn't explicitly set a `Client Authentication Method` value, likely because it expected the default of `Client Secret Post`.  If you adjust your step 2 to also explicitly set this to `Client Secret Post`, you'll find the expected results appear again.

Please let me know if you have any questions, thanks!

**Comment by JoyceWang08211** [comment]
> 3\. curl 'http://localhost:8080/o/oauth2/token' --data 'grant_type=client_credentials&client_id=abc123&client_secret=abc123'

Hi @ChrisKian, you're right. Thanks for the info.
I'll update OAuth2 tests based on current changes. cc @gaborlovasdotcom 

No regression was found. cc @oliverkecskemety

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-appsec/liferay-portal/pull/1207

**Pull request closed without merging**
