### PR TITLE
LPS-193886

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPS-193886](https://liferay.atlassian.net/browse/LPS-193886)

I reuse the `passwordPolicy.getResetTicketMaxAge()` property as I don't believe we need two seperate properties for nearly identical situations.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
I've added a FF commit.  I'm not sure if I did things correctly, but please let me know if I need to make any changes, thanks!

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @ChrisKian . Your changes look great. Please can you review the CI results and the FF commit needs splitting into two commits with commit messages like this:

> LPS-200009 Define feature flag.
> 
> For LPS-193884.

> LPS-200003 Apply feature flag
> 
> For LPS-193886.

The FF changes you includes creates a DEV feature flag. Because the whole epic will be complete, we should not use a DEV status. Can you discuss with Bence because I think we should make this a RELEASE status (so the ACs on LPS-200009 can be met)? Not sure if it is should be opt in or opt out, but he can decide.

**Review by stian-sigvartsen — CHANGES_REQUESTED** [review]
See previous comment

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,

Thanks for the feedback.  I've changed the commit messages, separated the creation and use of the FF, and changed the type to release.  I'm confident this is correct, although I could still be off.

I looked into CI failures but didn't see anything relevant; not sure if you asked me to review CI because you saw something wrong or just as a normal precaution.  I also rebased the branch, since it was fairly old.

I've chosen the keep the feature as opt-in, but I've reached out to Bence just to double-check.  Please let me know if you have any questions or issues with my changes, thanks!

**Comment by stian-sigvartsen** [comment]
Looks perfect now @ChrisKian ! Thanks

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
