### PR TITLE
LRQA-72513 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-72513](https://issues.liferay.com/browse/LRQA-72513)

This modification will remap the tests we execute during **ci:test:relevant** calls, aka before PR forwarding.
Please review our setup and verify that we didn't miss out or add any extra test calls directory by directory

Thank you

cc @JoyceWang08211

Forwarded from https://github.com/gaborlovasdotcom/liferay-portal/pull/288

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
OpenIDConnect test cases will be fixed by: https://github.com/gaborlovasdotcom/liferay-portal/pull/289

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:security

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 Could you please rebase your branch?

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 Could you please rebase your branch?

Done

**Comment by JoyceWang08211** [comment]
The functional failure of OpenIDConnect#OpenIDConnectOnInstanceLevelSmoke in above also occurs on [the latest upstream](https://testray.liferay.com/home/-/testray/case_results/1601851408). Not related to the current PR.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1277401_1526

**Comment by JoyceWang08211** [comment]
Rebase the PR.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
Removed integration test deletion

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
> Hi @JoyceWang08211. I don't think we need LDAP tests to execute for the VLDAP app. There is no dependency. What do you think?
> 
> /cc @gaborlovasdotcom

Thanks for the review, I will remove LDAP tests validation from VLDAP module.

**Comment by JoyceWang08211** [comment]
Rebased PR and resolved the conflict.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
Now the test failures are related to real Security tests, nice.
We need to fix them

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The unique failures of [SAML#AddUserInheritedRolesAsSAMLAttributeStatements](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/21210//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_AddUserInheritedRolesAsSAMLAttributeStatements_) and [SAML#ViewSPInitiatedSSO](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12/21210//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SAML_ViewSPInitiatedSSO_) are due to the following error:

`2022-02-09 10:25:07.194 INFO  [http-nio-8080-exec-5][SamlAdminPortlet:77] User limit of inotify instances reached or too many open files`

This can be reproduced when running the same pull request test multiple times.

**Comment by JoyceWang08211** [comment]
ci:test:stop

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
If there are no changes needed, should we forward this PR? @gaborlovasdotcom

**Review by stian-sigvartsen — APPROVED** [review]
This looks fine to me. 

I don't understand why the Facebook Connect and OpenSSO tests have moved into `OpenIDConnect.testcase` in a separate merged PR 2 weeks ago. These are completely different protocols to OpenId Connect. But I assume it is just easier for QA to manage fewer files.

If they were given their own `testcase` files then of course we would need to adjust the filters in this PR again.

**Comment by JoyceWang08211** [comment]
@stian-sigvartsen I moved Facebook Connect and OpenSSO tests from Login.testcase to OpenIDConnect.testcase because I thought Facebook Connect and OpenSSO tests should belong to portal-security-sso module rather than login module. 
And we've extended the coverage of Facebook Connect and OpenSSO tests for portal-security-sso and login module no matter place these tests in OpenIDConnect.testcase or Login.testcase since the current PR merged into master.
But you're right, it's more reasonable that move Facebook Connect and OpenSSO tests back to Login.testcase.

**Pull request closed without merging**
