### PR TITLE
LPD-6870 Sign In Utility Page - rename 2nd struts action

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@manuelecastro please can you help identify the true CI test failures on this one?

**Comment by manuelecastro** [comment]
ci:help

**Comment by manuelecastro** [comment]
ci:test:smoke

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
Failures don't seem to be related for now. I'm running relevant again because there were a lot of tests that didn't run (I believe it's because portal smoke test failed also).

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
Hi @stian-sigvartsen 

LGTM!  :tada: 
The failures are not relevant to this PR

**Comment by stian-sigvartsen** [comment]
Thanks for reviewing @manuelecastro !

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
