### PR TITLE
[TS] LPS-130819 Allow reference fields to be overriden.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
https://issues.liferay.com/browse/LPS-130819

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@marianoalvarosaiz https://grow.liferay.com/share/How+to+send+Pull+Request+to+the+Application+Security+Team+liferay-appsec#trigger-ci--review-results

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
