### PR TITLE
LPS-203432

### PR DESCRIPTION
**Pull request by MirnaGama**
### Commits included:
 - LPS-203432 Add default filter properties

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Hi @MirnaGama ! The root cause of this appears to be that the RemoteAccessFilter is not mapped to these URLs. However it is mapped for the regular JAX-RS requests without a locale, so I think we should try to stick to one piece of code invoking `AccessControlThreadLocal.setRemoteAccess(true)` .

Did you find a reason not to?

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @MirnaGama . This was a lot better. I tweaked it to 

1. Use the HTTP whiteboard properties for filtering
2. Reduced the number of dispatch types to only what is needed
3. Applied to all filters registered by the `AuthVerifierFilterTracker` so that permission checking works

Please see liferay-appsec/liferay-portal/pull/1570

**Pull request closed without merging**
